// SP11e: LEARN_PATH server-side. Function ck predicates replaced by JSON DSL
// (CkRule) interpreted by src/lib/learnPathRules.ts on the client.
//
// CkLeaf shapes (interpreted by evalCk):
//   { ctIncludes: 'topic' }  → stats.ct includes topic
//   { vsIncludes: 'screen' } → stats.vs includes screen
//   { lcAtLeast: N }         → stats.lc >= N  (lesson count)
//   { gcAtLeast: N }         → stats.gc >= N  (grammar drill count)
//   { xpAtLeast: N }         → stats.xp >= N  (total XP)
//   { spAtLeast: N }         → stats.sp >= N  (speaking sessions)
//
// Combinators (recursive — nodes may be leaves OR sub-rules):
//   { anyOf: [...] } → at least one matches
//   { allOf: [...] } → all match
//
// Unknown leaf kinds evaluate false (forward-compat).

export const LEARN_PATH = [
  {
    level: 1,
    title: 'Survivor',
    desc: 'First 48 hours',
    items: [
      {
        id: 'lp1',
        name: 'Basic Greetings',
        diff: 1,
        dur: '~5 min',
        ckRule: { anyOf: [{ ctIncludes: 'greetings' }, { lcAtLeast: 1 }] },
        go: 'lesson',
        topic: 'greetings',
      },
      {
        id: 'lp2',
        name: 'Numbers',
        diff: 1,
        dur: '~5 min',
        ckRule: { anyOf: [{ ctIncludes: 'numbers' }, { lcAtLeast: 2 }] },
        go: 'lesson',
        topic: 'numbers',
      },
      {
        id: 'lp_listen_basics',
        name: 'Hear Croatian',
        cat: 'listening',
        icon: '🎧',
        desc: 'Train your ear — listen to basic Croatian phrases',
        dur: '~5 min',
        diff: 1,
        go: 'listening',
        ckRule: { anyOf: [{ vsIncludes: 'listening' }, { lcAtLeast: 2 }] },
      },
      {
        id: 'lp3',
        name: 'Emergency Phrases',
        diff: 1,
        dur: '~6 min',
        ckRule: { anyOf: [{ ctIncludes: 'health' }, { lcAtLeast: 3 }] },
        go: 'lesson',
        topic: 'health',
      },
      {
        id: 'lp4',
        name: 'Order Food',
        diff: 1,
        dur: '~6 min',
        ckRule: { anyOf: [{ ctIncludes: 'restaurant' }, { lcAtLeast: 4 }] },
        go: 'lesson',
        topic: 'restaurant',
      },
      {
        id: 'lp5',
        name: 'Get Around',
        diff: 1,
        dur: '~8 min',
        ckRule: { anyOf: [{ ctIncludes: 'transport' }, { lcAtLeast: 5 }] },
        go: 'lesson',
        topic: 'transport',
      },
    ],
  },
  {
    level: 2,
    title: 'Settler',
    desc: 'First week',
    items: [
      {
        id: 'lp6',
        name: 'Family Words',
        diff: 1,
        dur: '~8 min',
        ckRule: { anyOf: [{ ctIncludes: 'family' }, { lcAtLeast: 6 }] },
        go: 'lesson',
        topic: 'family',
      },
      {
        id: 'lp7',
        name: 'School Kit',
        diff: 1,
        dur: '~8 min',
        ckRule: { anyOf: [{ ctIncludes: 'in the classroom' }, { lcAtLeast: 7 }] },
        go: 'lesson',
        topic: 'in the classroom',
      },
      {
        id: 'lp8',
        name: 'Making Friends',
        diff: 2,
        dur: '~8 min',
        ckRule: { anyOf: [{ ctIncludes: 'personality' }, { lcAtLeast: 8 }] },
        go: 'lesson',
        topic: 'personality',
      },
      {
        id: 'lp9',
        name: 'Grocery Shopping',
        diff: 1,
        dur: '~8 min',
        ckRule: { anyOf: [{ ctIncludes: 'shopping' }, { lcAtLeast: 9 }] },
        go: 'lesson',
        topic: 'shopping',
      },
      {
        id: 'lp10',
        name: 'Alphabet',
        diff: 2,
        dur: '~10 min',
        ckRule: { anyOf: [{ vsIncludes: 'alphabet' }, { lcAtLeast: 3 }] },
        go: 'alphabet',
        topic: 'alphabet',
      },
      {
        id: 'lp_phonology',
        name: 'Sounds & Diacritics',
        diff: 2,
        dur: '~10 min',
        cat: 'pronunciation',
        icon: '🎵',
        desc: 'Č,Ć,Š,Ž,Đ — the 5 letters that define Croatian pronunciation and how to voice them correctly',
        ckRule: { anyOf: [{ vsIncludes: 'phonology' }, { lcAtLeast: 4 }] },
        go: 'phonology',
      },
      {
        id: 'lp_gender',
        name: 'Noun Gender',
        diff: 1,
        dur: '~10 min',
        cat: 'grammar',
        icon: '⚧️',
        desc: 'Every Croatian noun is masculine, feminine, or neuter — and the ending tells you which',
        ckRule: { anyOf: [{ vsIncludes: 'lp_gender' }, { lcAtLeast: 4 }] },
        go: 'animlesson',
        lessonId: 'gender',
      },
      {
        id: 'lp_time_calendar',
        name: 'Time & Calendar',
        diff: 1,
        dur: '~8 min',
        cat: 'grammar',
        icon: '🕐',
        desc: 'Tell the time, name the days, say the months — Croatian time words are unlike any other language',
        ckRule: { anyOf: [{ vsIncludes: 'lp_time_calendar' }, { lcAtLeast: 4 }] },
        go: 'animlesson',
        lessonId: 'time-calendar',
      },
      {
        id: 'lp_present_tense',
        name: 'Present Tense Verbs',
        diff: 2,
        dur: '~10 min',
        cat: 'grammar',
        icon: '🔄',
        desc: "Three conjugation classes (-em/-im/-am), biti, htjeti, and 15 verbs you'll use every day",
        ckRule: { anyOf: [{ vsIncludes: 'lp_present_tense' }, { lcAtLeast: 6 }] },
        go: 'animlesson',
        lessonId: 'present-tense-verbs',
      },
      {
        id: 'lp_perfective_verbs_a2',
        name: 'Useful Verbs',
        diff: 1,
        dur: '~8 min',
        cat: 'vocabulary',
        icon: '⚡',
        desc: '7 super-useful verbs you will use every day. Aspect theory comes later — for now, just learn the meanings.',
        ckRule: { anyOf: [{ ctIncludes: 'perfective_verbs_a2' }, { lcAtLeast: 7 }] },
        go: 'lesson',
        topic: 'perfective_verbs_a2',
      },
      {
        id: 'lp11',
        name: 'First Quiz',
        diff: 1,
        dur: '~5 min',
        ckRule: { anyOf: [{ xpAtLeast: 50 }] },
        go: 'mcgame',
      },
    ],
  },
  {
    level: 3,
    title: 'Communicator',
    desc: 'First month',
    items: [
      {
        id: 'lp12',
        name: 'Grammar Intro',
        diff: 2,
        dur: '~10 min',
        ckRule: { anyOf: [{ gcAtLeast: 1 }] },
        go: 'grammar',
      },
      {
        id: 'lp13',
        name: 'Texting/Slang',
        diff: 2,
        dur: '~10 min',
        ckRule: { anyOf: [{ vsIncludes: 'texting' }, { lcAtLeast: 10 }] },
        go: 'texting',
      },
      {
        id: 'lp14',
        name: 'Role-Play',
        diff: 2,
        dur: '~10 min',
        ckRule: { anyOf: [{ vsIncludes: 'roleplay' }, { lcAtLeast: 10 }] },
        go: 'roleplay',
      },
      {
        id: 'lp15',
        name: 'Read a Story',
        diff: 2,
        dur: '~12 min',
        ckRule: { anyOf: [{ vsIncludes: 'readlist' }, { lcAtLeast: 12 }] },
        go: 'readlist',
        filter: ['beginner'],
      },
      {
        id: 'lp16',
        name: 'Conjugation',
        diff: 3,
        dur: '~12 min',
        ckRule: { anyOf: [{ gcAtLeast: 2 }, { lcAtLeast: 12 }] },
        go: 'conjdrill',
      },
      {
        id: 'lp17',
        name: 'Listening',
        diff: 2,
        dur: '~10 min',
        ckRule: { anyOf: [{ vsIncludes: 'listening' }, { lcAtLeast: 12 }] },
        go: 'listening',
      },
      {
        id: 'lp18',
        name: 'Tenses & Gender',
        diff: 3,
        dur: '~12 min',
        ckRule: { anyOf: [{ vsIncludes: 'tenses' }, { gcAtLeast: 3 }] },
        go: 'tenses',
      },
      {
        id: 'lp_past_tense',
        name: 'Past Tense',
        diff: 2,
        dur: '~12 min',
        cat: 'grammar',
        icon: '⏪',
        desc: 'Govoriti→govorio/la sam — talk about what already happened',
        ckRule: { anyOf: [{ vsIncludes: 'past_tense_lesson' }, { gcAtLeast: 3 }] },
        go: 'past_tense_lesson',
      },
      {
        id: 'lp_fut_tense',
        name: 'Future Tense',
        diff: 2,
        dur: '~12 min',
        cat: 'grammar',
        icon: '⏩',
        desc: 'Govorit ću — express plans, predictions, and intentions',
        ckRule: { anyOf: [{ vsIncludes: 'future_tense_lesson' }, { gcAtLeast: 4 }] },
        go: 'future_tense_lesson',
      },
      {
        id: 'lp_adj_agree',
        name: 'Adjective Agreement',
        diff: 2,
        dur: '~12 min',
        cat: 'grammar',
        icon: '🎨',
        desc: 'Adjectives must match noun gender, case, and number — how Croatian sentences hold together',
        ckRule: { anyOf: [{ vsIncludes: 'lp_adj_agree' }, { gcAtLeast: 3 }] },
        go: 'animlesson',
        lessonId: 'adjective-agreement',
      },
      {
        id: 'lp_acc_deep',
        name: 'Accusative in Depth',
        diff: 2,
        dur: '~12 min',
        cat: 'grammar',
        icon: '⚖️',
        desc: 'Animate vs inanimate, direction vs location — where Croatian gets precise',
        ckRule: { anyOf: [{ vsIncludes: 'lp_acc_deep' }, { gcAtLeast: 3 }] },
        go: 'animlesson',
        lessonId: 'accusative-deep',
      },
      {
        id: 'lp34',
        name: 'Vi ili ti?',
        diff: 2,
        dur: '~10 min',
        ckRule: { anyOf: [{ vsIncludes: 'formalregister' }, { gcAtLeast: 3 }] },
        go: 'formalregister',
      },
      {
        id: 'lp35',
        name: 'Tech & Digital',
        diff: 2,
        dur: '~10 min',
        ckRule: { anyOf: [{ vsIncludes: 'techvoc' }, { lcAtLeast: 12 }] },
        go: 'techvoc',
      },
      {
        id: 'lp42',
        name: 'Work & Career',
        diff: 2,
        dur: '~10 min',
        ckRule: { anyOf: [{ ctIncludes: 'work' }, { lcAtLeast: 14 }] },
        go: 'lesson',
        topic: 'work',
      },
      {
        id: 'lp43',
        name: 'Opinions & Debate',
        diff: 2,
        dur: '~12 min',
        ckRule: { anyOf: [{ ctIncludes: 'opinions' }, { lcAtLeast: 15 }] },
        go: 'lesson',
        topic: 'opinions',
      },
      {
        id: 'lp_prepositions',
        name: 'Prepositions in Action',
        diff: 2,
        dur: '~10 min',
        cat: 'grammar',
        icon: '📍',
        desc: 'u/na with accusative vs locative (the direction/location split), genitive preps od/do/iz/bez/kod, and instrumental s/sa',
        ckRule: { anyOf: [{ vsIncludes: 'lp_prepositions' }, { lcAtLeast: 12 }] },
        go: 'animlesson',
        lessonId: 'prepositions-action',
      },
    ],
  },
  {
    level: 4,
    title: 'Explorer',
    desc: 'Months 2-3',
    items: [
      {
        id: 'lp19',
        name: '7 Cases',
        diff: 3,
        dur: '~12 min',
        ckRule: { anyOf: [{ gcAtLeast: 4 }] },
        go: 'padezi',
      },
      {
        id: 'lp20',
        name: 'Padeži Master',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'padezifull' }, { gcAtLeast: 5 }] },
        go: 'padezifull',
      },
      {
        id: 'lp21',
        name: 'Verb Aspect',
        diff: 3,
        dur: '~12 min',
        ckRule: { anyOf: [{ vsIncludes: 'aspect' }, { gcAtLeast: 5 }] },
        go: 'aspect',
      },
      {
        id: 'lp_asp_impf',
        name: 'Aspect — Imperfective',
        diff: 3,
        dur: '~12 min',
        cat: 'grammar',
        icon: '🔄',
        desc: 'Ongoing, habitual, general truth — understanding imperfective is half the battle with Croatian verbs',
        ckRule: { anyOf: [{ vsIncludes: 'lp_asp_impf' }, { gcAtLeast: 5 }] },
        go: 'animlesson',
        lessonId: 'aspect-imperfective',
      },
      {
        id: 'lp_asp_pf',
        name: 'Aspect — Perfective',
        diff: 3,
        dur: '~12 min',
        cat: 'grammar',
        icon: '✅',
        desc: 'Completed events, narrative chains, results — perfective is how you tell stories in Croatian',
        ckRule: { anyOf: [{ vsIncludes: 'lp_asp_pf' }, { gcAtLeast: 5 }] },
        go: 'animlesson',
        lessonId: 'aspect-perfective',
      },
      {
        id: 'lp_gen_deep',
        name: 'Genitive in Depth',
        diff: 3,
        dur: '~12 min',
        cat: 'grammar',
        icon: '📦',
        desc: 'Possession, nema, quantities, 8 key prepositions — genitive is used more than any other case',
        ckRule: { anyOf: [{ vsIncludes: 'lp_gen_deep' }, { gcAtLeast: 5 }] },
        go: 'animlesson',
        lessonId: 'genitive-deep',
      },
      {
        id: 'lp_dat_loc',
        name: 'Dative & Locative',
        diff: 3,
        dur: '~12 min',
        cat: 'grammar',
        icon: '📍',
        desc: 'Shared endings, recipient structures, location prepositions — two cases, one learning load',
        ckRule: { anyOf: [{ vsIncludes: 'lp_dat_loc' }, { gcAtLeast: 5 }] },
        go: 'animlesson',
        lessonId: 'dative-locative',
      },
      {
        id: 'lp_instr',
        name: 'Instrumental Case',
        diff: 3,
        dur: '~12 min',
        cat: 'grammar',
        icon: '🛠️',
        desc: 'Tools, means, accompaniment, s/sa — the case that connects nouns to action',
        ckRule: { anyOf: [{ vsIncludes: 'lp_instr' }, { gcAtLeast: 5 }] },
        go: 'animlesson',
        lessonId: 'instrumental',
      },
      {
        id: 'lp_reflexive',
        name: 'SE Reflexive Verbs',
        diff: 3,
        dur: '~12 min',
        cat: 'grammar',
        icon: '🧲',
        desc: "Tuširati se, zvati se, vratiti se — the 'se' that changes everything",
        ckRule: { anyOf: [{ vsIncludes: 'reflexive' }, { gcAtLeast: 5 }] },
        go: 'reflexive',
      },
      {
        id: 'lp_vocative',
        name: 'Vocative Case',
        diff: 3,
        dur: '~10 min',
        cat: 'grammar',
        icon: '📣',
        desc: "'Petre!' not 'Petar!' — address people directly and correctly. Natives notice every single time.",
        ckRule: { anyOf: [{ vsIncludes: 'vocative' }, { gcAtLeast: 6 }] },
        go: 'vocative',
      },
      {
        id: 'lp22',
        name: 'Modal Verbs',
        diff: 2,
        dur: '~10 min',
        ckRule: { anyOf: [{ gcAtLeast: 6 }] },
        go: 'modal',
      },
      {
        id: 'lp23',
        name: 'Declension',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'declension' }, { gcAtLeast: 6 }] },
        go: 'declension',
      },
      {
        id: 'lp24',
        name: 'False Friends',
        diff: 2,
        dur: '~10 min',
        ckRule: { anyOf: [{ vsIncludes: 'falsefr' }, { lcAtLeast: 20 }] },
        go: 'falsefr',
      },
      {
        id: 'lp25',
        name: 'Dialects',
        diff: 2,
        dur: '~12 min',
        ckRule: { anyOf: [{ vsIncludes: 'dialects' }, { lcAtLeast: 20 }] },
        go: 'dialects',
      },
      {
        id: 'lp36',
        name: 'Conditional Mood',
        diff: 3,
        dur: '~12 min',
        ckRule: { anyOf: [{ vsIncludes: 'conditional' }, { gcAtLeast: 5 }] },
        go: 'conditional',
      },
      {
        id: 'lp37',
        name: 'Impersonal',
        diff: 3,
        dur: '~12 min',
        ckRule: { anyOf: [{ vsIncludes: 'impersonal' }, { gcAtLeast: 6 }] },
        go: 'impersonal',
      },
      {
        id: 'lp39',
        name: 'Clitic Pronouns',
        diff: 3,
        dur: '~12 min',
        ckRule: { anyOf: [{ vsIncludes: 'clitic' }, { gcAtLeast: 6 }] },
        go: 'clitic',
      },
      {
        id: 'lp_svojmoj',
        name: 'Svoj vs Moj',
        diff: 3,
        dur: '~10 min',
        cat: 'grammar',
        icon: '🔄',
        desc: 'The reflexive possessive — tiny detail, huge impact on sounding natural',
        ckRule: { anyOf: [{ vsIncludes: 'svojmoj' }, { gcAtLeast: 7 }] },
        go: 'svojmoj',
      },
      {
        id: 'lp44',
        name: 'Environment',
        diff: 2,
        dur: '~10 min',
        ckRule: { anyOf: [{ ctIncludes: 'environment' }, { lcAtLeast: 22 }] },
        go: 'lesson',
        topic: 'environment',
      },
      {
        id: 'lp45',
        name: 'Society & Community',
        diff: 2,
        dur: '~12 min',
        ckRule: { anyOf: [{ ctIncludes: 'society' }, { lcAtLeast: 23 }] },
        go: 'lesson',
        topic: 'society',
      },
      {
        id: 'lp_writing',
        name: 'Write in Croatian',
        diff: 2,
        dur: '~15 min',
        cat: 'writing',
        icon: '✍️',
        desc: 'Put everything together — write structured paragraphs and get real-time AI grammar feedback',
        ckRule: { anyOf: [{ vsIncludes: 'writing' }, { lcAtLeast: 24 }] },
        go: 'writing',
      },
      {
        id: 'lp_numbers_nouns',
        name: 'Numbers & Nouns',
        diff: 3,
        dur: '~10 min',
        cat: 'grammar',
        icon: '🔢',
        desc: 'The 3-way counting rule (1/2-4/5+), the 11-19 exception, and collective numbers for mixed groups',
        ckRule: { anyOf: [{ vsIncludes: 'lp_numbers_nouns' }, { lcAtLeast: 20 }] },
        go: 'animlesson',
        lessonId: 'numbers-nouns',
      },
    ],
  },
  {
    level: 5,
    title: 'Hrvat',
    desc: 'Months 4-6',
    items: [
      {
        id: 'lp_asp_neg',
        name: 'Aspect + Negation',
        diff: 3,
        dur: '~12 min',
        cat: 'grammar',
        icon: '🚫',
        desc: 'Negation flips the default aspect rule — the rule Croatian learners get wrong longest',
        ckRule: { anyOf: [{ vsIncludes: 'lp_asp_neg' }, { gcAtLeast: 6 }] },
        go: 'animlesson',
        lessonId: 'aspect-negation',
      },
      {
        id: 'lp26',
        name: 'Idioms',
        diff: 3,
        dur: '~12 min',
        ckRule: { anyOf: [{ vsIncludes: 'idioms' }, { lcAtLeast: 25 }] },
        go: 'idioms',
      },
      {
        id: 'lp27',
        name: 'Tongue Twisters',
        diff: 3,
        dur: '~12 min',
        ckRule: { anyOf: [{ vsIncludes: 'brzalice' }, { lcAtLeast: 25 }] },
        go: 'brzalice',
      },
      {
        id: 'lp28',
        name: 'Word Formation',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'wordform' }, { lcAtLeast: 25 }] },
        go: 'wordform',
      },
      {
        id: 'lp29',
        name: 'Diminutives',
        diff: 3,
        dur: '~12 min',
        ckRule: { anyOf: [{ vsIncludes: 'diminutives' }, { lcAtLeast: 28 }] },
        go: 'diminutives',
      },
      {
        id: 'lp31',
        name: 'Domovinski Rat',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'history' }, { lcAtLeast: 30 }] },
        go: 'history',
      },
      {
        id: 'lp32',
        name: 'Cook Croatian!',
        diff: 2,
        dur: '~12 min',
        ckRule: { anyOf: [{ vsIncludes: 'recipes' }, { lcAtLeast: 30 }] },
        go: 'recipes',
      },
      {
        id: 'lp33',
        name: '200 XP!',
        diff: 3,
        dur: '~5 min',
        ckRule: { anyOf: [{ xpAtLeast: 200 }] },
        go: 'dashboard',
      },
      {
        id: 'lp38',
        name: 'Admin Life',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'bureaucratic' }, { lcAtLeast: 28 }] },
        go: 'bureaucratic',
      },
      {
        id: 'lp40',
        name: 'Subjunctive (da + Verb)',
        diff: 3,
        dur: '~12 min',
        ckRule: { anyOf: [{ gcAtLeast: 6 }] },
        go: 'grammar',
      },
      {
        id: 'lp41',
        name: 'Listening Path',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'listeningpath' }, { lcAtLeast: 25 }] },
        go: 'listeningpath',
      },
      {
        id: 'lp_feelings',
        name: 'Feelings & Inner Life',
        diff: 3,
        dur: '~12 min',
        cat: 'grammar',
        icon: '💙',
        desc: 'Reflexive emotion verbs, the dative of experience, and untranslatable words: čežnja, inat, snalaziti se',
        ckRule: { anyOf: [{ vsIncludes: 'lp_feelings' }, { lcAtLeast: 26 }] },
        go: 'animlesson',
        lessonId: 'feelings-inner-life',
      },
    ],
  },
  {
    level: 6,
    title: 'Virtuoz',
    desc: 'Months 7-12',
    items: [
      {
        id: 'lp50',
        name: 'Pitch Accent',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'pitchaccent' }, { lcAtLeast: 35 }] },
        go: 'pitchaccent',
      },
      {
        id: 'lp51',
        name: 'Shadowing',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'shadowing' }, { lcAtLeast: 35 }] },
        go: 'shadowing',
      },
      {
        id: 'lp52',
        name: 'Aspect Drill',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'aspectdrill' }, { lcAtLeast: 35 }] },
        go: 'aspectdrill',
      },
      {
        id: 'lp_clitics_adv',
        name: 'Clitics: Advanced',
        diff: 3,
        dur: '~15 min',
        cat: 'grammar',
        icon: '🧬',
        desc: 'Second-position law, full internal order, double je — the rule that makes Croatian speech flow',
        ckRule: { anyOf: [{ vsIncludes: 'lp_clitics_adv' }, { gcAtLeast: 7 }] },
        go: 'animlesson',
        lessonId: 'clitics-advanced',
      },
      {
        id: 'lp_verbal_nouns',
        name: 'Verbal Nouns & Participles',
        diff: 3,
        dur: '~15 min',
        cat: 'grammar',
        icon: '📝',
        desc: 'Gerunds (-nje/-će), active/passive/adverbial forms — the nominalization patterns of formal Croatian',
        ckRule: { anyOf: [{ vsIncludes: 'lp_verbal_nouns' }, { gcAtLeast: 7 }] },
        go: 'animlesson',
        lessonId: 'verbal-nouns',
      },
      {
        id: 'lp53',
        name: 'Clitics: Mastery',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'lp53' }, { lcAtLeast: 36 }] },
        go: 'clitic',
      },
      {
        id: 'lp54',
        name: 'Grammar Constellation',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'grammarmap' }, { gcAtLeast: 7 }] },
        go: 'grammarmap',
      },
      {
        id: 'lp55',
        name: 'Impersonal: Mastery',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'lp55' }, { gcAtLeast: 8 }] },
        go: 'impersonal',
      },
      {
        id: 'lp56',
        name: 'Conditional: Mastery',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'lp56' }, { gcAtLeast: 8 }] },
        go: 'conditional',
      },
      {
        id: 'lp57',
        name: 'Word Formation: B2',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'lp57' }, { lcAtLeast: 38 }] },
        go: 'wordform',
      },
      {
        id: 'lp58',
        name: 'Politics Vocabulary',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'lp58' }, { ctIncludes: 'civic' }, { lcAtLeast: 38 }] },
        go: 'lesson',
        topic: 'civic',
      },
      {
        id: 'lp59',
        name: 'Arts & Culture',
        diff: 3,
        dur: '~15 min',
        ckRule: { anyOf: [{ vsIncludes: 'lp59' }, { ctIncludes: 'arts' }, { lcAtLeast: 38 }] },
        go: 'lesson',
        topic: 'arts',
      },
      {
        id: 'lp61',
        name: 'Croatian History',
        diff: 3,
        dur: '~20 min',
        ckRule: { anyOf: [{ vsIncludes: 'history' }, { vsIncludes: 'lp61' }, { lcAtLeast: 40 }] },
        go: 'history',
      },
      {
        id: 'lp62',
        name: 'Listening Mastery',
        diff: 3,
        dur: '~20 min',
        ckRule: { anyOf: [{ vsIncludes: 'lp62' }, { lcAtLeast: 40 }] },
        go: 'listeningpath',
      },
      {
        id: 'lp_speaking_b2',
        name: 'Speaking Practice',
        diff: 3,
        dur: '~20 min',
        cat: 'speaking',
        icon: '🗣️',
        desc: 'Train your spoken output — complete 3 speaking sessions to develop fluency beyond reading and writing',
        ckRule: { anyOf: [{ vsIncludes: 'lp_speaking_b2' }, { spAtLeast: 3 }] },
        go: 'speaking',
      },
      {
        id: 'lp_production_drill',
        name: 'Production Drills',
        diff: 3,
        dur: '~20 min',
        cat: 'grammar',
        icon: '✍️',
        desc: 'Move beyond recognition — transform sentences, translate to Croatian, build from word tiles, and fix real errors',
        ckRule: {
          anyOf: [{ vsIncludes: 'lp_production_drill' }, { gcAtLeast: 7 }, { lcAtLeast: 42 }],
        },
        go: 'production_drill',
      },
      {
        id: 'lp_pronunciation_course',
        name: 'Pronunciation Course',
        diff: 3,
        dur: '~20 min',
        cat: 'pronunciation',
        icon: '🎤',
        desc: 'Systematic phoneme-by-phoneme training — eliminate your foreign accent at the source',
        ckRule: { anyOf: [{ vsIncludes: 'pronunciation_course' }, { lcAtLeast: 37 }] },
        go: 'pronunciation_course',
      },
      {
        id: 'lp_registers',
        name: 'Croatian Writing Registers',
        diff: 3,
        dur: '~15 min',
        cat: 'grammar',
        icon: '✍️',
        desc: 'Informal vs journalistic vs formal Croatian — passive voice, nominalization, and discourse markers (međutim/naime/stoga)',
        ckRule: { anyOf: [{ vsIncludes: 'lp_registers' }, { lcAtLeast: 35 }] },
        go: 'animlesson',
        lessonId: 'writing-registers',
      },
    ],
  },
  {
    level: 7,
    title: 'Majstor',
    desc: 'Year 1+',
    items: [
      {
        id: 'lp63',
        name: 'Dialects: Deep Dive',
        diff: 3,
        dur: '~20 min',
        ckRule: { anyOf: [{ vsIncludes: 'lp63' }, { lcAtLeast: 45 }] },
        go: 'dialects',
      },
      {
        id: 'lp64',
        name: 'Croatian Literature',
        diff: 3,
        dur: '~20 min',
        ckRule: {
          anyOf: [{ vsIncludes: 'lp64' }, { ctIncludes: 'academic writing' }, { lcAtLeast: 45 }],
        },
        go: 'lesson',
        topic: 'academic writing',
      },
      {
        id: 'lp65',
        name: 'Proverbs Deep Dive',
        diff: 3,
        dur: '~20 min',
        ckRule: { anyOf: [{ vsIncludes: 'proverbs' }, { vsIncludes: 'lp65' }, { lcAtLeast: 45 }] },
        go: 'proverbs',
      },
      {
        id: 'lp66',
        name: 'Idioms: Expert',
        diff: 3,
        dur: '~20 min',
        ckRule: {
          anyOf: [
            { vsIncludes: 'lp66' },
            { xpAtLeast: 2000 },
            { allOf: [{ lcAtLeast: 40 }, { gcAtLeast: 8 }] },
          ],
        },
        go: 'idioms',
      },
      {
        id: 'lp67',
        name: 'Abstract Language',
        diff: 3,
        dur: '~20 min',
        ckRule: {
          anyOf: [
            { vsIncludes: 'lp67' },
            { ctIncludes: 'abstract concepts' },
            { xpAtLeast: 2000 },
            { gcAtLeast: 8 },
          ],
        },
        go: 'lesson',
        topic: 'abstract concepts',
      },
      {
        id: 'lp68',
        name: 'Media Language',
        diff: 3,
        dur: '~20 min',
        ckRule: {
          anyOf: [
            { vsIncludes: 'lp68' },
            { ctIncludes: 'academic language' },
            { xpAtLeast: 2000 },
            { gcAtLeast: 8 },
          ],
        },
        go: 'lesson',
        topic: 'academic language',
      },
      {
        id: 'lp69',
        name: 'Legal Croatian',
        diff: 3,
        dur: '~20 min',
        ckRule: {
          anyOf: [
            { vsIncludes: 'lp69' },
            { ctIncludes: 'law' },
            { xpAtLeast: 2500 },
            { gcAtLeast: 9 },
          ],
        },
        go: 'lesson',
        topic: 'law',
      },
      {
        id: 'lp70',
        name: 'Tongue Twisters: Expert',
        diff: 3,
        dur: '~15 min',
        ckRule: {
          anyOf: [{ vsIncludes: 'lp70' }, { vsIncludes: 'pitchaccent' }, { xpAtLeast: 2500 }],
        },
        go: 'brzalice',
      },
      {
        id: 'lp_speaking_c1',
        name: 'Conversation: C1',
        diff: 3,
        dur: '~25 min',
        cat: 'speaking',
        icon: '🎯',
        desc: "Complete 10 speaking sessions — fluent speakers don't pause to translate in their head",
        ckRule: { anyOf: [{ vsIncludes: 'lp_speaking_c1' }, { spAtLeast: 10 }] },
        go: 'speaking',
      },
      {
        id: 'lp_pitch_mastery',
        name: 'Pitch Accent Mastery',
        diff: 3,
        dur: '~20 min',
        cat: 'pronunciation',
        icon: '🔊',
        desc: 'The final phonological frontier — 4 accent types, tonal distinctions, native-like rhythm',
        ckRule: {
          anyOf: [
            { vsIncludes: 'lp_pitch_mastery' },
            { vsIncludes: 'pitch_accent' },
            { gcAtLeast: 9 },
          ],
        },
        go: 'pitch_accent',
      },
      {
        id: 'lp_idioms_reg',
        name: 'Idioms & Register',
        diff: 3,
        dur: '~20 min',
        cat: 'grammar',
        icon: '🎭',
        desc: 'Ti/Vi shift, diminutives, discourse markers, proverbs — this is what separates functional Croatian from fluency',
        ckRule: { anyOf: [{ vsIncludes: 'lp_idioms_reg' }, { xpAtLeast: 2000 }, { gcAtLeast: 8 }] },
        go: 'animlesson',
        lessonId: 'idioms-register',
      },
      {
        id: 'lp_lang_identity',
        name: 'Croatian Language Identity',
        diff: 3,
        dur: '~15 min',
        cat: 'heritage',
        icon: '🇭🇷',
        desc: 'Post-independence vocabulary, Glagolitic heritage, dialect dignity, and language anxiety — the soul of the language',
        ckRule: {
          anyOf: [{ vsIncludes: 'lp_lang_identity' }, { xpAtLeast: 2500 }, { gcAtLeast: 10 }],
        },
        go: 'animlesson',
        lessonId: 'language-identity',
      },
    ],
  },
];
