// src/lib/appData.ts
// Public data module — re-exports Croatian language data from data.jsx.
// Import from here when a component only needs data (not utility functions).
//
// This module is mapped to the same 'chunk-data' Vite chunk as data.jsx
// (see vite.config.js manualChunks), so no bundle-size regression occurs.
//
// Grammar data (ASPECT, PADEZI, PADEZI_FULL, MODAL, GRAM, CONDITIONAL,
// FORMAL_REGISTER, IMPERSONAL, CONJ, PITCH_ACCENT, ASPECT_PAIRS, PHONOLOGY,
// TENSES) was moved server-side in SP11b. Use useGrammar() hook (components)
// or contentClient.getGrammar() (non-components) instead.

export {
  // Vocabulary & situational content
  V,
  FOODORDER,
  EMERGENCY,
  TRANSPORT,
  GROCERY,
  RECIPES,
  SCHOOL,
  FRIENDS,
  GYM,
  TEXTING,
  PRACTICAL,
  FOOTBALL,
  POPCULTURE,
  ROLEPLAY,
  SCENES,
  // Grammar structures
  VOCATIVE,
  NUMCOUNT,
  NUMTIME,
  FALSEFR,
  DIALECTS,
  DECL,
  PREPDRILL,
  BRZALICE,
  DIMWORDS,
  WORDFORM,
  REFLEXIVE,
  SVOJMOJ,
  TECH_VOC,
  BUREAUCRATIC,
  // Stories & practice content
  STORIES,
  PROVERBS,
  LISTEN,
  HIST_FACTS,
  FILL_STORIES,
  ZNAM,
  BOJE,
  UNJUMBLE,
  IDIOMS,
  PREPS,
  ALPHA,
  READ,
  // Exercises
  RIDDLES,
  LOGICQUIZ,
  ORDINALS,
  ORDQUIZ,
  RELPRON,
  EMOGENDER,
  QWORDS,
  NEGATION,
  COLORAGREE,
  SIBIL,
  PROFGENDER,
  COMPARE,
  COMPQUIZ,
  FUTURE,
  RESTCONV,
  POSSESS,
  ADJOPPOSITES,
  CITYLOC,
  AKUFOOD,
  AKUCLOTHES,
  CONVMATCH,
  VERBDRILL,
  VBPERSONS,
  TENSEFLIP,
  GENDERDRILL,
  SENTBUILD,
  PRONOUNCASE,
  COLORQUIRK,
  SHADOWING,
  // Cultural & geographic data
  HISTORY,
  EVENTS,
  KINGS,
  TOP100,
  REGIONS,
  CROATIAN_CITIES,
  COUNTRIES,
  MAPPLACES,
  MEDIA,
  PROFESSIONS,
  WEATHER,
  CLOTHES,
  BODYDESC,
  BASKETBALL,
  // App structure
  LEARN_PATH,
  BADGES,
  DAILY_QUESTS,
  SEASONAL_CAMPAIGNS,
  LEVEL_NARRATIVE,
  PLACE,
  // Theme colors
  BG_LIGHT,
  BG_DARK,
} from '../data';
