/**
 * blackHoleScreens — LEARN_PATH screens that don't self-report completion;
 * the launcher's dwell timer (useScreenLauncher.launchPathItem) grants lc/gc
 * credit after 20s on-screen. Extracted from useScreenLauncher for max-lines
 * (data only — the dwell mechanism stays in the hook).
 */
// Screens in LEARN_PATH that don't self-report completion — dwell ≥20s grants credit.
export const BLACK_HOLE_SCREENS: Record<string, string> = {
  texting: 'lc',
  roleplay: 'lc',
  readlist: 'lc',
  idioms: 'lc',
  brzalice: 'lc',
  history: 'lc',
  recipes: 'lc',
  listeningpath: 'lc',
  falsefr: 'lc',
  dialects: 'lc',
  listening: 'lc',
  alphabet: 'lc',
  techvoc: 'lc',
  pitchaccent: 'lc',
  grammarmap: 'gc',
  shadowing: 'lc',
  proverbs: 'lc',
  bureaucratic: 'lc',
  conjlab: 'gc',
  conjpractice: 'gc',
  reflexive: 'gc',
  grammarreader: 'gc',
  colorquirk: 'gc',
  writing: 'lc',
  pitch_accent: 'gc',
  pronunciation_course: 'lc',
  professions: 'lc',
  bodydesc: 'lc',
  clothes: 'lc',
  countries: 'lc',
  weather: 'lc',
  civic: 'lc',
  top100: 'lc',
  tivicompare: 'lc',
  lifeevents: 'lc',
  popculture: 'lc',
  events: 'lc',
  cityofday: 'lc',
  kafic: 'lc',
  kings: 'lc',
  school: 'lc',
  restaurant: 'lc',
  emergency: 'lc',
  crmap: 'lc',
  storyselect: 'lc',
  foodorder: 'lc',
  grocery: 'lc',
  transport: 'lc',
  grammarvideos: 'lc',
  production_drill: 'gc',
};
