// src/lib/croatianIrregulars.ts
//
// Irregular noun paradigms, split out of `croatianMorphology.ts` when that file
// reached the 800-line lint cap. Data only — no behaviour moved, and the cap was
// not raised (the precedent: sessionPools, croatiaPool, categoryRoutes,
// inputSlot, retentionSlot).
//
// Only lemmas whose irregularity a learner MEETS — the app's own A1/A2 content
// uses every one of these. A lemma absent from here gets the computed regular
// table from the rules, and that table says it was computed.

import type { Gender } from './croatianMorphologyTypes';

export type Table = Record<string, string>;

export const IRREGULAR: Record<string, { gender: Gender; table: Table; note: string }> = {
  čovjek: {
    gender: 'm',
    note: 'The plural is supplied by a different word, ljudi.',
    table: {
      Nsg: 'čovjek',
      Gsg: 'čovjeka',
      Dsg: 'čovjeku',
      Asg: 'čovjeka',
      Vsg: 'čovječe',
      Lsg: 'čovjeku',
      Isg: 'čovjekom',
      Npl: 'ljudi',
      Gpl: 'ljudi',
      Dpl: 'ljudima',
      Apl: 'ljude',
      Vpl: 'ljudi',
      Lpl: 'ljudima',
      Ipl: 'ljudima',
    },
  },
  dijete: {
    gender: 'n',
    note: 'The plural djeca is a feminine singular collective: djeca su… is wrong, djeca je… is right in strict usage, though djeca su is now standard.',
    table: {
      Nsg: 'dijete',
      Gsg: 'djeteta',
      Dsg: 'djetetu',
      Asg: 'dijete',
      Vsg: 'dijete',
      Lsg: 'djetetu',
      Isg: 'djetetom',
      Npl: 'djeca',
      Gpl: 'djece',
      Dpl: 'djeci',
      Apl: 'djecu',
      Vpl: 'djeco',
      Lpl: 'djeci',
      Ipl: 'djecom',
    },
  },
  brat: {
    gender: 'm',
    note: 'The plural braća is a collective and behaves like a feminine singular.',
    table: {
      Nsg: 'brat',
      Gsg: 'brata',
      Dsg: 'bratu',
      Asg: 'brata',
      Vsg: 'brate',
      Lsg: 'bratu',
      Isg: 'bratom',
      Npl: 'braća',
      Gpl: 'braće',
      Dpl: 'braći',
      Apl: 'braću',
      Vpl: 'braćo',
      Lpl: 'braći',
      Ipl: 'braćom',
    },
  },
  ime: {
    gender: 'n',
    note: 'An n-stem: every case except the nominative and accusative singular adds -en-.',
    table: {
      Nsg: 'ime',
      Gsg: 'imena',
      Dsg: 'imenu',
      Asg: 'ime',
      Vsg: 'ime',
      Lsg: 'imenu',
      Isg: 'imenom',
      Npl: 'imena',
      Gpl: 'imena',
      Dpl: 'imenima',
      Apl: 'imena',
      Vpl: 'imena',
      Lpl: 'imenima',
      Ipl: 'imenima',
    },
  },
  vrijeme: {
    gender: 'n',
    note: 'An n-stem, and the ije shortens to e in every other form: vremena, vremenu. Those are standard Croatian, not Serbian.',
    table: {
      Nsg: 'vrijeme',
      Gsg: 'vremena',
      Dsg: 'vremenu',
      Asg: 'vrijeme',
      Vsg: 'vrijeme',
      Lsg: 'vremenu',
      Isg: 'vremenom',
      Npl: 'vremena',
      Gpl: 'vremena',
      Dpl: 'vremenima',
      Apl: 'vremena',
      Vpl: 'vremena',
      Lpl: 'vremenima',
      Ipl: 'vremenima',
    },
  },
  oko: {
    gender: 'n',
    note: 'The body-part plural is oči and declines like a feminine i-noun.',
    table: {
      Nsg: 'oko',
      Gsg: 'oka',
      Dsg: 'oku',
      Asg: 'oko',
      Vsg: 'oko',
      Lsg: 'oku',
      Isg: 'okom',
      Npl: 'oči',
      Gpl: 'očiju',
      Dpl: 'očima',
      Apl: 'oči',
      Vpl: 'oči',
      Lpl: 'očima',
      Ipl: 'očima',
    },
  },
  uho: {
    gender: 'n',
    note: 'The body-part plural is uši and declines like a feminine i-noun.',
    table: {
      Nsg: 'uho',
      Gsg: 'uha',
      Dsg: 'uhu',
      Asg: 'uho',
      Vsg: 'uho',
      Lsg: 'uhu',
      Isg: 'uhom',
      Npl: 'uši',
      Gpl: 'ušiju',
      Dpl: 'ušima',
      Apl: 'uši',
      Vpl: 'uši',
      Lpl: 'ušima',
      Ipl: 'ušima',
    },
  },
  ruka: {
    gender: 'f',
    note: 'Regular except the genitive plural ruku, which has no added -a.',
    table: {
      Nsg: 'ruka',
      Gsg: 'ruke',
      Dsg: 'ruci',
      Asg: 'ruku',
      Vsg: 'ruko',
      Lsg: 'ruci',
      Isg: 'rukom',
      Npl: 'ruke',
      Gpl: 'ruku',
      Dpl: 'rukama',
      Apl: 'ruke',
      Vpl: 'ruke',
      Lpl: 'rukama',
      Ipl: 'rukama',
    },
  },
  noga: {
    gender: 'f',
    note: 'Regular except the genitive plural nogu.',
    table: {
      Nsg: 'noga',
      Gsg: 'noge',
      Dsg: 'nozi',
      Asg: 'nogu',
      Vsg: 'nogo',
      Lsg: 'nozi',
      Isg: 'nogom',
      Npl: 'noge',
      Gpl: 'nogu',
      Dpl: 'nogama',
      Apl: 'noge',
      Vpl: 'noge',
      Lpl: 'nogama',
      Ipl: 'nogama',
    },
  },
  // ── The fleeting -a in -ak is LEXICAL, in BOTH directions (2026-09-23) ──
  // The rule drops the a for polysyllabic -ac/-ak, which is right for početak,
  // zaključak, naglasak and podatak — and WRONG for korak and stručnjak, which
  // keep it. It also cannot know that dolazak devoices its z (dolasku, never
  // dolazku), that tjedan has a fleeting a outside the -ac/-ak scope, or that
  // podatak sibilarizes to podacima rather than podatcima. Found by printing
  // every form before authoring speaking data; `decline()` also backs the
  // tap-a-word sheet, so all five were being shown to learners. There is no
  // rule that gets this right — the list is the mechanism, and it can only grow.
  korak: {
    gender: 'm',
    note: 'The a does NOT drop — korak, koraka, koraku. Sibilarization still reaches the -i and -ima plurals: koraci, koracima.',
    table: {
      Nsg: 'korak',
      Gsg: 'koraka',
      Dsg: 'koraku',
      Asg: 'korak',
      Vsg: 'korače',
      Lsg: 'koraku',
      Isg: 'korakom',
      Npl: 'koraci',
      Gpl: 'koraka',
      Dpl: 'koracima',
      Apl: 'korake',
      Vpl: 'koraci',
      Lpl: 'koracima',
      Ipl: 'koracima',
    },
  },
  stručnjak: {
    gender: 'm',
    note: 'An agent noun in -njak: the a stays — stručnjaka, not strucnjka. Animate, so the accusative copies the genitive.',
    table: {
      Nsg: 'stručnjak',
      Gsg: 'stručnjaka',
      Dsg: 'stručnjaku',
      Asg: 'stručnjaka',
      Vsg: 'stručnjače',
      Lsg: 'stručnjaku',
      Isg: 'stručnjakom',
      Npl: 'stručnjaci',
      Gpl: 'stručnjaka',
      Dpl: 'stručnjacima',
      Apl: 'stručnjake',
      Vpl: 'stručnjaci',
      Lpl: 'stručnjacima',
      Ipl: 'stručnjacima',
    },
  },
  dolazak: {
    gender: 'm',
    note: 'The a drops AND the z devoices to s before the k: dolazak, dolaska, dolasku.',
    table: {
      Nsg: 'dolazak',
      Gsg: 'dolaska',
      Dsg: 'dolasku',
      Asg: 'dolazak',
      Vsg: 'dolazak',
      Lsg: 'dolasku',
      Isg: 'dolaskom',
      Npl: 'dolasci',
      Gpl: 'dolazaka',
      Dpl: 'dolascima',
      Apl: 'dolaske',
      Vpl: 'dolasci',
      Lpl: 'dolascima',
      Ipl: 'dolascima',
    },
  },
  tjedan: {
    gender: 'm',
    note: 'A fleeting a in -an, outside the -ac/-ak scope of the rule: tjedan, tjedna, tjednu.',
    table: {
      Nsg: 'tjedan',
      Gsg: 'tjedna',
      Dsg: 'tjednu',
      Asg: 'tjedan',
      Vsg: 'tjedne',
      Lsg: 'tjednu',
      Isg: 'tjednom',
      Npl: 'tjedni',
      Gpl: 'tjedana',
      Dpl: 'tjednima',
      Apl: 'tjedne',
      Vpl: 'tjedni',
      Lpl: 'tjednima',
      Ipl: 'tjednima',
    },
  },
  podatak: {
    gender: 'm',
    note: 'The a drops in the singular (podatka) and the plural sibilarizes to podaci/podacima — the k softens to c, it is not kept beside one.',
    table: {
      Nsg: 'podatak',
      Gsg: 'podatka',
      Dsg: 'podatku',
      Asg: 'podatak',
      Vsg: 'podatak',
      Lsg: 'podatku',
      Isg: 'podatkom',
      Npl: 'podaci',
      Gpl: 'podataka',
      Dpl: 'podacima',
      Apl: 'podatke',
      Vpl: 'podaci',
      Lpl: 'podacima',
      Ipl: 'podacima',
    },
  },
  // ── Fleeting -a in -ar nouns (2026-09-23) ────────────────────────────────
  // The general fleeting-a rule is deliberately scoped to polysyllabic -ac/-ak,
  // because stated generally it turns `grad` into `grd`. These -ar nouns drop
  // the a too, and the class is LEXICAL — `mornar` and `zidar` keep theirs — so
  // it can only be a list, never a rule. Found by verifying every form before
  // authoring speaking data: the engine produced `u centaru`, which is not
  // Croatian, and `decline()` also backs the tap-a-word sheet, so that paradigm
  // was being shown to learners.
  centar: {
    gender: 'm',
    note: 'The a drops in every oblique form: centar, centra, centru — never centaru. It comes back in the genitive plural, centara.',
    table: {
      Nsg: 'centar',
      Gsg: 'centra',
      Dsg: 'centru',
      Asg: 'centar',
      Vsg: 'centre',
      Lsg: 'centru',
      Isg: 'centrom',
      Npl: 'centri',
      Gpl: 'centara',
      Dpl: 'centrima',
      Apl: 'centre',
      Vpl: 'centri',
      Lpl: 'centrima',
      Ipl: 'centrima',
    },
  },
  metar: {
    gender: 'm',
    note: 'Same fleeting a as centar: metar, metra, metru.',
    table: {
      Nsg: 'metar',
      Gsg: 'metra',
      Dsg: 'metru',
      Asg: 'metar',
      Vsg: 'metre',
      Lsg: 'metru',
      Isg: 'metrom',
      Npl: 'metri',
      Gpl: 'metara',
      Dpl: 'metrima',
      Apl: 'metre',
      Vpl: 'metri',
      Lpl: 'metrima',
      Ipl: 'metrima',
    },
  },
  litar: {
    gender: 'm',
    note: 'Same fleeting a as centar: litar, litra, litru.',
    table: {
      Nsg: 'litar',
      Gsg: 'litra',
      Dsg: 'litru',
      Asg: 'litar',
      Vsg: 'litre',
      Lsg: 'litru',
      Isg: 'litrom',
      Npl: 'litri',
      Gpl: 'litara',
      Dpl: 'litrima',
      Apl: 'litre',
      Vpl: 'litri',
      Lpl: 'litrima',
      Ipl: 'litrima',
    },
  },
  vjetar: {
    gender: 'm',
    note: 'The a drops, and the plural takes the long -ovi: vjetar, vjetra, vjetrovi.',
    table: {
      Nsg: 'vjetar',
      Gsg: 'vjetra',
      Dsg: 'vjetru',
      Asg: 'vjetar',
      Vsg: 'vjetre',
      Lsg: 'vjetru',
      Isg: 'vjetrom',
      Npl: 'vjetrovi',
      Gpl: 'vjetrova',
      Dpl: 'vjetrovima',
      Apl: 'vjetrove',
      Vpl: 'vjetrovi',
      Lpl: 'vjetrovima',
      Ipl: 'vjetrovima',
    },
  },
  ministar: {
    gender: 'm',
    note: 'The a drops, and it is animate, so the accusative singular copies the genitive: ministra.',
    table: {
      Nsg: 'ministar',
      Gsg: 'ministra',
      Dsg: 'ministru',
      Asg: 'ministra',
      Vsg: 'ministre',
      Lsg: 'ministru',
      Isg: 'ministrom',
      Npl: 'ministri',
      Gpl: 'ministara',
      Dpl: 'ministrima',
      Apl: 'ministre',
      Vpl: 'ministri',
      Lpl: 'ministrima',
      Ipl: 'ministrima',
    },
  },
  otac: {
    gender: 'm',
    note: 'The a drops AND so does the t: otac, oca, ocu. The vocative oče is the form you hear in prayers and in speech to a father.',
    table: {
      Nsg: 'otac',
      Gsg: 'oca',
      Dsg: 'ocu',
      Asg: 'oca',
      Vsg: 'oče',
      Lsg: 'ocu',
      Isg: 'ocem',
      Npl: 'očevi',
      Gpl: 'očeva',
      Dpl: 'očevima',
      Apl: 'očeve',
      Vpl: 'očevi',
      Lpl: 'očevima',
      Ipl: 'očevima',
    },
  },
  pas: {
    gender: 'm',
    note: 'A monosyllable that still loses its a: pas, psa, psu. It is animate, so the accusative singular copies the genitive.',
    table: {
      Nsg: 'pas',
      Gsg: 'psa',
      Dsg: 'psu',
      Asg: 'psa',
      Vsg: 'pse',
      Lsg: 'psu',
      Isg: 'psom',
      Npl: 'psi',
      Gpl: 'pasa',
      Dpl: 'psima',
      Apl: 'pse',
      Vpl: 'psi',
      Lpl: 'psima',
      Ipl: 'psima',
    },
  },
  kći: {
    gender: 'f',
    note: 'An i-declension noun with a -er- stem everywhere but the nominative singular.',
    table: {
      Nsg: 'kći',
      Gsg: 'kćeri',
      Dsg: 'kćeri',
      Asg: 'kćer',
      Vsg: 'kćeri',
      Lsg: 'kćeri',
      Isg: 'kćeri',
      Npl: 'kćeri',
      Gpl: 'kćeri',
      Dpl: 'kćerima',
      Apl: 'kćeri',
      Vpl: 'kćeri',
      Lpl: 'kćerima',
      Ipl: 'kćerima',
    },
  },
  mati: {
    gender: 'f',
    note: 'An i-declension noun with a -er- stem; majka is the everyday word.',
    table: {
      Nsg: 'mati',
      Gsg: 'matere',
      Dsg: 'materi',
      Asg: 'mater',
      Vsg: 'mati',
      Lsg: 'materi',
      Isg: 'materom',
      Npl: 'matere',
      Gpl: 'matera',
      Dpl: 'materama',
      Apl: 'matere',
      Vpl: 'matere',
      Lpl: 'materama',
      Ipl: 'materama',
    },
  },
};
