// src/lib/croatianIrregulars.ts
//
// Irregular noun paradigms, split out of `croatianMorphology.ts` when that file
// reached the 800-line lint cap. Data only — no behaviour moved, and the cap was
// not raised (the precedent: sessionPools, croatiaPool, categoryRoutes,
// inputSlot, retentionSlot).
//
// Only lemmas whose irregularity a learner MEETS — the app's own A1/A2 content
// uses every one of these. A lemma absent from here gets the computed regular
// table from the rules, and that table says it was computed.

import type { Gender } from './croatianMorphologyTypes';

export type Table = Record<string, string>;

export const IRREGULAR: Record<string, { gender: Gender; table: Table; note: string }> = {
  čovjek: {
    gender: 'm',
    note: 'The plural is supplied by a different word, ljudi.',
    table: {
      Nsg: 'čovjek',
      Gsg: 'čovjeka',
      Dsg: 'čovjeku',
      Asg: 'čovjeka',
      Vsg: 'čovječe',
      Lsg: 'čovjeku',
      Isg: 'čovjekom',
      Npl: 'ljudi',
      Gpl: 'ljudi',
      Dpl: 'ljudima',
      Apl: 'ljude',
      Vpl: 'ljudi',
      Lpl: 'ljudima',
      Ipl: 'ljudima',
    },
  },
  dijete: {
    gender: 'n',
    note: 'The plural djeca is a feminine singular collective: djeca su… is wrong, djeca je… is right in strict usage, though djeca su is now standard.',
    table: {
      Nsg: 'dijete',
      Gsg: 'djeteta',
      Dsg: 'djetetu',
      Asg: 'dijete',
      Vsg: 'dijete',
      Lsg: 'djetetu',
      Isg: 'djetetom',
      Npl: 'djeca',
      Gpl: 'djece',
      Dpl: 'djeci',
      Apl: 'djecu',
      Vpl: 'djeco',
      Lpl: 'djeci',
      Ipl: 'djecom',
    },
  },
  brat: {
    gender: 'm',
    note: 'The plural braća is a collective and behaves like a feminine singular.',
    table: {
      Nsg: 'brat',
      Gsg: 'brata',
      Dsg: 'bratu',
      Asg: 'brata',
      Vsg: 'brate',
      Lsg: 'bratu',
      Isg: 'bratom',
      Npl: 'braća',
      Gpl: 'braće',
      Dpl: 'braći',
      Apl: 'braću',
      Vpl: 'braćo',
      Lpl: 'braći',
      Ipl: 'braćom',
    },
  },
  ime: {
    gender: 'n',
    note: 'An n-stem: every case except the nominative and accusative singular adds -en-.',
    table: {
      Nsg: 'ime',
      Gsg: 'imena',
      Dsg: 'imenu',
      Asg: 'ime',
      Vsg: 'ime',
      Lsg: 'imenu',
      Isg: 'imenom',
      Npl: 'imena',
      Gpl: 'imena',
      Dpl: 'imenima',
      Apl: 'imena',
      Vpl: 'imena',
      Lpl: 'imenima',
      Ipl: 'imenima',
    },
  },
  vrijeme: {
    gender: 'n',
    note: 'An n-stem, and the ije shortens to e in every other form: vremena, vremenu. Those are standard Croatian, not Serbian.',
    table: {
      Nsg: 'vrijeme',
      Gsg: 'vremena',
      Dsg: 'vremenu',
      Asg: 'vrijeme',
      Vsg: 'vrijeme',
      Lsg: 'vremenu',
      Isg: 'vremenom',
      Npl: 'vremena',
      Gpl: 'vremena',
      Dpl: 'vremenima',
      Apl: 'vremena',
      Vpl: 'vremena',
      Lpl: 'vremenima',
      Ipl: 'vremenima',
    },
  },
  oko: {
    gender: 'n',
    note: 'The body-part plural is oči and declines like a feminine i-noun.',
    table: {
      Nsg: 'oko',
      Gsg: 'oka',
      Dsg: 'oku',
      Asg: 'oko',
      Vsg: 'oko',
      Lsg: 'oku',
      Isg: 'okom',
      Npl: 'oči',
      Gpl: 'očiju',
      Dpl: 'očima',
      Apl: 'oči',
      Vpl: 'oči',
      Lpl: 'očima',
      Ipl: 'očima',
    },
  },
  uho: {
    gender: 'n',
    note: 'The body-part plural is uši and declines like a feminine i-noun.',
    table: {
      Nsg: 'uho',
      Gsg: 'uha',
      Dsg: 'uhu',
      Asg: 'uho',
      Vsg: 'uho',
      Lsg: 'uhu',
      Isg: 'uhom',
      Npl: 'uši',
      Gpl: 'ušiju',
      Dpl: 'ušima',
      Apl: 'uši',
      Vpl: 'uši',
      Lpl: 'ušima',
      Ipl: 'ušima',
    },
  },
  ruka: {
    gender: 'f',
    note: 'Regular except the genitive plural ruku, which has no added -a.',
    table: {
      Nsg: 'ruka',
      Gsg: 'ruke',
      Dsg: 'ruci',
      Asg: 'ruku',
      Vsg: 'ruko',
      Lsg: 'ruci',
      Isg: 'rukom',
      Npl: 'ruke',
      Gpl: 'ruku',
      Dpl: 'rukama',
      Apl: 'ruke',
      Vpl: 'ruke',
      Lpl: 'rukama',
      Ipl: 'rukama',
    },
  },
  noga: {
    gender: 'f',
    note: 'Regular except the genitive plural nogu.',
    table: {
      Nsg: 'noga',
      Gsg: 'noge',
      Dsg: 'nozi',
      Asg: 'nogu',
      Vsg: 'nogo',
      Lsg: 'nozi',
      Isg: 'nogom',
      Npl: 'noge',
      Gpl: 'nogu',
      Dpl: 'nogama',
      Apl: 'noge',
      Vpl: 'noge',
      Lpl: 'nogama',
      Ipl: 'nogama',
    },
  },
  otac: {
    gender: 'm',
    note: 'The a drops AND so does the t: otac, oca, ocu. The vocative oče is the form you hear in prayers and in speech to a father.',
    table: {
      Nsg: 'otac',
      Gsg: 'oca',
      Dsg: 'ocu',
      Asg: 'oca',
      Vsg: 'oče',
      Lsg: 'ocu',
      Isg: 'ocem',
      Npl: 'očevi',
      Gpl: 'očeva',
      Dpl: 'očevima',
      Apl: 'očeve',
      Vpl: 'očevi',
      Lpl: 'očevima',
      Ipl: 'očevima',
    },
  },
  pas: {
    gender: 'm',
    note: 'A monosyllable that still loses its a: pas, psa, psu. It is animate, so the accusative singular copies the genitive.',
    table: {
      Nsg: 'pas',
      Gsg: 'psa',
      Dsg: 'psu',
      Asg: 'psa',
      Vsg: 'pse',
      Lsg: 'psu',
      Isg: 'psom',
      Npl: 'psi',
      Gpl: 'pasa',
      Dpl: 'psima',
      Apl: 'pse',
      Vpl: 'psi',
      Lpl: 'psima',
      Ipl: 'psima',
    },
  },
  kći: {
    gender: 'f',
    note: 'An i-declension noun with a -er- stem everywhere but the nominative singular.',
    table: {
      Nsg: 'kći',
      Gsg: 'kćeri',
      Dsg: 'kćeri',
      Asg: 'kćer',
      Vsg: 'kćeri',
      Lsg: 'kćeri',
      Isg: 'kćeri',
      Npl: 'kćeri',
      Gpl: 'kćeri',
      Dpl: 'kćerima',
      Apl: 'kćeri',
      Vpl: 'kćeri',
      Lpl: 'kćerima',
      Ipl: 'kćerima',
    },
  },
  mati: {
    gender: 'f',
    note: 'An i-declension noun with a -er- stem; majka is the everyday word.',
    table: {
      Nsg: 'mati',
      Gsg: 'matere',
      Dsg: 'materi',
      Asg: 'mater',
      Vsg: 'mati',
      Lsg: 'materi',
      Isg: 'materom',
      Npl: 'matere',
      Gpl: 'matera',
      Dpl: 'materama',
      Apl: 'matere',
      Vpl: 'matere',
      Lpl: 'materama',
      Ipl: 'materama',
    },
  },
};
