// exerciseDifficulty — structural difficulty tiers for the Priority-3 fill
// sort. Split from sessionPools.ts (max-lines) as the drill pools grow
// toward the 30-per-level program target. Re-exported from sessionPools for
// import stability.
// Structural difficulty tier per session exercise type (1 = recognition …
// 5 = open production), mirroring exerciseMeta's scale. Used to bias the daily
// Priority-3 fill toward the user's ability so content scales as they advance
// (defect #1: difficulty was inert — nothing consumed difficulty tiers). Any id
// not listed defaults to tier 3.
export const EXERCISE_DIFFICULTY: Record<string, number> = {
  flashcards: 1,
  mcgame: 1,
  match: 1,
  review: 2,
  qwords: 2,
  genderdrill: 2,
  nomdrill: 2,
  unjumble: 2,
  negation: 2,
  znam: 3,
  cloze: 3,
  prepdrill: 3,
  genitivedrill: 3,
  locdrill: 3,
  sentencetiles: 3,
  typing: 3,
  accusativedrill: 3,
  future: 3,
  comparatives: 3,
  dictation: 3,
  sentbuild: 4,
  aspectdrill: 4,
  clitic: 4,
  instrumental: 3,
  dative: 3,
  animateacc: 3,
  numcases: 4,
  passive: 4,
  participles: 4,
  subordination: 4,
  conditionaldrill: 4,
  idiomdrill: 4,
  discourse: 4,
  register: 4,
  nominalization: 4,
  listeningComprehension: 3,
  aiListening: 4,
  // 7a additions — recognition/matching games tier 1-2, guided drills tier 2-3.
  boje: 1,
  wordsprint: 1,
  numtime: 2,
  possess: 2,
  cityloc: 2,
  coloragree: 2,
  imperative: 3,
  neggen: 3,
  c2drill: 5,
  gerunddrill: 5,
  preciznost: 5,
  futur2: 4,
  bezlicne: 4,
  neodredjene: 4,
  slaganjebrojeva: 4,
  posudjenice: 5,
  glasovnepromjene: 5,
  administrativni: 5,
  kolokacije: 5,
  pogodbene: 5,
  odredjenost: 4,
  datumi: 4,
  povratni: 4,
  sklonidbaimena: 4,
  prijedlozni: 4,
  frazeologija: 5,
  tvorbarijeci: 5,
  sinonimija: 5,
  emfaza: 5,
  vidnijanse: 4,
  neizravni: 4,
  kretanje: 4,
  // Wave 1 additions — recognition games tier 2, guided drills tier 3.
  declension: 3,
  padezi: 3,
  vocative: 3,
  ordinals: 2,
  pronouns: 2,
  modal: 2,
  conjdrill: 3,
  verbdrill: 3,
  fillstory: 3,
  emogender: 2,
  profgender: 2,
  proncontrast: 2,
  vocabscenes: 2,
  reflexive: 3,
  tenseflip: 3,
  casetransformer: 3,
  relpron: 3,
  svojmoj: 3,
  diminutives: 2,
  wordfamilies: 3,
  collocations: 3,
  riddles: 2,
  logicquiz: 2,
  translate_drills: 3,
  wordform: 3,
  // Wave 2 additions — recognition game tier 2, morphophonology drill tier 3.
  alka: 2,
  sibil: 3,
  // Wave 3 additions — comprehension tiers 2-3, guided production tier 4.
  gradedreader: 3,
  aistory: 3,
  listeninggame: 2,
  conjpractice: 3,
  phonemes: 2,
  roleplay: 4,
  // Wave 4a — graded reference-group screens.
  alphabet: 1,
  convmatch: 2,
  falsefr: 1,
  phonology: 2,
  padezifull: 3,
  aspectlesson: 3,
  conditionallesson: 3,
  tenses: 3,
  texting: 2,
  formalregister: 3,
  impersonal: 4,
  techvoc: 2,
  pitchaccent: 4,
  // Wave 4b — reference (browse) entries, recognition tiers.
  opposites: 1,
  clothes: 1,
  weather: 1,
  bodydesc: 2,
  countries: 2,
  professions: 2,
  lifeevents: 2,
  brzalice: 2,
  tivicompare: 2,
  colorquirk: 2,
  idioms: 2,
  // Wave 5 — lessons tier 2 (guided teaching), drills/quizzes tier 3-4.
  animlesson: 2,
  fleetinga: 4,
  future_tense_lesson: 3,
  past_tense_lesson: 3,
  video_lesson: 3,
  // Wave 6 — hub-embedded drills.
  adaptive_review: 3,
  mistakes: 2,
  frequency_track: 2,
  pronunciation_course: 2,
  // Wave 7 — AI-cost admissions.
  aiconvo: 5,
  grammarexplainer: 3,
  micro_lesson: 3,
  grammarreader: 3,
  // Wave 8 — AI tutors, open production.
  maja: 5,
  live_tutor: 5,
  // Wave 9 — redesigned-for-completion screens.
  storymode: 3,
  pronunciation_assess: 4,
};
