// frequency500.ts — the most common Croatian words ranked by corpus frequency.
// Currently ranks 1-1250 (2026-07 content expansion extended the original 500;
// the FREQUENCY_500 export name is kept for its existing consumers). Ordering
// within a band is approximate across corpora; band membership is the signal.
// Each entry: { rank, hr, en, pos }
// POS: 'conj' | 'prep' | 'pron' | 'verb' | 'noun' | 'adj' | 'adv' | 'det' | 'num' | 'part' | 'interj'

export type PartOfSpeech =
  'conj' | 'prep' | 'pron' | 'verb' | 'noun' | 'adj' | 'adv' | 'det' | 'num' | 'part' | 'interj';

export interface FrequencyEntry {
  rank: number;
  hr: string;
  en: string;
  pos: PartOfSpeech;
}

export const FREQUENCY_500: FrequencyEntry[] = [
  { rank: 1, hr: 'i', en: 'and', pos: 'conj' },
  { rank: 2, hr: 'je', en: 'is', pos: 'verb' },
  { rank: 3, hr: 'u', en: 'in / into', pos: 'prep' },
  { rank: 4, hr: 'se', en: 'reflexive particle', pos: 'part' },
  { rank: 5, hr: 'da', en: 'that / yes', pos: 'conj' },
  { rank: 6, hr: 'na', en: 'on / at', pos: 'prep' },
  { rank: 7, hr: 'ne', en: 'not / no', pos: 'part' },
  { rank: 8, hr: 'što', en: 'what / that', pos: 'pron' },
  { rank: 9, hr: 'koji', en: 'which / who (m)', pos: 'pron' },
  { rank: 10, hr: 'biti', en: 'to be', pos: 'verb' },
  { rank: 11, hr: 'imati', en: 'to have', pos: 'verb' },
  { rank: 12, hr: 'za', en: 'for', pos: 'prep' },
  { rank: 13, hr: 'od', en: 'from / of', pos: 'prep' },
  { rank: 14, hr: 'sa', en: 'with', pos: 'prep' },
  { rank: 15, hr: 'kao', en: 'as / like', pos: 'conj' },
  { rank: 16, hr: 'ali', en: 'but', pos: 'conj' },
  { rank: 17, hr: 'ili', en: 'or', pos: 'conj' },
  { rank: 18, hr: 'pa', en: 'so / and then', pos: 'conj' },
  { rank: 19, hr: 'ni', en: 'nor / not even', pos: 'conj' },
  { rank: 20, hr: 'te', en: 'and / which', pos: 'conj' },
  { rank: 21, hr: 'ako', en: 'if', pos: 'conj' },
  { rank: 22, hr: 'jer', en: 'because', pos: 'conj' },
  { rank: 23, hr: 'već', en: 'already / but', pos: 'adv' },
  { rank: 24, hr: 'samo', en: 'only / just', pos: 'adv' },
  { rank: 25, hr: 'još', en: 'still / more / yet', pos: 'adv' },
  { rank: 26, hr: 'tako', en: 'so / thus', pos: 'adv' },
  { rank: 27, hr: 'sve', en: 'everything / all', pos: 'pron' },
  { rank: 28, hr: 'kroz', en: 'through', pos: 'prep' },
  { rank: 29, hr: 'po', en: 'along / per / after', pos: 'prep' },
  { rank: 30, hr: 'do', en: 'to / until', pos: 'prep' },
  { rank: 31, hr: 'iz', en: 'from / out of', pos: 'prep' },
  { rank: 32, hr: 'o', en: 'about', pos: 'prep' },
  { rank: 33, hr: 'između', en: 'between', pos: 'prep' },
  { rank: 34, hr: 'može', en: 'can / is able', pos: 'verb' },
  { rank: 35, hr: 'ovo', en: 'this (n)', pos: 'pron' },
  { rank: 36, hr: 'taj', en: 'that (m)', pos: 'det' },
  { rank: 37, hr: 'ti', en: 'you (sg)', pos: 'pron' },
  { rank: 38, hr: 'ja', en: 'I', pos: 'pron' },
  { rank: 39, hr: 'on', en: 'he', pos: 'pron' },
  { rank: 40, hr: 'ona', en: 'she', pos: 'pron' },
  { rank: 41, hr: 'oni', en: 'they (m)', pos: 'pron' },
  { rank: 42, hr: 'mi', en: 'we', pos: 'pron' },
  { rank: 43, hr: 'vi', en: 'you (pl/formal)', pos: 'pron' },
  { rank: 44, hr: 'to', en: 'that / it', pos: 'pron' },
  { rank: 45, hr: 'tu', en: 'here / there', pos: 'adv' },
  { rank: 46, hr: 'gdje', en: 'where', pos: 'adv' },
  { rank: 47, hr: 'kada', en: 'when', pos: 'adv' },
  { rank: 48, hr: 'kako', en: 'how', pos: 'adv' },
  { rank: 49, hr: 'koliko', en: 'how much / how many', pos: 'adv' },
  { rank: 50, hr: 'čiji', en: 'whose', pos: 'pron' },
  { rank: 51, hr: 'tko', en: 'who', pos: 'pron' },
  { rank: 52, hr: 'li', en: 'question particle', pos: 'part' },
  { rank: 53, hr: 'bi', en: 'would (conditional)', pos: 'verb' },
  { rank: 54, hr: 'će', en: 'will (future)', pos: 'verb' },
  { rank: 55, hr: 'su', en: 'are (3pl)', pos: 'verb' },
  { rank: 56, hr: 'smo', en: 'we are', pos: 'verb' },
  { rank: 57, hr: 'ste', en: 'you are (pl)', pos: 'verb' },
  { rank: 58, hr: 'sam', en: 'I am', pos: 'verb' },
  { rank: 59, hr: 'si', en: 'you are (sg)', pos: 'verb' },
  { rank: 60, hr: 'nije', en: 'is not', pos: 'verb' },
  { rank: 61, hr: 'nema', en: 'there is no / has no', pos: 'verb' },
  { rank: 62, hr: 'ima', en: 'there is / has', pos: 'verb' },
  { rank: 63, hr: 'mogu', en: 'I can / they can', pos: 'verb' },
  { rank: 64, hr: 'treba', en: 'needs / should', pos: 'verb' },
  { rank: 65, hr: 'mora', en: 'must', pos: 'verb' },
  { rank: 66, hr: 'želi', en: 'wants', pos: 'verb' },
  { rank: 67, hr: 'voli', en: 'loves / likes', pos: 'verb' },
  { rank: 68, hr: 'zna', en: 'knows', pos: 'verb' },
  { rank: 69, hr: 'ide', en: 'goes', pos: 'verb' },
  { rank: 70, hr: 'dolazi', en: 'comes / arrives', pos: 'verb' },
  { rank: 71, hr: 'kaže', en: 'says', pos: 'verb' },
  { rank: 72, hr: 'misli', en: 'thinks', pos: 'verb' },
  { rank: 73, hr: 'radi', en: 'works / does', pos: 'verb' },
  { rank: 74, hr: 'daje', en: 'gives', pos: 'verb' },
  { rank: 75, hr: 'uzima', en: 'takes', pos: 'verb' },
  { rank: 76, hr: 'vidi', en: 'sees', pos: 'verb' },
  { rank: 77, hr: 'čuje', en: 'hears', pos: 'verb' },
  { rank: 78, hr: 'pita', en: 'asks', pos: 'verb' },
  { rank: 79, hr: 'odgovara', en: 'answers / corresponds', pos: 'verb' },
  { rank: 80, hr: 'stoji', en: 'stands / costs', pos: 'verb' },
  { rank: 81, hr: 'sjedi', en: 'sits', pos: 'verb' },
  { rank: 82, hr: 'leži', en: 'lies (down)', pos: 'verb' },
  { rank: 83, hr: 'čeka', en: 'waits', pos: 'verb' },
  { rank: 84, hr: 'traži', en: 'searches / seeks', pos: 'verb' },
  { rank: 85, hr: 'nalazi', en: 'finds', pos: 'verb' },
  { rank: 86, hr: 'vraća', en: 'returns', pos: 'verb' },
  { rank: 87, hr: 'ostavlja', en: 'leaves / abandons', pos: 'verb' },
  { rank: 88, hr: 'počinje', en: 'begins', pos: 'verb' },
  { rank: 89, hr: 'završava', en: 'ends / finishes', pos: 'verb' },
  { rank: 90, hr: 'piše', en: 'writes', pos: 'verb' },
  { rank: 91, hr: 'čita', en: 'reads', pos: 'verb' },
  { rank: 92, hr: 'govori', en: 'speaks / says', pos: 'verb' },
  { rank: 93, hr: 'uči', en: 'learns / studies', pos: 'verb' },
  { rank: 94, hr: 'igra', en: 'plays', pos: 'verb' },
  { rank: 95, hr: 'živi', en: 'lives', pos: 'verb' },
  { rank: 96, hr: 'čovjek', en: 'man / person', pos: 'noun' },
  { rank: 97, hr: 'žena', en: 'woman / wife', pos: 'noun' },
  { rank: 98, hr: 'dijete', en: 'child', pos: 'noun' },
  { rank: 99, hr: 'otac', en: 'father', pos: 'noun' },
  { rank: 100, hr: 'majka', en: 'mother', pos: 'noun' },
  { rank: 101, hr: 'brat', en: 'brother', pos: 'noun' },
  { rank: 102, hr: 'sestra', en: 'sister', pos: 'noun' },
  { rank: 103, hr: 'sin', en: 'son', pos: 'noun' },
  { rank: 104, hr: 'kći', en: 'daughter', pos: 'noun' },
  { rank: 105, hr: 'djed', en: 'grandfather', pos: 'noun' },
  { rank: 106, hr: 'baka', en: 'grandmother', pos: 'noun' },
  { rank: 107, hr: 'muž', en: 'husband', pos: 'noun' },
  { rank: 108, hr: 'prijatelj', en: 'friend (m)', pos: 'noun' },
  { rank: 109, hr: 'prijateljica', en: 'friend (f)', pos: 'noun' },
  { rank: 110, hr: 'dan', en: 'day', pos: 'noun' },
  { rank: 111, hr: 'godina', en: 'year', pos: 'noun' },
  { rank: 112, hr: 'sat', en: 'hour / clock', pos: 'noun' },
  { rank: 113, hr: 'tjedan', en: 'week', pos: 'noun' },
  { rank: 114, hr: 'mjesec', en: 'month / moon', pos: 'noun' },
  { rank: 115, hr: 'noć', en: 'night', pos: 'noun' },
  { rank: 116, hr: 'jutro', en: 'morning', pos: 'noun' },
  { rank: 117, hr: 'večer', en: 'evening', pos: 'noun' },
  { rank: 118, hr: 'podne', en: 'noon', pos: 'noun' },
  { rank: 119, hr: 'sada', en: 'now', pos: 'adv' },
  { rank: 120, hr: 'danas', en: 'today', pos: 'adv' },
  { rank: 121, hr: 'sutra', en: 'tomorrow', pos: 'adv' },
  { rank: 122, hr: 'jučer', en: 'yesterday', pos: 'adv' },
  { rank: 123, hr: 'uvijek', en: 'always', pos: 'adv' },
  { rank: 124, hr: 'nikad', en: 'never', pos: 'adv' },
  { rank: 125, hr: 'često', en: 'often', pos: 'adv' },
  { rank: 126, hr: 'ponekad', en: 'sometimes', pos: 'adv' },
  { rank: 127, hr: 'rijetko', en: 'rarely', pos: 'adv' },
  { rank: 128, hr: 'brzo', en: 'quickly / fast', pos: 'adv' },
  { rank: 129, hr: 'polako', en: 'slowly', pos: 'adv' },
  { rank: 130, hr: 'dobro', en: 'well / good', pos: 'adv' },
  { rank: 131, hr: 'loše', en: 'badly / poorly', pos: 'adv' },
  { rank: 132, hr: 'jako', en: 'very / strongly', pos: 'adv' },
  { rank: 133, hr: 'malo', en: 'a little / few', pos: 'adv' },
  { rank: 134, hr: 'puno', en: 'a lot / much', pos: 'adv' },
  { rank: 135, hr: 'više', en: 'more', pos: 'adv' },
  { rank: 136, hr: 'manje', en: 'less / fewer', pos: 'adv' },
  { rank: 137, hr: 'ovdje', en: 'here', pos: 'adv' },
  { rank: 138, hr: 'tamo', en: 'there', pos: 'adv' },
  { rank: 139, hr: 'gore', en: 'up / upstairs', pos: 'adv' },
  { rank: 140, hr: 'dolje', en: 'down / downstairs', pos: 'adv' },
  { rank: 141, hr: 'lijevo', en: 'left', pos: 'adv' },
  { rank: 142, hr: 'desno', en: 'right', pos: 'adv' },
  { rank: 143, hr: 'naprijed', en: 'forward / ahead', pos: 'adv' },
  { rank: 144, hr: 'natrag', en: 'back / backwards', pos: 'adv' },
  { rank: 145, hr: 'jedan', en: 'one (m)', pos: 'num' },
  { rank: 146, hr: 'dva', en: 'two', pos: 'num' },
  { rank: 147, hr: 'tri', en: 'three', pos: 'num' },
  { rank: 148, hr: 'četiri', en: 'four', pos: 'num' },
  { rank: 149, hr: 'pet', en: 'five', pos: 'num' },
  { rank: 150, hr: 'šest', en: 'six', pos: 'num' },
  { rank: 151, hr: 'sedam', en: 'seven', pos: 'num' },
  { rank: 152, hr: 'osam', en: 'eight', pos: 'num' },
  { rank: 153, hr: 'devet', en: 'nine', pos: 'num' },
  { rank: 154, hr: 'deset', en: 'ten', pos: 'num' },
  { rank: 155, hr: 'sto', en: 'hundred', pos: 'num' },
  { rank: 156, hr: 'tisuća', en: 'thousand', pos: 'num' },
  { rank: 157, hr: 'prvo', en: 'first / firstly', pos: 'adv' },
  { rank: 158, hr: 'drugo', en: 'second / secondly', pos: 'adv' },
  { rank: 159, hr: 'veliki', en: 'big / large', pos: 'adj' },
  { rank: 160, hr: 'mali', en: 'small / little', pos: 'adj' },
  { rank: 161, hr: 'novi', en: 'new', pos: 'adj' },
  { rank: 162, hr: 'stari', en: 'old', pos: 'adj' },
  { rank: 163, hr: 'dobar', en: 'good', pos: 'adj' },
  { rank: 164, hr: 'loš', en: 'bad', pos: 'adj' },
  { rank: 165, hr: 'lijep', en: 'beautiful / nice', pos: 'adj' },
  { rank: 166, hr: 'ružan', en: 'ugly', pos: 'adj' },
  { rank: 167, hr: 'brz', en: 'fast / quick', pos: 'adj' },
  { rank: 168, hr: 'spor', en: 'slow', pos: 'adj' },
  { rank: 169, hr: 'jak', en: 'strong', pos: 'adj' },
  { rank: 170, hr: 'slab', en: 'weak', pos: 'adj' },
  { rank: 171, hr: 'visok', en: 'tall / high', pos: 'adj' },
  { rank: 172, hr: 'nizak', en: 'short / low', pos: 'adj' },
  { rank: 173, hr: 'dug', en: 'long', pos: 'adj' },
  { rank: 174, hr: 'kratak', en: 'short (length)', pos: 'adj' },
  { rank: 175, hr: 'težak', en: 'heavy / difficult', pos: 'adj' },
  { rank: 176, hr: 'lak', en: 'light / easy', pos: 'adj' },
  { rank: 177, hr: 'crven', en: 'red', pos: 'adj' },
  { rank: 178, hr: 'plav', en: 'blue / blond', pos: 'adj' },
  { rank: 179, hr: 'zelen', en: 'green', pos: 'adj' },
  { rank: 180, hr: 'žut', en: 'yellow', pos: 'adj' },
  { rank: 181, hr: 'bijel', en: 'white', pos: 'adj' },
  { rank: 182, hr: 'crn', en: 'black', pos: 'adj' },
  { rank: 183, hr: 'siv', en: 'gray', pos: 'adj' },
  { rank: 184, hr: 'smeđ', en: 'brown', pos: 'adj' },
  { rank: 185, hr: 'narančast', en: 'orange (color)', pos: 'adj' },
  { rank: 186, hr: 'ljubičast', en: 'purple', pos: 'adj' },
  { rank: 187, hr: 'ružičast', en: 'pink', pos: 'adj' },
  { rank: 188, hr: 'kuća', en: 'house', pos: 'noun' },
  { rank: 189, hr: 'stan', en: 'apartment / flat', pos: 'noun' },
  { rank: 190, hr: 'soba', en: 'room', pos: 'noun' },
  { rank: 191, hr: 'kuhinja', en: 'kitchen', pos: 'noun' },
  { rank: 192, hr: 'spavaća', en: 'bedroom', pos: 'noun' },
  { rank: 193, hr: 'kupaonica', en: 'bathroom', pos: 'noun' },
  { rank: 194, hr: 'ulaz', en: 'entrance / hallway', pos: 'noun' },
  { rank: 195, hr: 'prozor', en: 'window', pos: 'noun' },
  { rank: 196, hr: 'vrata', en: 'door', pos: 'noun' },
  { rank: 197, hr: 'stol', en: 'table', pos: 'noun' },
  { rank: 198, hr: 'stolica', en: 'chair', pos: 'noun' },
  { rank: 199, hr: 'krevet', en: 'bed', pos: 'noun' },
  { rank: 200, hr: 'sofa', en: 'sofa / couch', pos: 'noun' },
  { rank: 201, hr: 'grad', en: 'city / town', pos: 'noun' },
  { rank: 202, hr: 'ulica', en: 'street', pos: 'noun' },
  { rank: 203, hr: 'trg', en: 'square / plaza', pos: 'noun' },
  { rank: 204, hr: 'park', en: 'park', pos: 'noun' },
  { rank: 205, hr: 'škola', en: 'school', pos: 'noun' },
  { rank: 206, hr: 'bolnica', en: 'hospital', pos: 'noun' },
  { rank: 207, hr: 'trgovina', en: 'shop / store', pos: 'noun' },
  { rank: 208, hr: 'restoran', en: 'restaurant', pos: 'noun' },
  { rank: 209, hr: 'kafić', en: 'café', pos: 'noun' },
  { rank: 210, hr: 'plaža', en: 'beach', pos: 'noun' },
  { rank: 211, hr: 'more', en: 'sea', pos: 'noun' },
  { rank: 212, hr: 'rijeka', en: 'river', pos: 'noun' },
  { rank: 213, hr: 'planina', en: 'mountain', pos: 'noun' },
  { rank: 214, hr: 'šuma', en: 'forest', pos: 'noun' },
  { rank: 215, hr: 'polje', en: 'field', pos: 'noun' },
  { rank: 216, hr: 'zemlja', en: 'land / earth / country', pos: 'noun' },
  { rank: 217, hr: 'nebo', en: 'sky', pos: 'noun' },
  { rank: 218, hr: 'sunce', en: 'sun', pos: 'noun' },
  { rank: 219, hr: 'svijet', en: 'world', pos: 'noun' },
  { rank: 220, hr: 'zvijezda', en: 'star', pos: 'noun' },
  { rank: 221, hr: 'kiša', en: 'rain', pos: 'noun' },
  { rank: 222, hr: 'snijeg', en: 'snow', pos: 'noun' },
  { rank: 223, hr: 'vjetar', en: 'wind', pos: 'noun' },
  { rank: 224, hr: 'oblak', en: 'cloud', pos: 'noun' },
  { rank: 225, hr: 'temperatura', en: 'temperature', pos: 'noun' },
  { rank: 226, hr: 'topao', en: 'warm', pos: 'adj' },
  { rank: 227, hr: 'hladan', en: 'cold', pos: 'adj' },
  { rank: 228, hr: 'vruć', en: 'hot', pos: 'adj' },
  { rank: 229, hr: 'hladnoća', en: 'coldness / cold weather', pos: 'noun' },
  { rank: 230, hr: 'vrućina', en: 'heat', pos: 'noun' },
  { rank: 231, hr: 'hrana', en: 'food', pos: 'noun' },
  { rank: 232, hr: 'kruh', en: 'bread', pos: 'noun' },
  { rank: 233, hr: 'meso', en: 'meat', pos: 'noun' },
  { rank: 234, hr: 'riba', en: 'fish', pos: 'noun' },
  { rank: 235, hr: 'povrće', en: 'vegetables', pos: 'noun' },
  { rank: 236, hr: 'voće', en: 'fruit', pos: 'noun' },
  { rank: 237, hr: 'jaje', en: 'egg', pos: 'noun' },
  { rank: 238, hr: 'mlijeko', en: 'milk', pos: 'noun' },
  { rank: 239, hr: 'sir', en: 'cheese', pos: 'noun' },
  { rank: 240, hr: 'maslac', en: 'butter', pos: 'noun' },
  { rank: 241, hr: 'šećer', en: 'sugar', pos: 'noun' },
  { rank: 242, hr: 'sol', en: 'salt', pos: 'noun' },
  { rank: 243, hr: 'ulje', en: 'oil', pos: 'noun' },
  { rank: 244, hr: 'voda', en: 'water', pos: 'noun' },
  { rank: 245, hr: 'kava', en: 'coffee', pos: 'noun' },
  { rank: 246, hr: 'čaj', en: 'tea', pos: 'noun' },
  { rank: 247, hr: 'vino', en: 'wine', pos: 'noun' },
  { rank: 248, hr: 'pivo', en: 'beer', pos: 'noun' },
  { rank: 249, hr: 'sok', en: 'juice', pos: 'noun' },
  { rank: 250, hr: 'jabuka', en: 'apple', pos: 'noun' },
  { rank: 251, hr: 'kruška', en: 'pear', pos: 'noun' },
  { rank: 252, hr: 'banana', en: 'banana', pos: 'noun' },
  { rank: 253, hr: 'grožđe', en: 'grapes', pos: 'noun' },
  { rank: 254, hr: 'rajčica', en: 'tomato', pos: 'noun' },
  { rank: 255, hr: 'krumpir', en: 'potato', pos: 'noun' },
  { rank: 256, hr: 'luk', en: 'onion', pos: 'noun' },
  { rank: 257, hr: 'češnjak', en: 'garlic', pos: 'noun' },
  { rank: 258, hr: 'mrkva', en: 'carrot', pos: 'noun' },
  { rank: 259, hr: 'salata', en: 'salad / lettuce', pos: 'noun' },
  { rank: 260, hr: 'juha', en: 'soup', pos: 'noun' },
  { rank: 261, hr: 'piletina', en: 'chicken (meat)', pos: 'noun' },
  { rank: 262, hr: 'svinjetina', en: 'pork', pos: 'noun' },
  { rank: 263, hr: 'govedina', en: 'beef', pos: 'noun' },
  { rank: 264, hr: 'glava', en: 'head', pos: 'noun' },
  { rank: 265, hr: 'lice', en: 'face', pos: 'noun' },
  { rank: 266, hr: 'oči', en: 'eyes', pos: 'noun' },
  { rank: 267, hr: 'uho', en: 'ear', pos: 'noun' },
  { rank: 268, hr: 'nos', en: 'nose', pos: 'noun' },
  { rank: 269, hr: 'usta', en: 'mouth', pos: 'noun' },
  { rank: 270, hr: 'zub', en: 'tooth', pos: 'noun' },
  { rank: 271, hr: 'jezik', en: 'tongue / language', pos: 'noun' },
  { rank: 272, hr: 'ruka', en: 'arm / hand', pos: 'noun' },
  { rank: 273, hr: 'noga', en: 'leg / foot', pos: 'noun' },
  { rank: 274, hr: 'prst', en: 'finger / toe', pos: 'noun' },
  { rank: 275, hr: 'leđa', en: 'back', pos: 'noun' },
  { rank: 276, hr: 'trbuh', en: 'stomach / belly', pos: 'noun' },
  { rank: 277, hr: 'srce', en: 'heart', pos: 'noun' },
  { rank: 278, hr: 'kosa', en: 'hair', pos: 'noun' },
  { rank: 279, hr: 'koža', en: 'skin', pos: 'noun' },
  { rank: 280, hr: 'kost', en: 'bone', pos: 'noun' },
  { rank: 281, hr: 'posao', en: 'job / work', pos: 'noun' },
  { rank: 282, hr: 'ured', en: 'office', pos: 'noun' },
  { rank: 283, hr: 'tvrtka', en: 'company / firm', pos: 'noun' },
  { rank: 284, hr: 'novac', en: 'money', pos: 'noun' },
  { rank: 285, hr: 'cijena', en: 'price', pos: 'noun' },
  { rank: 286, hr: 'račun', en: 'bill / account', pos: 'noun' },
  { rank: 287, hr: 'kartica', en: 'card', pos: 'noun' },
  { rank: 288, hr: 'bankovni', en: 'bank (adj)', pos: 'adj' },
  { rank: 289, hr: 'banka', en: 'bank', pos: 'noun' },
  { rank: 290, hr: 'auto', en: 'car', pos: 'noun' },
  { rank: 291, hr: 'vlak', en: 'train', pos: 'noun' },
  { rank: 292, hr: 'avion', en: 'plane / airplane', pos: 'noun' },
  { rank: 293, hr: 'brod', en: 'ship / boat', pos: 'noun' },
  { rank: 294, hr: 'autobus', en: 'bus', pos: 'noun' },
  { rank: 295, hr: 'tramvaj', en: 'tram', pos: 'noun' },
  { rank: 296, hr: 'bicikl', en: 'bicycle', pos: 'noun' },
  { rank: 297, hr: 'put', en: 'road / way / journey', pos: 'noun' },
  { rank: 298, hr: 'kolodvor', en: 'railway station', pos: 'noun' },
  { rank: 299, hr: 'aerodrom', en: 'airport', pos: 'noun' },
  { rank: 300, hr: 'luka', en: 'port / harbour', pos: 'noun' },
  { rank: 301, hr: 'hotel', en: 'hotel', pos: 'noun' },
  { rank: 302, hr: 'vrijeme', en: 'time / weather', pos: 'noun' },
  { rank: 303, hr: 'karta', en: 'ticket / card / map', pos: 'noun' },
  { rank: 304, hr: 'putovnica', en: 'passport', pos: 'noun' },
  { rank: 305, hr: 'prtljaga', en: 'luggage', pos: 'noun' },
  { rank: 306, hr: 'odmor', en: 'holiday / rest', pos: 'noun' },
  { rank: 307, hr: 'putovanje', en: 'trip / travel', pos: 'noun' },
  { rank: 308, hr: 'turizam', en: 'tourism', pos: 'noun' },
  { rank: 309, hr: 'telefon', en: 'phone', pos: 'noun' },
  { rank: 310, hr: 'računalo', en: 'computer', pos: 'noun' },
  { rank: 311, hr: 'internet', en: 'internet', pos: 'noun' },
  { rank: 312, hr: 'poruka', en: 'message', pos: 'noun' },
  { rank: 313, hr: 'e-pošta', en: 'email', pos: 'noun' },
  { rank: 314, hr: 'aplikacija', en: 'app / application', pos: 'noun' },
  { rank: 315, hr: 'stranica', en: 'page / website', pos: 'noun' },
  { rank: 316, hr: 'slika', en: 'picture / image', pos: 'noun' },
  { rank: 317, hr: 'glazba', en: 'music', pos: 'noun' },
  { rank: 318, hr: 'film', en: 'film / movie', pos: 'noun' },
  { rank: 319, hr: 'knjiga', en: 'book', pos: 'noun' },
  { rank: 320, hr: 'novine', en: 'newspaper', pos: 'noun' },
  { rank: 321, hr: 'televizija', en: 'television', pos: 'noun' },
  { rank: 322, hr: 'radio', en: 'radio', pos: 'noun' },
  { rank: 323, hr: 'sport', en: 'sport', pos: 'noun' },
  { rank: 324, hr: 'pjesma', en: 'song / poem', pos: 'noun' },
  { rank: 325, hr: 'lopta', en: 'ball', pos: 'noun' },
  { rank: 326, hr: 'tim', en: 'team', pos: 'noun' },
  { rank: 327, hr: 'igrač', en: 'player', pos: 'noun' },
  { rank: 328, hr: 'utakmica', en: 'match / game', pos: 'noun' },
  { rank: 329, hr: 'pobijeda', en: 'victory', pos: 'noun' },
  { rank: 330, hr: 'poraz', en: 'defeat', pos: 'noun' },
  { rank: 331, hr: 'sretan', en: 'happy', pos: 'adj' },
  { rank: 332, hr: 'tužan', en: 'sad', pos: 'adj' },
  { rank: 333, hr: 'ljut', en: 'angry', pos: 'adj' },
  { rank: 334, hr: 'strana', en: 'side / page', pos: 'noun' },
  { rank: 335, hr: 'umoran', en: 'tired', pos: 'adj' },
  { rank: 336, hr: 'gladan', en: 'hungry', pos: 'adj' },
  { rank: 337, hr: 'žedan', en: 'thirsty', pos: 'adj' },
  { rank: 338, hr: 'bolestan', en: 'sick / ill', pos: 'adj' },
  { rank: 339, hr: 'zdrav', en: 'healthy', pos: 'adj' },
  { rank: 340, hr: 'zabrinut', en: 'worried', pos: 'adj' },
  { rank: 341, hr: 'iznenađen', en: 'surprised', pos: 'adj' },
  { rank: 342, hr: 'ljubav', en: 'love', pos: 'noun' },
  { rank: 343, hr: 'sreća', en: 'happiness / luck', pos: 'noun' },
  { rank: 344, hr: 'strah', en: 'fear', pos: 'noun' },
  { rank: 345, hr: 'bol', en: 'pain', pos: 'noun' },
  { rank: 346, hr: 'nada', en: 'hope', pos: 'noun' },
  { rank: 347, hr: 'život', en: 'life', pos: 'noun' },
  { rank: 348, hr: 'smrt', en: 'death', pos: 'noun' },
  { rank: 349, hr: 'mir', en: 'peace', pos: 'noun' },
  { rank: 350, hr: 'rat', en: 'war', pos: 'noun' },
  { rank: 351, hr: 'istina', en: 'truth', pos: 'noun' },
  { rank: 352, hr: 'laž', en: 'lie', pos: 'noun' },
  { rank: 353, hr: 'pitanje', en: 'question', pos: 'noun' },
  { rank: 354, hr: 'odgovor', en: 'answer', pos: 'noun' },
  { rank: 355, hr: 'problem', en: 'problem', pos: 'noun' },
  { rank: 356, hr: 'rješenje', en: 'solution', pos: 'noun' },
  { rank: 357, hr: 'ideja', en: 'idea', pos: 'noun' },
  { rank: 358, hr: 'priča', en: 'story', pos: 'noun' },
  { rank: 359, hr: 'vijest', en: 'news', pos: 'noun' },
  { rank: 360, hr: 'razgovor', en: 'conversation', pos: 'noun' },
  { rank: 361, hr: 'pjevati', en: 'to sing', pos: 'verb' },
  { rank: 362, hr: 'plesati', en: 'to dance', pos: 'verb' },
  { rank: 363, hr: 'crtati', en: 'to draw', pos: 'verb' },
  { rank: 364, hr: 'kuhati', en: 'to cook', pos: 'verb' },
  { rank: 365, hr: 'jesti', en: 'to eat', pos: 'verb' },
  { rank: 366, hr: 'piti', en: 'to drink', pos: 'verb' },
  { rank: 367, hr: 'spavati', en: 'to sleep', pos: 'verb' },
  { rank: 368, hr: 'hodati', en: 'to walk', pos: 'verb' },
  { rank: 369, hr: 'trčati', en: 'to run', pos: 'verb' },
  { rank: 370, hr: 'skakati', en: 'to jump', pos: 'verb' },
  { rank: 371, hr: 'plivati', en: 'to swim', pos: 'verb' },
  { rank: 372, hr: 'letjeti', en: 'to fly', pos: 'verb' },
  { rank: 373, hr: 'voziti', en: 'to drive', pos: 'verb' },
  { rank: 374, hr: 'kupiti', en: 'to buy', pos: 'verb' },
  { rank: 375, hr: 'prodati', en: 'to sell', pos: 'verb' },
  { rank: 376, hr: 'platiti', en: 'to pay', pos: 'verb' },
  { rank: 377, hr: 'otvoriti', en: 'to open', pos: 'verb' },
  { rank: 378, hr: 'zatvoriti', en: 'to close', pos: 'verb' },
  { rank: 379, hr: 'pomoći', en: 'to help', pos: 'verb' },
  { rank: 380, hr: 'naučiti', en: 'to learn / teach', pos: 'verb' },
  { rank: 381, hr: 'razumjeti', en: 'to understand', pos: 'verb' },
  { rank: 382, hr: 'govoriti', en: 'to speak / talk', pos: 'verb' },
  { rank: 383, hr: 'slušati', en: 'to listen', pos: 'verb' },
  { rank: 384, hr: 'gledati', en: 'to look / watch', pos: 'verb' },
  { rank: 385, hr: 'smijati se', en: 'to laugh', pos: 'verb' },
  { rank: 386, hr: 'plakati', en: 'to cry', pos: 'verb' },
  { rank: 387, hr: 'sviđati se', en: 'to like', pos: 'verb' },
  { rank: 388, hr: 'trebati', en: 'to need', pos: 'verb' },
  { rank: 389, hr: 'moći', en: 'to be able / can', pos: 'verb' },
  { rank: 390, hr: 'htjeti', en: 'to want', pos: 'verb' },
  { rank: 391, hr: 'morati', en: 'to have to / must', pos: 'verb' },
  { rank: 392, hr: 'smjeti', en: 'to be allowed', pos: 'verb' },
  { rank: 393, hr: 'znati', en: 'to know', pos: 'verb' },
  { rank: 394, hr: 'misliti', en: 'to think', pos: 'verb' },
  { rank: 395, hr: 'vjerovati', en: 'to believe', pos: 'verb' },
  { rank: 396, hr: 'osjećati', en: 'to feel', pos: 'verb' },
  { rank: 397, hr: 'pamtiti', en: 'to remember', pos: 'verb' },
  { rank: 398, hr: 'zaboraviti', en: 'to forget', pos: 'verb' },
  { rank: 399, hr: 'čekati', en: 'to wait', pos: 'verb' },
  { rank: 400, hr: 'dolaziti', en: 'to come / arrive', pos: 'verb' },
  { rank: 401, hr: 'odlaziti', en: 'to leave / go away', pos: 'verb' },
  { rank: 402, hr: 'sretati', en: 'to meet', pos: 'verb' },
  { rank: 403, hr: 'dijeliti', en: 'to share / divide', pos: 'verb' },
  { rank: 404, hr: 'mijenjati', en: 'to change', pos: 'verb' },
  { rank: 405, hr: 'birati', en: 'to choose', pos: 'verb' },
  { rank: 406, hr: 'čuvati', en: 'to keep / guard', pos: 'verb' },
  { rank: 407, hr: 'čistiti', en: 'to clean', pos: 'verb' },
  { rank: 408, hr: 'graditi', en: 'to build', pos: 'verb' },
  { rank: 409, hr: 'pričati', en: 'to talk / tell', pos: 'verb' },
  { rank: 410, hr: 'zvati', en: 'to call', pos: 'verb' },
  { rank: 411, hr: 'odijevati', en: 'to dress', pos: 'verb' },
  { rank: 412, hr: 'oblačiti', en: 'to put on (clothes)', pos: 'verb' },
  { rank: 413, hr: 'svlačiti', en: 'to take off (clothes)', pos: 'verb' },
  { rank: 414, hr: 'brinuti', en: 'to worry / take care', pos: 'verb' },
  { rank: 415, hr: 'naći', en: 'to find', pos: 'verb' },
  { rank: 416, hr: 'izgubiti', en: 'to lose', pos: 'verb' },
  { rank: 417, hr: 'pobijediti', en: 'to win', pos: 'verb' },
  { rank: 418, hr: 'ući', en: 'to enter', pos: 'verb' },
  { rank: 419, hr: 'izaći', en: 'to exit / go out', pos: 'verb' },
  { rank: 420, hr: 'sjediti', en: 'to sit', pos: 'verb' },
  { rank: 421, hr: 'ustati', en: 'to get up / stand', pos: 'verb' },
  { rank: 422, hr: 'ležati', en: 'to lie (down)', pos: 'verb' },
  { rank: 423, hr: 'smiješan', en: 'funny', pos: 'adj' },
  { rank: 424, hr: 'zanimljiv', en: 'interesting', pos: 'adj' },
  { rank: 425, hr: 'dosadan', en: 'boring', pos: 'adj' },
  { rank: 426, hr: 'važan', en: 'important', pos: 'adj' },
  { rank: 427, hr: 'opasan', en: 'dangerous', pos: 'adj' },
  { rank: 428, hr: 'siguran', en: 'safe / certain', pos: 'adj' },
  { rank: 429, hr: 'slobodan', en: 'free', pos: 'adj' },
  { rank: 430, hr: 'zauzet', en: 'busy', pos: 'adj' },
  { rank: 431, hr: 'bogat', en: 'rich', pos: 'adj' },
  { rank: 432, hr: 'siromašan', en: 'poor', pos: 'adj' },
  { rank: 433, hr: 'pametan', en: 'smart / clever', pos: 'adj' },
  { rank: 434, hr: 'glup', en: 'stupid / dumb', pos: 'adj' },
  { rank: 435, hr: 'mlad', en: 'young', pos: 'adj' },
  { rank: 436, hr: 'star', en: 'old', pos: 'adj' },
  { rank: 437, hr: 'svjež', en: 'fresh', pos: 'adj' },
  { rank: 438, hr: 'tih', en: 'quiet / calm', pos: 'adj' },
  { rank: 439, hr: 'glasan', en: 'loud / noisy', pos: 'adj' },
  { rank: 440, hr: 'pun', en: 'full', pos: 'adj' },
  { rank: 441, hr: 'prazan', en: 'empty', pos: 'adj' },
  { rank: 442, hr: 'čist', en: 'clean', pos: 'adj' },
  { rank: 443, hr: 'prljav', en: 'dirty', pos: 'adj' },
  { rank: 444, hr: 'udoban', en: 'comfortable', pos: 'adj' },
  { rank: 445, hr: 'neudoban', en: 'uncomfortable', pos: 'adj' },
  { rank: 446, hr: 'moram', en: 'I must', pos: 'verb' },
  { rank: 447, hr: 'hoću', en: 'I want / I will', pos: 'verb' },
  { rank: 448, hr: 'način', en: 'way / manner', pos: 'noun' },
  { rank: 449, hr: 'znam', en: 'I know', pos: 'verb' },
  { rank: 450, hr: 'volim', en: 'I love / I like', pos: 'verb' },
  { rank: 451, hr: 'živim', en: 'I live', pos: 'verb' },
  { rank: 452, hr: 'radim', en: 'I work / I do', pos: 'verb' },
  { rank: 453, hr: 'govorim', en: 'I speak', pos: 'verb' },
  { rank: 454, hr: 'razumijem', en: 'I understand', pos: 'verb' },
  { rank: 455, hr: 'hvala', en: 'thank you', pos: 'interj' },
  { rank: 456, hr: 'molim', en: "please / you're welcome", pos: 'interj' },
  { rank: 457, hr: 'zdravo', en: 'hello / hi', pos: 'interj' },
  { rank: 458, hr: 'doviđenja', en: 'goodbye', pos: 'interj' },
  { rank: 459, hr: 'oprosti', en: 'sorry / excuse me', pos: 'interj' },
  { rank: 460, hr: 'izvolite', en: 'here you are / please', pos: 'interj' },
  { rank: 461, hr: 'naravno', en: 'of course', pos: 'adv' },
  { rank: 462, hr: 'možda', en: 'maybe / perhaps', pos: 'adv' },
  { rank: 463, hr: 'sigurno', en: 'certainly / surely', pos: 'adv' },
  { rank: 464, hr: 'vjerojatno', en: 'probably', pos: 'adv' },
  { rank: 465, hr: 'zapravo', en: 'actually / in fact', pos: 'adv' },
  { rank: 466, hr: 'ipak', en: 'however / still', pos: 'adv' },
  { rank: 467, hr: 'dakle', en: 'so / therefore', pos: 'adv' },
  { rank: 468, hr: 'inače', en: 'otherwise / usually', pos: 'adv' },
  { rank: 469, hr: 'uglavnom', en: 'mainly / mostly', pos: 'adv' },
  { rank: 470, hr: 'posebno', en: 'especially', pos: 'adv' },
  { rank: 471, hr: 'odmah', en: 'immediately', pos: 'adv' },
  { rank: 472, hr: 'tek', en: 'just / only', pos: 'adv' },
  { rank: 473, hr: 'baš', en: 'exactly / just', pos: 'adv' },
  { rank: 474, hr: 'bog', en: 'hi / bye (informal)', pos: 'interj' },
  { rank: 475, hr: 'dobar dan', en: 'good day', pos: 'interj' },
  { rank: 476, hr: 'dobro jutro', en: 'good morning', pos: 'interj' },
  { rank: 477, hr: 'dobra večer', en: 'good evening', pos: 'interj' },
  { rank: 478, hr: 'laku noć', en: 'good night', pos: 'interj' },
  { rank: 479, hr: 'crvena', en: 'red (f)', pos: 'adj' },
  { rank: 480, hr: 'plava', en: 'blue (f)', pos: 'adj' },
  { rank: 481, hr: 'zelena', en: 'green (f)', pos: 'adj' },
  { rank: 482, hr: 'žuta', en: 'yellow (f)', pos: 'adj' },
  { rank: 483, hr: 'bijela', en: 'white (f)', pos: 'adj' },
  { rank: 484, hr: 'crna', en: 'black (f)', pos: 'adj' },
  { rank: 485, hr: 'prijedlog', en: 'proposition / preposition', pos: 'noun' },
  { rank: 486, hr: 'glagol', en: 'verb', pos: 'noun' },
  { rank: 487, hr: 'imenica', en: 'noun', pos: 'noun' },
  { rank: 488, hr: 'pridjev', en: 'adjective', pos: 'noun' },
  { rank: 489, hr: 'rečenica', en: 'sentence', pos: 'noun' },
  { rank: 490, hr: 'riječ', en: 'word', pos: 'noun' },
  { rank: 491, hr: 'slovo', en: 'letter (alphabet)', pos: 'noun' },
  { rank: 492, hr: 'broj', en: 'number', pos: 'noun' },
  { rank: 493, hr: 'boja', en: 'color', pos: 'noun' },
  { rank: 494, hr: 'oblik', en: 'shape / form', pos: 'noun' },
  { rank: 495, hr: 'veličina', en: 'size', pos: 'noun' },
  { rank: 496, hr: 'težina', en: 'weight', pos: 'noun' },
  { rank: 497, hr: 'brzina', en: 'speed', pos: 'noun' },
  { rank: 498, hr: 'smjer', en: 'direction', pos: 'noun' },
  { rank: 499, hr: 'razlog', en: 'reason', pos: 'noun' },
  { rank: 500, hr: 'zaključak', en: 'conclusion', pos: 'noun' },
  // ── Ranks 501-1250 — the second thousand (2026-07 expansion). Ordering
  // within the band is approximate by corpus; band membership is the signal. ──
  { rank: 501, hr: 'onda', en: 'then', pos: 'adv' },
  { rank: 502, hr: 'zatim', en: 'then / next', pos: 'adv' },
  { rank: 503, hr: 'prije', en: 'before / earlier', pos: 'prep' },
  { rank: 504, hr: 'poslije', en: 'after / later', pos: 'prep' },
  { rank: 505, hr: 'tijekom', en: 'during', pos: 'prep' },
  { rank: 506, hr: 'protiv', en: 'against', pos: 'prep' },
  { rank: 507, hr: 'bez', en: 'without', pos: 'prep' },
  { rank: 508, hr: 'pored', en: 'beside / next to', pos: 'prep' },
  { rank: 509, hr: 'ispred', en: 'in front of', pos: 'prep' },
  { rank: 510, hr: 'iza', en: 'behind', pos: 'prep' },
  { rank: 511, hr: 'ispod', en: 'below / under', pos: 'prep' },
  { rank: 512, hr: 'iznad', en: 'above', pos: 'prep' },
  { rank: 513, hr: 'oko', en: 'around / about', pos: 'prep' },
  { rank: 514, hr: 'unutar', en: 'within / inside', pos: 'prep' },
  { rank: 515, hr: 'izvan', en: 'outside of', pos: 'prep' },
  { rank: 516, hr: 'prema', en: 'towards / according to', pos: 'prep' },
  { rank: 517, hr: 'osim', en: 'except / besides', pos: 'prep' },
  { rank: 518, hr: 'umjesto', en: 'instead of', pos: 'prep' },
  { rank: 519, hr: 'zbog', en: 'because of', pos: 'prep' },
  { rank: 520, hr: 'dok', en: 'while / until', pos: 'conj' },
  { rank: 521, hr: 'čim', en: 'as soon as', pos: 'conj' },
  { rank: 522, hr: 'iako', en: 'although', pos: 'conj' },
  { rank: 523, hr: 'premda', en: 'even though', pos: 'conj' },
  { rank: 524, hr: 'stoga', en: 'therefore', pos: 'conj' },
  { rank: 525, hr: 'međutim', en: 'however', pos: 'conj' },
  { rank: 526, hr: 'naime', en: 'namely / you see', pos: 'part' },
  { rank: 527, hr: 'odnosno', en: 'that is / respectively', pos: 'conj' },
  { rank: 528, hr: 'primjerice', en: 'for example', pos: 'adv' },
  { rank: 529, hr: 'gotovo', en: 'almost / nearly', pos: 'adv' },
  { rank: 530, hr: 'upravo', en: 'just / exactly', pos: 'adv' },
  { rank: 531, hr: 'ubrzo', en: 'soon / shortly', pos: 'adv' },
  { rank: 532, hr: 'uskoro', en: 'soon', pos: 'adv' },
  { rank: 533, hr: 'napokon', en: 'at last', pos: 'adv' },
  { rank: 534, hr: 'konačno', en: 'finally', pos: 'adv' },
  { rank: 535, hr: 'odjednom', en: 'suddenly', pos: 'adv' },
  { rank: 536, hr: 'ponovno', en: 'again', pos: 'adv' },
  { rank: 537, hr: 'opet', en: 'again', pos: 'adv' },
  { rank: 538, hr: 'također', en: 'also / as well', pos: 'adv' },
  { rank: 539, hr: 'čak', en: 'even', pos: 'part' },
  { rank: 540, hr: 'barem', en: 'at least', pos: 'adv' },
  { rank: 541, hr: 'uopće', en: 'at all', pos: 'adv' },
  { rank: 542, hr: 'potpuno', en: 'completely', pos: 'adv' },
  { rank: 543, hr: 'sasvim', en: 'entirely / quite', pos: 'adv' },
  { rank: 544, hr: 'prilično', en: 'fairly / rather', pos: 'adv' },
  { rank: 545, hr: 'previše', en: 'too much', pos: 'adv' },
  { rank: 546, hr: 'dovoljno', en: 'enough', pos: 'adv' },
  { rank: 547, hr: 'skoro', en: 'almost', pos: 'adv' },
  { rank: 548, hr: 'negdje', en: 'somewhere', pos: 'adv' },
  { rank: 549, hr: 'nigdje', en: 'nowhere', pos: 'adv' },
  { rank: 550, hr: 'svugdje', en: 'everywhere', pos: 'adv' },
  { rank: 551, hr: 'nešto', en: 'something', pos: 'pron' },
  { rank: 552, hr: 'netko', en: 'someone', pos: 'pron' },
  { rank: 553, hr: 'ništa', en: 'nothing', pos: 'pron' },
  { rank: 554, hr: 'nitko', en: 'no one', pos: 'pron' },
  { rank: 555, hr: 'svatko', en: 'everyone', pos: 'pron' },
  { rank: 556, hr: 'nekoliko', en: 'a few / several', pos: 'adv' },
  { rank: 557, hr: 'mnogo', en: 'a lot / many', pos: 'adv' },
  { rank: 558, hr: 'većina', en: 'majority / most', pos: 'noun' },
  { rank: 559, hr: 'ostalo', en: 'the rest', pos: 'pron' },
  { rank: 560, hr: 'isti', en: 'same', pos: 'adj' },
  { rank: 561, hr: 'svaki', en: 'every / each', pos: 'det' },
  { rank: 562, hr: 'nijedan', en: 'not a single / none', pos: 'det' },
  { rank: 563, hr: 'takav', en: 'such', pos: 'det' },
  { rank: 564, hr: 'ovaj', en: 'this', pos: 'det' },
  { rank: 565, hr: 'onaj', en: 'that (over there)', pos: 'det' },
  { rank: 566, hr: 'moj', en: 'my', pos: 'det' },
  { rank: 567, hr: 'tvoj', en: 'your (sg)', pos: 'det' },
  { rank: 568, hr: 'njegov', en: 'his', pos: 'det' },
  { rank: 569, hr: 'njezin', en: 'her', pos: 'det' },
  { rank: 570, hr: 'naš', en: 'our', pos: 'det' },
  { rank: 571, hr: 'vaš', en: 'your (pl/formal)', pos: 'det' },
  { rank: 572, hr: 'njihov', en: 'their', pos: 'det' },
  { rank: 573, hr: 'svoj', en: "one's own", pos: 'det' },
  { rank: 574, hr: 'sebe', en: 'oneself', pos: 'pron' },
  { rank: 575, hr: 'zajedno', en: 'together', pos: 'adv' },
  { rank: 576, hr: 'ponedjeljak', en: 'Monday', pos: 'noun' },
  { rank: 577, hr: 'utorak', en: 'Tuesday', pos: 'noun' },
  { rank: 578, hr: 'srijeda', en: 'Wednesday', pos: 'noun' },
  { rank: 579, hr: 'četvrtak', en: 'Thursday', pos: 'noun' },
  { rank: 580, hr: 'petak', en: 'Friday', pos: 'noun' },
  { rank: 581, hr: 'subota', en: 'Saturday', pos: 'noun' },
  { rank: 582, hr: 'nedjelja', en: 'Sunday', pos: 'noun' },
  { rank: 583, hr: 'vikend', en: 'weekend', pos: 'noun' },
  { rank: 584, hr: 'trenutak', en: 'moment', pos: 'noun' },
  { rank: 585, hr: 'razdoblje', en: 'period / era', pos: 'noun' },
  { rank: 586, hr: 'stoljeće', en: 'century', pos: 'noun' },
  { rank: 587, hr: 'desetljeće', en: 'decade', pos: 'noun' },
  { rank: 588, hr: 'budućnost', en: 'future', pos: 'noun' },
  { rank: 589, hr: 'prošlost', en: 'past', pos: 'noun' },
  { rank: 590, hr: 'sadašnjost', en: 'present (time)', pos: 'noun' },
  { rank: 591, hr: 'početak', en: 'beginning', pos: 'noun' },
  { rank: 592, hr: 'kraj', en: 'end', pos: 'noun' },
  { rank: 593, hr: 'sredina', en: 'middle', pos: 'noun' },
  { rank: 594, hr: 'rok', en: 'deadline', pos: 'noun' },
  { rank: 595, hr: 'prilika', en: 'opportunity / occasion', pos: 'noun' },
  { rank: 596, hr: 'slučaj', en: 'case / incident', pos: 'noun' },
  { rank: 597, hr: 'događaj', en: 'event', pos: 'noun' },
  { rank: 598, hr: 'datum', en: 'date', pos: 'noun' },
  { rank: 599, hr: 'doba', en: 'age / time of day', pos: 'noun' },
  { rank: 600, hr: 'sezona', en: 'season (sports/tourist)', pos: 'noun' },
  { rank: 601, hr: 'proljeće', en: 'spring', pos: 'noun' },
  { rank: 602, hr: 'ljeto', en: 'summer', pos: 'noun' },
  { rank: 603, hr: 'jesen', en: 'autumn', pos: 'noun' },
  { rank: 604, hr: 'zima', en: 'winter', pos: 'noun' },
  { rank: 605, hr: 'blagdan', en: 'holiday (religious/public)', pos: 'noun' },
  { rank: 606, hr: 'rođendan', en: 'birthday', pos: 'noun' },
  { rank: 607, hr: 'proslava', en: 'celebration', pos: 'noun' },
  { rank: 608, hr: 'praznik', en: 'holiday', pos: 'noun' },
  { rank: 609, hr: 'jedanaest', en: 'eleven', pos: 'num' },
  { rank: 610, hr: 'dvanaest', en: 'twelve', pos: 'num' },
  { rank: 611, hr: 'petnaest', en: 'fifteen', pos: 'num' },
  { rank: 612, hr: 'dvadeset', en: 'twenty', pos: 'num' },
  { rank: 613, hr: 'trideset', en: 'thirty', pos: 'num' },
  { rank: 614, hr: 'četrdeset', en: 'forty', pos: 'num' },
  { rank: 615, hr: 'pedeset', en: 'fifty', pos: 'num' },
  { rank: 616, hr: 'milijun', en: 'million', pos: 'num' },
  { rank: 617, hr: 'pola', en: 'half', pos: 'num' },
  { rank: 618, hr: 'postotak', en: 'percentage', pos: 'noun' },
  { rank: 619, hr: 'količina', en: 'quantity / amount', pos: 'noun' },
  { rank: 620, hr: 'dio', en: 'part', pos: 'noun' },
  { rank: 621, hr: 'par', en: 'pair / couple', pos: 'noun' },
  { rank: 622, hr: 'postati', en: 'to become', pos: 'verb' },
  { rank: 623, hr: 'ostati', en: 'to stay / remain', pos: 'verb' },
  { rank: 624, hr: 'dogoditi se', en: 'to happen', pos: 'verb' },
  { rank: 625, hr: 'činiti', en: 'to do / to seem', pos: 'verb' },
  { rank: 626, hr: 'učiniti', en: 'to do (pf)', pos: 'verb' },
  { rank: 627, hr: 'napraviti', en: 'to make / do', pos: 'verb' },
  { rank: 628, hr: 'reći', en: 'to say (pf)', pos: 'verb' },
  { rank: 629, hr: 'pokazati', en: 'to show', pos: 'verb' },
  { rank: 630, hr: 'pokušati', en: 'to try', pos: 'verb' },
  { rank: 631, hr: 'nastaviti', en: 'to continue', pos: 'verb' },
  { rank: 632, hr: 'prestati', en: 'to stop (doing)', pos: 'verb' },
  { rank: 633, hr: 'krenuti', en: 'to set off / start', pos: 'verb' },
  { rank: 634, hr: 'stići', en: 'to arrive / make it', pos: 'verb' },
  { rank: 635, hr: 'doći', en: 'to come (pf)', pos: 'verb' },
  { rank: 636, hr: 'otići', en: 'to leave (pf)', pos: 'verb' },
  { rank: 637, hr: 'proći', en: 'to pass (by)', pos: 'verb' },
  { rank: 638, hr: 'prijeći', en: 'to cross / switch', pos: 'verb' },
  { rank: 639, hr: 'donijeti', en: 'to bring', pos: 'verb' },
  { rank: 640, hr: 'odnijeti', en: 'to take away', pos: 'verb' },
  { rank: 641, hr: 'poslati', en: 'to send', pos: 'verb' },
  { rank: 642, hr: 'primiti', en: 'to receive', pos: 'verb' },
  { rank: 643, hr: 'nositi', en: 'to carry / wear', pos: 'verb' },
  { rank: 644, hr: 'držati', en: 'to hold / keep', pos: 'verb' },
  { rank: 645, hr: 'staviti', en: 'to put / place', pos: 'verb' },
  { rank: 646, hr: 'postaviti', en: 'to set up / pose (a question)', pos: 'verb' },
  { rank: 647, hr: 'podići', en: 'to raise / lift', pos: 'verb' },
  { rank: 648, hr: 'spustiti', en: 'to lower / put down', pos: 'verb' },
  { rank: 649, hr: 'baciti', en: 'to throw', pos: 'verb' },
  { rank: 650, hr: 'uhvatiti', en: 'to catch', pos: 'verb' },
  { rank: 651, hr: 'pustiti', en: 'to let / release', pos: 'verb' },
  { rank: 652, hr: 'napustiti', en: 'to abandon / leave', pos: 'verb' },
  { rank: 653, hr: 'dopustiti', en: 'to allow', pos: 'verb' },
  { rank: 654, hr: 'zabraniti', en: 'to forbid', pos: 'verb' },
  { rank: 655, hr: 'dogovoriti', en: 'to arrange / agree on', pos: 'verb' },
  { rank: 656, hr: 'odlučiti', en: 'to decide', pos: 'verb' },
  { rank: 657, hr: 'planirati', en: 'to plan', pos: 'verb' },
  { rank: 658, hr: 'pripremiti', en: 'to prepare', pos: 'verb' },
  { rank: 659, hr: 'organizirati', en: 'to organize', pos: 'verb' },
  { rank: 660, hr: 'sudjelovati', en: 'to participate', pos: 'verb' },
  { rank: 661, hr: 'predložiti', en: 'to suggest', pos: 'verb' },
  { rank: 662, hr: 'prihvatiti', en: 'to accept', pos: 'verb' },
  { rank: 663, hr: 'odbiti', en: 'to refuse / reject', pos: 'verb' },
  { rank: 664, hr: 'obećati', en: 'to promise', pos: 'verb' },
  { rank: 665, hr: 'objasniti', en: 'to explain', pos: 'verb' },
  { rank: 666, hr: 'opisati', en: 'to describe', pos: 'verb' },
  { rank: 667, hr: 'spomenuti', en: 'to mention', pos: 'verb' },
  { rank: 668, hr: 'primijetiti', en: 'to notice', pos: 'verb' },
  { rank: 669, hr: 'provjeriti', en: 'to check / verify', pos: 'verb' },
  { rank: 670, hr: 'potvrditi', en: 'to confirm', pos: 'verb' },
  { rank: 671, hr: 'izabrati', en: 'to choose (pf)', pos: 'verb' },
  { rank: 672, hr: 'preporučiti', en: 'to recommend', pos: 'verb' },
  { rank: 673, hr: 'savjetovati', en: 'to advise', pos: 'verb' },
  { rank: 674, hr: 'upozoriti', en: 'to warn', pos: 'verb' },
  { rank: 675, hr: 'obavijestiti', en: 'to inform', pos: 'verb' },
  { rank: 676, hr: 'javiti', en: 'to notify / let know', pos: 'verb' },
  { rank: 677, hr: 'objaviti', en: 'to publish / announce', pos: 'verb' },
  { rank: 678, hr: 'izraziti', en: 'to express', pos: 'verb' },
  { rank: 679, hr: 'značiti', en: 'to mean', pos: 'verb' },
  { rank: 680, hr: 'predstavljati', en: 'to represent', pos: 'verb' },
  { rank: 681, hr: 'postojati', en: 'to exist', pos: 'verb' },
  { rank: 682, hr: 'nedostajati', en: 'to be missing / to miss', pos: 'verb' },
  { rank: 683, hr: 'pripadati', en: 'to belong', pos: 'verb' },
  { rank: 684, hr: 'sadržavati', en: 'to contain', pos: 'verb' },
  { rank: 685, hr: 'uključivati', en: 'to include', pos: 'verb' },
  { rank: 686, hr: 'isključiti', en: 'to exclude / switch off', pos: 'verb' },
  { rank: 687, hr: 'ovisiti', en: 'to depend', pos: 'verb' },
  { rank: 688, hr: 'utjecati', en: 'to influence', pos: 'verb' },
  { rank: 689, hr: 'omogućiti', en: 'to enable', pos: 'verb' },
  { rank: 690, hr: 'spriječiti', en: 'to prevent', pos: 'verb' },
  { rank: 691, hr: 'izbjeći', en: 'to avoid', pos: 'verb' },
  { rank: 692, hr: 'uspjeti', en: 'to succeed', pos: 'verb' },
  { rank: 693, hr: 'pokvariti', en: 'to break / spoil', pos: 'verb' },
  { rank: 694, hr: 'popraviti', en: 'to repair / fix', pos: 'verb' },
  { rank: 695, hr: 'poboljšati', en: 'to improve', pos: 'verb' },
  { rank: 696, hr: 'pogoršati', en: 'to worsen', pos: 'verb' },
  { rank: 697, hr: 'povećati', en: 'to increase', pos: 'verb' },
  { rank: 698, hr: 'smanjiti', en: 'to decrease', pos: 'verb' },
  { rank: 699, hr: 'rasti', en: 'to grow', pos: 'verb' },
  { rank: 700, hr: 'pasti', en: 'to fall', pos: 'verb' },
  { rank: 701, hr: 'razviti', en: 'to develop', pos: 'verb' },
  { rank: 702, hr: 'stvoriti', en: 'to create', pos: 'verb' },
  { rank: 703, hr: 'proizvoditi', en: 'to produce', pos: 'verb' },
  { rank: 704, hr: 'trošiti', en: 'to spend / consume', pos: 'verb' },
  { rank: 705, hr: 'štedjeti', en: 'to save (money)', pos: 'verb' },
  { rank: 706, hr: 'zaraditi', en: 'to earn', pos: 'verb' },
  { rank: 707, hr: 'koštati', en: 'to cost', pos: 'verb' },
  { rank: 708, hr: 'vrijediti', en: 'to be worth / be valid', pos: 'verb' },
  { rank: 709, hr: 'iznositi', en: 'to amount to', pos: 'verb' },
  { rank: 710, hr: 'iznajmiti', en: 'to rent (out)', pos: 'verb' },
  { rank: 711, hr: 'posuditi', en: 'to borrow / lend', pos: 'verb' },
  { rank: 712, hr: 'dugovati', en: 'to owe', pos: 'verb' },
  { rank: 713, hr: 'zaposliti', en: 'to employ', pos: 'verb' },
  { rank: 714, hr: 'upravljati', en: 'to manage / steer', pos: 'verb' },
  { rank: 715, hr: 'voditi', en: 'to lead / guide', pos: 'verb' },
  { rank: 716, hr: 'slijediti', en: 'to follow', pos: 'verb' },
  { rank: 717, hr: 'pratiti', en: 'to accompany / track', pos: 'verb' },
  { rank: 718, hr: 'susresti', en: 'to meet / encounter', pos: 'verb' },
  { rank: 719, hr: 'posjetiti', en: 'to visit', pos: 'verb' },
  { rank: 720, hr: 'pozvati', en: 'to invite / call', pos: 'verb' },
  { rank: 721, hr: 'upoznati', en: 'to meet / get to know', pos: 'verb' },
  { rank: 722, hr: 'predstaviti', en: 'to introduce / present', pos: 'verb' },
  { rank: 723, hr: 'pozdraviti', en: 'to greet', pos: 'verb' },
  { rank: 724, hr: 'zahvaliti', en: 'to thank', pos: 'verb' },
  { rank: 725, hr: 'ispričati', en: 'to tell (a story) / excuse', pos: 'verb' },
  { rank: 726, hr: 'čestitati', en: 'to congratulate', pos: 'verb' },
  { rank: 727, hr: 'nadati se', en: 'to hope', pos: 'verb' },
  { rank: 728, hr: 'baviti se', en: 'to be engaged in / do (a hobby)', pos: 'verb' },
  { rank: 729, hr: 'sjećati se', en: 'to remember', pos: 'verb' },
  { rank: 730, hr: 'bojati se', en: 'to be afraid', pos: 'verb' },
  { rank: 731, hr: 'žaliti', en: 'to regret / mourn', pos: 'verb' },
  { rank: 732, hr: 'veseliti se', en: 'to look forward to', pos: 'verb' },
  { rank: 733, hr: 'mrziti', en: 'to hate', pos: 'verb' },
  { rank: 734, hr: 'poštovati', en: 'to respect', pos: 'verb' },
  { rank: 735, hr: 'cijeniti', en: 'to appreciate / value', pos: 'verb' },
  { rank: 736, hr: 'diviti se', en: 'to admire', pos: 'verb' },
  { rank: 737, hr: 'smetati', en: 'to bother / disturb', pos: 'verb' },
  { rank: 738, hr: 'zabavljati se', en: 'to have fun', pos: 'verb' },
  { rank: 739, hr: 'odmarati se', en: 'to rest', pos: 'verb' },
  { rank: 740, hr: 'probuditi se', en: 'to wake up', pos: 'verb' },
  { rank: 741, hr: 'zaspati', en: 'to fall asleep', pos: 'verb' },
  { rank: 742, hr: 'sanjati', en: 'to dream', pos: 'verb' },
  { rank: 743, hr: 'umrijeti', en: 'to die', pos: 'verb' },
  { rank: 744, hr: 'roditi se', en: 'to be born', pos: 'verb' },
  { rank: 745, hr: 'odrasti', en: 'to grow up', pos: 'verb' },
  { rank: 746, hr: 'oženiti se', en: 'to marry (of a man)', pos: 'verb' },
  { rank: 747, hr: 'udati se', en: 'to marry (of a woman)', pos: 'verb' },
  { rank: 748, hr: 'razvesti se', en: 'to divorce', pos: 'verb' },
  { rank: 749, hr: 'preseliti se', en: 'to move (house)', pos: 'verb' },
  { rank: 750, hr: 'putovati', en: 'to travel', pos: 'verb' },
  { rank: 751, hr: 'stanovati', en: 'to reside', pos: 'verb' },
  { rank: 752, hr: 'boraviti', en: 'to stay / sojourn', pos: 'verb' },
  { rank: 753, hr: 'naručiti', en: 'to order (goods/food)', pos: 'verb' },
  { rank: 754, hr: 'rezervirati', en: 'to reserve / book', pos: 'verb' },
  { rank: 755, hr: 'otkazati', en: 'to cancel', pos: 'verb' },
  { rank: 756, hr: 'potpisati', en: 'to sign', pos: 'verb' },
  { rank: 757, hr: 'ispuniti', en: 'to fill in / fulfil', pos: 'verb' },
  { rank: 758, hr: 'prijaviti', en: 'to register / report', pos: 'verb' },
  { rank: 759, hr: 'preuzeti', en: 'to download / take over', pos: 'verb' },
  { rank: 760, hr: 'spremiti', en: 'to save / put away', pos: 'verb' },
  { rank: 761, hr: 'izbrisati', en: 'to delete / erase', pos: 'verb' },
  { rank: 762, hr: 'pronaći', en: 'to find (pf)', pos: 'verb' },
  { rank: 763, hr: 'istraživati', en: 'to research / explore', pos: 'verb' },
  { rank: 764, hr: 'proučavati', en: 'to study (examine)', pos: 'verb' },
  { rank: 765, hr: 'otkriti', en: 'to discover / reveal', pos: 'verb' },
  { rank: 766, hr: 'mjeriti', en: 'to measure', pos: 'verb' },
  { rank: 767, hr: 'računati', en: 'to calculate / count on', pos: 'verb' },
  { rank: 768, hr: 'usporediti', en: 'to compare', pos: 'verb' },
  { rank: 769, hr: 'razlikovati', en: 'to distinguish', pos: 'verb' },
  { rank: 770, hr: 'odrediti', en: 'to determine / define', pos: 'verb' },
  { rank: 771, hr: 'procijeniti', en: 'to estimate / assess', pos: 'verb' },
  { rank: 772, hr: 'pretpostaviti', en: 'to assume', pos: 'verb' },
  { rank: 773, hr: 'sumnjati', en: 'to doubt / suspect', pos: 'verb' },
  { rank: 774, hr: 'zaključiti', en: 'to conclude', pos: 'verb' },
  { rank: 775, hr: 'dokazati', en: 'to prove', pos: 'verb' },
  { rank: 776, hr: 'tvrditi', en: 'to claim', pos: 'verb' },
  { rank: 777, hr: 'raspravljati', en: 'to discuss / debate', pos: 'verb' },
  { rank: 778, hr: 'svađati se', en: 'to argue / quarrel', pos: 'verb' },
  { rank: 779, hr: 'složiti se', en: 'to agree', pos: 'verb' },
  { rank: 780, hr: 'podržati', en: 'to support', pos: 'verb' },
  { rank: 781, hr: 'braniti', en: 'to defend', pos: 'verb' },
  { rank: 782, hr: 'napasti', en: 'to attack', pos: 'verb' },
  { rank: 783, hr: 'boriti se', en: 'to fight / struggle', pos: 'verb' },
  { rank: 784, hr: 'vježbati', en: 'to practise / exercise', pos: 'verb' },
  { rank: 785, hr: 'trenirati', en: 'to train', pos: 'verb' },
  { rank: 786, hr: 'natjecati se', en: 'to compete', pos: 'verb' },
  { rank: 787, hr: 'osvojiti', en: 'to win (a prize) / conquer', pos: 'verb' },
  { rank: 788, hr: 'postići', en: 'to achieve', pos: 'verb' },
  { rank: 789, hr: 'ostvariti', en: 'to realize / accomplish', pos: 'verb' },
  { rank: 790, hr: 'propustiti', en: 'to miss (a chance)', pos: 'verb' },
  { rank: 791, hr: 'zakasniti', en: 'to be late', pos: 'verb' },
  { rank: 792, hr: 'požuriti', en: 'to hurry', pos: 'verb' },
  { rank: 793, hr: 'provesti', en: 'to spend (time) / carry out', pos: 'verb' },
  { rank: 794, hr: 'uživati', en: 'to enjoy', pos: 'verb' },
  { rank: 795, hr: 'proslaviti', en: 'to celebrate', pos: 'verb' },
  { rank: 796, hr: 'šaliti se', en: 'to joke', pos: 'verb' },
  { rank: 797, hr: 'vikati', en: 'to shout', pos: 'verb' },
  { rank: 798, hr: 'šutjeti', en: 'to be silent', pos: 'verb' },
  { rank: 799, hr: 'zamoliti', en: 'to ask (a favour)', pos: 'verb' },
  { rank: 800, hr: 'zahtijevati', en: 'to demand / require', pos: 'verb' },
  { rank: 801, hr: 'nuditi', en: 'to offer (impf)', pos: 'verb' },
  { rank: 802, hr: 'ponuditi', en: 'to offer (pf)', pos: 'verb' },
  { rank: 803, hr: 'koristiti', en: 'to use', pos: 'verb' },
  { rank: 804, hr: 'primijeniti', en: 'to apply', pos: 'verb' },
  { rank: 805, hr: 'pokrenuti', en: 'to launch / start up', pos: 'verb' },
  { rank: 806, hr: 'zaustaviti', en: 'to stop (something)', pos: 'verb' },
  { rank: 807, hr: 'uključiti', en: 'to include / switch on', pos: 'verb' },
  { rank: 808, hr: 'ugasiti', en: 'to turn off / extinguish', pos: 'verb' },
  { rank: 809, hr: 'upaliti', en: 'to turn on / light', pos: 'verb' },
  { rank: 810, hr: 'svirati', en: 'to play (an instrument)', pos: 'verb' },
  { rank: 811, hr: 'snimati', en: 'to record / film', pos: 'verb' },
  { rank: 812, hr: 'fotografirati', en: 'to photograph', pos: 'verb' },
  { rank: 813, hr: 'prevesti', en: 'to translate', pos: 'verb' },
  { rank: 814, hr: 'izgovoriti', en: 'to pronounce / utter', pos: 'verb' },
  { rank: 815, hr: 'napisati', en: 'to write (pf)', pos: 'verb' },
  { rank: 816, hr: 'pročitati', en: 'to read (pf)', pos: 'verb' },
  { rank: 817, hr: 'srušiti', en: 'to demolish / knock down', pos: 'verb' },
  { rank: 818, hr: 'oštetiti', en: 'to damage', pos: 'verb' },
  { rank: 819, hr: 'uništiti', en: 'to destroy', pos: 'verb' },
  { rank: 820, hr: 'ozlijediti', en: 'to injure', pos: 'verb' },
  { rank: 821, hr: 'liječiti', en: 'to treat (medically)', pos: 'verb' },
  { rank: 822, hr: 'boljeti', en: 'to hurt / ache', pos: 'verb' },
  { rank: 823, hr: 'disati', en: 'to breathe', pos: 'verb' },
  { rank: 824, hr: 'mirisati', en: 'to smell (nice)', pos: 'verb' },
  { rank: 825, hr: 'dodirnuti', en: 'to touch', pos: 'verb' },
  { rank: 826, hr: 'promatrati', en: 'to observe', pos: 'verb' },
  { rank: 827, hr: 'prepoznati', en: 'to recognize', pos: 'verb' },
  { rank: 828, hr: 'sjetiti se', en: 'to recall', pos: 'verb' },
  { rank: 829, hr: 'podsjetiti', en: 'to remind', pos: 'verb' },
  { rank: 830, hr: 'zamisliti', en: 'to imagine', pos: 'verb' },
  { rank: 831, hr: 'predvidjeti', en: 'to predict / foresee', pos: 'verb' },
  { rank: 832, hr: 'očekivati', en: 'to expect', pos: 'verb' },
  { rank: 833, hr: 'iznenaditi', en: 'to surprise', pos: 'verb' },
  { rank: 834, hr: 'razočarati', en: 'to disappoint', pos: 'verb' },
  { rank: 835, hr: 'oduševiti', en: 'to delight / thrill', pos: 'verb' },
  { rank: 836, hr: 'smiriti se', en: 'to calm down', pos: 'verb' },
  { rank: 837, hr: 'opustiti se', en: 'to relax', pos: 'verb' },
  { rank: 838, hr: 'naviknuti se', en: 'to get used to', pos: 'verb' },
  { rank: 839, hr: 'predavati', en: 'to lecture / teach', pos: 'verb' },
  { rank: 840, hr: 'studirati', en: 'to study (at university)', pos: 'verb' },
  { rank: 841, hr: 'diplomirati', en: 'to graduate', pos: 'verb' },
  { rank: 842, hr: 'položiti', en: 'to pass (an exam)', pos: 'verb' },
  { rank: 843, hr: 'upisati', en: 'to enrol / write in', pos: 'verb' },
  { rank: 844, hr: 'osoba', en: 'person', pos: 'noun' },
  { rank: 845, hr: 'ljudi', en: 'people', pos: 'noun' },
  { rank: 846, hr: 'muškarac', en: 'man', pos: 'noun' },
  { rank: 847, hr: 'djevojka', en: 'girl / girlfriend', pos: 'noun' },
  { rank: 848, hr: 'dječak', en: 'boy', pos: 'noun' },
  { rank: 849, hr: 'djevojčica', en: 'little girl', pos: 'noun' },
  { rank: 850, hr: 'mladić', en: 'young man', pos: 'noun' },
  { rank: 851, hr: 'gospodin', en: 'gentleman / Mr', pos: 'noun' },
  { rank: 852, hr: 'gospođa', en: 'lady / Mrs', pos: 'noun' },
  { rank: 853, hr: 'susjed', en: 'neighbour', pos: 'noun' },
  { rank: 854, hr: 'gost', en: 'guest', pos: 'noun' },
  { rank: 855, hr: 'stranac', en: 'foreigner / stranger', pos: 'noun' },
  { rank: 856, hr: 'kolega', en: 'colleague', pos: 'noun' },
  { rank: 857, hr: 'šef', en: 'boss', pos: 'noun' },
  { rank: 858, hr: 'radnik', en: 'worker', pos: 'noun' },
  { rank: 859, hr: 'učitelj', en: 'teacher (primary)', pos: 'noun' },
  { rank: 860, hr: 'učenik', en: 'pupil', pos: 'noun' },
  { rank: 861, hr: 'student', en: 'university student', pos: 'noun' },
  { rank: 862, hr: 'profesor', en: 'professor / teacher', pos: 'noun' },
  { rank: 863, hr: 'liječnik', en: 'doctor', pos: 'noun' },
  { rank: 864, hr: 'policajac', en: 'police officer', pos: 'noun' },
  { rank: 865, hr: 'vojnik', en: 'soldier', pos: 'noun' },
  { rank: 866, hr: 'glumac', en: 'actor', pos: 'noun' },
  { rank: 867, hr: 'pjevač', en: 'singer', pos: 'noun' },
  { rank: 868, hr: 'pisac', en: 'writer', pos: 'noun' },
  { rank: 869, hr: 'umjetnik', en: 'artist', pos: 'noun' },
  { rank: 870, hr: 'znanstvenik', en: 'scientist', pos: 'noun' },
  { rank: 871, hr: 'inženjer', en: 'engineer', pos: 'noun' },
  { rank: 872, hr: 'pravnik', en: 'lawyer', pos: 'noun' },
  { rank: 873, hr: 'sudac', en: 'judge / referee', pos: 'noun' },
  { rank: 874, hr: 'kuhar', en: 'cook / chef', pos: 'noun' },
  { rank: 875, hr: 'konobar', en: 'waiter', pos: 'noun' },
  { rank: 876, hr: 'prodavač', en: 'salesperson', pos: 'noun' },
  { rank: 877, hr: 'vozač', en: 'driver', pos: 'noun' },
  { rank: 878, hr: 'ravnatelj', en: 'director / principal', pos: 'noun' },
  { rank: 879, hr: 'predsjednik', en: 'president', pos: 'noun' },
  { rank: 880, hr: 'ministar', en: 'minister', pos: 'noun' },
  { rank: 881, hr: 'vlada', en: 'government', pos: 'noun' },
  { rank: 882, hr: 'država', en: 'state / country', pos: 'noun' },
  { rank: 883, hr: 'narod', en: 'nation / people', pos: 'noun' },
  { rank: 884, hr: 'društvo', en: 'society / company (of people)', pos: 'noun' },
  { rank: 885, hr: 'zajednica', en: 'community', pos: 'noun' },
  { rank: 886, hr: 'obitelj', en: 'family', pos: 'noun' },
  { rank: 887, hr: 'brak', en: 'marriage', pos: 'noun' },
  { rank: 888, hr: 'veza', en: 'relationship / connection', pos: 'noun' },
  { rank: 889, hr: 'odnos', en: 'relation / attitude', pos: 'noun' },
  { rank: 890, hr: 'razlika', en: 'difference', pos: 'noun' },
  { rank: 891, hr: 'promjena', en: 'change', pos: 'noun' },
  { rank: 892, hr: 'razvoj', en: 'development', pos: 'noun' },
  { rank: 893, hr: 'napredak', en: 'progress', pos: 'noun' },
  { rank: 894, hr: 'uspjeh', en: 'success', pos: 'noun' },
  { rank: 895, hr: 'neuspjeh', en: 'failure', pos: 'noun' },
  { rank: 896, hr: 'pokušaj', en: 'attempt', pos: 'noun' },
  { rank: 897, hr: 'iskustvo', en: 'experience', pos: 'noun' },
  { rank: 898, hr: 'znanje', en: 'knowledge', pos: 'noun' },
  { rank: 899, hr: 'vještina', en: 'skill', pos: 'noun' },
  { rank: 900, hr: 'sposobnost', en: 'ability', pos: 'noun' },
  { rank: 901, hr: 'mogućnost', en: 'possibility', pos: 'noun' },
  { rank: 902, hr: 'izbor', en: 'choice / selection', pos: 'noun' },
  { rank: 903, hr: 'odluka', en: 'decision', pos: 'noun' },
  { rank: 904, hr: 'namjera', en: 'intention', pos: 'noun' },
  { rank: 905, hr: 'cilj', en: 'goal / aim', pos: 'noun' },
  { rank: 906, hr: 'plan', en: 'plan', pos: 'noun' },
  { rank: 907, hr: 'projekt', en: 'project', pos: 'noun' },
  { rank: 908, hr: 'zadatak', en: 'task', pos: 'noun' },
  { rank: 909, hr: 'obveza', en: 'obligation', pos: 'noun' },
  { rank: 910, hr: 'dužnost', en: 'duty', pos: 'noun' },
  { rank: 911, hr: 'pravo', en: 'right / law (field)', pos: 'noun' },
  { rank: 912, hr: 'zakon', en: 'law (statute)', pos: 'noun' },
  { rank: 913, hr: 'pravilo', en: 'rule', pos: 'noun' },
  { rank: 914, hr: 'uvjet', en: 'condition', pos: 'noun' },
  { rank: 915, hr: 'zahtjev', en: 'requirement / request', pos: 'noun' },
  { rank: 916, hr: 'dogovor', en: 'agreement / arrangement', pos: 'noun' },
  { rank: 917, hr: 'ugovor', en: 'contract', pos: 'noun' },
  { rank: 918, hr: 'sastanak', en: 'meeting', pos: 'noun' },
  { rank: 919, hr: 'rasprava', en: 'discussion / debate', pos: 'noun' },
  { rank: 920, hr: 'dojam', en: 'impression', pos: 'noun' },
  { rank: 921, hr: 'mišljenje', en: 'opinion', pos: 'noun' },
  { rank: 922, hr: 'stav', en: 'attitude / stance', pos: 'noun' },
  { rank: 923, hr: 'osjećaj', en: 'feeling', pos: 'noun' },
  { rank: 924, hr: 'raspoloženje', en: 'mood', pos: 'noun' },
  { rank: 925, hr: 'briga', en: 'worry / care', pos: 'noun' },
  { rank: 926, hr: 'trud', en: 'effort', pos: 'noun' },
  { rank: 927, hr: 'napor', en: 'exertion / strain', pos: 'noun' },
  { rank: 928, hr: 'pažnja', en: 'attention', pos: 'noun' },
  { rank: 929, hr: 'interes', en: 'interest', pos: 'noun' },
  { rank: 930, hr: 'svrha', en: 'purpose', pos: 'noun' },
  { rank: 931, hr: 'značenje', en: 'meaning', pos: 'noun' },
  { rank: 932, hr: 'vrijednost', en: 'value', pos: 'noun' },
  { rank: 933, hr: 'korist', en: 'benefit', pos: 'noun' },
  { rank: 934, hr: 'šteta', en: 'damage / a pity', pos: 'noun' },
  { rank: 935, hr: 'opasnost', en: 'danger', pos: 'noun' },
  { rank: 936, hr: 'rizik', en: 'risk', pos: 'noun' },
  { rank: 937, hr: 'zaštita', en: 'protection', pos: 'noun' },
  { rank: 938, hr: 'sigurnost', en: 'safety / security', pos: 'noun' },
  { rank: 939, hr: 'pomoć', en: 'help', pos: 'noun' },
  { rank: 940, hr: 'podrška', en: 'support', pos: 'noun' },
  { rank: 941, hr: 'savjet', en: 'advice', pos: 'noun' },
  { rank: 942, hr: 'uputa', en: 'instruction', pos: 'noun' },
  { rank: 943, hr: 'informacija', en: 'information', pos: 'noun' },
  { rank: 944, hr: 'podatak', en: 'piece of data', pos: 'noun' },
  { rank: 945, hr: 'dokaz', en: 'proof / evidence', pos: 'noun' },
  { rank: 946, hr: 'primjer', en: 'example', pos: 'noun' },
  { rank: 947, hr: 'stvar', en: 'thing', pos: 'noun' },
  { rank: 948, hr: 'predmet', en: 'object / subject', pos: 'noun' },
  { rank: 949, hr: 'oprema', en: 'equipment', pos: 'noun' },
  { rank: 950, hr: 'alat', en: 'tool', pos: 'noun' },
  { rank: 951, hr: 'stroj', en: 'machine', pos: 'noun' },
  { rank: 952, hr: 'uređaj', en: 'device', pos: 'noun' },
  { rank: 953, hr: 'sustav', en: 'system', pos: 'noun' },
  { rank: 954, hr: 'mreža', en: 'network / net', pos: 'noun' },
  { rank: 955, hr: 'izvor', en: 'source / spring', pos: 'noun' },
  { rank: 956, hr: 'materijal', en: 'material', pos: 'noun' },
  { rank: 957, hr: 'proizvod', en: 'product', pos: 'noun' },
  { rank: 958, hr: 'roba', en: 'goods', pos: 'noun' },
  { rank: 959, hr: 'usluga', en: 'service', pos: 'noun' },
  { rank: 960, hr: 'ponuda', en: 'offer', pos: 'noun' },
  { rank: 961, hr: 'tržište', en: 'market (economy)', pos: 'noun' },
  { rank: 962, hr: 'gospodarstvo', en: 'economy', pos: 'noun' },
  { rank: 963, hr: 'politika', en: 'politics / policy', pos: 'noun' },
  { rank: 964, hr: 'izbori', en: 'elections', pos: 'noun' },
  { rank: 965, hr: 'stranka', en: '(political) party / client', pos: 'noun' },
  { rank: 966, hr: 'mediji', en: 'media', pos: 'noun' },
  { rank: 967, hr: 'javnost', en: 'the public', pos: 'noun' },
  { rank: 968, hr: 'kultura', en: 'culture', pos: 'noun' },
  { rank: 969, hr: 'umjetnost', en: 'art', pos: 'noun' },
  { rank: 970, hr: 'povijest', en: 'history', pos: 'noun' },
  { rank: 971, hr: 'znanost', en: 'science', pos: 'noun' },
  { rank: 972, hr: 'istraživanje', en: 'research', pos: 'noun' },
  { rank: 973, hr: 'obrazovanje', en: 'education', pos: 'noun' },
  { rank: 974, hr: 'nastava', en: 'classes / instruction', pos: 'noun' },
  { rank: 975, hr: 'tečaj', en: 'course / exchange rate', pos: 'noun' },
  { rank: 976, hr: 'ispit', en: 'exam', pos: 'noun' },
  { rank: 977, hr: 'ocjena', en: 'grade / assessment', pos: 'noun' },
  { rank: 978, hr: 'razred', en: 'class / grade (school)', pos: 'noun' },
  { rank: 979, hr: 'fakultet', en: 'faculty / college', pos: 'noun' },
  { rank: 980, hr: 'sveučilište', en: 'university', pos: 'noun' },
  { rank: 981, hr: 'knjižnica', en: 'library', pos: 'noun' },
  { rank: 982, hr: 'tvornica', en: 'factory', pos: 'noun' },
  { rank: 983, hr: 'plaća', en: 'salary', pos: 'noun' },
  { rank: 984, hr: 'porez', en: 'tax', pos: 'noun' },
  { rank: 985, hr: 'trošak', en: 'expense', pos: 'noun' },
  { rank: 986, hr: 'popust', en: 'discount', pos: 'noun' },
  { rank: 987, hr: 'kvaliteta', en: 'quality', pos: 'noun' },
  { rank: 988, hr: 'visina', en: 'height', pos: 'noun' },
  { rank: 989, hr: 'širina', en: 'width', pos: 'noun' },
  { rank: 990, hr: 'dužina', en: 'length', pos: 'noun' },
  { rank: 991, hr: 'dubina', en: 'depth', pos: 'noun' },
  { rank: 992, hr: 'udaljenost', en: 'distance', pos: 'noun' },
  { rank: 993, hr: 'površina', en: 'surface / area', pos: 'noun' },
  { rank: 994, hr: 'prostor', en: 'space / room', pos: 'noun' },
  { rank: 995, hr: 'mjesto', en: 'place', pos: 'noun' },
  { rank: 996, hr: 'područje', en: 'area / field', pos: 'noun' },
  { rank: 997, hr: 'regija', en: 'region', pos: 'noun' },
  { rank: 998, hr: 'granica', en: 'border / limit', pos: 'noun' },
  { rank: 999, hr: 'okolina', en: 'surroundings', pos: 'noun' },
  { rank: 1000, hr: 'okoliš', en: 'environment', pos: 'noun' },
  { rank: 1001, hr: 'priroda', en: 'nature', pos: 'noun' },
  { rank: 1002, hr: 'biljka', en: 'plant', pos: 'noun' },
  { rank: 1003, hr: 'drvo', en: 'tree / wood', pos: 'noun' },
  { rank: 1004, hr: 'cvijet', en: 'flower', pos: 'noun' },
  { rank: 1005, hr: 'trava', en: 'grass', pos: 'noun' },
  { rank: 1006, hr: 'list', en: 'leaf / sheet', pos: 'noun' },
  { rank: 1007, hr: 'grana', en: 'branch', pos: 'noun' },
  { rank: 1008, hr: 'korijen', en: 'root', pos: 'noun' },
  { rank: 1009, hr: 'životinja', en: 'animal', pos: 'noun' },
  { rank: 1010, hr: 'pas', en: 'dog', pos: 'noun' },
  { rank: 1011, hr: 'mačka', en: 'cat', pos: 'noun' },
  { rank: 1012, hr: 'konj', en: 'horse', pos: 'noun' },
  { rank: 1013, hr: 'ptica', en: 'bird', pos: 'noun' },
  { rank: 1014, hr: 'zrak', en: 'air', pos: 'noun' },
  { rank: 1015, hr: 'vatra', en: 'fire', pos: 'noun' },
  { rank: 1016, hr: 'dim', en: 'smoke', pos: 'noun' },
  { rank: 1017, hr: 'svjetlo', en: 'light', pos: 'noun' },
  { rank: 1018, hr: 'sjena', en: 'shadow / shade', pos: 'noun' },
  { rank: 1019, hr: 'zvuk', en: 'sound', pos: 'noun' },
  { rank: 1020, hr: 'glas', en: 'voice / vote', pos: 'noun' },
  { rank: 1021, hr: 'buka', en: 'noise', pos: 'noun' },
  { rank: 1022, hr: 'tišina', en: 'silence', pos: 'noun' },
  { rank: 1023, hr: 'miris', en: 'smell / scent', pos: 'noun' },
  { rank: 1024, hr: 'okus', en: 'taste', pos: 'noun' },
  { rank: 1025, hr: 'pogled', en: 'view / glance', pos: 'noun' },
  { rank: 1026, hr: 'korak', en: 'step', pos: 'noun' },
  { rank: 1027, hr: 'pokret', en: 'movement', pos: 'noun' },
  { rank: 1028, hr: 'snaga', en: 'strength / power', pos: 'noun' },
  { rank: 1029, hr: 'energija', en: 'energy', pos: 'noun' },
  { rank: 1030, hr: 'zdravlje', en: 'health', pos: 'noun' },
  { rank: 1031, hr: 'bolest', en: 'illness', pos: 'noun' },
  { rank: 1032, hr: 'lijek', en: 'medicine (drug)', pos: 'noun' },
  { rank: 1033, hr: 'ljekarna', en: 'pharmacy', pos: 'noun' },
  { rank: 1034, hr: 'ozljeda', en: 'injury', pos: 'noun' },
  { rank: 1035, hr: 'rana', en: 'wound', pos: 'noun' },
  { rank: 1036, hr: 'odjeća', en: 'clothes', pos: 'noun' },
  { rank: 1037, hr: 'cipela', en: 'shoe', pos: 'noun' },
  { rank: 1038, hr: 'hlače', en: 'trousers', pos: 'noun' },
  { rank: 1039, hr: 'košulja', en: 'shirt', pos: 'noun' },
  { rank: 1040, hr: 'majica', en: 'T-shirt', pos: 'noun' },
  { rank: 1041, hr: 'haljina', en: 'dress', pos: 'noun' },
  { rank: 1042, hr: 'kaput', en: 'coat', pos: 'noun' },
  { rank: 1043, hr: 'jakna', en: 'jacket', pos: 'noun' },
  { rank: 1044, hr: 'torba', en: 'bag', pos: 'noun' },
  { rank: 1045, hr: 'novčanik', en: 'wallet', pos: 'noun' },
  { rank: 1046, hr: 'ključ', en: 'key', pos: 'noun' },
  { rank: 1047, hr: 'naočale', en: 'glasses', pos: 'noun' },
  { rank: 1048, hr: 'prsten', en: 'ring', pos: 'noun' },
  { rank: 1049, hr: 'namještaj', en: 'furniture', pos: 'noun' },
  { rank: 1050, hr: 'ormar', en: 'wardrobe / cupboard', pos: 'noun' },
  { rank: 1051, hr: 'polica', en: 'shelf', pos: 'noun' },
  { rank: 1052, hr: 'ogledalo', en: 'mirror', pos: 'noun' },
  { rank: 1053, hr: 'hladnjak', en: 'refrigerator', pos: 'noun' },
  { rank: 1054, hr: 'tanjur', en: 'plate', pos: 'noun' },
  { rank: 1055, hr: 'čaša', en: 'glass (cup)', pos: 'noun' },
  { rank: 1056, hr: 'šalica', en: 'cup / mug', pos: 'noun' },
  { rank: 1057, hr: 'žlica', en: 'spoon', pos: 'noun' },
  { rank: 1058, hr: 'vilica', en: 'fork', pos: 'noun' },
  { rank: 1059, hr: 'nož', en: 'knife', pos: 'noun' },
  { rank: 1060, hr: 'boca', en: 'bottle', pos: 'noun' },
  { rank: 1061, hr: 'kutija', en: 'box', pos: 'noun' },
  { rank: 1062, hr: 'papir', en: 'paper', pos: 'noun' },
  { rank: 1063, hr: 'olovka', en: 'pencil / pen', pos: 'noun' },
  { rank: 1064, hr: 'pismo', en: 'letter (mail)', pos: 'noun' },
  { rank: 1065, hr: 'paket', en: 'package', pos: 'noun' },
  { rank: 1066, hr: 'adresa', en: 'address', pos: 'noun' },
  { rank: 1067, hr: 'pošta', en: 'post office / mail', pos: 'noun' },
  { rank: 1068, hr: 'bankomat', en: 'ATM', pos: 'noun' },
  { rank: 1069, hr: 'osiguranje', en: 'insurance', pos: 'noun' },
  { rank: 1070, hr: 'dokument', en: 'document', pos: 'noun' },
  { rank: 1071, hr: 'obrazac', en: 'form (paperwork)', pos: 'noun' },
  { rank: 1072, hr: 'potpis', en: 'signature', pos: 'noun' },
  { rank: 1073, hr: 'dozvola', en: 'permit / licence', pos: 'noun' },
  { rank: 1074, hr: 'promet', en: 'traffic / turnover', pos: 'noun' },
  { rank: 1075, hr: 'pješak', en: 'pedestrian', pos: 'noun' },
  { rank: 1076, hr: 'cesta', en: 'road', pos: 'noun' },
  { rank: 1077, hr: 'autocesta', en: 'motorway', pos: 'noun' },
  { rank: 1078, hr: 'most', en: 'bridge', pos: 'noun' },
  { rank: 1079, hr: 'gorivo', en: 'fuel', pos: 'noun' },
  { rank: 1080, hr: 'guma', en: 'tyre / rubber', pos: 'noun' },
  { rank: 1081, hr: 'motor', en: 'engine / motorbike', pos: 'noun' },
  { rank: 1082, hr: 'kvar', en: 'malfunction / breakdown', pos: 'noun' },
  { rank: 1083, hr: 'servis', en: 'repair shop / service', pos: 'noun' },
  { rank: 1084, hr: 'kazna', en: 'fine / punishment', pos: 'noun' },
  { rank: 1085, hr: 'sljedeći', en: 'next / following', pos: 'adj' },
  { rank: 1086, hr: 'prethodni', en: 'previous', pos: 'adj' },
  { rank: 1087, hr: 'posljednji', en: 'last (final)', pos: 'adj' },
  { rank: 1088, hr: 'zadnji', en: 'last / rear', pos: 'adj' },
  { rank: 1089, hr: 'budući', en: 'future (adj)', pos: 'adj' },
  { rank: 1090, hr: 'prošli', en: 'past / last (week etc.)', pos: 'adj' },
  { rank: 1091, hr: 'trenutačni', en: 'current', pos: 'adj' },
  { rank: 1092, hr: 'moderan', en: 'modern', pos: 'adj' },
  { rank: 1093, hr: 'tradicionalan', en: 'traditional', pos: 'adj' },
  { rank: 1094, hr: 'običan', en: 'ordinary', pos: 'adj' },
  { rank: 1095, hr: 'poseban', en: 'special', pos: 'adj' },
  { rank: 1096, hr: 'različit', en: 'different / various', pos: 'adj' },
  { rank: 1097, hr: 'sličan', en: 'similar', pos: 'adj' },
  { rank: 1098, hr: 'jednak', en: 'equal', pos: 'adj' },
  { rank: 1099, hr: 'glavni', en: 'main', pos: 'adj' },
  { rank: 1100, hr: 'osnovni', en: 'basic', pos: 'adj' },
  { rank: 1101, hr: 'dodatan', en: 'additional', pos: 'adj' },
  { rank: 1102, hr: 'potreban', en: 'necessary', pos: 'adj' },
  { rank: 1103, hr: 'moguć', en: 'possible', pos: 'adj' },
  { rank: 1104, hr: 'nemoguć', en: 'impossible', pos: 'adj' },
  { rank: 1105, hr: 'točan', en: 'accurate / correct', pos: 'adj' },
  { rank: 1106, hr: 'pogrešan', en: 'wrong', pos: 'adj' },
  { rank: 1107, hr: 'ispravan', en: 'correct / proper', pos: 'adj' },
  { rank: 1108, hr: 'jasan', en: 'clear', pos: 'adj' },
  { rank: 1109, hr: 'očit', en: 'obvious', pos: 'adj' },
  { rank: 1110, hr: 'poznat', en: 'well-known / familiar', pos: 'adj' },
  { rank: 1111, hr: 'nepoznat', en: 'unknown', pos: 'adj' },
  { rank: 1112, hr: 'slavan', en: 'famous', pos: 'adj' },
  { rank: 1113, hr: 'popularan', en: 'popular', pos: 'adj' },
  { rank: 1114, hr: 'uspješan', en: 'successful', pos: 'adj' },
  { rank: 1115, hr: 'sposoban', en: 'capable', pos: 'adj' },
  { rank: 1116, hr: 'iskusan', en: 'experienced', pos: 'adj' },
  { rank: 1117, hr: 'stručan', en: 'expert / professional', pos: 'adj' },
  { rank: 1118, hr: 'odgovoran', en: 'responsible', pos: 'adj' },
  { rank: 1119, hr: 'ozbiljan', en: 'serious', pos: 'adj' },
  { rank: 1120, hr: 'strog', en: 'strict', pos: 'adj' },
  { rank: 1121, hr: 'blag', en: 'mild / gentle', pos: 'adj' },
  { rank: 1122, hr: 'ljubazan', en: 'kind / polite', pos: 'adj' },
  { rank: 1123, hr: 'pristojan', en: 'decent / polite', pos: 'adj' },
  { rank: 1124, hr: 'grub', en: 'rough / rude', pos: 'adj' },
  { rank: 1125, hr: 'pošten', en: 'honest / fair', pos: 'adj' },
  { rank: 1126, hr: 'iskren', en: 'sincere', pos: 'adj' },
  { rank: 1127, hr: 'lažan', en: 'false / fake', pos: 'adj' },
  { rank: 1128, hr: 'vjeran', en: 'faithful', pos: 'adj' },
  { rank: 1129, hr: 'ponosan', en: 'proud', pos: 'adj' },
  { rank: 1130, hr: 'skroman', en: 'modest', pos: 'adj' },
  { rank: 1131, hr: 'hrabar', en: 'brave', pos: 'adj' },
  { rank: 1132, hr: 'oprezan', en: 'careful / cautious', pos: 'adj' },
  { rank: 1133, hr: 'pažljiv', en: 'attentive / careful', pos: 'adj' },
  { rank: 1134, hr: 'lijen', en: 'lazy', pos: 'adj' },
  { rank: 1135, hr: 'marljiv', en: 'diligent', pos: 'adj' },
  { rank: 1136, hr: 'vrijedan', en: 'hard-working / valuable', pos: 'adj' },
  { rank: 1137, hr: 'uporan', en: 'persistent', pos: 'adj' },
  { rank: 1138, hr: 'strpljiv', en: 'patient', pos: 'adj' },
  { rank: 1139, hr: 'nestrpljiv', en: 'impatient', pos: 'adj' },
  { rank: 1140, hr: 'nervozan', en: 'nervous', pos: 'adj' },
  { rank: 1141, hr: 'smiren', en: 'calm (composed)', pos: 'adj' },
  { rank: 1142, hr: 'miran', en: 'calm / peaceful', pos: 'adj' },
  { rank: 1143, hr: 'uzbuđen', en: 'excited', pos: 'adj' },
  { rank: 1144, hr: 'nesretan', en: 'unhappy', pos: 'adj' },
  { rank: 1145, hr: 'zadovoljan', en: 'satisfied', pos: 'adj' },
  { rank: 1146, hr: 'nezadovoljan', en: 'dissatisfied', pos: 'adj' },
  { rank: 1147, hr: 'razočaran', en: 'disappointed', pos: 'adj' },
  { rank: 1148, hr: 'usamljen', en: 'lonely', pos: 'adj' },
  { rank: 1149, hr: 'jednostavan', en: 'simple', pos: 'adj' },
  { rank: 1150, hr: 'složen', en: 'complex', pos: 'adj' },
  { rank: 1151, hr: 'otvoren', en: 'open', pos: 'adj' },
  { rank: 1152, hr: 'zatvoren', en: 'closed', pos: 'adj' },
  { rank: 1153, hr: 'širok', en: 'wide', pos: 'adj' },
  { rank: 1154, hr: 'uzak', en: 'narrow', pos: 'adj' },
  { rank: 1155, hr: 'dubok', en: 'deep', pos: 'adj' },
  { rank: 1156, hr: 'plitak', en: 'shallow', pos: 'adj' },
  { rank: 1157, hr: 'debeo', en: 'fat / thick', pos: 'adj' },
  { rank: 1158, hr: 'tanak', en: 'thin', pos: 'adj' },
  { rank: 1159, hr: 'mršav', en: 'skinny', pos: 'adj' },
  { rank: 1160, hr: 'okrugao', en: 'round', pos: 'adj' },
  { rank: 1161, hr: 'ravan', en: 'flat / straight', pos: 'adj' },
  { rank: 1162, hr: 'oštar', en: 'sharp', pos: 'adj' },
  { rank: 1163, hr: 'mekan', en: 'soft', pos: 'adj' },
  { rank: 1164, hr: 'tvrd', en: 'hard (firm)', pos: 'adj' },
  { rank: 1165, hr: 'gladak', en: 'smooth', pos: 'adj' },
  { rank: 1166, hr: 'mokar', en: 'wet', pos: 'adj' },
  { rank: 1167, hr: 'suh', en: 'dry', pos: 'adj' },
  { rank: 1168, hr: 'vlažan', en: 'humid / damp', pos: 'adj' },
  { rank: 1169, hr: 'svijetao', en: 'bright / light-coloured', pos: 'adj' },
  { rank: 1170, hr: 'taman', en: 'dark', pos: 'adj' },
  { rank: 1171, hr: 'sjajan', en: 'brilliant / shiny', pos: 'adj' },
  { rank: 1172, hr: 'šaren', en: 'colourful', pos: 'adj' },
  { rank: 1173, hr: 'skup', en: 'expensive', pos: 'adj' },
  { rank: 1174, hr: 'jeftin', en: 'cheap', pos: 'adj' },
  { rank: 1175, hr: 'besplatan', en: 'free of charge', pos: 'adj' },
  { rank: 1176, hr: 'vlastiti', en: "one's own", pos: 'adj' },
  { rank: 1177, hr: 'zajednički', en: 'common / shared', pos: 'adj' },
  { rank: 1178, hr: 'javan', en: 'public', pos: 'adj' },
  { rank: 1179, hr: 'privatan', en: 'private', pos: 'adj' },
  { rank: 1180, hr: 'domaći', en: 'domestic / homemade', pos: 'adj' },
  { rank: 1181, hr: 'strani', en: 'foreign', pos: 'adj' },
  { rank: 1182, hr: 'međunarodni', en: 'international', pos: 'adj' },
  { rank: 1183, hr: 'lokalni', en: 'local', pos: 'adj' },
  { rank: 1184, hr: 'prirodan', en: 'natural', pos: 'adj' },
  { rank: 1185, hr: 'umjetan', en: 'artificial', pos: 'adj' },
  { rank: 1186, hr: 'svjetski', en: 'world (adj) / global', pos: 'adj' },
  { rank: 1187, hr: 'europski', en: 'European', pos: 'adj' },
  { rank: 1188, hr: 'hrvatski', en: 'Croatian', pos: 'adj' },
  { rank: 1189, hr: 'prosječan', en: 'average', pos: 'adj' },
  { rank: 1190, hr: 'izvrstan', en: 'excellent', pos: 'adj' },
  { rank: 1191, hr: 'odličan', en: 'excellent / great', pos: 'adj' },
  { rank: 1192, hr: 'savršen', en: 'perfect', pos: 'adj' },
  { rank: 1193, hr: 'užasan', en: 'terrible', pos: 'adj' },
  { rank: 1194, hr: 'strašan', en: 'dreadful / awesome', pos: 'adj' },
  { rank: 1195, hr: 'grozan', en: 'horrible', pos: 'adj' },
  { rank: 1196, hr: 'čudan', en: 'strange', pos: 'adj' },
  { rank: 1197, hr: 'neobičan', en: 'unusual', pos: 'adj' },
  { rank: 1198, hr: 'tipičan', en: 'typical', pos: 'adj' },
  { rank: 1199, hr: 'redovit', en: 'regular', pos: 'adj' },
  { rank: 1200, hr: 'stalan', en: 'constant / permanent', pos: 'adj' },
  { rank: 1201, hr: 'privremen', en: 'temporary', pos: 'adj' },
  { rank: 1202, hr: 'hitan', en: 'urgent', pos: 'adj' },
  { rank: 1203, hr: 'gotov', en: 'finished / done', pos: 'adj' },
  { rank: 1204, hr: 'spreman', en: 'ready', pos: 'adj' },
  { rank: 1205, hr: 'dostupan', en: 'available / accessible', pos: 'adj' },
  { rank: 1206, hr: 'prisutan', en: 'present (in attendance)', pos: 'adj' },
  { rank: 1207, hr: 'živ', en: 'alive / lively', pos: 'adj' },
  { rank: 1208, hr: 'mrtav', en: 'dead', pos: 'adj' },
  { rank: 1209, hr: 'budan', en: 'awake', pos: 'adj' },
  { rank: 1210, hr: 'pospan', en: 'sleepy', pos: 'adj' },
  { rank: 1211, hr: 'sit', en: 'full (sated)', pos: 'adj' },
  { rank: 1212, hr: 'unaprijed', en: 'in advance', pos: 'adv' },
  { rank: 1213, hr: 'usput', en: 'by the way / on the way', pos: 'adv' },
  { rank: 1214, hr: 'slučajno', en: 'accidentally / by chance', pos: 'adv' },
  { rank: 1215, hr: 'namjerno', en: 'on purpose', pos: 'adv' },
  { rank: 1216, hr: 'ozbiljno', en: 'seriously', pos: 'adv' },
  { rank: 1217, hr: 'stvarno', en: 'really', pos: 'adv' },
  { rank: 1218, hr: 'zaista', en: 'truly / indeed', pos: 'adv' },
  { rank: 1219, hr: 'jedva', en: 'barely / hardly', pos: 'adv' },
  { rank: 1220, hr: 'tiho', en: 'quietly', pos: 'adv' },
  { rank: 1221, hr: 'pažljivo', en: 'carefully', pos: 'adv' },
  { rank: 1222, hr: 'točno', en: 'exactly / correctly', pos: 'adv' },
  { rank: 1223, hr: 'vani', en: 'outside', pos: 'adv' },
  { rank: 1224, hr: 'unutra', en: 'inside', pos: 'adv' },
  { rank: 1225, hr: 'blizu', en: 'near', pos: 'adv' },
  { rank: 1226, hr: 'daleko', en: 'far', pos: 'adv' },
  { rank: 1227, hr: 'visoko', en: 'high (up)', pos: 'adv' },
  { rank: 1228, hr: 'okolo', en: 'around', pos: 'adv' },
  { rank: 1229, hr: 'dnevno', en: 'daily / per day', pos: 'adv' },
  { rank: 1230, hr: 'tjedno', en: 'weekly', pos: 'adv' },
  { rank: 1231, hr: 'mjesečno', en: 'monthly', pos: 'adv' },
  { rank: 1232, hr: 'godišnje', en: 'yearly / annually', pos: 'adv' },
  { rank: 1233, hr: 'ujutro', en: 'in the morning', pos: 'adv' },
  { rank: 1234, hr: 'popodne', en: 'in the afternoon', pos: 'adv' },
  { rank: 1235, hr: 'navečer', en: 'in the evening', pos: 'adv' },
  { rank: 1236, hr: 'noću', en: 'at night', pos: 'adv' },
  { rank: 1237, hr: 'rano', en: 'early', pos: 'adv' },
  { rank: 1238, hr: 'kasno', en: 'late', pos: 'adv' },
  { rank: 1239, hr: 'nedavno', en: 'recently', pos: 'adv' },
  { rank: 1240, hr: 'davno', en: 'long ago', pos: 'adv' },
  { rank: 1241, hr: 'trenutno', en: 'currently', pos: 'adv' },
  { rank: 1242, hr: 'istovremeno', en: 'simultaneously', pos: 'adv' },
  { rank: 1243, hr: 'postupno', en: 'gradually', pos: 'adv' },
  { rank: 1244, hr: 'obično', en: 'usually', pos: 'adv' },
  { rank: 1245, hr: 'nažalost', en: 'unfortunately', pos: 'adv' },
  { rank: 1246, hr: 'srećom', en: 'fortunately', pos: 'adv' },
  { rank: 1247, hr: 'svakako', en: 'by all means / definitely', pos: 'adv' },
  { rank: 1248, hr: 'pješice', en: 'on foot', pos: 'adv' },
  { rank: 1249, hr: 'inozemstvo', en: 'abroad (foreign countries)', pos: 'noun' },
  { rank: 1250, hr: 'otprilike', en: 'approximately', pos: 'adv' },
];

export function getFrequencyWords(): FrequencyEntry[] {
  return FREQUENCY_500;
}

export function getLearnedFrequencyWords(): number[] {
  try {
    return JSON.parse(localStorage.getItem('nh_freq_learned') || '[]');
  } catch {
    return [];
  }
}

export function markFrequencyWordLearned(rank: number): void {
  try {
    const learned = getLearnedFrequencyWords();
    if (!learned.includes(rank)) {
      learned.push(rank);
      localStorage.setItem('nh_freq_learned', JSON.stringify(learned));
    }
  } catch {
    // ignore storage errors
  }
}
