/**
 * screenTabs — which tab a screen belongs to, and which screens survive a
 * back-navigation. One definition each.
 *
 * WHAT THIS REPLACES, and why it is not merely tidying. App.tsx carried FOUR
 * declarations for two facts: `_RESTORE_SAFE` and `SAFE_RESTORE` (byte-identical
 * sets, 300 lines apart) and `_TAB_FOR_SCR` and `stm` (screen to tab). Two
 * places that must agree with nothing enforcing it — and they HAD disagreed:
 * a comment beside the second map still records that `grammarmap` was 'practice'
 * in one and 'learn' in the other, so the highlighted tab flipped depending on
 * whether the learner arrived by deep link or by navigation.
 *
 * MEASURED BEFORE MERGING THEM, because "duplicate" was the wrong word: the two
 * maps were NESTED, not equal — 46 entries against 203, with the smaller a
 * strict subset and ZERO disagreements at the time of the merge. The set of
 * facts is therefore the bigger map, and nothing was lost by dropping the
 * smaller one.
 *
 * THE 36 DEAD ENTRIES. `_TAB_FOR_SCR[s]` was read only inside
 * `if (_RESTORE_SAFE.has(s))`, so only the 11 restore-safe screens could ever
 * reach it. Thirty-six of its forty-six rows were unreachable — written, never
 * read, and reading exactly like coverage. They are gone; `screenTabs.test.ts`
 * fails if a restore-safe screen ever lacks a tab here.
 *
 * `dashboard` is DELIBERATELY absent, and is the one restore-safe screen with no
 * entry. It is the per-tab home of every tab, so it cannot name one — and the
 * restore path already falls back to `dashboard`, so the absence costs nothing.
 * Adding it would mean choosing a tab arbitrarily.
 */

/** Screen id → the tab it belongs to. */
export const SCREEN_TAB: Record<string, string> = {
  lesson: 'learn',
  grammar: 'learn',
  padezi: 'learn',
  padezifull: 'learn',
  modal: 'learn',
  tenses: 'learn',
  alphabet: 'learn',
  reading: 'learn',
  read: 'learn',
  readinglist: 'learn',
  readlist: 'learn',
  aspect: 'learn',
  falsefr: 'learn',
  declension: 'learn',
  brzalice: 'learn',
  dialects: 'learn',
  diminutives: 'learn',
  wordform: 'learn',
  colorquirk: 'learn',
  svojmoj: 'learn',
  countries: 'learn',
  professions: 'learn',
  weather: 'learn',
  clothes: 'learn',
  bodydesc: 'learn',
  phonology: 'learn',
  mcgame: 'practice',
  mcresult: 'practice',
  flashcards: 'practice',
  match: 'practice',
  typing: 'practice',
  listening: 'practice',
  speaking: 'practice',
  znam: 'practice',
  boje: 'practice',
  conj: 'practice',
  conjdrill: 'practice',
  unjumble: 'practice',
  prepdrill: 'practice',
  numtime: 'practice',
  wordsprint: 'practice',
  profgender: 'practice',
  comparatives: 'practice',
  future: 'practice',
  sibil: 'practice',
  restaurant: 'practice',
  qwords: 'practice',
  negation: 'practice',
  possess: 'practice',
  coloragree: 'practice',
  opposites: 'practice',
  cityloc: 'practice',
  accusativedrill: 'practice',
  ordinals: 'practice',
  relpron: 'practice',
  emogender: 'practice',
  verbdrill: 'practice',
  tenseflip: 'practice',
  riddles: 'practice',
  logicquiz: 'practice',
  pronouns: 'practice',
  genderdrill: 'practice',
  sentbuild: 'practice',
  reflexive: 'practice',
  fillstory: 'practice',
  convmatch: 'practice',
  scenes: 'practice',
  storyselect: 'practice',
  story: 'practice',
  proverbs: 'practice',
  idioms: 'practice',
  pitchaccent: 'practice',
  shadowing: 'practice',
  review: 'practice',
  writing: 'practice',
  aspectdrill: 'practice',
  clitic: 'practice',
  numcases: 'practice',
  passive: 'practice',
  instrumental: 'practice',
  dative: 'practice',
  animateacc: 'practice',
  participles: 'practice',
  subordination: 'practice',
  conditionaldrill: 'practice',
  idiomdrill: 'practice',
  discourse: 'practice',
  register: 'practice',
  nominalization: 'practice',
  imperative: 'practice',
  neggen: 'practice',
  collocations: 'practice',
  wordfamilies: 'practice',
  dictation: 'practice',
  proncontrast: 'practice',
  dialogue: 'practice',
  cefrtest: 'practice',
  slang: 'practice',
  region_labin: 'croatia',
  region_bibinje: 'croatia',
  region_hercegovina: 'croatia',
  region_vukovar: 'croatia',
  region_vinkovci: 'croatia',
  region_zagreb: 'croatia',
  region_split: 'croatia',
  region_mostar: 'croatia',
  region_tomislavgrad: 'croatia',
  region_knin: 'croatia',
  cityofday: 'croatia',
  immersion: 'croatia',
  aiconvo: 'croatia',
  crmap: 'croatia',
  history: 'croatia',
  kings: 'croatia',
  grocery: 'croatia',
  recipes: 'croatia',
  roleplay: 'ai',
  texting: 'croatia',
  friends: 'croatia',
  foodorder: 'croatia',
  transport: 'croatia',
  emergency: 'croatia',
  football: 'croatia',
  popculture: 'croatia',
  practical: 'croatia',
  school: 'croatia',
  basketball: 'croatia',
  gym: 'croatia',
  top100: 'croatia',
  events: 'croatia',
  croatiaathletes: 'croatia',
  baka_summer: 'croatia',
  croatia_today: 'croatia',
  survival_dinner: 'croatia',
  kafic: 'croatia',
  diaspora: 'croatia',
  postcard: 'croatia',
  storymode: 'croatia',
  heritage: 'croatia',
  croatianews: 'croatia',
  phraseofday: 'croatia',
  maja: 'ai',
  tivicompare: 'learn',
  grammarvideos: 'learn',
  grammarexplainer: 'learn',
  casetransformer: 'learn',
  vocabscenes: 'learn',
  animlesson: 'learn',
  lessonreview: 'learn',
  grammarreader: 'learn',
  lifeevents: 'croatia',
  civic: 'croatia',
  easter: 'croatia',
  midsummer: 'croatia',
  domovina: 'croatia',
  bozic: 'croatia',
  cloze: 'practice',
  badges: 'profile',
  journal: 'profile',
  favorites: 'profile',
  learnpath: 'learn',
  contact: 'profile',
  certificate: 'profile',
  analytics: 'profile',
  profile: 'profile',
  admin: 'profile',
  privacy: 'profile',
  terms: 'profile',
  'grammar-ref': 'learn',
  learning_center: 'learn',
  coursemap: 'learn',
  mistakes: 'practice',
  listeningpath: 'practice',
  grammarmap: 'learn', // align with _TAB_FOR_SCR.grammarmap; was 'practice' → the two maps disagreed, so the highlighted tab flipped depending on entry path
  my_words: 'practice',
  speaking_sprint: 'practice',
  ai_listening: 'practice',
  ai_story: 'practice',
  grammar_diagnosis: 'learn',
  micro_lesson: 'learn',
  personas: 'ai',
  live_tutor: 'ai',
  grammar_track: 'learn',
  listening_comprehension: 'practice',
  translate_drills: 'practice',
  sentencetiles: 'practice',
  photo_vocab: 'learn',
  video_lesson: 'practice',
  graded_input: 'practice',
  pronunciation_course: 'learn',
  past_tense_lesson: 'learn',
  future_tense_lesson: 'learn',
  advanced_vocab: 'learn',
  pronunciation_assess: 'practice',
  production_drill: 'practice',
  adaptive_review: 'practice',
  pitch_accent: 'learn',
  vocative: 'learn',
  heritage_path: 'croatia',
  dialect_awareness: 'learn',
  heritage_mode: 'croatia',
  phoneme_practice: 'learn',
  frequency_track: 'learn',
  practical_croatian: 'croatia',
};

/**
 * Screens safe to restore when returning to a tab via browser back or a tab-bar
 * press. Exercise screens are excluded: they need launch-time state a back-nav
 * cannot provide, and land on ScreenGuard without it.
 */
export const RESTORE_SAFE_SCREENS: ReadonlySet<string> = new Set([
  'dashboard',
  'learnpath',
  'grammar_track',
  'grammar-ref',
  'learning_center',
  'coursemap',
  'grammarmap',
  'favorites',
  'journal',
  'analytics',
  'badges',
  'certificate',
]);
