import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactPlugin from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import security from 'eslint-plugin-security';
import globals from 'globals';

export default [
  // Ignore build output and scripts
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'scripts/**',
      'public/**',
      // Regenerated by scripts/rebuildCities.mjs from JSON inputs.
      'src/data/cultural/geography.js',
      'functions/api/content/_data/cultural/geography.js',
    ],
  },

  // Base JS rules
  js.configs.recommended,

  // Security rules — applied everywhere (src + Cloudflare functions)
  {
    files: ['src/**/*.{js,jsx}', 'functions/**/*.js'],
    plugins: { security },
    rules: {
      // Catches: regex injection, unsafe eval, object injection via bracket notation,
      // non-literal require, non-literal fs paths, buffer constructor misuse
      ...security.configs.recommended.rules,
      // Off in src — data.jsx and lib files use bracket notation throughout for
      // legitimate key-based lookups (vocabulary maps, stat counters, etc.).
      // Functions files use eslint-disable-next-line where needed.
      'security/detect-object-injection': 'off',
      'security/detect-non-literal-regexp': 'off',
    },
  },

  // React + hooks rules for all source files
  {
    files: ['src/**/*.{js,jsx}'],
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooks,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.es2022,
      },
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
    },
    settings: {
      react: { version: 'detect' },
    },
    rules: {
      // ── React core ──────────────────────────────────────────────────────
      ...reactPlugin.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off',        // React 17+ auto-import
      'react/display-name': 'off',              // HOC display names are optional
      'react/no-unknown-property': 'error',
      'react/jsx-key': 'error',                 // Missing key= in lists — runtime error
      'react/no-array-index-key': 'off',        // Many list items have no stable ID
      'react/prop-types': 'off',                // TypeScript/JSDoc covers this
      'react/no-unescaped-entities': 'off',     // Croatian strings contain apostrophes — harmless

      // ── React Hooks ─────────────────────────────────────────────────────
      // These two rules catch the class of bugs that burned us:
      // stale closures, missing deps, conditional hook calls
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',

      // ── General quality ─────────────────────────────────────────────────
      'no-unused-vars': ['warn', {
        // Don't check function args — components often accept props they don't always use
        args: 'none',
        // Ignore vars/destructured values starting with _ (intentional placeholder)
        varsIgnorePattern: '^_',
        // ESLint 9 changed caughtErrors default to 'all'; ignore _ and e in catch blocks
        caughtErrors: 'all',
        caughtErrorsIgnorePattern: '^_|^e$',
      }],
      'no-console': ['warn', { allow: ['error', 'warn'] }],
      'no-debugger': 'error',
      'no-undef': 'error',
      'eqeqeq': ['error', 'always', { null: 'ignore' }],
      'no-var': 'off',              // Legacy code — cleanup deferred
      'prefer-const': 'off',        // Style preference — deferred
      'no-empty': 'off',            // Intentional empty catch blocks exist throughout
      'no-useless-escape': 'off',   // Escaped characters in Croatian data strings — harmless
      // SP3a: cap new files at 800 lines (excluding blank + comment lines).
      // Grandfathered offenders are in their own override block at the bottom.
      'max-lines': ['error', { max: 800, skipBlankLines: true, skipComments: true }],
    },
  },

  // Cloudflare Functions — Node/worker globals
  {
    files: ['functions/**/*.js'],
    languageOptions: {
      globals: {
        ...globals.browser, // Cloudflare Workers have a browser-like env
        Request: 'readonly',
        Response: 'readonly',
        URL: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': ['warn', { allow: ['error', 'warn'] }],
      // Same Croatian data files (grammar.js etc.) now live under functions/api/content/_data/
      // for Cloudflare Functions consumption; escapes are harmless string literals.
      'no-useless-escape': 'off',
      // SP11d: vocabScenes.js (originally src/components/learn/VocabSceneData.js) uses
      // try { ... } catch {} idioms for localStorage best-effort. Harmless empty catches.
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },

  // TypeScript source files — type-aware linting for converted .ts/.tsx files
  ...tseslint.configs.recommended.map(cfg => ({
    ...cfg,
    files: ['src/**/*.{ts,tsx}'],
  })),
  {
    files: ['src/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': ['warn', {
        args: 'none',
        varsIgnorePattern: '^_',
        caughtErrors: 'all',
        caughtErrorsIgnorePattern: '^_|^e$',
      }],
      // Allow .js extensions in imports (Vite resolves .ts transparently)
      '@typescript-eslint/consistent-type-imports': ['warn', { prefer: 'type-imports', fixStyle: 'inline-type-imports' }],
      // Migration: @ts-nocheck marks files with pre-existing type violations being
      // progressively fixed. Banning it during migration would force 2000+ type fixes
      // before any TypeScript coverage is possible. Remove this override once all
      // @ts-nocheck markers have been resolved.
      '@typescript-eslint/ban-ts-comment': 'error',
      // The following rules were already off for .jsx files and must stay off for .tsx
      // during migration — same code patterns exist throughout (React && expr, escapes, etc.)
      '@typescript-eslint/no-unused-expressions': 'off',
      'no-useless-escape': 'off',
      'prefer-const': 'off',
      'no-var': 'off',
      'no-empty': 'off',
      // SP3a: cap new files at 800 lines (matches .js/.jsx block above).
      'max-lines': ['error', { max: 800, skipBlankLines: true, skipComments: true }],
    },
  },
  // React hooks plugin for TypeScript files (mirrors .js/.jsx block above)
  {
    files: ['src/**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': reactHooks,
    },
    rules: {
      'react-hooks/exhaustive-deps': 'warn',
      'no-empty': 'off',
    },
  },

  // SP11d: consumer screens that read 26 loose-typed Content fields via useContent.
  // The data has heterogeneous nested shapes; tightening to specific interfaces would
  // require ~100 type declarations matching source files exactly. Pragmatic 'any'
  // narrowing at consumption sites preserves runtime behavior. Tighten in a future SP.
  {
    files: [
      'src/components/croatia/**/*.{ts,tsx}',
      'src/components/learn/**/*.{ts,tsx}',
      'src/components/practice/**/*.{ts,tsx}',
      'src/components/profile/**/*.{ts,tsx}',
      'src/components/home/**/*.{ts,tsx}',
    ],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  // SP3a: curriculum content (vocabulary, scenarios, exercises, cultural).
  // Length is determined by curriculum scope, not code complexity. Wholesale
  // exempt — splitting would not improve maintainability. Mostly src/data/**;
  // listening/exercises.ts is the comprehension-exercise corpus extracted from
  // ListeningComprehensionScreen in 1b (data only, no logic).
  {
    files: ['src/data/**/*.{js,ts,tsx}', 'src/components/practice/listening/exercises.ts'],
    rules: { 'max-lines': 'off' },
  },
  // SP3a: grandfathered files over the 800-line threshold (audit 2026-05-16).
  // New files added after this date must respect the rule. Each entry here
  // represents a deliberate scope decision to NOT split this file in SP3a.
  // To remove a file from this list: split it into smaller modules first.
  {
    files: [
      'src/components/practice/PracticeTab.tsx',
      'src/components/practice/ListeningComprehensionScreen.tsx',
      'src/components/AppRouter.tsx',
      'src/App.tsx',
      'src/components/home/HeroSection.tsx',
      'src/components/profile/SettingsTab.tsx',
      'src/components/learn/LearnTab.tsx',
      'src/components/croatia/CroatiaCulture.tsx',
      'src/components/croatia/AIConversation.tsx',
      'src/components/practice/ProductionDrillScreen.tsx',
      'src/components/learn/GrammarExplainer.tsx',
      'src/components/learn/LessonScreen.tsx',
      'src/components/learn/PitchAccentMastery.tsx',
      'src/lib/firebase.ts',
      'src/components/croatia/HeritagePathScreen.tsx',
      'src/components/croatia/LiveTutorScreen.tsx',
      'src/components/shared/CroatianKnight.tsx',
      'src/components/learn/VocabScreens.tsx',
      'src/components/practice/SpeakingScreen.tsx',
      'src/components/practice/FlashcardCardFront.tsx',
      'src/components/croatia/CroatiaHistoryScreen.tsx',
      'src/components/profile/LearnPath.tsx',
      'src/components/profile/PrivacyScreen.tsx',
      // 800–1500 line offenders from full lint audit
      'src/components/croatia/AIConversationChat.tsx',
      'src/components/croatia/ConversationScenarios.js',
      'src/components/croatia/CroatiaToday.tsx',
      'src/components/croatia/CultureTab.tsx',
      'src/components/croatia/DialectAwarenessScreen.tsx',
      'src/components/croatia/HeritageStoryScreen.tsx',
      'src/components/croatia/HNLScreen.tsx',
      'src/components/croatia/ImmersionHub.tsx',
      'src/components/croatia/MajaScreen.tsx',
      'src/components/croatia/MediaTab.tsx',
      'src/components/croatia/PhraseOfDayScreen.tsx',
      'src/components/croatia/PostcardScreen.tsx',
      'src/components/home/GrammarDiagnosisScreen.tsx',
      'src/components/home/WelcomeScreen.tsx',
      'src/components/illustrations/DalmatianCoast.tsx',
      'src/components/learn/BrowseContentModal.tsx',
      'src/components/learn/FutureTenseLessonScreen.tsx',
      'src/components/learn/GradedInputScreen.tsx',
      'src/components/learn/GrammarTrackScreen.tsx',
      'src/components/learn/HeritageModeScreen.tsx',
      'src/components/learn/MicroLessonScreen.tsx',
      'src/components/learn/NewLessons.tsx',
      'src/components/learn/PracticalCroatianScreen.tsx',
      'src/components/learn/VocabSceneSVGs.tsx',
      'src/components/practice/CefrTest.tsx',
      'src/components/practice/ClozeEngine.tsx',
      'src/components/practice/slangData.js',
      'src/components/practice/VideoLessonScreen.tsx',
      'src/components/profile/StatsTab.tsx',
      'src/components/shared/KnightSpeech.tsx',
    ],
    rules: { 'max-lines': 'off' },
  },
  // SP3a: tests can legitimately exceed 800 lines (parametrized describes).
  {
    files: [
      'src/**/__tests__/**',
      'src/**/*.test.{ts,tsx,js,jsx}',
      'src/**/*.spec.{ts,tsx,js,jsx}',
      'src/tests/**',
    ],
    rules: { 'max-lines': 'off' },
  },
  // SP3a: config + e2e files exempt.
  {
    files: ['*.config.{js,mjs,ts}', 'vite.config.*', 'playwright.*.config.*', 'e2e/**'],
    rules: { 'max-lines': 'off' },
  },

  // Test files — relax some rules
  {
    files: ['src/tests/**/*.{js,jsx}', '**/*.test.{js,jsx}', '**/*.spec.{js,jsx}'],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        vi: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
      'react-hooks/exhaustive-deps': 'off',
    },
  },
];
