// language.js
export const DIALECTS = {
  intro: 'Croatian has three main dialects named after how they say \u0027what\u0027:',
  types: [
    {
      name: 'Štokavski',
      what: 'Što?',
      region: 'Standard Croatian, most of Croatia, all of Bosnia',
      desc: 'The basis for standard Croatian. Used in schools, media, and official settings. If you learn standard Croatian, you\u0027re learning Štokavski.',
      color: '#0e7490',
    },
    {
      name: 'Kajkavski',
      what: 'Kaj?',
      region: 'Zagreb and northwestern Croatia (Zagorje)',
      desc: 'Spoken in and around Zagreb. Sounds quite different from standard — shorter words, different intonation. Many Zagreb expressions come from Kajkavski.',
      color: '#7c3aed',
    },
    {
      name: 'Čakavski',
      what: 'Ča?',
      region: 'Istria, Kvarner, Dalmatian islands',
      desc: 'The coastal dialect. Heard on islands and in Istria. Has Italian influences and archaic Croatian forms. Very different vocabulary from standard.',
      color: '#b45309',
    },
  ],
  examples: [
    { en: 'What?', std: 'Što?', kaj: 'Kaj?', cak: 'Ča?' },
    { en: 'What are you doing?', std: 'Što radiš?', kaj: 'Kaj delaš?', cak: 'Ča činiš?' },
    { en: 'Where?', std: 'Gdje?', kaj: 'Gde? / Kam?', cak: 'Di?' },
    { en: 'I don\u0027t know', std: 'Ne znam', kaj: 'Neznam / Nevem', cak: 'Ne znan' },
    { en: 'House', std: 'Kuća', kaj: 'Hiža', cak: 'Kaša / Kuća' },
    { en: 'Boy', std: 'Dječak', kaj: 'Deček', cak: 'Mulac' },
    { en: 'Beautiful', std: 'Lijep', kaj: 'Lep', cak: 'Lip' },
    { en: 'Bread', std: 'Kruh', kaj: 'Kruh', cak: 'Kru(h)' },
  ],
  chakavianNote:
    "Čakavian (Čakavski) is the dialect of the Adriatic coast — Istria, Kvarner, and the Dalmatian islands. It preserves many archaic Croatian features and shows Italian/Venetian influence (words like 'škulj' for hole, 'šufit' for attic from Italian 'soffitto'). If you visit Hvar, Brač, Vis, or Rovinj, locals may speak Čakavian at home. You don't need to speak it, but recognizing it prevents confusion. Key markers: 'ča' for 'what', 'di' for 'gdje/where', 'more' still means sea, 'znan' for 'znam'. Čakavian poems by writers like Tin Ujević are considered some of the most beautiful Croatian literature.",
  heritageNote:
    'Heritage speakers (diaspora Croatian) often mix Štokavian grammar with vocabulary frozen from the 1960s-1990s emigration wave, anglicisms, or regional forms from Dalmatia/Slavonia. Common heritage patterns: older vocabulary (auto instead of automobil), German/Australian English loanwords, simplified case system. If your Croatian comes from family, you may speak naturally but make systematic errors in formal cases — especially genitive plural. This is normal and fixable.',
  mutualIntelligibility:
    'All three dialects are mutually intelligible with effort, but Kajkavian and Čakavian can sound very foreign to a Štokavian speaker at first. Standard Croatian is always understood across all regions. Serbian is essentially mutually intelligible with Croatian — grammatically identical, vocabulary differs especially in loanwords (Serbian uses more Slavic/Russian roots; Croatian uses Latin/German).',
};
export const SHADOWING = [
  {
    hr: 'Dobro jutro! Kako ste?',
    en: 'Good morning! How are you?',
    tip: 'Formal greeting — ste is formal/plural',
    level: 'A1',
  },
  {
    hr: 'Gdje je najbliža ljekarna?',
    en: 'Where is the nearest pharmacy?',
    tip: 'Asking directions — gdje = where',
    level: 'A1',
  },
  {
    hr: 'Molim vas, možete li mi pomoći?',
    en: 'Please, can you help me?',
    tip: 'Polite request — molim vas = please (formal)',
    level: 'A2',
  },
  {
    hr: 'Koliko košta taj kruh?',
    en: 'How much does that bread cost?',
    tip: 'Shopping — koliko košta = how much does it cost',
    level: 'A1',
  },
  {
    hr: 'Trebam kartu za Split.',
    en: 'I need a ticket for Split.',
    tip: 'Travel vocabulary — trebam = I need',
    level: 'A1',
  },
  {
    hr: 'Nisam razumio. Možete li ponoviti?',
    en: "I didn't understand. Can you repeat?",
    tip: 'Clarification — essential phrase for learners',
    level: 'A2',
  },
  {
    hr: 'Volim Hrvatsku i njezin jezik.',
    en: 'I love Croatia and its language.',
    tip: 'Possessive — njezin = its/her (for feminine noun)',
    level: 'A2',
  },
  {
    hr: 'Ona svaki dan uči hrvatski.',
    en: 'She studies Croatian every day.',
    tip: 'Daily routine — svaki dan = every day',
    level: 'A2',
  },
  {
    hr: 'Djeca se igraju na plaži.',
    en: 'Children are playing on the beach.',
    tip: 'Reflexive verb — igrati se = to play',
    level: 'A2',
  },
  {
    hr: 'Jesi li već večerao?',
    en: 'Have you had dinner yet?',
    tip: 'Perfect tense question — jesi li = have you',
    level: 'B1',
  },
  {
    hr: 'Sutra ćemo ići u kino.',
    en: 'Tomorrow we will go to the cinema.',
    tip: 'Future tense — ćemo ići = we will go',
    level: 'A2',
  },
  {
    hr: 'Ova kava je jako dobra.',
    en: 'This coffee is very good.',
    tip: 'Gender agreement — ova (fem.) kava (fem.)',
    level: 'A1',
  },
  {
    hr: 'Mogu li platiti karticom?',
    en: 'Can I pay by card?',
    tip: 'Instrumental case — karticom = by card',
    level: 'B1',
  },
  {
    hr: 'Rezervirao sam stol za dvoje.',
    en: 'I reserved a table for two.',
    tip: 'Past tense — rezervirao sam = I reserved',
    level: 'B1',
  },
  {
    hr: 'Ne razumijem, govorite li engleski?',
    en: "I don't understand, do you speak English?",
    tip: 'Essential learner phrase',
    level: 'A1',
  },
  {
    hr: "Kako se kaže 'hello' na hrvatskom?",
    en: "How do you say 'hello' in Croatian?",
    tip: 'Asking for translation',
    level: 'A1',
  },
  {
    hr: 'Imam rezervaciju na ime Smith.',
    en: 'I have a reservation under the name Smith.',
    tip: 'Hotel/restaurant vocabulary',
    level: 'B1',
  },
  {
    hr: 'Koja je razlika između tih dvaju vina?',
    en: 'What is the difference between those two wines?',
    tip: 'Genitive plural — dvaju = of two (genitive dual)',
    level: 'C1',
  },
  {
    hr: 'Da sam znao, došao bih ranije.',
    en: 'If I had known, I would have come earlier.',
    tip: 'Conditional — došao bih = I would have come',
    level: 'B1',
  },
  {
    hr: 'Upravo sam se vratio s posla.',
    en: 'I have just returned from work.',
    tip: 'upravo sam se — clitic cluster: aux before se',
    level: 'B1',
  },
  {
    hr: 'Iako je padala kiša, odlučili smo prošetati uz rivu.',
    en: 'Although it was raining, we decided to take a walk along the seafront.',
    tip: 'Concessive clause — iako = although; comma after it',
    level: 'B2',
  },
  {
    hr: 'Najviše me se dojmila gostoljubivost domaćina.',
    en: "What impressed me most was the hosts' hospitality.",
    tip: 'dojmiti se + genitive — me se cluster',
    level: 'B2',
  },
  {
    hr: 'Prije nego što odgovorite, dobro razmislite o svim mogućnostima.',
    en: 'Before you answer, think carefully about all the options.',
    tip: 'prije nego što + present; o + locative plural',
    level: 'B2',
  },
  {
    hr: 'Sastanak je odgođen zbog nepredviđenih okolnosti.',
    en: 'The meeting has been postponed due to unforeseen circumstances.',
    tip: 'Passive — odgođen; zbog + genitive',
    level: 'B2',
  },
  {
    hr: 'Što se mene tiče, možemo krenuti odmah.',
    en: 'As far as I am concerned, we can leave right away.',
    tip: 'Fixed phrase — što se mene tiče',
    level: 'B2',
  },
  {
    hr: 'Nisam siguran hoće li stići na vrijeme.',
    en: 'I am not sure whether he will arrive on time.',
    tip: 'Indirect question — hoće li, no comma before it',
    level: 'B2',
  },
  {
    hr: 'Unatoč svim poteškoćama, projekt je priveden kraju u roku.',
    en: 'Despite all the difficulties, the project was completed on schedule.',
    tip: 'unatoč + dative; privesti kraju = bring to completion',
    level: 'C1',
  },
  {
    hr: 'Bilo bi mi iznimno drago kad biste nam se pridružili.',
    en: 'I would be extremely glad if you joined us.',
    tip: 'kad + conditional biste; dative mi',
    level: 'C1',
  },
  {
    hr: 'Riječ je o pitanju koje zaslužuje ozbiljnu javnu raspravu.',
    en: 'This is a matter that deserves serious public debate.',
    tip: 'riječ je o + locative — formal register opener',
    level: 'C1',
  },
  {
    hr: 'Koliko god se trudili, savršenstvo je nedostižno.',
    en: 'However hard we try, perfection is unattainable.',
    tip: 'koliko god + conditional-like concession',
    level: 'C1',
  },
  {
    hr: 'S obzirom na okolnosti, postupili ste sasvim ispravno.',
    en: 'Considering the circumstances, you acted entirely correctly.',
    tip: 's obzirom na + accusative — formal connective',
    level: 'C1',
  },
  {
    hr: 'Ma koliko se okolnosti činile nepovoljnima, ne smijemo posustati.',
    en: 'However unfavourable the circumstances may seem, we must not falter.',
    tip: 'ma koliko + instrumental predicate — elevated register',
    level: 'C2',
  },
  {
    hr: 'Njegova je argumentacija, premda dojmljiva, počivala na spornim pretpostavkama.',
    en: 'His argumentation, though impressive, rested on questionable assumptions.',
    tip: 'Inserted concession fenced by commas — premda',
    level: 'C2',
  },
  {
    hr: 'Zamolio bih vas da ubuduće takve primjedbe iznosite pisanim putem.',
    en: 'I would ask you to submit such remarks in writing in future.',
    tip: 'Formal complaint register — pisanim putem = in writing',
    level: 'C2',
  },
  {
    hr: 'Vrijeme je bilo prekrasno. Šteta što niste bili s nama.',
    en: 'The weather was wonderful. A pity you were not with us.',
    tip: 'Two-sentence prosody — šteta što + clause',
    level: 'C2',
  },
  {
    hr: 'Sve u svemu, dojmovi su izvrsni. Rado bismo ponovno došli.',
    en: 'All in all, the impressions are excellent. We would gladly come again.',
    tip: 'Connected speech — sve u svemu; rado bismo',
    level: 'C2',
  },
];
