// proverbs.js
export const PROVERBS = [
  { hr: 'Tko rano rani, dvije sreće grabi.', en: 'The early bird catches two fortunes.' },
  { hr: 'Bolje spriječiti nego liječiti.', en: 'Better to prevent than to cure.' },
  { hr: 'Bez muke nema nauke.', en: 'No pain, no gain.' },
  { hr: 'Tko pita, ne skita.', en: "He who asks, doesn't wander." },
  { hr: 'Vuk dlaku mijenja, ali ćud nikada.', en: 'A wolf changes fur, but never character.' },
  { hr: 'Polako se daleko stigne.', en: 'Going slowly, you reach far.' },
  { hr: 'Svaka ptica svome jatu leti.', en: 'Every bird flies to its own flock.' },
  { hr: 'Kakav otac, takav sin.', en: 'Like father, like son.' },
  {
    hr: 'Tko drugome jamu kopa, sam u nju upada.',
    en: 'He who digs a pit for others falls in himself.',
  },
  { hr: 'Tiha voda brijeg roni.', en: 'Still waters erode mountains.' },
  { hr: 'Čovjek uči dok je živ.', en: 'A person learns as long as they live.' },
  { hr: 'Tko ne riskira, ne profitira.', en: 'Nothing ventured, nothing gained.' },
  {
    hr: 'Udarac se zaboravi, a ružna riječ nikada.',
    en: 'A blow is forgotten, but an ugly word never.',
  },
  {
    hr: 'Bolje vrabac u ruci nego golub na grani.',
    en: 'A sparrow in hand beats a pigeon on a branch.',
  },
  { hr: 'Svaki početak je težak.', en: 'Every beginning is hard.' },
  { hr: 'Tko čeka, dočeka.', en: "He who waits, gets what he's waiting for." },
  { hr: 'Nada umire posljednja.', en: 'Hope dies last.' },
  { hr: 'Oko za oko, zub za zub.', en: 'An eye for an eye, a tooth for a tooth.' },
  {
    hr: 'Tko pod drugim jamu kopa, sam u nju pada.',
    en: 'He who digs a pit for another falls in it.',
  },
  { hr: 'Gdje ima dima, ima i vatre.', en: "Where there's smoke, there's fire." },
  { hr: 'Što se Ivica naučio, to Ivan zna.', en: 'What little Ivan learns, grown Ivan knows.' },
  {
    hr: 'Lako je tuđim kurcem gloginje mlatiti.',
    en: "Easy to beat bushes with someone else's stick.",
  },
  { hr: 'Pametnom dosta.', en: 'Enough said to the wise.' },
  { hr: 'Novac ne raste na drveću.', en: "Money doesn't grow on trees." },
  { hr: 'Tko laže, taj i krade.', en: 'He who lies also steals.' },
  { hr: 'Jedna lasta ne čini proljeće.', en: "One swallow doesn't make spring." },
  { hr: 'Bolje kasno nego nikad.', en: 'Better late than never.' },
  { hr: 'Tko se zadnji smije, najslađe se smije.', en: 'He who laughs last, laughs sweetest.' },
  { hr: 'Ljubav je slijepa.', en: 'Love is blind.' },
  { hr: 'Glad je najbolji kuhar.', en: 'Hunger is the best cook.' },
  { hr: 'U laži su kratke noge.', en: 'Lies have short legs.' },
  { hr: 'Kako siješ, tako ćeš žeti.', en: 'As you sow, so shall you reap.' },
  { hr: 'Ne govori hop dok ne preskočiš.', en: "Don't say hop until you've jumped." },
  { hr: 'Jabuka ne pada daleko od stabla.', en: "The apple doesn't fall far from the tree." },
  { hr: 'Pas koji laje, ne grize.', en: "A barking dog doesn't bite." },
  { hr: 'Riba od glave smrdi.', en: 'Fish rots from the head.' },
  { hr: 'Novac nije sve.', en: "Money isn't everything." },
  { hr: 'Nitko nije prorok u svom selu.', en: 'No one is a prophet in their own village.' },
  { hr: 'Što je previše, nije zdravo.', en: 'Too much of anything is unhealthy.' },
  { hr: 'Svakom loncu poklopac.', en: 'Every pot has its lid.' },
  { hr: 'Tko žuri, griješi.', en: 'He who hurries, makes mistakes.' },
  { hr: 'Vježba čini majstora.', en: 'Practice makes perfect.' },
  { hr: 'Mladost ludost.', en: 'Youth is folly.' },
  { hr: 'Ne daj Bože da se seljak obogati.', en: 'God forbid a peasant gets rich. (ironic)' },
  { hr: 'Život je lijep.', en: 'Life is beautiful.' },
  { hr: 'Jezik kosti nema, ali kosti lomi.', en: 'The tongue has no bones, but breaks bones.' },
  { hr: 'Na muci se poznaju junaci.', en: 'Heroes are known in times of hardship.' },
  { hr: 'Čista savjest, miran san.', en: 'Clean conscience, peaceful sleep.' },
  { hr: 'Dobro jutro, susjede!', en: 'Good morning, neighbor!' },
  { hr: 'Iza kiše dolazi sunce.', en: 'After rain comes sunshine.' },
  { hr: 'Znanje je moć.', en: 'Knowledge is power.' },
  { hr: 'Kad mačke nema, miševi kolo vode.', en: "When the cat's away, the mice dance." },
  {
    hr: 'Koliko jezika znaš, toliko vrijediš.',
    en: "You're worth as many people as languages you know.",
  },
  { hr: 'Tko se boji, ne ide u šumu.', en: "He who's afraid doesn't go into the forest." },
  { hr: 'Kraj psa i štap stoji.', en: 'Keep a stick near the dog. (Be prepared)' },
  { hr: 'Nije sve zlato što sija.', en: 'Not all that glitters is gold.' },
  { hr: 'U zdravom tijelu, zdrav duh.', en: 'A healthy mind in a healthy body.' },
  { hr: 'Ne budi ovca među vukovima.', en: "Don't be a sheep among wolves." },
  { hr: 'Moja kuća, moja pravila.', en: 'My house, my rules.' },
  { hr: 'I sam Bog odmara nedjeljom.', en: 'Even God rests on Sunday.' },
  { hr: 'Teško onom tko nema nikoga.', en: 'Woe to those who have no one.' },
  { hr: 'Svaki put vodi u Rim.', en: 'All roads lead to Rome.' },
  { hr: 'Krv nije voda.', en: 'Blood is thicker than water.' },
  { hr: 'Bolje grob nego rob.', en: 'Better the grave than a slave.' },
  { hr: 'U slozi je snaga.', en: 'In unity there is strength.' },
  { hr: 'Mirna Bosna.', en: 'Quiet Bosnia. (sarcastic — when things are chaotic)' },
  { hr: 'Dva loša ubiju dobrog.', en: 'Two bad ones beat a good one.' },
  { hr: 'Pravda je spora, ali dostižna.', en: 'Justice is slow, but reachable.' },
  { hr: 'Što Bog daje, to se ne odbija.', en: "What God gives, one doesn't refuse." },
  { hr: 'Čuvaj se onoga kome se ne vidi rog.', en: "Beware of those whose horns you can't see." },
  { hr: 'Svaka medalja ima dvije strane.', en: 'Every medal has two sides.' },
  { hr: 'Daleko od očiju, daleko od srca.', en: 'Far from eyes, far from heart.' },
  { hr: 'Nema kruha bez motike.', en: 'No bread without a hoe. (Hard work needed)' },
  { hr: 'Prazna vreća ne stoji uspravno.', en: "An empty sack can't stand upright." },
  { hr: 'Riba i gost treći dan smrde.', en: 'Fish and guests stink on the third day.' },
  {
    hr: 'Tko s đavolom tikve sadi, o glavu mu se razbijaju.',
    en: 'He who plants pumpkins with the devil gets them smashed on his head.',
  },
  { hr: 'Vjera čini čuda.', en: 'Faith works miracles.' },
  {
    hr: 'Tko te ljubi više od majke, taj te laže.',
    en: 'Whoever loves you more than your mother is lying.',
  },
  { hr: 'Vrijeme je novac.', en: 'Time is money.' },
  { hr: 'Dvaput mjeri, jednom reži.', en: 'Measure twice, cut once.' },
  { hr: 'Ne vrijedi plakati nad prolivenim mlijekom.', en: 'No use crying over spilled milk.' },
  { hr: 'Svaka priča ima kraj.', en: 'Every story has an end.' },
  { hr: 'Tko visoko leti, nisko pada.', en: 'He who flies high, falls low.' },
  { hr: 'Sreća prati hrabre.', en: 'Fortune favors the brave.' },
  { hr: 'Jači bježi, slabiji trči.', en: 'The strong flee, the weak run. (ironic)' },
  { hr: 'Za svaku bolest ima lijek.', en: "For every illness there's a cure." },
  { hr: 'Tko radi, ne boji se gladi.', en: "He who works doesn't fear hunger." },
  {
    hr: 'Čovjek se ne poznaje dok se ne iskuša.',
    en: "You don't know a person until they're tested.",
  },
  { hr: 'Istina boli.', en: 'Truth hurts.' },
  {
    hr: 'Tri su stvari u životu važne: zdravlje, obitelj i ljubav.',
    en: 'Three things matter in life: health, family, and love.',
  },
  { hr: 'Dobar glas daleko se čuje.', en: 'A good reputation carries far.' },
  { hr: 'Naša snaga je u jedinstvu.', en: 'Our strength is in unity.' },
  { hr: 'Život je borba.', en: 'Life is a struggle.' },
  { hr: 'Dok je živjeti, dotle je i nadati se.', en: "As long as there's life, there's hope." },
  { hr: 'Vranino pero ne bude bijelo.', en: "A crow's feather doesn't become white." },
  { hr: 'Tko se jednom opeče, drugi put puše.', en: 'Once burned, twice shy.' },
  {
    hr: 'Ključ od svakih vrata visi o strpljenju.',
    en: 'The key to every door hangs on patience.',
  },
  { hr: 'Od viška glava ne boli.', en: "Surplus doesn't cause headache." },
  {
    hr: 'Mršava pogodba bolja od debele parnice.',
    en: 'A thin deal is better than a fat lawsuit.',
  },
  { hr: 'Obraz je najljepši dar.', en: 'Dignity is the most beautiful gift.' },
  {
    hr: 'Ne prodaji medvjedu kožu dok ga nisi ulovio.',
    en: "Don't sell the bear's skin before catching it.",
  },
  { hr: 'Govor je srebro, šutnja je zlato.', en: 'Speech is silver, silence is gold.' },
  { hr: 'Šilo za ognjilo.', en: 'A needle for a flintstone. (Tit for tat)' },
  { hr: 'Iz tuđe kože širi remen.', en: "Cutting wide straps from someone else's leather." },
  { hr: 'Kratka pamet, dugačak jezik.', en: 'Short brain, long tongue.' },
  { hr: 'Kap po kap i kamen probiješ.', en: 'Drop by drop, you pierce the stone.' },
  { hr: 'Ruka ruku pere, a obraz obadvije.', en: 'One hand washes the other, both wash the face.' },
  { hr: 'Svaka čast poštenom čovjeku.', en: 'All honor to an honest person.' },
  { hr: 'Ni u raju nije dobro sam.', en: "Even in paradise it's not good to be alone." },
  { hr: 'Kome nije dano, nije mu ni suđeno.', en: 'What is not given is not destined.' },
  { hr: 'Boj se Boga i nikoga.', en: 'Fear God and no one else.' },
  { hr: 'Rodila gora miša.', en: 'The mountain gave birth to a mouse.' },
  { hr: 'Lakše je savjetovati nego pomoći.', en: 'Easier to advise than to help.' },
  { hr: 'I na vrbi raste grožđe.', en: "Even on a willow, grapes can grow. (Anything's possible)" },
  { hr: 'Svojta do koljena.', en: 'Relatives to the knee. (Family closeness)' },
  { hr: 'Stara ljubav ne zarđa.', en: "Old love doesn't rust." },
  { hr: 'S kim si, takav si.', en: "You are who you're with." },
  { hr: 'Nevolja ne dolazi sama.', en: "Trouble doesn't come alone." },
  { hr: 'Lijepa riječ i željezna vrata otvara.', en: 'A kind word opens even iron gates.' },
  { hr: 'Ispeci pa reci.', en: 'Bake it then say it. (Think before speaking)' },
  { hr: 'Ako Bog da.', en: 'God willing.' },
  { hr: 'Dobar dan se poznaje po jutru.', en: 'A good day is known by its morning.' },
  { hr: 'Sjekira ne padne daleko od klade.', en: "The axe doesn't fall far from the stump." },
  { hr: 'Istina izlazi na vidjelo.', en: 'Truth comes to light.' },
  {
    hr: 'Tko drugom jamu kopa, sam u nju pada.',
    en: 'Who digs a pit for another falls in it himself.',
  },
  {
    hr: 'Za dom spremni znači: kuću čistiti!',
    en: 'Ready for home means: clean the house! (joke)',
  },
  { hr: 'Što narod reče, Bog potvrdi.', en: 'What the people say, God confirms.' },
  {
    hr: 'Učenje je blago koje svog vlasnika prati svuda.',
    en: 'Learning is a treasure that follows its owner everywhere.',
  },
  { hr: 'Dva oka više vide nego jedno.', en: 'Two eyes see more than one.' },
  { hr: 'Sto puta mjeri, jednom reži.', en: 'Measure a hundred times, cut once.' },
  {
    hr: 'Bolje znoj na čelu nego mrlji na obrazu.',
    en: "Better sweat on the forehead than a stain on one's honor.",
  },
  {
    hr: 'Čega se pametan stidi, budala se ponosi.',
    en: 'What the wise are ashamed of, fools are proud of.',
  },
  { hr: 'Čuvaj bijele novce za crne dane.', en: 'Save white coins for black days.' },
  {
    hr: 'Da zna čovjek gdje će pasti, prostro bi slamu.',
    en: "If one knew where they'd fall, they'd spread straw.",
  },
  { hr: 'Dobro se dobrim vraća.', en: 'Good is repaid with good.' },
  { hr: 'Drago kamenje se u blatu nalazi.', en: 'Precious stones are found in mud.' },
  { hr: 'Gost u kuću, Bog u kuću.', en: 'A guest in the house, God in the house.' },
  {
    hr: 'Govori istinu i kad te po glavi biju.',
    en: 'Speak the truth even when they beat you over the head.',
  },
  {
    hr: 'Hrabrost nije ne bojati se, nego raditi unatoč strahu.',
    en: "Courage isn't fearlessness, but acting despite fear.",
  },
  { hr: 'I Rim se nije sagradio u jednom danu.', en: "Rome wasn't built in a day either." },
  { hr: 'Iz malih žira rastu veliki hrastovi.', en: 'From small acorns grow great oaks.' },
  { hr: 'Jak kao bik.', en: 'Strong as a bull.' },
  { hr: 'Jutarnja kava, najbolja kava.', en: 'Morning coffee, best coffee.' },
  { hr: 'Kaplja koja prelije čašu.', en: 'The drop that overflows the glass. (Last straw)' },
  {
    hr: 'Kad te udari po jednom obrazu, okreni drugi.',
    en: 'When struck on one cheek, turn the other.',
  },
  { hr: 'Koji vuk odgoji, takva lisica bude.', en: 'Whatever wolf raises, such a fox it becomes.' },
  { hr: 'Lako je biti general poslije bitke.', en: 'Easy to be a general after the battle.' },
  { hr: 'Ljubav prema domovini je sveta dužnost.', en: 'Love for the homeland is a sacred duty.' },
  { hr: 'Mali čovjek, velika duša.', en: 'Small person, great soul.' },
  {
    hr: 'More je solju bogato, ali se ne može piti.',
    en: "The sea is rich with salt, but you can't drink it.",
  },
  {
    hr: 'Mudrosti u tisuću godina ima za jedan dan.',
    en: "A thousand years' wisdom fits in one day.",
  },
  { hr: 'Na pametnog se ne treba ljutiti.', en: "There's no need to be angry at the wise." },
  {
    hr: 'Nasmij se svijetu, i svijet će se tebi nasmiješiti.',
    en: 'Smile at the world, and the world smiles back.',
  },
  { hr: 'Nemoj se hvalisati tuđim perjem.', en: "Don't boast with someone else's feathers." },
  {
    hr: 'Nije sramota ne znati, sramota je ne učiti.',
    en: "It's no shame not to know; it's shame not to learn.",
  },
  { hr: 'Nikad se ne zna tko ti sutra treba.', en: "You never know who you'll need tomorrow." },
  { hr: 'Obećano, ispunjeno.', en: 'Promised, fulfilled.' },
  { hr: 'Otvorena knjiga, otvoreno srce.', en: 'Open book, open heart.' },
  { hr: 'Piti vodu s izvora.', en: 'To drink water from the source. (Go to the origin)' },
  { hr: 'Potreba je majka izuma.', en: 'Necessity is the mother of invention.' },
  {
    hr: 'Pravi prijatelj se u nevolji poznaje.',
    en: 'A true friend is known in times of trouble.',
  },
  {
    hr: 'Put od tisuću milja počinje jednim korakom.',
    en: 'A journey of a thousand miles begins with one step.',
  },
  { hr: 'Rad je spas.', en: 'Work is salvation.' },
  { hr: 'Samo mrtva riba pliva niz struju.', en: 'Only a dead fish swims downstream.' },
  { hr: 'Tko čuva, taj ima.', en: 'He who saves, has.' },
  { hr: 'Trn ne ulazi u nogu bez razloga.', en: "A thorn doesn't enter the foot without reason." },
  { hr: 'Umjesto da kažeš, pokaži.', en: 'Instead of telling, show.' },
  { hr: 'Uz more se ljepše diše.', en: 'By the sea one breathes more beautifully.' },
  { hr: 'Vjerni drugovi u dobru i zlu.', en: 'Faithful companions in good and bad.' },
  { hr: 'Volja čovjekova, snaga Božja.', en: "Man's will, God's strength." },
  { hr: 'Za svakog ima mjesta pod suncem.', en: "There's a place under the sun for everyone." },
  { hr: 'Zdravlje je najveće bogatstvo.', en: 'Health is the greatest wealth.' },
  { hr: 'Želje su konji sirotinje.', en: 'Wishes are the horses of the poor.' },
  { hr: 'Život bez ljubavi je život bez sunca.', en: 'Life without love is life without sun.' },
  { hr: 'Bolje je malo, ali sigurno.', en: 'Better a little, but certain.' },
  { hr: 'Čovjek je čovjeku lijek.', en: "A person is a person's remedy." },
  { hr: 'Dobre stvari dolaze onima koji čekaju.', en: 'Good things come to those who wait.' },
  { hr: 'Gdje se dvoje svađa, treći profitira.', en: 'Where two quarrel, the third profits.' },
  { hr: 'Jedan za sve, svi za jednog.', en: 'One for all, all for one.' },
  { hr: 'Kako kreneš, tako ćeš završiti.', en: 'As you start, so you shall finish.' },
  {
    hr: 'Ljubav prema jeziku je ljubav prema narodu.',
    en: 'Love for language is love for the people.',
  },
  { hr: 'Mudrost je znati koliko ne znaš.', en: "Wisdom is knowing how much you don't know." },
  {
    hr: 'Ne pitaj koliko košta, pitaj koliko vrijedi.',
    en: "Don't ask what it costs, ask what it's worth.",
  },
  { hr: 'Pametan čovjek šuti kad je ljut.', en: 'A wise person is silent when angry.' },
  { hr: 'Svaki novi dan je novi početak.', en: 'Every new day is a new beginning.' },
  { hr: 'Temelj sreće je u obitelji.', en: 'The foundation of happiness is in family.' },
  { hr: 'Vjera premješta planine.', en: 'Faith moves mountains.' },
  { hr: 'Zajedništvo je snaga.', en: 'Togetherness is strength.' },
  { hr: 'Bog pomaže onima koji si sami pomažu.', en: 'God helps those who help themselves.' },
  { hr: 'Čuvaj prijatelja kao oko u glavi.', en: 'Guard a friend like the eye in your head.' },
  { hr: 'Dijete je radost kuće.', en: 'A child is the joy of the home.' },
  { hr: 'Gradi kuću od temelja.', en: 'Build a house from the foundation.' },
  {
    hr: 'Hrabar čovjek jednom umire, kukavica tisuću puta.',
    en: 'A brave person dies once, a coward a thousand times.',
  },
  { hr: 'Istina je gorka, ali ljekovita.', en: 'Truth is bitter, but healing.' },
  { hr: 'Koliko je lijepih dana pred nama!', en: 'How many beautiful days lie ahead of us!' },
  { hr: 'Lopov misli da svi kradu.', en: 'A thief thinks everyone steals.' },
  { hr: 'More odgaja jake ljude.', en: 'The sea raises strong people.' },
  { hr: 'Naši stari su znali.', en: 'Our elders knew.' },
  { hr: 'Pošten rad nikada ne propada.', en: 'Honest work never fails.' },
  { hr: 'Rok se ne može zaustaviti.', en: 'Time cannot be stopped.' },
  { hr: 'Sunce sija svima jednako.', en: 'The sun shines equally on everyone.' },
  { hr: 'Tko ima vjeru, ima sve.', en: 'He who has faith has everything.' },
  { hr: 'Uči od starih, gradi za mlade.', en: 'Learn from the old, build for the young.' },
  { hr: 'Zemlja je majka.', en: 'The earth is a mother.' },
  { hr: 'Život je dar.', en: 'Life is a gift.' },
  { hr: 'Bez trna nema ruže.', en: "Without thorns, there's no rose." },
  { hr: 'Croatia plena est virtutum.', en: 'Croatia is full of virtues. (Latin motto)' },
  { hr: 'Domovina se ne zaboravlja.', en: 'The homeland is never forgotten.' },
  { hr: 'Gori lampa u srcu hrvatskom.', en: 'A lamp burns in the Croatian heart.' },
  { hr: 'Hrvat zna put kući.', en: 'A Croat knows the way home.' },
  { hr: 'Jako je more, ali je Hrvat jači.', en: 'The sea is powerful, but the Croat is stronger.' },
  { hr: 'Kameni zidovi ne čine zatvor.', en: 'Stone walls do not a prison make.' },
  { hr: 'Ljepota je u oku promatrača.', en: 'Beauty is in the eye of the beholder.' },
  { hr: 'Mala zemlja, veliko srce.', en: 'Small country, big heart.' },
  { hr: 'Ne brini se za sutra.', en: "Don't worry about tomorrow." },
  { hr: 'Ostaviti trag na svijetu.', en: 'To leave a mark on the world.' },
  { hr: 'Prošlost je učiteljica budućnosti.', en: 'The past is the teacher of the future.' },
  { hr: 'Radost se dijeli, tuga se pola.', en: 'Joy is shared, sorrow halved.' },
  { hr: 'Snaga je u korijenu.', en: 'Strength is in the roots.' },
  {
    hr: 'Tisućama kilometara od kuće, ali srce je tamo.',
    en: 'Thousands of kilometers from home, but the heart is there.',
  },
  { hr: 'U tuđini se čovjek za dom najviše brine.', en: 'Abroad, one worries most about home.' },
  { hr: 'Vjerna zemlja, vjerni narod.', en: 'Faithful land, faithful people.' },
  { hr: 'Za Boga i Hrvatsku!', en: 'For God and Croatia!' },
  { hr: 'Duša Hrvata nikada ne umire.', en: 'The Croatian soul never dies.' },
  { hr: 'Gdje god bio, Hrvat ostaje.', en: 'Wherever they go, a Croat remains.' },
  { hr: 'Hrvatski ponos je vječan.', en: 'Croatian pride is eternal.' },
  { hr: 'Jednom Hrvat, uvijek Hrvat.', en: 'Once a Croat, always a Croat.' },
  { hr: 'Kroz borbu do pobjede.', en: 'Through struggle to victory.' },
  { hr: 'Ljubav prema domovini ne pozna granice.', en: 'Love for homeland knows no borders.' },
  { hr: 'Narod koji pamti, narod koji živi.', en: 'A people who remember, a people who live.' },
  { hr: 'Od mora do Dunava, sve je naše.', en: 'From the sea to the Danube, all is ours.' },
  {
    hr: 'Svako dijete nosi domovinu u srcu.',
    en: 'Every child carries the homeland in their heart.',
  },
  {
    hr: 'Tradicija je most između prošlosti i budućnosti.',
    en: 'Tradition is a bridge between past and future.',
  },
  {
    hr: 'U znaku križa, u sjeni grba.',
    en: 'In the sign of the cross, in the shade of the coat of arms.',
  },
  { hr: 'Vrijeme liječi rane, ali sjećanje ostaje.', en: 'Time heals wounds, but memory remains.' },
  { hr: 'Zauvijek zahvalni braniteljima.', en: 'Forever grateful to the defenders.' },
  { hr: 'Budućnost pripada hrabrima.', en: 'The future belongs to the brave.' },
  { hr: 'Čuvaj vjeru i obitelj.', en: 'Guard faith and family.' },
  { hr: 'Dom je tamo gdje je srce.', en: 'Home is where the heart is.' },
  { hr: 'Iz pepela se rađa feniks.', en: 'From ashes, the phoenix is born.' },
  { hr: 'Korak po korak, cilj se dostiže.', en: 'Step by step, the goal is reached.' },
  { hr: 'Ljubav, vjera, nada.', en: 'Love, faith, hope.' },
  { hr: 'Mi smo Hrvati i to je naš ponos.', en: 'We are Croats and that is our pride.' },
  { hr: 'Ništa nas ne može slomiti.', en: 'Nothing can break us.' },
  { hr: 'Ratnici su neuništivi.', en: 'Warriors are indestructible.' },
  { hr: 'Ja sam bio izuzetak.', en: 'I was the exception.' },
  { hr: 'Volja i strpljenje pobjeđuju sve.', en: 'Will and patience conquer all.' },
  {
    hr: 'Malo dijete, mali problemi; veliko dijete, veliki problemi.',
    en: 'Small child, small problems; big child, big problems.',
  },
  { hr: 'Bolje je dati nego primiti.', en: "It's better to give than to receive." },
  {
    hr: 'Nije bitno koliko padneš, nego koliko puta ustaneš.',
    en: "It doesn't matter how many times you fall, but how many times you get up.",
  },
  { hr: 'Strpljen — spašen.', en: 'Patient — saved.' },
  { hr: 'Tko ima volju, nađe i put.', en: "Where there's a will, there's a way." },
  { hr: 'Ne sudi po izgledu.', en: "Don't judge by appearance." },
  { hr: 'Bolje biti sam nego u lošem društvu.', en: 'Better alone than in bad company.' },
  { hr: 'Znanje se ne može ukrasti.', en: 'Knowledge cannot be stolen.' },
  { hr: 'Zora rano, mrak kasno.', en: 'Dawn early, dark late. (Long days of work)' },
  { hr: 'Tko koga čuva, Bog ga čuva.', en: 'Who protects others, God protects.' },
  { hr: 'Obraz je skuplji od zlata.', en: 'Honor is more expensive than gold.' },
  { hr: 'Dijete je ogledalo roditelja.', en: 'A child is a mirror of their parents.' },
  { hr: 'Pametan šuti kad budala govori.', en: 'The wise stay silent when a fool speaks.' },
  { hr: 'Što bi selo reklo?', en: 'What would the village say? (Social pressure)' },
  { hr: 'Nema uspjeha bez truda.', en: 'No success without effort.' },
  { hr: 'Tko rano sije, rano žanje.', en: 'He who sows early, reaps early.' },
  { hr: 'U zdravlju je sve.', en: 'Health is everything.' },
  {
    hr: 'Svaka majka misli da je njeno dijete najljepše.',
    en: 'Every mother thinks her child is the most beautiful.',
  },
  { hr: 'Kamen koji se kotrlja ne hvata mahovinu.', en: 'A rolling stone gathers no moss.' },
  { hr: 'Čini drugima ono što želiš da čine tebi.', en: "Do to others as you'd want done to you." },
  { hr: 'Ono što ne ubiješ, ojača te.', en: "What doesn't kill you makes you stronger." },
  { hr: 'S ponosom nosi svoje ime.', en: 'Carry your name with pride.' },
  { hr: 'Pobijediti sebe je najveća pobjeda.', en: 'Conquering yourself is the greatest victory.' },
  { hr: 'Tko štedi, taj ima.', en: 'He who saves, has.' },
  { hr: 'Sutra je novi dan.', en: 'Tomorrow is a new day.' },
  { hr: 'Prijatelji se broje u nevolji.', en: 'Friends are counted in times of trouble.' },
  { hr: 'Ne pljuj u bunar iz kojeg piješ.', en: "Don't spit in the well you drink from." },
  { hr: 'Mladi za rad, stari za savjet.', en: 'Youth for work, elders for advice.' },
  { hr: 'Tko traži, nađe.', en: 'He who seeks, finds.' },
  { hr: 'Uz rijeku do mora.', en: 'Along the river to the sea.' },
  { hr: 'Nitko ne zna što nosi sutra.', en: 'No one knows what tomorrow brings.' },
  {
    hr: 'Snaga obitelji je snaga naroda.',
    en: 'The strength of family is the strength of a nation.',
  },
  {
    hr: 'Tisuću prijatelja je malo, jedan neprijatelj je previše.',
    en: 'A thousand friends is few, one enemy is too many.',
  },
  { hr: 'Poslije oluje dolazi mir.', en: 'After the storm comes peace.' },
  { hr: 'Mudar čovjek uči od svakog.', en: 'A wise person learns from everyone.' },
  { hr: 'Na svoj način, ali na pravi put.', en: 'In your own way, but on the right path.' },
  { hr: 'Koliko glava, toliko ćudi.', en: 'As many heads, as many temperaments.' },
  { hr: 'Gdje nema pravde, nema ni mira.', en: "Where there's no justice, there's no peace." },
  { hr: 'U borbi za pravdu nikad ne odustaj.', en: 'In the fight for justice, never give up.' },
  { hr: 'Kada zatvorim oči, vidim Hrvatsku.', en: 'When I close my eyes, I see Croatia.' },
  { hr: 'Riječ je mač, a šutnja štit.', en: 'Words are a sword, silence a shield.' },
  { hr: 'Zlatne ruke stvaraju čuda.', en: 'Golden hands create wonders.' },
  {
    hr: 'Ne tražiti lakog puta, nego ispravnog.',
    en: "Don't seek the easy path, but the right one.",
  },
  { hr: 'Samo zajedno možemo.', en: 'Only together we can.' },
  { hr: 'Svaki dan je nova prilika.', en: 'Every day is a new opportunity.' },
  { hr: 'Ono što ima korijena, ne boji se vjetra.', en: "What has roots doesn't fear the wind." },
  {
    hr: 'Hrabar je onaj tko se boji, ali ipak ide naprijed.',
    en: "Brave is the one who's afraid but goes forward anyway.",
  },
  { hr: 'Svi putevi kući vode.', en: 'All roads lead home.' },
  { hr: 'Kiša je blagoslov neba.', en: "Rain is heaven's blessing." },
  { hr: 'Snaga dolazi iz srca.', en: 'Strength comes from the heart.' },
  {
    hr: 'Odgoj je najvažniji dar koji roditelj može dati.',
    en: 'Upbringing is the most important gift a parent can give.',
  },
  { hr: 'Zahvalnost je znak plemenite duše.', en: 'Gratitude is a sign of a noble soul.' },
  { hr: 'Ljubav prema djeci nema granica.', en: 'Love for children knows no limits.' },
  { hr: 'Gdje god bijaše, dom je u srcu.', en: "Wherever you've been, home is in the heart." },
  {
    hr: 'Reci mi s kim hodaš, pa ću ti reći tko si.',
    en: "Tell me who you walk with, I'll tell you who you are.",
  },
  { hr: 'Mudrost je kruna života.', en: 'Wisdom is the crown of life.' },
  {
    hr: 'Ponos ne hrani, ali bez njega nema života.',
    en: "Pride doesn't feed, but without it there's no life.",
  },
  { hr: 'Kada govoriš, govori srcem.', en: 'When you speak, speak from the heart.' },
  {
    hr: 'Što naučiš u mladosti, nosiš u starosti.',
    en: 'What you learn in youth, you carry in old age.',
  },
  { hr: 'Narod koji pjeva, narod koji živi.', en: 'A people who sing, a people who live.' },
  { hr: 'Tko čuva čast, čuva i budućnost.', en: 'Who preserves honor, preserves the future.' },
  { hr: 'Jednom se živi.', en: 'You only live once.' },
  { hr: 'Čistom srcu nema prepreka.', en: 'For a pure heart, there are no obstacles.' },
  { hr: 'Ako ne ja, tko? Ako ne sada, kada?', en: 'If not me, who? If not now, when?' },
  {
    hr: 'Temelji su najvažniji dio kuće.',
    en: 'The foundations are the most important part of a house.',
  },
  { hr: 'Ono što daješ, to ti se vraća.', en: 'What you give, comes back to you.' },
  {
    hr: 'Sretan je onaj tko ima za koga živjeti.',
    en: 'Happy is the one who has someone to live for.',
  },
  { hr: 'Jezik je ključ svijeta.', en: 'Language is the key to the world.' },
  { hr: 'Mudrost bez hrabrosti je beskorisna.', en: 'Wisdom without courage is useless.' },
  { hr: 'Mir je najskuplji dar.', en: 'Peace is the most expensive gift.' },
  { hr: 'Tko pjeva, zlo ne misli.', en: 'He who sings thinks no evil.' },
  { hr: 'Smijeh je lijek za dušu.', en: 'Laughter is medicine for the soul.' },
  { hr: 'U moru problema, budi luka.', en: 'In a sea of problems, be a port.' },
  { hr: 'Budi promjena koju želiš vidjeti.', en: 'Be the change you want to see.' },
  { hr: 'Ljubav pobjeđuje sve.', en: 'Love conquers all.' },
  { hr: 'Vjera bez djela je mrtva.', en: 'Faith without works is dead.' },
  {
    hr: 'Dobrota je jezik koji gluhi čuju i slijepi vide.',
    en: 'Kindness is a language the deaf hear and the blind see.',
  },
  { hr: 'Novi dan, nova nada.', en: 'New day, new hope.' },
  { hr: 'Tko ne plače, ne smije se.', en: "He who doesn't cry, cannot laugh." },
  { hr: 'Život piše najljepše priče.', en: 'Life writes the most beautiful stories.' },
  {
    hr: 'Nije važno odakle dolaziš, nego kamo ideš.',
    en: "It's not where you're from, but where you're going.",
  },
  { hr: 'Sreća je u malim stvarima.', en: 'Happiness is in the small things.' },
  { hr: 'Naša snaga je u raznolikosti.', en: 'Our strength is in diversity.' },
  { hr: 'Hvala Bogu na svakom danu.', en: 'Thank God for every day.' },
  { hr: 'Čovjek je jak koliko je jaka njegova volja.', en: 'A person is as strong as their will.' },
  { hr: 'Budi svjetlo u tami.', en: 'Be a light in the darkness.' },
  { hr: 'Osmijeh ne košta ništa.', en: 'A smile costs nothing.' },
  { hr: 'Život je putovanje, ne odredište.', en: 'Life is a journey, not a destination.' },
  {
    hr: 'Čuvaj ono što imaš dok ne shvatiš da nemaš.',
    en: "Appreciate what you have before you realize you don't.",
  },
  { hr: 'Stari prijatelji su kao staro vino.', en: 'Old friends are like old wine.' },
  { hr: 'Hrabrost počinje prvim korakom.', en: 'Courage begins with the first step.' },
  { hr: 'Svi smo putnici na istom putu.', en: 'We are all travelers on the same road.' },
  {
    hr: 'Ljubav je jedini rat koji se isplati voditi.',
    en: 'Love is the only war worth fighting.',
  },
  {
    hr: 'Kada se jedna vrata zatvore, druga se otvore.',
    en: 'When one door closes, another opens.',
  },
  { hr: 'Tko nosi križ, nosi i krunu.', en: 'He who carries the cross, carries the crown.' },
  {
    hr: 'Sretni su oni koji siju, jer će žeti.',
    en: 'Blessed are those who sow, for they shall reap.',
  },
  { hr: 'Odrasli smo na moru, vjetru i kamenu.', en: 'We grew up on sea, wind, and stone.' },
  { hr: 'Naš put je dug, ali siguran.', en: 'Our path is long, but certain.' },
  {
    hr: 'Kad si ponosan na svoje korijene, stabilan si kao hrast.',
    en: "When proud of your roots, you're steady as an oak.",
  },
  {
    hr: 'Sjeti se odakle dolaziš i znaj kamo ideš.',
    en: "Remember where you come from and know where you're going.",
  },
  {
    hr: 'Život bez izazova je život bez rasta.',
    en: 'Life without challenges is life without growth.',
  },
  { hr: 'Za svaku suzu, deset osmjeha.', en: 'For every tear, ten smiles.' },
  { hr: 'Nebo je granica.', en: 'The sky is the limit.' },
  { hr: 'Budi ponosan, budi Hrvat.', en: 'Be proud, be Croatian.' },
  { hr: 'Zajedno smo jači.', en: 'Together we are stronger.' },
  { hr: 'Naša Hrvatska, naš dom.', en: 'Our Croatia, our home.' },
  { hr: 'Onaj tko vjeruje, taj i može.', en: 'Those who believe, can.' },
  { hr: 'Kolijevka nas uči, grob nas čeka.', en: 'The cradle teaches us, the grave awaits.' },
  {
    hr: 'Ne daj da ti itko ugasi vatru u srcu.',
    en: "Don't let anyone extinguish the fire in your heart.",
  },
  { hr: 'Život je kratak, čini dobro.', en: 'Life is short, do good.' },
  { hr: 'Ako možeš sanjati, možeš i ostvariti.', en: 'If you can dream it, you can achieve it.' },
  {
    hr: 'Više vrijedi jedna istina nego tisuću laži.',
    en: 'One truth is worth more than a thousand lies.',
  },
  {
    hr: 'Čovjek bez domovine je kao drvo bez korijena.',
    en: 'A person without a homeland is like a tree without roots.',
  },
  { hr: 'Istina je kćerka vremena.', en: 'Truth is the daughter of time.' },
  { hr: 'Sreća dolazi iznutra.', en: 'Happiness comes from within.' },
  { hr: 'Majka je prvi učitelj.', en: 'A mother is the first teacher.' },
  { hr: 'Život nas uči svakim danom.', en: 'Life teaches us every day.' },
  { hr: 'Naša snaga je u vjeri i ljubavi.', en: 'Our strength is in faith and love.' },
];
