// @ts-nocheck
import React from 'react';
import { H } from '../../data';

export default function PrivacyScreen({ goBack }) {
  return (
    <div className="scr-wrap">
      {H('Privacy & Terms', 'Last updated: March 2026', goBack)}

      <div className="c" style={{ marginBottom: 16 }}>
        <h3 style={{ fontSize: 15, fontWeight: 800, color: 'var(--heading)', marginBottom: 8 }}>
          Privacy Policy
        </h3>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          This Privacy Policy applies to the Naša Hrvatska application operated by{' '}
          <strong>Lijepa Naša (personal non-commercial project)</strong>. By using this app, you
          agree to the collection and use of information as described in this policy.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>What we collect:</strong> Your email address and display name (used to identify
          your account). Your learning progress — XP, lesson completions, streak data,
          spaced-repetition records, favorites, and vocabulary journal — stored securely in Firebase
          Firestore and cached locally on your device for offline access. No browsing data, no
          device fingerprinting, no advertising identifiers.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>Family groups (parent-managed):</strong> The family leaderboard feature is
          designed to be created and managed by a parent or legal guardian. By creating a family
          group that includes minor children, the parent or guardian confirms they have authority to
          enroll those children and consents to their display name and learning progress (XP, lesson
          count) being shared within the family group. Member email addresses are visible to other
          members of the same family group in order to support the invite and management flow.
          Family data is stored in Firebase Firestore and is not accessible to users outside the
          group.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>Text-to-speech:</strong> Words and phrases you choose to hear aloud are sent to
          ElevenLabs (primary) or Microsoft Azure Speech Services (fallback) to generate audio.
          Voice audio is generated by ElevenLabs text-to-speech technology. Text sent for audio
          generation is processed by ElevenLabs. These requests are proxied through our server and
          are not stored or retained by us after the audio is delivered.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>AI writing assistance:</strong> When you use the AI Conversation or writing
          correction features, the text you write (up to 1,000 characters) and the current
          conversation context are sent to Anthropic's Claude API to generate feedback and
          corrections. This content is not stored by us after the response is returned. Anthropic's
          data practices are governed by their{' '}
          <a
            href="https://www.anthropic.com/privacy"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: '#0e7490' }}
          >
            privacy policy
          </a>
          .
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>Support tickets:</strong> When you submit a help request through the Contact
          Support form, the contents of your message (type, subject, description, and optional reply
          email) along with your display name, level, and XP are sent to our administrator via
          Resend, a transactional email service. This data is used solely to respond to your
          request.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>Analytics:</strong> We use Plausible Analytics, a privacy-first, cookie-free
          service. Plausible does not track individuals, set cookies, or sell data. We may also use
          PostHog for product analytics and Sentry for error monitoring — both configured to
          minimize personal data collection, disable session recording, and scrub sensitive fields.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>Data processors:</strong> The following third-party services process data on our
          behalf under their respective data processing agreements: Google Firebase (authentication
          and database), ElevenLabs (text-to-speech), Microsoft Azure Speech Services
          (text-to-speech fallback), Anthropic (AI writing assistance), Resend (support email
          delivery), Plausible Analytics (privacy-first analytics). We do not sell, rent, or share
          your personal data with third parties for commercial purposes.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>Data retention:</strong> Your account data is retained until you request deletion.
          Local device data (localStorage) persists until you clear your browser storage or
          uninstall the app. Cached family leaderboard data is stored locally for offline access and
          refreshed automatically.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>Cross-device sync:</strong> Your learning progress is automatically synchronized
          across your devices via Firebase Firestore. When you sign in on a new device, your
          progress is downloaded and the most recent version is applied.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>Your rights:</strong> You may request access to, correction of, or deletion of
          your personal data at any time. To exercise these rights, email{' '}
          <a href="mailto:privacy@nasahrvatska.com" style={{ color: '#0e7490' }}>
            privacy@nasahrvatska.com
          </a>
          . We will process your request within 30 days.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 6 }}>
          <strong>Additional rights:</strong>
        </p>
        <ul
          style={{
            fontSize: 13,
            color: 'var(--rt-c)',
            lineHeight: 1.7,
            marginBottom: 10,
            paddingLeft: 20,
          }}
        >
          <li style={{ marginBottom: 6 }}>
            <strong>Right to data portability (Article 20):</strong> You can request an export of
            your personal data in a structured, machine-readable format.
          </li>
          <li>
            <strong>Right to lodge a complaint:</strong> You have the right to lodge a complaint
            with your national data protection authority. In the EU, contact your country's DPA. In
            Germany, the supervisory authority is the{' '}
            <em>Bundesbeauftragter für den Datenschutz und die Informationsfreiheit</em> (
            <a
              href="https://www.bfdi.bund.de"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: '#0e7490' }}
            >
              bfdi.bund.de
            </a>
            ).
          </li>
        </ul>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 6 }}>
          <strong>Legal Basis for Processing (GDPR Article 6):</strong>
        </p>
        <ul
          style={{
            fontSize: 13,
            color: 'var(--rt-c)',
            lineHeight: 1.7,
            marginBottom: 10,
            paddingLeft: 20,
          }}
        >
          <li style={{ marginBottom: 6 }}>
            <strong>Learning progress and account data:</strong> processed on the basis of contract
            performance (Article 6(1)(b)).
          </li>
          <li style={{ marginBottom: 6 }}>
            <strong>Analytics (PostHog, Plausible):</strong> processed on the basis of your consent
            (Article 6(1)(a)). You may withdraw consent at any time via the cookie settings.
          </li>
          <li>
            <strong>Error monitoring (Sentry):</strong> processed on the basis of legitimate
            interests in maintaining app stability and security (Article 6(1)(f)).
          </li>
        </ul>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7 }}>
          <strong>Children and family accounts:</strong> The app is designed for use by families
          under parental supervision. The family leaderboard is a parent-managed feature — a parent
          or guardian must create the group and is responsible for enrolling minor members. We do
          not knowingly collect data from children under 13 outside of a parent-managed family
          group. If you believe a child under 13 has registered independently without parental
          consent, contact us at{' '}
          <a href="mailto:privacy@nasahrvatska.com" style={{ color: '#0e7490' }}>
            privacy@nasahrvatska.com
          </a>{' '}
          and we will promptly delete the account.
        </p>
      </div>

      <div className="c" style={{ marginBottom: 16 }}>
        <h3 style={{ fontSize: 15, fontWeight: 800, color: 'var(--heading)', marginBottom: 8 }}>
          AI-Powered Features
        </h3>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          Naša Hrvatska uses Claude AI (Anthropic) for conversation practice, grammar checking, and
          writing evaluation. Text you submit to AI features is sent to Anthropic's API. We do not
          store your conversation data beyond the current session.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          Voice audio is generated by ElevenLabs text-to-speech technology. Text sent for audio
          generation is processed by ElevenLabs.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7 }}>
          By using AI-powered features, you acknowledge that input text is transmitted to
          third-party AI service providers (Anthropic, ElevenLabs) subject to their respective
          privacy policies. Anthropic's policy:{' '}
          <a
            href="https://www.anthropic.com/privacy"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: '#0e7490' }}
          >
            anthropic.com/privacy
          </a>
          . ElevenLabs' policy:{' '}
          <a
            href="https://elevenlabs.io/privacy"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: '#0e7490' }}
          >
            elevenlabs.io/privacy
          </a>
          .
        </p>
      </div>

      <div className="c" style={{ marginBottom: 24 }}>
        <h3 style={{ fontSize: 15, fontWeight: 800, color: 'var(--heading)', marginBottom: 8 }}>
          Terms of Use
        </h3>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>Free to use:</strong> Naša Hrvatska is provided free of charge, with no ads. You
          may use the app for personal, non-commercial language learning.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>Account responsibility:</strong> You are responsible for keeping your password
          secure. Do not share your account. We reserve the right to suspend accounts engaged in
          abuse.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>Family group responsibility:</strong> The adult who creates a family group is
          responsible for managing membership and ensuring that any minor members have parental or
          guardian consent to participate. The group creator agrees to our privacy policy on behalf
          of all minor members they enroll.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>Content:</strong> All Croatian language content, exercises, and cultural material
          in this app is owned by Naša Hrvatska. You may not reproduce or redistribute it without
          permission.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7, marginBottom: 10 }}>
          <strong>Disclaimer:</strong> This app is an educational tool. While we strive for
          accuracy, we make no guarantee that all language content is error-free. For professional
          or medical translation, consult a qualified translator.
        </p>

        <p style={{ fontSize: 13, color: 'var(--rt-c)', lineHeight: 1.7 }}>
          <strong>Changes:</strong> We may update these terms. Continued use of the app after
          changes constitutes acceptance of the updated terms.
        </p>
      </div>

      <div style={{ textAlign: 'center', fontSize: 12, color: 'var(--subtext)', marginBottom: 24 }}>
        Questions? Email{' '}
        <a href="mailto:privacy@nasahrvatska.com" style={{ color: '#0e7490' }}>
          privacy@nasahrvatska.com
        </a>
      </div>

      <button className="b bg" style={{ width: '100%' }} onClick={goBack}>
        Back
      </button>
    </div>
  );
}
