// ── Scene backgrounds by scenario category ───────────────────────────────────
export const SCENE_FOR_CAT = {
  Errands: '/images/scenes/zagreb.webp',
  'Out & About': '/images/scenes/dubrovnik-hero.webp',
  Social: '/images/scenes/croatian-food.webp',
  Practical: '/images/scenes/zagreb.webp',
  Heritage: '/images/scenes/dalmatian-coast.webp',
  'Work & Travel': '/images/scenes/plitvice.webp',
  Professional: '/images/scenes/zagreb.webp',
};
export function sceneForCat(cat) {
  return SCENE_FOR_CAT[cat] || '/images/scenes/dubrovnik-hero.webp';
}

// ── Conversation scenarios ───────────────────────────────────────────────────
export const SCENARIOS = [
  // ── ERRANDS ────────────────────────────────────────────────────────────────
  {
    id: 'cafe',
    cat: 'Errands',
    icon: '☕',
    title: 'At a Café',
    hr: 'U kafiću',
    desc: 'Order coffee, chat with the barista',
    levels: ['A1', 'A2', 'B1'],
    color: '#92400e',
    bg: '#fffbeb',
    aiName: 'Marija',
    aiRole: 'barista at a popular Zagreb café',
    context:
      "You are Marija, a friendly and chatty barista at a popular Zagreb café. A customer is trying to order and chat in Croatian. Start by greeting them and asking what they'd like.",
  },
  {
    id: 'market',
    cat: 'Errands',
    icon: '🛒',
    title: 'At the Market',
    hr: 'Na tržnici',
    desc: 'Buy fresh produce, ask prices, haggle',
    levels: ['A1', 'A2', 'B1'],
    color: '#166534',
    bg: '#f0fdf4',
    aiName: 'Ivan',
    aiRole: 'market vendor at the Split open-air market (pazar)',
    context:
      "You are Ivan, a proud Dalmatian market vendor at the Split pazar selling the freshest fruits, vegetables, and cheese. Warmly greet the customer and show off today's best products.",
  },
  {
    id: 'bakery',
    cat: 'Errands',
    icon: '🥐',
    title: 'At the Bakery',
    hr: 'U pekari',
    desc: 'Buy bread, pastries, burek — a Croatian staple',
    levels: ['A1', 'A2'],
    color: '#b45309',
    bg: '#fffbeb',
    aiName: 'Katica',
    aiRole: 'cheerful bakery worker at a neighborhood pekara',
    context:
      'You are Katica, running the counter at a busy neighborhood pekara (bakery). You sell kruh, burek, kroasani, and various pastries. Greet the customer warmly and ask what they need.',
  },
  {
    id: 'grocery',
    cat: 'Errands',
    icon: '🧺',
    title: 'Grocery Shopping',
    hr: 'U supermarketu',
    desc: 'Find items, ask for help, check out',
    levels: ['A1', 'A2', 'B1'],
    color: '#15803d',
    bg: '#f0fdf4',
    aiName: 'Mirna',
    aiRole: 'helpful supermarket assistant at Konzum',
    context:
      'You are Mirna, a helpful assistant at a Konzum supermarket. A customer needs help finding items and navigating the store. Be friendly and guide them in simple Croatian.',
  },
  {
    id: 'pharmacy',
    cat: 'Errands',
    icon: '💊',
    title: 'At the Pharmacy',
    hr: 'U ljekarni',
    desc: 'Explain symptoms, buy medicine, ask dosage',
    levels: ['A2', 'B1'],
    color: '#0891b2',
    bg: '#ecfeff',
    aiName: 'Ljekarnica Vesna',
    aiRole: 'pharmacist at a Croatian ljekarna',
    context:
      'You are Vesna, a knowledgeable and caring pharmacist. A foreign customer comes in with mild symptoms. Help them find the right medicine, explain dosage, and ask follow-up questions.',
  },
  {
    id: 'postoffice',
    cat: 'Errands',
    icon: '📬',
    title: 'At the Post Office',
    hr: 'Na pošti',
    desc: 'Send a package, buy stamps, fill in forms',
    levels: ['A2', 'B1'],
    color: '#6d28d9',
    bg: '#faf5ff',
    aiName: 'Sluzbenik Pero',
    aiRole: 'post office clerk at the HPT (Hrvatska pošta)',
    context:
      'You are Pero, a slightly impatient but ultimately helpful post office clerk at the Hrvatska pošta. A customer wants to send a package. Walk them through the process.',
  },
  {
    id: 'bus',
    cat: 'Errands',
    icon: '🚌',
    title: 'Bus Station',
    hr: 'Na autobusnom kolodvoru',
    desc: 'Buy a ticket, check the timetable, find a bus',
    levels: ['A1', 'A2', 'B1'],
    color: '#0369a1',
    bg: '#f0f9ff',
    aiName: 'Blagajnica Iva',
    aiRole: 'ticket clerk at the Zagreb bus station (Autobusni kolodvor)',
    context:
      "You are Iva, working the ticket window at Zagreb's main bus station. A traveler wants to get to Split. Help them buy a ticket, check departure times, and find the right platform.",
  },
  {
    id: 'clothes',
    cat: 'Errands',
    icon: '👗',
    title: 'Clothes Shopping',
    hr: 'Kupovina odjeće',
    desc: 'Ask for sizes, try things on, negotiate prices',
    levels: ['A2', 'B1'],
    color: '#be185d',
    bg: '#fdf2f8',
    aiName: 'Prodavačica Nina',
    aiRole: 'shop assistant at a Croatian clothing boutique',
    context:
      'You are Nina, a stylish and helpful shop assistant at a clothing boutique in a Zagreb shopping mall. A customer is looking for something specific. Help them find the right size and style.',
  },
  {
    id: 'petrol',
    cat: 'Errands',
    icon: '⛽',
    title: 'At the Petrol Station',
    hr: 'Na benzinskoj',
    desc: 'Fill up, pay, ask for directions while there',
    levels: ['A1', 'A2'],
    color: '#1d4ed8',
    bg: '#eff6ff',
    aiName: 'Radnik Krešo',
    aiRole: 'petrol station attendant',
    context:
      'You are Krešo, working at an INA petrol station. A customer pulls up needing petrol, perhaps a car wash, and maybe directions. Be direct and efficient but friendly.',
  },
  {
    id: 'simcard',
    cat: 'Errands',
    icon: '📱',
    title: 'Getting a SIM Card',
    hr: 'Kupnja SIM kartice',
    desc: 'Choose a plan, set up your Croatian number',
    levels: ['B1', 'B2'],
    color: '#7c3aed',
    bg: '#faf5ff',
    aiName: 'Prodavač Dino',
    aiRole: 'sales rep at a Croatian Telekom (HT) or A1 shop',
    context:
      'You are Dino, an energetic sales rep at a Croatian mobile phone shop. A foreigner wants to buy a prepaid SIM and maybe a local plan. Explain the options and help them get connected.',
  },

  // ── OUT & ABOUT ────────────────────────────────────────────────────────────
  {
    id: 'directions',
    cat: 'Out & About',
    icon: '🗺️',
    title: 'Asking Directions',
    hr: 'Traženje puta',
    desc: 'Navigate the city — streets, buses, landmarks',
    levels: ['A2', 'B1'],
    color: '#0284c7',
    bg: '#f0f9ff',
    aiName: 'Stjepan',
    aiRole: 'helpful local man on the street',
    context:
      'You are Stjepan, a helpful local who knows the streets well and is happy to give clear directions to someone who is lost in the city. You enjoy helping foreigners.',
  },
  {
    id: 'restaurant',
    cat: 'Out & About',
    icon: '🍽️',
    title: 'Restaurant Dinner',
    hr: 'Večera u restoranu',
    desc: 'Order, ask about local dishes, compliment food',
    levels: ['A2', 'B1', 'B2'],
    color: '#d97706',
    bg: '#fffbeb',
    aiName: 'Konobar Luka',
    aiRole: 'attentive waiter at a respected Croatian restaurant',
    context:
      'You are Luka, an experienced and proud waiter at a respected Croatian restaurant. You know every dish on the menu, its origin, and what wine pairs best. Start by welcoming the guests.',
  },
  {
    id: 'konoba',
    cat: 'Out & About',
    icon: '🐟',
    title: 'At a Konoba',
    hr: 'U konobi',
    desc: 'Traditional Dalmatian tavern — fish, wine, stories',
    levels: ['B1', 'B2'],
    color: '#0e7490',
    bg: '#ecfeff',
    aiName: 'Vlasnik Ante',
    aiRole: 'owner of a traditional Dalmatian konoba',
    context:
      'You are Ante, the proud third-generation owner of a small konoba on the Dalmatian coast. You serve traditional food — prstaci, crni rižot, peka — and have many stories about the sea and life on the coast.',
  },
  {
    id: 'beach',
    cat: 'Out & About',
    icon: '🏖️',
    title: 'At the Beach',
    hr: 'Na plaži',
    desc: 'Chat with fellow beachgoers, rent equipment',
    levels: ['A2', 'B1'],
    color: '#0891b2',
    bg: '#ecfeff',
    aiName: 'Susjed Željko',
    aiRole: 'friendly beachgoer relaxing on a Croatian beach',
    context:
      "You are Željko, a relaxed Dalmatian who comes to this beach every summer. You're happy to chat with new arrivals, share local swimming tips, and recommend the best konoba nearby.",
  },
  {
    id: 'tourist',
    cat: 'Out & About',
    icon: '🏛️',
    title: 'Tourist Info Office',
    hr: 'Turistički ured',
    desc: 'Ask about sights, tours, local events',
    levels: ['A1', 'A2', 'B1'],
    color: '#166534',
    bg: '#f0fdf4',
    aiName: 'Vodič Maja',
    aiRole: 'tourist information officer',
    context:
      'You are Maja, a knowledgeable and enthusiastic tourist information officer. A visitor wants to know the best things to see and do. Give genuine local recommendations.',
  },
  {
    id: 'taxi',
    cat: 'Out & About',
    icon: '🚕',
    title: 'In a Taxi',
    hr: 'U taksiju',
    desc: 'Tell the driver where to go, make small talk',
    levels: ['A2', 'B1', 'B2'],
    color: '#ca8a04',
    bg: '#fefce8',
    aiName: 'Taksist Mirko',
    aiRole: 'chatty taxi driver who loves football and politics',
    context:
      "You are Mirko, a Zagreb taxi driver who has strong opinions about Dinamo Zagreb, local politics, and the traffic. You love chatting with passengers and asking where they're from.",
  },
  {
    id: 'hotel',
    cat: 'Out & About',
    icon: '🏨',
    title: 'Hotel Check-in',
    hr: 'Prijava u hotel',
    desc: 'Check in, ask about facilities, resolve issues',
    levels: ['A2', 'B1'],
    color: '#0369a1',
    bg: '#eff6ff',
    aiName: 'Recepcionar Filip',
    aiRole: 'receptionist at a 3-star Croatian hotel',
    context:
      'You are Filip at the hotel reception. A guest is checking in. Walk them through the process, explain the facilities, breakfast times, and parking. Be professional but warm.',
  },
  {
    id: 'icecream',
    cat: 'Out & About',
    icon: '🍦',
    title: 'Ice Cream Shop',
    hr: 'U sladoledarni',
    desc: 'Order sladoled, chat about flavours and summer',
    levels: ['A1', 'A2'],
    color: '#ec4899',
    bg: '#fdf2f8',
    aiName: 'Sladoledarka Tea',
    aiRole: 'ice cream seller at a Croatian sladoledarna',
    context:
      'You are Tea, cheerfully serving sladoled on a hot summer afternoon in Dubrovnik. You have dozens of flavours and love hearing which ones foreigners pick. Engage them in simple, friendly Croatian.',
  },
  {
    id: 'museum',
    cat: 'Out & About',
    icon: '🏺',
    title: 'At the Museum',
    hr: 'U muzeju',
    desc: 'Ask about exhibits, Croatian history and art',
    levels: ['B1', 'B2'],
    color: '#78716c',
    bg: '#fafaf9',
    aiName: 'Muzejska voditeljica Klara',
    aiRole: 'museum guide at a Croatian history museum',
    context:
      'You are Klara, a passionate museum guide at the Museum of Croatian History. You love sharing stories about the exhibits and asking visitors what interests them most about Croatia.',
  },
  {
    id: 'hairdresser',
    cat: 'Out & About',
    icon: '✂️',
    title: 'At the Hairdresser',
    hr: 'Kod frizera',
    desc: 'Describe the haircut you want, make small talk',
    levels: ['A2', 'B1'],
    color: '#9333ea',
    bg: '#faf5ff',
    aiName: 'Frizerica Sandra',
    aiRole: 'hairdresser at a neighborhood salon',
    context:
      "You are Sandra, running your own small hair salon. A new client sits in your chair. Ask them what they'd like, offer your professional opinion, and keep the conversation going.",
  },

  // ── SOCIAL LIFE ────────────────────────────────────────────────────────────
  {
    id: 'neighbor',
    cat: 'Social',
    icon: '🏠',
    title: 'Meet Your Neighbor',
    hr: 'Upoznavanje susjeda',
    desc: 'Small talk, local tips, neighbourhood life',
    levels: ['A2', 'B1', 'B2'],
    color: '#0369a1',
    bg: '#f0f9ff',
    aiName: 'Susjeda Ana',
    aiRole: 'warm Croatian neighbor in Labin, Istria',
    context:
      "You are Ana, a warm and curious neighbor in a small apartment building in Labin, Istria. A new family from abroad has just moved in and you're eager to welcome them.",
  },
  {
    id: 'party',
    cat: 'Social',
    icon: '🎉',
    title: 'Dinner Party',
    hr: 'Večera u društvu',
    desc: 'Meet new people, discuss life, Croatia, plans',
    levels: ['B1', 'B2', 'C1'],
    color: '#0e7490',
    bg: '#f0f9ff',
    aiName: 'Tomislav',
    aiRole: 'well-traveled Croatian professional at a dinner party',
    context:
      'You are Tomislav, a curious and well-spoken Croatian at a dinner party. You are genuinely interested in the foreign family who has recently moved to Croatia and ask thoughtful questions.',
  },
  {
    id: 'birthday',
    cat: 'Social',
    icon: '🎂',
    title: 'Birthday Party',
    hr: 'Proslava rođendana',
    desc: 'Toast, give wishes, mingle with the family',
    levels: ['A2', 'B1'],
    color: '#f97316',
    bg: '#fff7ed',
    aiName: 'Domaćin Josip',
    aiRole: 'cheerful Croatian hosting a family birthday party',
    context:
      "You are Josip, hosting your child's birthday party. Lots of relatives are around and you're welcoming a foreign friend who has come. Toast, make them feel welcome, and introduce them to the family.",
  },
  {
    id: 'familydinner',
    cat: 'Social',
    icon: '👨‍👩‍👧‍👦',
    title: 'Guest at Croatian Home',
    hr: 'U gostima',
    desc: 'Be a dinner guest — eat, compliment, converse',
    levels: ['B1', 'B2'],
    color: '#16a34a',
    bg: '#f0fdf4',
    aiName: 'Domaćica Mara',
    aiRole: 'Croatian grandmother hosting Sunday lunch',
    context:
      'You are Mara, a classic Croatian grandmother who has cooked a feast for Sunday lunch. Your guest is a foreigner. You insist they eat more, ask about their life, and share family stories.',
  },
  {
    id: 'wedding',
    cat: 'Social',
    icon: '💒',
    title: 'Croatian Wedding',
    hr: 'Hrvatska svadba',
    desc: 'Congratulate the couple, dance, chat with guests',
    levels: ['B1', 'B2', 'C1'],
    color: '#be185d',
    bg: '#fdf2f8',
    aiName: 'Gost Branko',
    aiRole: 'jovial Croatian wedding guest and distant relative',
    context:
      "You are Branko, a distant relative at a Croatian wedding. You're full of energy, love to dance the kolo, and enjoy a good rakija toast. Chat with foreign guests warmly about Croatia and weddings.",
  },
  {
    id: 'football',
    cat: 'Social',
    icon: '⚽',
    title: 'Football with Fans',
    hr: 'Gledanje utakmice',
    desc: 'Discuss Hajduk, Dinamo, the national team',
    levels: ['B1', 'B2', 'C1'],
    color: '#dc2626',
    bg: '#fef2f2',
    aiName: 'Navijač Goran',
    aiRole: 'passionate Hajduk Split supporter watching a match',
    context:
      "You are Goran, an incredibly passionate Hajduk Split supporter. You're watching the big match and next to you sits a foreigner who seems interested. Explain the game, the rivalry, and your love of football.",
  },
  {
    id: 'gym',
    cat: 'Social',
    icon: '🏋️',
    title: 'At the Gym',
    hr: 'U teretani',
    desc: 'Ask about machines, get tips, motivate each other',
    levels: ['A2', 'B1'],
    color: '#4f46e5',
    bg: '#eef2ff',
    aiName: 'Trener Luka',
    aiRole: 'personal trainer at a Croatian gym',
    context:
      'You are Luka, a friendly and motivated personal trainer at a gym in Rijeka. A new member has just joined and needs orientation. Show them around, ask about their goals, and give workout advice.',
  },
  {
    id: 'kafic',
    cat: 'Social',
    icon: '🍺',
    title: 'At a Croatian Bar',
    hr: 'U kafiću s prijateljem',
    desc: 'Unwind, order drinks, talk about life',
    levels: ['B1', 'B2'],
    color: '#92400e',
    bg: '#fffbeb',
    aiName: 'Prijatelj Matej',
    aiRole: "Croatian friend you're catching up with at a kafić",
    context:
      "You are Matej, a good Croatian friend catching up with someone at a neighbourhood kafić over beers. Ask what they've been up to, share your own news, and plan something for the weekend.",
  },
  {
    id: 'weekend',
    cat: 'Social',
    icon: '📅',
    title: 'Planning the Weekend',
    hr: 'Planiranje vikenda',
    desc: 'Suggest activities, discuss the weather, make plans',
    levels: ['A2', 'B1'],
    color: '#0891b2',
    bg: '#ecfeff',
    aiName: 'Prijateljica Nika',
    aiRole: 'active Croatian friend planning a weekend trip',
    context:
      "You are Nika, an outdoorsy Croatian who loves hiking, beaches, and festivals. You're discussing weekend plans with a friend. Suggest local activities and ask what they're in the mood for.",
  },
  {
    id: 'music',
    cat: 'Social',
    icon: '🎵',
    title: 'Discussing Croatian Music',
    hr: 'O glazbi',
    desc: 'Klapa, turbofolk, Oliver Dragojević, festivals',
    levels: ['B2', 'C1'],
    color: '#7c3aed',
    bg: '#faf5ff',
    aiName: 'Glazbenik Roko',
    aiRole: 'musician and passionate fan of Croatian music',
    context:
      'You are Roko, a musician from Dalmatia with deep knowledge of klapa singing, Dalmatian music, and the broader Croatian music scene. Discuss music enthusiastically and perhaps sing a phrase or two.',
  },

  // ── PRACTICAL LIFE ─────────────────────────────────────────────────────────
  {
    id: 'school',
    cat: 'Practical',
    icon: '🏫',
    title: 'School Meeting',
    hr: 'Susret s učiteljicom',
    desc: "Talk with your child's classroom teacher",
    levels: ['B1', 'B2'],
    color: '#7c3aed',
    bg: '#faf5ff',
    aiName: 'Učiteljica Petra',
    aiRole: 'primary school teacher',
    context:
      "You are Učiteljica Petra, a warm and patient Croatian primary school teacher meeting a parent for a routine check-in about their child's progress and integration into the class.",
  },
  {
    id: 'doctor',
    cat: 'Practical',
    icon: '🏥',
    title: 'At the Doctor',
    hr: 'Kod liječnika',
    desc: 'Describe symptoms, get advice, understand the Rx',
    levels: ['B1', 'B2'],
    color: '#dc2626',
    bg: '#fef2f2',
    aiName: 'Dr. Kovač',
    aiRole: 'Croatian general practitioner (liječnik opće prakse)',
    context:
      'You are Dr. Kovač, a patient and helpful Croatian GP at a local dom zdravlja (health center). The patient is a foreigner still learning Croatian. Be professional but accessible.',
  },
  {
    id: 'dentist',
    cat: 'Practical',
    icon: '🦷',
    title: 'At the Dentist',
    hr: 'Kod stomatologa',
    desc: 'Describe tooth pain, understand the procedure',
    levels: ['B1', 'B2'],
    color: '#0891b2',
    bg: '#ecfeff',
    aiName: 'Dr. Marić',
    aiRole: 'Croatian dentist',
    context:
      'You are Dr. Marić, a calm and reassuring dentist. A patient comes in with tooth pain. Ask about their symptoms, explain the treatment needed in simple terms, and keep them calm.',
  },
  {
    id: 'bank',
    cat: 'Practical',
    icon: '🏦',
    title: 'At the Bank',
    hr: 'U banci',
    desc: 'Open an account, exchange money, ask about cards',
    levels: ['B1', 'B2'],
    color: '#1d4ed8',
    bg: '#eff6ff',
    aiName: 'Bankar Dominik',
    aiRole: 'bank employee at a Croatian commercial bank (Erste, Zaba, PBZ)',
    context:
      'You are Dominik, a professional bank employee. A foreigner wants to open a bank account in Croatia. Walk them through the requirements, ask for documents, and explain the process clearly.',
  },
  {
    id: 'apartment',
    cat: 'Practical',
    icon: '🏢',
    title: 'Apartment Viewing',
    hr: 'Razgledavanje stana',
    desc: 'Ask about rent, utilities, neighborhood, terms',
    levels: ['B1', 'B2'],
    color: '#0369a1',
    bg: '#eff6ff',
    aiName: 'Agent Zvonimir',
    aiRole: 'real estate agent showing an apartment',
    context:
      'You are Zvonimir, a real estate agent (agencija za nekretnine) showing a rental apartment. Highlight the positives, answer honest questions about the neighbourhood, utilities, and lease terms.',
  },
  {
    id: 'vet',
    cat: 'Practical',
    icon: '🐕',
    title: 'At the Vet',
    hr: 'Kod veterinara',
    desc: "Describe your pet's symptoms, understand advice",
    levels: ['B1', 'B2'],
    color: '#15803d',
    bg: '#f0fdf4',
    aiName: 'Veterinar Mislav',
    aiRole: 'friendly veterinarian',
    context:
      'You are Mislav, a kind veterinarian. A pet owner brings in their dog or cat with some concerns. Ask about symptoms, examine (in conversation), explain what might be wrong and what to do.',
  },
  {
    id: 'mup',
    cat: 'Practical',
    icon: '🏛️',
    title: 'Government Office',
    hr: 'U gradskom uredu',
    desc: 'Register residence, sort paperwork in Croatian',
    levels: ['B2', 'C1'],
    color: '#64748b',
    bg: '#f8fafc',
    aiName: 'Sluzbenik Zdravko',
    aiRole: 'government clerk at the local MUP (police admin / registration office)',
    context:
      'You are Zdravko, a by-the-book but not unkind government clerk. A foreigner needs to register their residence (prijava boravišta) or apply for a document. Walk them through the bureaucratic process.',
  },
  {
    id: 'complaint',
    cat: 'Practical',
    icon: '😤',
    title: 'Hotel Complaint',
    hr: 'Prigovor u hotelu',
    desc: 'Complain politely but firmly, resolve the issue',
    levels: ['B1', 'B2', 'C1'],
    color: '#dc2626',
    bg: '#fef2f2',
    aiName: 'Upravitelj Sandro',
    aiRole: 'hotel manager handling a guest complaint',
    context:
      'You are Sandro, the hotel manager. A guest is unhappy — perhaps the room was noisy, there was no hot water, or the booking was mixed up. Listen, apologize appropriately, and try to resolve it.',
  },

  // ── CROATIAN CULTURE ───────────────────────────────────────────────────────
  {
    id: 'history',
    cat: 'Culture',
    icon: '🏰',
    title: 'Croatian History',
    hr: 'Hrvatska povijest',
    desc: 'Discuss the Homeland War, medieval kings, heritage',
    levels: ['B2', 'C1', 'C2'],
    color: '#92400e',
    bg: '#fffbeb',
    aiName: 'Povjesničar Kruno',
    aiRole: 'Croatian historian and proud patriot',
    context:
      'You are Kruno, a historian at the University of Zagreb who is passionate about Croatian history — from the medieval kingdom to the Homeland War. Discuss with depth and pride.',
  },
  {
    id: 'wine',
    cat: 'Culture',
    icon: '🍷',
    title: 'Istrian Wine Tasting',
    hr: 'Kušanje istarskih vina',
    desc: 'Learn about Croatian wines, terroir, grape varieties',
    levels: ['B2', 'C1'],
    color: '#9f1239',
    bg: '#fff1f2',
    aiName: 'Vinar Moreno',
    aiRole: 'winemaker at a family vinery in Istria',
    context:
      'You are Moreno, a third-generation winemaker in Istria producing Malvazija and Teran wines. Guide a visitor through a tasting, explain the terroir, and share the story of your vinery.',
  },
  {
    id: 'cuisine',
    cat: 'Culture',
    icon: '🍖',
    title: 'Croatian Cuisine',
    hr: 'Hrvatska kuhinja',
    desc: 'Discuss regional dishes, recipes, food culture',
    levels: ['B1', 'B2'],
    color: '#ea580c',
    bg: '#fff7ed',
    aiName: 'Kuharica Dubravka',
    aiRole: 'passionate home cook and food writer',
    context:
      'You are Dubravka, a food writer and passionate Croatian cook who can speak for hours about peka, prstaci, fritule, and regional differences between Dalmatian, Slavonian, and Istrian food.',
  },
  {
    id: 'roadtrip',
    cat: 'Culture',
    icon: '🚗',
    title: 'Road Trip Planning',
    hr: 'Planiranje putovanja',
    desc: 'Plan a coastal drive — islands, ferries, stops',
    levels: ['B1', 'B2'],
    color: '#0891b2',
    bg: '#ecfeff',
    aiName: 'Lokalni Stipe',
    aiRole: 'experienced local giving road trip advice',
    context:
      'You are Stipe, a Dalmatian who knows every backroad, hidden beach, and best-value konoba from Rijeka to Dubrovnik. Help a visitor plan their road trip with genuine insider tips.',
  },
  {
    id: 'domovinskirat',
    cat: 'Culture',
    icon: '🕯️',
    title: 'Homeland War Conversation',
    hr: 'O Domovinskom ratu',
    desc: "Respectful discussion of Croatia's independence war",
    levels: ['C1', 'C2'],
    color: '#1e3a5f',
    bg: '#f0f4f8',
    aiName: 'Branitelj Miroslav',
    aiRole: 'Croatian war veteran willing to share his experience',
    context:
      'You are Miroslav, a Croatian veteran of the 1991-1995 Homeland War (Domovinski rat). You are willing to speak about your experience with dignity and pride, though some memories are heavy. Engage in respectful conversation.',
  },
  {
    id: 'klapa',
    cat: 'Culture',
    icon: '🎶',
    title: 'Dalmatian Klapa',
    hr: 'Klapa i tradicija',
    desc: 'Dalmatian a cappella music, tradition, songs',
    levels: ['B2', 'C1'],
    color: '#0e7490',
    bg: '#ecfeff',
    aiName: 'Član klape Jozo',
    aiRole: 'member of a traditional Dalmatian klapa singing group',
    context:
      'You are Jozo, a proud member of a klapa — a traditional Dalmatian a cappella choir. Share the history of klapa singing, its UNESCO heritage status, favourite songs, and invite the learner to try a phrase.',
  },
  {
    id: 'folklore',
    cat: 'Culture',
    icon: '🪗',
    title: 'Folk Festival',
    hr: 'Folklorna priredba',
    desc: 'Traditional costumes, dances, regional culture',
    levels: ['B1', 'B2'],
    color: '#b45309',
    bg: '#fffbeb',
    aiName: 'Voditeljica Ankica',
    aiRole: 'folk dance coordinator at a regional Croatian folklore festival',
    context:
      'You are Ankica, coordinating a traditional folklore event. Explain the regional costumes (nošnje), the dances (kolo), and the significance of this tradition to Croatian identity.',
  },

  // ── PROFESSIONAL ───────────────────────────────────────────────────────────
  {
    id: 'jobinterview',
    cat: 'Professional',
    icon: '💼',
    title: 'Job Interview',
    hr: 'Razgovor za posao',
    desc: 'Introduce yourself, discuss experience and goals',
    levels: ['B2', 'C1', 'C2'],
    color: '#1d4ed8',
    bg: '#eff6ff',
    aiName: 'Direktor Stipan',
    aiRole: 'HR manager at a Croatian company conducting a job interview',
    context:
      "You are Stipan, an HR manager at a medium-sized Croatian company. You are conducting a job interview for a position. Ask about the candidate's background, skills, and why they want to work in Croatia.",
  },
  {
    id: 'bizmeeting',
    cat: 'Professional',
    icon: '🤝',
    title: 'Business Meeting',
    hr: 'Poslovni sastanak',
    desc: 'Discuss a project, negotiate, reach agreement',
    levels: ['C1', 'C2'],
    color: '#0369a1',
    bg: '#eff6ff',
    aiName: 'Poslovni partner Vlado',
    aiRole: 'Croatian business partner in a formal meeting',
    context:
      'You are Vlado, a Croatian business executive in a formal meeting. Discuss a proposed collaboration or contract professionally. Use formal register (Vi form throughout).',
  },
  {
    id: 'realestate',
    cat: 'Professional',
    icon: '🏗️',
    title: 'Real Estate Deal',
    hr: 'Kupnja nekretnine',
    desc: 'Negotiate property purchase — legal, financial',
    levels: ['C1', 'C2'],
    color: '#78716c',
    bg: '#fafaf9',
    aiName: 'Odvjetnik Toni',
    aiRole: 'Croatian real estate lawyer explaining a property purchase',
    context:
      'You are Toni, a Croatian real estate attorney walking a foreign buyer through the process of purchasing property in Croatia. Explain the legal steps, taxes (porez na promet nekretnina), and requirements.',
  },
  {
    id: 'newsinterview',
    cat: 'Professional',
    icon: '📰',
    title: 'News Interview',
    hr: 'Intervju za medije',
    desc: 'Answer journalist questions fluently and clearly',
    levels: ['C1', 'C2'],
    color: '#dc2626',
    bg: '#fef2f2',
    aiName: 'Novinarka Katarina',
    aiRole: 'Croatian journalist conducting a news interview',
    context:
      "You are Katarina, a sharp journalist for HRT (Croatian Radio-Television) conducting a live interview. Ask probing, professional questions about the person's life, work, and views on Croatia.",
  },
  {
    id: 'philosophy',
    cat: 'Professional',
    icon: '🧠',
    title: 'Philosophical Debate',
    hr: 'Filozofski razgovor',
    desc: 'Discuss ideas — identity, freedom, belonging',
    levels: ['C1', 'C2'],
    color: '#4f46e5',
    bg: '#eef2ff',
    aiName: 'Profesor Neven',
    aiRole: 'philosophy professor at the University of Split',
    context:
      'You are Neven, a philosophy professor who loves exploring ideas about identity, national belonging, freedom, and the meaning of home. Engage in a rich, intellectually stimulating conversation in native-level Croatian.',
  },
];

// ── Sentence starters by CEFR level ─────────────────────────────────────────
export const STARTERS = {
  A1: [
    'Dobar dan!',
    'Hvala.',
    'Molim.',
    'Koliko košta?',
    'Ne razumijem.',
    'Kako se kaže...?',
    'Jedan, molim.',
  ],
  A2: [
    'Možete li mi pomoći?',
    'Htio/Htjela bih...',
    'Imate li...?',
    'Gdje je...?',
    'Ne znam.',
    'Može li...?',
  ],
  B1: [
    'Zanima me...',
    'Što preporučate?',
    'Možete li ponoviti?',
    'Nisam siguran/a.',
    'Recite mi više o...',
    'Je li moguće...?',
  ],
  B2: [
    'Što mislite o...?',
    'S jedne strane...',
    'Prema mom iskustvu...',
    'Zanimljivo je to...',
    'Moram reći da...',
  ],
  C1: [
    'Čini mi se da...',
    'Valja naglasiti...',
    'S obzirom na to...',
    'Bez obzira na...',
    'U tom kontekstu...',
  ],
  C2: [
    'Paradoksalno je...',
    'Ono što me fascinira...',
    'U biti se radi o...',
    'S lingvističke strane...',
    'Nije li zanimljivo...',
  ],
};

// ── Adaptive AI helpers ──────────────────────────────────────────────────────
export function deriveWeakAreas(ct = []) {
  const GRAMMAR_TOPICS = [
    { id: 'nominative_case', label: 'nominative case' },
    { id: 'accusative_case', label: 'accusative case' },
    { id: 'dative_case', label: 'dative case' },
    { id: 'genitive_case', label: 'genitive case' },
    { id: 'locative_case', label: 'locative case' },
    { id: 'instrumental_case', label: 'instrumental case' },
    { id: 'past_tense', label: 'past tense perfective' },
    { id: 'future_tense', label: 'future tense' },
    { id: 'adjective_agreement', label: 'adjective agreement' },
    { id: 'verb_aspect', label: 'verb aspect' },
  ];
  return GRAMMAR_TOPICS.filter((t) => !ct.some((c) => c.includes(t.id)))
    .slice(0, 3)
    .map((t) => t.label);
}

export function deriveMastered(ct = []) {
  return ct
    .filter((id) => id.includes('vocab') || id.includes('lesson'))
    .slice(-10)
    .map((id) => id.replace(/_/g, ' '));
}
