import React from 'react';

// ── Portrait mapping — scenario ID → portrait filename ──────────────────────
// Images live at /images/portraits/*.webp (generated by scripts/generate-portraits.mjs)
export const PORTRAIT_MAP = {
  cafe: 'barista',
  market: 'vendor',
  bakery: 'mature-woman',
  grocery: 'mature-woman',
  pharmacy: 'mature-woman',
  postoffice: 'mature-man',
  bus: 'young-woman',
  clothes: 'young-woman',
  petrol: 'mature-man',
  simcard: 'young-man',
  directions: 'mature-man',
  restaurant: 'young-man',
  konoba: 'fisherman',
  beach: 'mature-man',
  tourist: 'young-woman',
  taxi: 'young-man',
  hotel: 'young-man',
  icecream: 'young-woman',
  museum: 'young-woman',
  hairdresser: 'young-woman',
  neighbor: 'mature-woman',
  party: 'young-man',
  birthday: 'mature-man',
  familydinner: 'grandmother',
  wedding: 'mature-man',
  football: 'young-man',
  gym: 'young-man',
  kafic: 'young-man',
  weekend: 'young-woman',
};

export function portraitSrc(scenarioId: string): string {
  const key = (PORTRAIT_MAP as Record<string, string>)[scenarioId] ?? 'young-woman';
  return `/images/portraits/${key}.webp`;
}

// ── Speaking avatar — portrait photo with live speaking ring ────────────────
// (The D-ID lip-sync video variant was removed 2026-08 by owner decision:
// avatar video cost ~$0.20/clip against a $5/month total AI budget. The
// static portrait + speaking ring + TTS voice is the permanent presentation.)
interface SpeakingAvatarProps {
  src: string;
  name: string;
  size?: number;
  isSpeaking?: boolean;
  style?: React.CSSProperties;
}

export default function SpeakingAvatar({
  src,
  name,
  size = 38,
  isSpeaking = false,
  style: extraStyle = undefined,
}: SpeakingAvatarProps) {
  const [imgErr, setImgErr] = React.useState(false);

  const ring = isSpeaking
    ? `0 0 0 2.5px #0e7490, 0 0 0 5px rgba(14,116,144,.25), 0 0 16px rgba(14,116,144,.35)`
    : `0 0 0 2px rgba(14,116,144,.25)`;

  return (
    <div
      style={{
        width: size,
        height: size,
        borderRadius: '50%',
        flexShrink: 0,
        overflow: 'hidden',
        boxShadow: ring,
        transition: 'box-shadow .3s ease',
        background: 'linear-gradient(135deg,#0e7490,#0c4a6e)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        ...(extraStyle ?? {}),
      }}
    >
      {!imgErr ? (
        <img
          src={src}
          alt={name}
          loading="lazy"
          onError={() => setImgErr(true)}
          style={{
            width: '100%',
            height: '100%',
            objectFit: 'cover',
            objectPosition: 'top center',
          }}
        />
      ) : (
        <span style={{ fontSize: Math.round(size * 0.45) }}>🇭🇷</span>
      )}
    </div>
  );
}
