import React from 'react';

// ── Portrait mapping — scenario ID → portrait filename ──────────────────────
// Images live at /images/portraits/*.webp (generated by scripts/generate-portraits.mjs)
const PORTRAIT_MAP = {
  cafe:'barista',        market:'vendor',        bakery:'mature-woman',
  grocery:'mature-woman',pharmacy:'mature-woman', postoffice:'mature-man',
  bus:'young-woman',     clothes:'young-woman',   petrol:'mature-man',
  simcard:'young-man',   directions:'mature-man', restaurant:'young-man',
  konoba:'fisherman',    beach:'mature-man',      tourist:'young-woman',
  taxi:'young-man',      hotel:'young-man',       icecream:'young-woman',
  museum:'young-woman',  hairdresser:'young-woman',neighbor:'mature-woman',
  party:'young-man',     birthday:'mature-man',   familydinner:'grandmother',
  wedding:'mature-man',  football:'young-man',    gym:'young-man',
  kafic:'young-man',     weekend:'young-woman',
};

export function portraitSrc(scenarioId) {
  const key = PORTRAIT_MAP[scenarioId] || 'young-woman';
  return `/images/portraits/${key}.webp`;
}

// ── Speaking avatar — portrait photo with live speaking ring + D-ID video ──
// When videoUrl is provided and isSpeaking is true, shows the lip-synced video.
// Falls back to static portrait otherwise.
export default function SpeakingAvatar({ src, name, size = 38, isSpeaking = false, videoUrl = null, style: extraStyle = undefined }) {
  const [imgErr, setImgErr] = React.useState(false);
  const [videoEnded, setVideoEnded] = React.useState(false);
  const videoRef = React.useRef(null);

  // Play video when speaking starts; reset when done
  React.useEffect(() => {
    if (videoUrl && isSpeaking && videoRef.current && videoEnded) {
      setVideoEnded(false);
      videoRef.current.currentTime = 0;
      videoRef.current.play().catch(() => {});
    }
  }, [isSpeaking, videoUrl, videoEnded]);

  const showVideo = videoUrl && isSpeaking && !videoEnded;
  const ring = isSpeaking
    ? `0 0 0 2.5px #0e7490, 0 0 0 5px rgba(14,116,144,.25), 0 0 16px rgba(14,116,144,.35)`
    : `0 0 0 2px rgba(14,116,144,.25)`;

  return (
    <div style={{
      width: size, height: size, borderRadius: '50%', flexShrink: 0, overflow: 'hidden',
      boxShadow: ring, transition: 'box-shadow .3s ease',
      background: 'linear-gradient(135deg,#0e7490,#0c4a6e)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      ...extraStyle,
    }}>
      {/* D-ID lip-sync video (shown when speaking) */}
      {videoUrl && (
        <video
          ref={videoRef}
          src={videoUrl}
          autoPlay={isSpeaking && !videoEnded}
          muted={false}
          playsInline
          onEnded={() => setVideoEnded(true)}
          style={{
            position: 'absolute',
            width: '100%', height: '100%',
            objectFit: 'cover', objectPosition: 'top center',
            display: showVideo ? 'block' : 'none',
            borderRadius: '50%',
          }}
        />
      )}
      {/* Static portrait (shown when not speaking or video ended) */}
      {!showVideo && (
        !imgErr
          ? <img src={src} alt={name} loading="lazy" onError={() => setImgErr(true)}
              style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'top center' }} />
          : <span style={{ fontSize: Math.round(size * 0.45) }}>🇭🇷</span>
      )}
    </div>
  );
}
