// scripts/rebuildCities.mjs
//
// Rewrites src/data/cultural/geography.js and the mirrored
// functions/api/content/_data/cultural/geography.js with a deduplicated +
// extended CROATIAN_CITIES array. Run as: `node scripts/rebuildCities.mjs`.
//
// Inputs:
//   --extras=<path>    JSON file containing { newCities: [...] }
//                      Can be repeated to merge multiple batch files.
//                      Defaults to scripts/_newCities.json when omitted.
//
// The script preserves MAPPLACES untouched, dedups CROATIAN_CITIES by
// case-folded name (keeps the entry with the highest score:
// facts.length * 100 + intro.length + vocab.length), appends the new
// cities, asserts a name-unique invariant, then writes the result back
// to both files identically.

import { readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const SRC_PATH = resolve(REPO_ROOT, 'src/data/cultural/geography.js');
const FUNC_PATH = resolve(
  REPO_ROOT,
  'functions/api/content/_data/cultural/geography.js',
);

function scoreEntry(c) {
  const f = Array.isArray(c.facts) ? c.facts.length : 0;
  const v = Array.isArray(c.vocab) ? c.vocab.length : 0;
  const i = typeof c.intro === 'string' ? c.intro.length : 0;
  return f * 1000 + i + v * 50;
}

function dedupByName(entries) {
  const best = new Map();
  for (const c of entries) {
    const key = String(c.name || '').toLowerCase().trim();
    if (!key) continue;
    const cur = best.get(key);
    if (!cur || scoreEntry(c) > scoreEntry(cur)) best.set(key, c);
  }
  return Array.from(best.values());
}

function emitCities(cities) {
  // Pretty-print as JS array literal. Top-level objects each take a block
  // with a trailing comma. Strings use JSON.stringify so escapes are safe.
  const lines = ['  /* eslint-disable */', ''];
  for (const c of cities) {
    lines.push('  {');
    for (const [k, v] of Object.entries(c)) {
      if (v == null) continue;
      lines.push(`    ${k}: ${JSON.stringify(v)},`);
    }
    lines.push('  },');
  }
  return lines.join('\n');
}

async function readSection(src, exportName) {
  // Use dynamic import so we always get the current exported values.
  const url = pathToFileURL(src).href + '?t=' + Date.now();
  const mod = await import(url);
  return mod[exportName];
}

async function loadExtras(extrasPath) {
  if (!extrasPath) return [];
  const buf = await readFile(extrasPath, 'utf8');
  const parsed = JSON.parse(buf);
  if (!parsed || !Array.isArray(parsed.newCities)) {
    throw new Error(`${extrasPath}: expected { newCities: [...] }`);
  }
  return parsed.newCities;
}

function rebuildFileContent(mapplacesSrc, citiesLiteral) {
  return `// geography.js — regenerated by scripts/rebuildCities.mjs
${mapplacesSrc}

export const CROATIAN_CITIES = [
${citiesLiteral}
];
`;
}

async function extractMapplacesSrc(src) {
  const raw = await readFile(src, 'utf8');
  const start = raw.indexOf('export const MAPPLACES');
  if (start < 0) throw new Error('MAPPLACES export not found');
  // Find the matching closing `];` for MAPPLACES at top level. We assume
  // MAPPLACES is an object whose final block ends with `};`.
  const fromStart = raw.slice(start);
  const endRel = fromStart.indexOf('\n};\n');
  if (endRel < 0) {
    // Fallback: try '\n};' at the end
    const endRel2 = fromStart.indexOf('\n};');
    if (endRel2 < 0) throw new Error('MAPPLACES end not found');
    return fromStart.slice(0, endRel2 + 3);
  }
  return fromStart.slice(0, endRel + 3);
}

async function main() {
  // Collect --extras flags (may be repeated). Anything that doesn't match the
  // flag pattern falls through to the unused-args bucket.
  const rawArgs = process.argv.slice(2);
  const extrasPaths = [];
  for (const a of rawArgs) {
    const m = a.match(/^--extras=(.*)$/);
    if (m) extrasPaths.push(resolve(REPO_ROOT, m[1]));
  }
  if (extrasPaths.length === 0) {
    extrasPaths.push(resolve(__dirname, '_newCities.json'));
  }

  const cities = await readSection(SRC_PATH, 'CROATIAN_CITIES');
  const originalCount = cities.length;
  const dedupCount = dedupByName(cities).length;

  // Concatenate newCities from every --extras file. Missing files are ignored
  // so an unused default path doesn't crash the script.
  const newCities = [];
  for (const p of extrasPaths) {
    const batch = await loadExtras(p).catch((e) => {
      if (e.code === 'ENOENT') return [];
      throw e;
    });
    newCities.push(...batch);
    if (batch.length > 0) console.log(`  loaded ${batch.length} entries from ${p}`);
  }

  // Dedup new cities against existing + against themselves.
  const existingNames = new Set(
    dedupByName(cities).map((c) => String(c.name).toLowerCase().trim()),
  );
  const acceptedNew = [];
  for (const nc of newCities) {
    const key = String(nc.name || '').toLowerCase().trim();
    if (!key) {
      console.warn('skip nameless new-city entry:', nc);
      continue;
    }
    if (existingNames.has(key)) {
      console.warn(`new city already in list — skipping: ${nc.name}`);
      continue;
    }
    existingNames.add(key);
    acceptedNew.push(nc);
  }

  const finalCities = [...dedupByName(cities), ...acceptedNew];
  // Invariant: all names unique.
  const nameSet = new Set();
  for (const c of finalCities) {
    const k = String(c.name).toLowerCase().trim();
    if (nameSet.has(k)) throw new Error(`duplicate name after merge: ${c.name}`);
    nameSet.add(k);
  }

  const mapplacesSrc = await extractMapplacesSrc(SRC_PATH);
  const literal = emitCities(finalCities);
  const out = rebuildFileContent(mapplacesSrc, literal);

  await writeFile(SRC_PATH, out, 'utf8');
  await writeFile(FUNC_PATH, out, 'utf8');

  console.log(`original entries : ${originalCount}`);
  console.log(`after dedup      : ${dedupCount}`);
  console.log(`new cities added : ${acceptedNew.length}`);
  console.log(`final unique     : ${finalCities.length}`);
}

await main();
