// scripts/removeCities.mjs
//
// Removes one or more entries from CROATIAN_CITIES by exact (case-insensitive)
// name and re-emits both geography.js files using the SAME serializer as
// rebuildCities.mjs / applyCityUpgrades.mjs, so unchanged cities stay
// byte-identical and the diff shows only the removed block(s).
//
// Usage: node scripts/removeCities.mjs "Prozor" ["Other Name" ...]

import { readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const SRC_PATH = resolve(REPO_ROOT, 'src/data/cultural/geography.js');
const FUNC_PATH = resolve(REPO_ROOT, 'functions/api/content/_data/cultural/geography.js');

function emitCities(cities) {
  const lines = ['  /* eslint-disable */', ''];
  for (const c of cities) {
    lines.push('  {');
    for (const [k, v] of Object.entries(c)) {
      if (v == null) continue;
      lines.push(`    ${k}: ${JSON.stringify(v)},`);
    }
    lines.push('  },');
  }
  return lines.join('\n');
}

async function extractMapplacesSrc(src) {
  const raw = await readFile(src, 'utf8');
  const start = raw.indexOf('export const MAPPLACES');
  if (start < 0) throw new Error('MAPPLACES export not found');
  const fromStart = raw.slice(start);
  const endRel = fromStart.indexOf('\n};\n');
  if (endRel < 0) {
    const endRel2 = fromStart.indexOf('\n};');
    if (endRel2 < 0) throw new Error('MAPPLACES end not found');
    return fromStart.slice(0, endRel2 + 3);
  }
  return fromStart.slice(0, endRel + 3);
}

async function main() {
  const names = process.argv.slice(2);
  if (names.length === 0) {
    console.error('Usage: node removeCities.mjs "<name>" [...]');
    process.exit(2);
  }
  const wanted = new Set(names.map((n) => n.toLowerCase().trim()));

  const url = pathToFileURL(SRC_PATH).href + '?t=' + Date.now();
  const cities = (await import(url)).CROATIAN_CITIES;
  const before = cities.length;

  const removed = [];
  const kept = cities.filter((c) => {
    const k = String(c.name).toLowerCase().trim();
    if (wanted.has(k)) {
      removed.push(c.name);
      return false;
    }
    return true;
  });

  const stillWanted = [...wanted].filter(
    (w) => !removed.some((r) => r.toLowerCase().trim() === w),
  );
  if (stillWanted.length) {
    console.error('ERROR: names not found, nothing removed:', stillWanted.join(', '));
    process.exit(1);
  }

  const mapplacesSrc = await extractMapplacesSrc(SRC_PATH);
  const out = `// geography.js — regenerated by scripts/rebuildCities.mjs
${mapplacesSrc}

export const CROATIAN_CITIES = [
${emitCities(kept)}
];
`.replace(/\r\n/g, '\n');

  await writeFile(SRC_PATH, out, 'utf8');
  await writeFile(FUNC_PATH, out, 'utf8');
  console.log(`removed: ${removed.join(', ')}`);
  console.log(`cities ${before} -> ${kept.length} (written to both files)`);
}

await main();
