import React from 'react';
import ModeDrill from './ModeDrill';

export const DATA = [
  {
    q: 'Vidim svog ___ na ulici.',
    nom: 'brat (brother)',
    en: 'I see my brother on the street.',
    opts: ['brata', 'brat', 'bratu', 'bratom'],
    answer: 'brata',
    tip: 'brat is ANIMATE (person) → accusative = genitive form: brat → brata',
  },
  {
    q: 'Ona čita ___.',
    nom: 'roman (novel)',
    en: 'She is reading a novel.',
    opts: ['roman', 'romana', 'romanu', 'romanom'],
    answer: 'roman',
    tip: 'roman is INANIMATE → accusative = nominative: roman (no change)',
  },
  {
    q: 'Imam ___.',
    nom: 'pas (dog)',
    en: 'I have a dog.',
    opts: ['psa', 'pas', 'psu', 'psom'],
    answer: 'psa',
    tip: 'pas is ANIMATE (animal) → accusative = genitive: pas → psa',
  },
  {
    q: 'Ona gleda ___.',
    nom: 'film (film)',
    en: 'She is watching a movie.',
    opts: ['film', 'filma', 'filmu', 'filmom'],
    answer: 'film',
    tip: 'film is INANIMATE → accusative = nominative: film (no change)',
  },
  {
    q: 'Mama zove ___.',
    nom: 'sin (son)',
    en: 'Mom is calling her son.',
    opts: ['sina', 'sin', 'sinu', 'sinom'],
    answer: 'sina',
    tip: 'sin is ANIMATE (person) → accusative = genitive: sin → sina',
  },
  {
    q: 'Kupio sam novi ___.',
    nom: 'stol (table)',
    en: 'I bought a new table.',
    opts: ['stol', 'stola', 'stolu', 'stolom'],
    answer: 'stol',
    tip: 'stol is INANIMATE → accusative = nominative: stol (no change)',
  },
  {
    q: 'Traži svog ___.',
    nom: 'prijatelj (friend)',
    en: 'She is looking for her friend.',
    opts: ['prijatelja', 'prijatelj', 'prijatelju', 'prijateljem'],
    answer: 'prijatelja',
    tip: 'prijatelj is ANIMATE (person) → accusative = genitive: prijatelj → prijatelja',
  },
  {
    q: 'Kupila sam novi ___.',
    nom: 'telefon (phone)',
    en: 'I bought a new phone.',
    opts: ['telefon', 'telefona', 'telefonu', 'telefonom'],
    answer: 'telefon',
    tip: 'telefon is INANIMATE → accusative = nominative: telefon (no change)',
  },
  {
    q: 'Volim svog ___.',
    nom: 'mačak (cat)',
    en: 'I love my cat.',
    opts: ['mačka', 'mačak', 'mačku', 'mačkom'],
    answer: 'mačka',
    tip: 'mačak is ANIMATE (animal) → accusative = genitive: mačak → mačka',
  },
  {
    q: 'Čujem ___.',
    nom: 'vlak (train)',
    en: 'I hear the train.',
    opts: ['vlak', 'vlaka', 'vlaku', 'vlakom'],
    answer: 'vlak',
    tip: 'vlak is INANIMATE → accusative = nominative: vlak (no change)',
  },
  {
    q: 'Pitam ___.',
    nom: 'profesor (professor)',
    en: 'I am asking the professor.',
    opts: ['profesora', 'profesor', 'profesoru', 'profesorom'],
    answer: 'profesora',
    tip: 'profesor is ANIMATE (person) → accusative = genitive: profesor → profesora',
  },
  {
    q: 'Vozim ___.',
    nom: 'auto (car)',
    en: 'I drive a car.',
    opts: ['auto', 'auta', 'autu', 'autom'],
    answer: 'auto',
    tip: 'auto is INANIMATE → accusative = nominative: auto (no change; it still declines: auta, autu, autom)',
  },
  {
    q: 'Vidim ___.',
    nom: 'konj (horse)',
    en: 'I see a horse.',
    opts: ['konja', 'konj', 'konju', 'konjem'],
    answer: 'konja',
    tip: 'konj is ANIMATE (animal) → accusative = genitive: konj → konja',
  },
  {
    q: 'Imam ___.',
    nom: 'ključ (key)',
    en: 'I have a key.',
    opts: ['ključ', 'ključa', 'ključu', 'ključem'],
    answer: 'ključ',
    tip: 'ključ is INANIMATE → accusative = nominative: ključ (no change)',
  },
  {
    q: 'Znam ___.',
    nom: 'liječnik (doctor)',
    en: 'I know the doctor.',
    opts: ['liječnika', 'liječnik', 'liječniku', 'liječnikom'],
    answer: 'liječnika',
    tip: 'liječnik is ANIMATE (person) → accusative = genitive: liječnik → liječnika',
  },
  {
    q: 'Otvaramo ___.',
    nom: 'prozor (window)',
    en: 'We are opening the window.',
    opts: ['prozor', 'prozora', 'prozoru', 'prozorom'],
    answer: 'prozor',
    tip: 'prozor is INANIMATE → accusative = nominative: prozor (no change)',
  },
  {
    q: 'Volim svog ___.',
    nom: 'muž (husband)',
    en: 'I love my husband.',
    opts: ['muža', 'muž', 'mužu', 'mužem'],
    answer: 'muža',
    tip: 'muž is ANIMATE (person) → accusative = genitive: muž → muža',
  },
  {
    q: 'Vidim ___.',
    nom: 'brod (ship)',
    en: 'I see a ship.',
    opts: ['brod', 'broda', 'brodu', 'brodom'],
    answer: 'brod',
    tip: 'brod is INANIMATE → accusative = nominative: brod (no change)',
  },
  {
    q: 'Promatram ___.',
    nom: 'stranac (stranger)',
    en: 'I am watching the stranger.',
    opts: ['stranca', 'stranac', 'strancu', 'strancem'],
    answer: 'stranca',
    tip: 'stranac is ANIMATE (person) → accusative = genitive: stranac → stranca',
  },
  {
    q: 'Čujem ___.',
    nom: 'sat (clock)',
    en: 'I hear the clock.',
    opts: ['sat', 'sata', 'satu', 'satom'],
    answer: 'sat',
    tip: 'sat is INANIMATE → accusative = nominative: sat (no change)',
  },
  // ── 2026-07 depth expansion (+30): animate vs inanimate + PLURAL (no animacy split!) ──
  {
    q: 'Zovem ___ na večeru.',
    nom: 'susjed (neighbour)',
    en: 'I am inviting the neighbour to dinner.',
    opts: ['susjeda', 'susjed', 'susjedu', 'susjedom'],
    answer: 'susjeda',
    tip: 'ANIMATE masculine: accusative = genitive → susjeda.',
  },
  {
    q: 'Čitam ___ svaki dan.',
    nom: 'časopis (magazine)',
    en: 'I read the magazine every day.',
    opts: ['časopis', 'časopisa', 'časopisu', 'časopisom'],
    answer: 'časopis',
    tip: 'INANIMATE masculine: accusative = nominative → časopis.',
  },
  {
    q: 'Slikar crta ___.',
    nom: 'konj (horse)',
    en: 'The painter draws a horse.',
    opts: ['konja', 'konj', 'konju', 'konjem'],
    answer: 'konja',
    tip: 'Animals are ANIMATE: konj → konja.',
  },
  {
    q: 'Parkiram ___ ispred zgrade.',
    nom: 'automobil (car)',
    en: 'I park the car in front of the building.',
    opts: ['automobil', 'automobila', 'automobilu', 'automobilom'],
    answer: 'automobil',
    tip: 'INANIMATE: acc = nom → automobil.',
  },
  {
    q: 'Djeca gledaju ___.',
    nom: 'klaun (clown)',
    en: 'The children watch the clown.',
    opts: ['klauna', 'klaun', 'klaunu', 'klaunom'],
    answer: 'klauna',
    tip: 'ANIMATE: klaun → klauna.',
  },
  {
    q: 'Baka je ispekla ___.',
    nom: 'kolač (cake)',
    en: 'Grandma baked a cake.',
    opts: ['kolač', 'kolača', 'kolaču', 'kolačem'],
    answer: 'kolač',
    tip: 'INANIMATE: acc = nom → kolač.',
  },
  {
    q: 'Policija traži ___.',
    nom: 'lopov (thief)',
    en: 'The police are looking for the thief.',
    opts: ['lopova', 'lopov', 'lopovu', 'lopovom'],
    answer: 'lopova',
    tip: 'ANIMATE: lopov → lopova.',
  },
  {
    q: 'Sutra polažem ___.',
    nom: 'ispit (exam)',
    en: 'Tomorrow I am taking the exam.',
    opts: ['ispit', 'ispita', 'ispitu', 'ispitom'],
    answer: 'ispit',
    tip: 'INANIMATE: acc = nom → ispit.',
  },
  {
    q: 'Fotografiram ___ u zoološkom vrtu.',
    nom: 'medvjed (bear)',
    en: 'I photograph the bear at the zoo.',
    opts: ['medvjeda', 'medvjed', 'medvjedu', 'medvjedom'],
    answer: 'medvjeda',
    tip: 'ANIMATE animal: medvjed → medvjeda.',
  },
  {
    q: 'Prelazimo ___ pješice.',
    nom: 'most (bridge)',
    en: 'We cross the bridge on foot.',
    opts: ['most', 'mosta', 'mostu', 'mostom'],
    answer: 'most',
    tip: 'INANIMATE: acc = nom → most.',
  },
  {
    q: 'Trener hvali ___.',
    nom: 'igrač (player)',
    en: 'The coach praises the player.',
    opts: ['igrača', 'igrač', 'igraču', 'igračem'],
    answer: 'igrača',
    tip: 'ANIMATE: igrač → igrača.',
  },
  {
    q: 'Uključi ___, molim te.',
    nom: 'televizor (TV set)',
    en: 'Turn on the TV, please.',
    opts: ['televizor', 'televizora', 'televizoru', 'televizorom'],
    answer: 'televizor',
    tip: 'INANIMATE (devices are not animate): acc = nom → televizor.',
  },
  {
    q: 'Vidim ___ svaki dan u parku.',
    nom: 'starac (old man)',
    en: 'I see the old man in the park every day.',
    opts: ['starca', 'starac', 'starcu', 'starcem'],
    answer: 'starca',
    tip: 'ANIMATE with fleeting -a-: starac → starca.',
  },
  {
    q: 'Pijem ___ bez šećera.',
    nom: 'čaj (tea)',
    en: 'I drink tea without sugar.',
    opts: ['čaj', 'čaja', 'čaju', 'čajem'],
    answer: 'čaj',
    tip: 'INANIMATE: acc = nom → čaj.',
  },
  {
    q: 'Veterinar pregledava ___.',
    nom: 'mačak (tomcat)',
    en: 'The vet examines the tomcat.',
    opts: ['mačka', 'mačak', 'mačku', 'mačkom'],
    answer: 'mačka',
    tip: 'ANIMATE with fleeting -a-: mačak → mačka.',
  },
  {
    q: 'Gledamo ___ o Jadranu.',
    nom: 'dokumentarac (documentary)',
    en: 'We are watching a documentary about the Adriatic.',
    opts: ['dokumentarac', 'dokumentarca', 'dokumentarcu', 'dokumentarcem'],
    answer: 'dokumentarac',
    tip: 'INANIMATE: acc = nom → dokumentarac (films are things).',
  },
  {
    q: 'Pozdravljam ___ svako jutro.',
    nom: 'poštar (postman)',
    en: 'I greet the postman every morning.',
    opts: ['poštara', 'poštar', 'poštaru', 'poštarom'],
    answer: 'poštara',
    tip: 'ANIMATE: poštar → poštara.',
  },
  {
    q: 'Kupujem ___ za zimu.',
    nom: 'kaput (coat)',
    en: 'I am buying a coat for winter.',
    opts: ['kaput', 'kaputa', 'kaputu', 'kaputom'],
    answer: 'kaput',
    tip: 'INANIMATE: acc = nom → kaput.',
  },
  {
    q: 'Slušamo ___ na radiju.',
    nom: 'pjevač (singer)',
    en: 'We listen to the singer on the radio.',
    opts: ['pjevača', 'pjevač', 'pjevaču', 'pjevačem'],
    answer: 'pjevača',
    tip: 'ANIMATE: pjevač → pjevača.',
  },
  {
    q: 'Vidim ___ kroz prozor.',
    nom: 'vrt (garden)',
    en: 'I see the garden through the window.',
    opts: ['vrt', 'vrta', 'vrtu', 'vrtom'],
    answer: 'vrt',
    tip: 'INANIMATE: acc = nom → vrt.',
  },
  {
    q: 'Pozvali smo ___ na kavu.',
    nom: 'prijatelji (friends, pl.)',
    en: 'We invited our friends for coffee.',
    opts: ['prijatelje', 'prijatelji', 'prijatelja', 'prijateljima'],
    answer: 'prijatelje',
    tip: 'PLURAL has NO animacy split — all masc. pl. accusatives take -e: prijatelje.',
  },
  {
    q: 'Vidim ___ na parkiralištu.',
    nom: 'automobili (cars, pl.)',
    en: 'I see the cars in the car park.',
    opts: ['automobile', 'automobili', 'automobila', 'automobilima'],
    answer: 'automobile',
    tip: 'PLURAL: animate or not, acc. pl. is -e → automobile.',
  },
  {
    q: 'Farmer hrani ___.',
    nom: 'konji (horses, pl.)',
    en: 'The farmer feeds the horses.',
    opts: ['konje', 'konji', 'konja', 'konjima'],
    answer: 'konje',
    tip: 'PLURAL animate — same -e as inanimate: konje. Animacy matters only in the SINGULAR.',
  },
  {
    q: 'Skupljam stare ___.',
    nom: 'novčići (coins, pl.)',
    en: 'I collect old coins.',
    opts: ['novčiće', 'novčići', 'novčića', 'novčićima'],
    answer: 'novčiće',
    tip: 'PLURAL: novčići → novčiće.',
  },
  {
    q: 'Učiteljica poziva ___ pred ploču.',
    nom: 'učenici (pupils, pl.)',
    en: 'The teacher calls the pupils to the board.',
    opts: ['učenike', 'učenici', 'učenika', 'učenicima'],
    answer: 'učenike',
    tip: 'PLURAL acc: učenici → učenike (c reverts to k!).',
  },
  {
    q: 'Molim ___, ponovite pitanje.',
    nom: 'vi (you, formal)',
    en: 'Please (you formal), repeat the question.',
    opts: ['vas', 'vi', 'vama', 'vam'],
    answer: 'vas',
    tip: "Pronoun accusative: vi → vas ('moliti koga').",
  },
  {
    q: 'Nazvat ću ___ sutra.',
    nom: 'ujak (uncle)',
    en: 'I will call my uncle tomorrow.',
    opts: ['ujaka', 'ujak', 'ujaku', 'ujakom'],
    answer: 'ujaka',
    tip: 'ANIMATE: ujak → ujaka.',
  },
  {
    q: 'Stavljam ___ na stol.',
    nom: 'laptop (laptop)',
    en: 'I put the computer on the table.',
    opts: ['laptop', 'laptopa', 'laptopu', 'laptopom'],
    answer: 'laptop',
    tip: 'INANIMATE loanword: acc = nom → laptop.',
  },
  {
    q: 'Susrećemo ___ u hodniku.',
    nom: 'profesori (professors, pl.)',
    en: 'We meet the professors in the corridor.',
    opts: ['profesore', 'profesori', 'profesora', 'profesorima'],
    answer: 'profesore',
    tip: 'PLURAL: profesori → profesore.',
  },
  {
    q: 'Obitelj gleda ___ zajedno.',
    nom: 'film (film)',
    en: 'The family watches a movie together.',
    opts: ['film', 'filma', 'filmu', 'filmom'],
    answer: 'film',
    tip: 'INANIMATE: acc = nom → film.',
  },
];

// One question type, so the engine's run is 12 from the whole bank (DRILL_RUN_LENGTH).
const MODE_LABEL: Record<string, string> = { fill: 'Choose the accusative form' };
const BANK = DATA.map(({ nom, ...rest }) => ({ ...rest, cue: nom, mode: 'fill' }));

interface Props {
  goBack: () => void;
  award?: (xp: number, celebrate?: boolean, activityType?: string) => void;
}

export default function AnimateAccDrill({ goBack, award }: Props) {
  return (
    <ModeDrill
      id="animateacc"
      title={'🎯 Animate Accusative'}
      subtitle={'Inanimate = same as nom; Animate = genitive form'}
      modeLabels={MODE_LABEL}
      data={BANK}
      praise={{
        perfect: 'Perfect! Animate accusative mastered! 🏆',
        good: 'Great work! 💪',
        more: 'Keep practising — animate vs inanimate is tricky!',
      }}
      goBack={goBack}
      award={award}
    />
  );
}
