export const SCENARIOS = [
  {
    id:"cafe",
    title:"☕ At the Café",
    subtitle:"Order drinks and pay the bill",
    difficulty:"A1",
    turns:[
      { speaker:"Konobar", line:"Dobar dan! Što ćete naručiti?", en:"Good day! What would you like to order?",
        opts:["Mogu li dobiti kavu, molim?","Ja hoću kava.","Daj mi kavu.","Kava!"],
        answer:0, tip:"'Mogu li dobiti...' is the polite way to order. 'Ja hoću...' is too direct/childlike." },
      { speaker:"Konobar", line:"S mlijekom ili bez?", en:"With milk or without?",
        opts:["S mlijekom, hvala.","Ja hoću s mlijekom.","Mlijeko da.","S mlijeko, hvala."],
        answer:0, tip:"'S mlijekom' is correct — instrumental case. 📚 See: Instrumental Case (Lesson 4)" },
      { speaker:"Konobar", line:"Izvolite. Trebate li još nešto?", en:"Here you go. Do you need anything else?",
        opts:["Molim vas, možete li donijeti i čašu vode?","Ja trebam voda.","Daj vodu.","Ne, bog."],
        answer:0, tip:"Polite request with 'možete li donijeti' — could you bring. Always use 'molim vas' in formal settings." },
      { speaker:"Konobar", line:"Naravno! Još nešto?", en:"Of course! Anything else?",
        opts:["Ne, hvala, to je sve.","Ništa ne.","Nema.","Ne hvala."],
        answer:0, tip:"'To je sve' (that's all) is the natural way to close an order." },
      { speaker:"Konobar", line:"Mogu li vam donijeti račun?", en:"May I bring you the bill?",
        opts:["Da, molim. Koliko je to?","Koliko košta?","Daj račun.","Da, hvala."],
        answer:0, tip:"'Koliko je to?' (How much is that?) is more natural than just accepting." },
    ]
  },
  {
    id:"directions",
    title:"🗺️ Asking for Directions",
    subtitle:"Find your way around a Croatian city",
    difficulty:"A1",
    turns:[
      { speaker:"You approach someone", line:"[You need to ask where the post office is]", en:"Ask politely for directions",
        opts:["Oprostite, gdje je pošta?","Gdje je pošta?","Pošta gdje?","Tražim poštu."],
        answer:0, tip:"'Oprostite' (excuse me) is essential before asking a stranger." },
      { speaker:"Prolaznik", line:"Pošta? Idite ravno, pa skrenite lijevo.", en:"The post office? Go straight, then turn left.",
        opts:["Hvala lijepa, koliko je daleko?","Što?","Hvala.","Ne razumijem."],
        answer:0, tip:"Asking 'koliko je daleko?' (how far is it?) shows you're engaged." },
      { speaker:"Prolaznik", line:"Otprilike deset minuta pješice.", en:"About ten minutes on foot.",
        opts:["Odlično, hvala puno!","Dobro.","Ok.","Hvala."],
        answer:0, tip:"'Odlično' (excellent) + 'hvala puno' (thank you very much) is warm and natural." },
      { speaker:"Prolaznik", line:"Nema na čemu! Sretno!", en:"Don't mention it! Good luck!",
        opts:["Hvala, i vama!","Ok.","Bog.","Hvala."],
        answer:0, tip:"'I vama' (to you too) is the standard response to a kind wish." },
    ]
  },
  {
    id:"doctor",
    title:"🏥 At the Doctor",
    subtitle:"Describe symptoms and understand advice",
    difficulty:"A2",
    turns:[
      { speaker:"Doktor", line:"Dobar dan. Što vas muči?", en:"Good day. What's bothering you?",
        opts:["Boli me grlo i imam temperaturu.","Ja imam bolestan.","Moj grlo boli.","Temperatura."],
        answer:0, tip:"'Boli me grlo' (my throat hurts) is the correct Croatian structure. 📚 See: Cases — Accusative (Lesson 4)" },
      { speaker:"Doktor", line:"Koliko dugo imate te tegobe?", en:"How long have you had these symptoms?",
        opts:["Od jučer, oko dva dana.","Dva dana.","Ja imam ovo dva dana.","Jučer."],
        answer:0, tip:"'Od jučer' (since yesterday) + specific timeframe is natural." },
      { speaker:"Doktor", line:"Imate li kakve alergije na lijekove?", en:"Do you have any allergies to medications?",
        opts:["Ne, koliko znam, nemam alergija.","Ne.","Nemam.","Ja nemam alergija."],
        answer:0, tip:"'Koliko znam' (as far as I know) is a natural hedge." },
      { speaker:"Doktor", line:"Prepisat ću vam antibiotike. Uzimajte tri puta dnevno.", en:"I'll prescribe antibiotics. Take them three times daily.",
        opts:["Razumijem. Koliko dana ih trebam uzimati?","Ok.","Hvala.","Razumijem."],
        answer:0, tip:"Always ask clarifying questions! 'Koliko dana' (how many days) shows you're engaged." },
      { speaker:"Doktor", line:"Sedam dana. I odmarajte se više.", en:"Seven days. And rest more.",
        opts:["Hoću, hvala doktore. Vidimo se!","Ok doktor.","Hvala.","Vidimo se."],
        answer:0, tip:"'Vidimo se!' (See you!) is a warm farewell." },
    ]
  },
  {
    id:"shopping",
    title:"🛍️ Shopping",
    subtitle:"Buy clothes at a Croatian shop",
    difficulty:"A2",
    turns:[
      { speaker:"Prodavačica", line:"Mogu li vam pomoći?", en:"Can I help you?",
        opts:["Samo gledam, hvala.","Ne.","Da.","Tražim majicu."],
        answer:0, tip:"'Samo gledam' (just browsing) is the universal polite answer." },
      { speaker:"Prodavačica", line:"[You found a shirt you like] Imate li ovo u većoj veličini?", en:"Do you have this in a larger size?",
        opts:["Imate li ovo u većoj veličini?","Ja hoću veće.","Veće, molim.","Ovo je malo."],
        answer:0, tip:"'Imate li' (do you have) + 'u većoj veličini' (in a larger size) is the full natural question." },
      { speaker:"Prodavačica", line:"Naravno, imate medium i large.", en:"Of course, we have medium and large.",
        opts:["Mogu li probati medium?","Daj mi medium.","Medium.","Probati?"],
        answer:0, tip:"'Mogu li probati' (may I try on) is polite and natural." },
      { speaker:"Prodavačica", line:"Svlačionica je tamo lijevo.", en:"The fitting room is over there on the left.",
        opts:["Hvala!","Ok.","Dobro.","Da."],
        answer:0, tip:"A simple warm 'Hvala!' is perfect here." },
      { speaker:"Prodavačica", line:"Kako vam stoji?", en:"How does it fit you?",
        opts:["Savršeno! Uzet ću ovo. Gdje se plaća?","Dobro.","Ok.","Stoji mi."],
        answer:0, tip:"'Savršeno!' (perfectly) + 'uzet ću' (I'll take it) + asking where to pay." },
    ]
  },
  {
    id:"meeting",
    title:"👋 Meeting Someone New",
    subtitle:"Introduce yourself at a social event",
    difficulty:"A1",
    turns:[
      { speaker:"Stranger", line:"Bog! Jesi li ti novi u gradu?", en:"Hi! Are you new to the city?",
        opts:["Da, tek sam se doselio/doselila. Ja sam [ime].","Da, ja sam novi.","Da.","Novi sam."],
        answer:0, tip:"'Tek sam se doselio' (I just moved here) + introducing yourself is the natural full response." },
      { speaker:"Stranger", line:"Drago mi je! Ja sam Marko. Otkud si?", en:"Nice to meet you! I'm Marko. Where are you from?",
        opts:["Drago mi je, Marko! Ja sam iz Engleske, ali učim hrvatski.","Engleska.","Iz Engleske.","Ja sam Englez."],
        answer:0, tip:"Full response with their name + your origin + showing you're learning Croatian." },
      { speaker:"Marko", line:"Super! Kako ti ide s hrvatskim?", en:"Great! How's your Croatian going?",
        opts:["Polako, ali napredujem. Jezik mi je teži nego što sam mislio.","Dobro.","Teško.","Ok, teško."],
        answer:0, tip:"'Polako, ali napredujem' (slowly but I'm progressing) is honest and shows effort." },
      { speaker:"Marko", line:"Ha! Svima nam je bio težak. Hoćeš još piće?", en:"Ha! It was hard for all of us. Do you want another drink?",
        opts:["Rado! Hvala puno, Marko.","Da.","Hoću.","Ok."],
        answer:0, tip:"'Rado!' (gladly/with pleasure) is a warm enthusiastic yes." },
    ]
  },
  {
    id:"transport",
    title:"🚌 Public Transport",
    subtitle:"Buy a ticket and find your platform",
    difficulty:"A2",
    turns:[
      { speaker:"Blagajnica", line:"Izvolite, slušam vas.", en:"Yes, I'm listening.",
        opts:["Molim vas jednu kartu za Split, molim.","Jedan karta za Split.","Split karta.","Karta Split."],
        answer:0, tip:"'Jednu kartu za Split' — accusative 'kartu' (ticket-ACC)." },
      { speaker:"Blagajnica", line:"Povratnu ili u jednom smjeru?", en:"Return or one-way?",
        opts:["U jednom smjeru, molim.","Jedan smjer.","One way.","Samo tamo."],
        answer:0, tip:"'U jednom smjeru' (one-way) is the Croatian term." },
      { speaker:"Blagajnica", line:"To je sto dvadeset kuna... pardon, eura.", en:"That's 120 euros.",
        opts:["Izvolite. S kojeg perona polazi vlak?","Hvala.","Ok.","Peron?"],
        answer:0, tip:"'S kojeg perona' (from which platform) — genitive after 's'." },
      { speaker:"Blagajnica", line:"S petog perona, polazi u 14:30.", en:"From platform 5, it departs at 14:30.",
        opts:["Hvala lijepa! Imate li neku kavu dok čekam?","Hvala.","Ok.","Razumijem."],
        answer:0, tip:"All options are grammatically acceptable here." },
    ]
  },
  {
    id:"emergency",
    title:"🚨 Emergency",
    subtitle:"Handle an urgent situation in Croatian",
    difficulty:"A2",
    turns:[
      { speaker:"(You need to call for help)", line:"[You see someone fall and need help]", en:"Call for help urgently",
        opts:["Pomoć! Zovite hitnu pomoć, molim!","Pomoć!","Hitna pomoć!","Help!"],
        answer:0, tip:"Full clear sentence gives bystanders all the information." },
      { speaker:"Prolaznik", line:"Što se dogodilo?", en:"What happened?",
        opts:["Čovjek je pao i ne reagira. Zovite 112!","Pao je.","Hitna pomoć.","Ne znam."],
        answer:0, tip:"Clear description + '112' (Croatian emergency number). Be specific in emergencies!" },
      { speaker:"Dispečer (112)", line:"Koji je vaš položaj?", en:"What is your location?",
        opts:["Nalazimo se na Trgu bana Jelačića, ispred fontane.","Trg.","Centar.","Ovdje."],
        answer:0, tip:"Specific landmark + position is critical." },
      { speaker:"Dispečer", line:"Hitna pomoć dolazi. Je li osoba svjesna?", en:"Ambulance is coming. Is the person conscious?",
        opts:["Čini se da nije. Disanje je nepravilno.","Ne.","Nesvjestan.","Ne znam."],
        answer:0, tip:"Providing breathing information is crucial medical data." },
    ]
  },
  {
    id:"pharmacy",
    title:"💊 At the Pharmacy",
    subtitle:"Get medication for a headache in Split",
    difficulty:"A2",
    turns:[
      { speaker:"Ljekarnica Ana", line:"Dobar dan! Mogu li vam pomoći?", en:"Good day! Can I help you?",
        opts:["Dobar dan! Imate li nešto za glavobolju?","Ja imam glavobolja.","Hoću lijek za glava.","Glavobolja."],
        answer:0, tip:"'Imate li nešto za glavobolju?' — correct accusative 'glavobolju' after 'za'." },
      { speaker:"Ljekarnica Ana", line:"Imate li recept, ili vam treba nešto bez recepta?", en:"Do you have a prescription, or do you need something over the counter?",
        opts:["Nemam recept. Trebam nešto bez recepta, molim.","Ja nemam recept.","Ne imam recept.","Bez recept."],
        answer:0, tip:"'Nemam recept' + 'trebam nešto bez recepta' is a complete natural response." },
      { speaker:"Ljekarnica Ana", line:"U redu. Preporučujem ibuprofen ili aspirin. Koji preferirate?", en:"Alright. I recommend ibuprofen or aspirin. Which do you prefer?",
        opts:["Ibuprofen, molim. Koliko tableta trebam uzimati i kako često?","Ibuprofen.","Dajte mi ibuprofen.","Hoću ibuprofen."],
        answer:0, tip:"Asking 'koliko tableta... i kako često?' shows competence and gets dosage info." },
      { speaker:"Ljekarnica Ana", line:"Jednu do dvije tablete, svaka četiri do šest sati. Ne više od šest tableta dnevno.", en:"One to two tablets every four to six hours. No more than six tablets per day.",
        opts:["Razumijem, hvala. Smiju li se uzimati na prazan želudac?","Ok.","Razumijem.","Hvala, gotovo."],
        answer:0, tip:"'Smiju li se uzimati na prazan želudac?' is a practical follow-up question." },
      { speaker:"Ljekarnica Ana", line:"Bolje s hranom ili mlijekom. Ima li još nešto?", en:"Better with food or milk. Is there anything else?",
        opts:["Hvala lijepa. Koliko to košta?","Koliko košta?","Što košta?","Cijena?"],
        answer:0, tip:"'Hvala lijepa' before asking the price is polite." },
      { speaker:"Ljekarnica Ana", line:"Deset eura, molim. Evo vam račun.", en:"Ten euros, please. Here is your receipt.",
        opts:["Izvolite, hvala lijepa! Ugodan dan!","Hvala.","Ok, bog.","Bok."],
        answer:0, tip:"'Izvolite' + 'hvala lijepa' + 'Ugodan dan!' is the complete warm leave-taking." },
    ]
  },
  {
    id:"restaurant",
    title:"🍽️ Restaurant Reservation",
    subtitle:"Make a reservation and order a meal",
    difficulty:"B1",
    turns:[
      { speaker:"Recepcionista", line:"Dobra večer, restoran 'Dubrovnik', izvolite.", en:"Good evening, restaurant 'Dubrovnik', how can I help?",
        opts:["Dobra večer. Htjela bih rezervirati stol za dvoje za petak navečer.","Rezervacija.","Htjeti stol.","Stol za dvoje."],
        answer:0, tip:"'Htjela bih' (I would like — conditional, feminine) is perfectly polite." },
      { speaker:"Recepcionista", line:"Za koliko sati?", en:"For what time?",
        opts:["Za osam sati navečer, ako je moguće.","Osam sati.","20:00.","Osam."],
        answer:0, tip:"'Ako je moguće' (if possible) is a polite hedge." },
      { speaker:"Recepcionista", line:"Savršeno. Ime i prezime?", en:"Perfect. Name and surname?",
        opts:["[Vaše ime i prezime], molim.","Moje ime je...","Ja sam...","[Ime]."],
        answer:0, tip:"In Croatian, you'd state your full name naturally." },
      { speaker:"Konobar (at restaurant)", line:"Što preporučujete?", en:"What do you recommend?",
        opts:["Što biste Vi preporučili — riba ili meso?","Riba.","Što je dobro?","Preporučite nešto."],
        answer:0, tip:"Turning the question back — 'što BISTE Vi preporučili' — is elegant and social. 📚 See: Conditional Mood (Lesson 7)" },
      { speaker:"Konobar", line:"Naša riba je danas posebno svježa. Dorade imate od lokalne flote.", en:"Our fish is especially fresh today. The sea bream is from the local fleet.",
        opts:["Zvuči odlično! Uzet ću dorade s povrćem.","Ok.","Da.","Dorade."],
        answer:0, tip:"'Zvuči odlično' (sounds excellent) + complete order = perfect response." },
    ]
  },
  {
    id: 'family_gathering',
    title: '🏠 Obiteljski susret',
    subtitle: 'Meet your Croatian partner\'s family for the first time',
    difficulty: 'B1',
    turns: [
      {
        speaker: 'Gospođa Horvat',
        line: 'Dobro došli! Drago mi je što ste konačno došli k nama.',
        en: 'Welcome! I\'m so glad you\'ve finally come to us.',
        opts: [
          'Hvala lijepa! I meni je drago. Lijepo ste uredili.',
          'Hvala. Tvoja kuća je lijepa.',
          'Ja sam sretan što sam ovdje.',
          'Hvala, bok.',
        ],
        answer: 0,
        tip: 'Use "Vi" (formal you) with elders and on first meetings. "Lijepo ste uredili" is the perfect house compliment.',
      },
      {
        speaker: 'Gospođa Horvat',
        line: 'Hoćete li rakiju? Domaća je, od šljiva.',
        en: 'Would you like some rakija? It\'s homemade, from plums.',
        opts: [
          'Hvala lijepa, malo, molim. Čuo sam da je vaša domaća rakija posebna.',
          'Ne, ne volim rakiju.',
          'Da, ja pijem rakiju svaki dan.',
          'Što je rakija?',
        ],
        answer: 0,
        tip: 'Never flatly refuse — "malo, molim" (just a little) is the graceful acceptance.',
      },
      {
        speaker: 'Baka',
        line: 'Probajte ovo! Ja sam to cijeli dan kuhala za vas.',
        en: 'Try this! I cooked it all day for you.',
        opts: [
          'Hvala, izvrsno je! Nikad nisam jeo/jela ovako ukusno.',
          'Hvala, ali nisam gladan/gladna.',
          'Što je ovo?',
          'Ok, probat ću.',
        ],
        answer: 0,
        tip: '"Izvrsno je" (it\'s excellent) said immediately upon tasting is mandatory Croatian table etiquette.',
      },
      {
        speaker: 'Gospodin Horvat',
        line: 'Kako učite naš jezik? Teško je, zar ne?',
        en: 'How are you learning our language? It\'s hard, isn\'t it?',
        opts: [
          'Polako napredujem. Jezik mi je teži nego što sam mislio, ali vrijedi svaki trud.',
          'Da, jako je težak. Možda odustanem.',
          'Nije teško, brzo učim.',
          'Učim malo svaki dan na telefonu.',
        ],
        answer: 0,
        tip: '"Vrijedi svaki trud" (it\'s worth every effort) shows respect for the language and the family.',
      },
      {
        speaker: 'Tomislav (Anin bratić)',
        line: 'Hej, možemo li prijeći na ti? Vi mi zvuči čudno od nekoga Anine dobi.',
        en: 'Hey, can we switch to "ti"? "Vi" sounds strange from someone Ana\'s age.',
        opts: [
          'Naravno, s veseljem! Hvala što si predložio.',
          'Ne, preferiram Vi.',
          'Nisam razumio/razumjela — možeš li ponoviti?',
          'Sve mi je isto.',
        ],
        answer: 0,
        tip: 'When a Croatian peer explicitly offers to switch to "ti", always accept warmly.',
      },
      {
        speaker: 'Gospodin Horvat',
        line: 'Za zdravlje naših obitelji! Živjeli!',
        en: 'To the health of our families! Cheers!',
        opts: [
          'Živjeli! Za zdravlje i sreću!',
          'Cheers!',
          'Hvala, živjeli.',
          'Ok.',
        ],
        answer: 0,
        tip: 'Always respond to "Živjeli!" with "Živjeli!" — it\'s the universal Croatian toast.',
      },
      {
        speaker: 'Gospođa Horvat',
        line: 'Ostanite na večeru! Imam još toliko hrane.',
        en: 'Stay for dinner! I have so much more food.',
        opts: [
          'Hvala puno na pozivu! Jako smo se lijepo proveli. Vidimo se uskoro!',
          'Ne možemo, idemo kući.',
          'Možda drugi put.',
          'Ok, doviđenja.',
        ],
        answer: 0,
        tip: '"Hvala puno na pozivu" (thank you so much for the invitation) is the essential parting phrase.',
      },
    ],
  },
];
