export const SCENARIOS = [
  {
    id: 'cafe',
    title: '☕ At the Café',
    subtitle: 'Order drinks and pay the bill',
    difficulty: 'A1',
    turns: [
      {
        speaker: 'Konobar',
        line: 'Dobar dan! Što ćete naručiti?',
        en: 'Good day! What would you like to order?',
        opts: ['Mogu li dobiti kavu, molim?', 'Ja hoću kava.', 'Daj mi kavu.', 'Kava!'],
        answer: 0,
        tip: "'Mogu li dobiti...' is the polite way to order. 'Ja hoću...' is too direct/childlike.",
      },
      {
        speaker: 'Konobar',
        line: 'S mlijekom ili bez?',
        en: 'With milk or without?',
        opts: ['S mlijekom, hvala.', 'Ja hoću s mlijekom.', 'Mlijeko da.', 'S mlijeko, hvala.'],
        answer: 0,
        tip: "'S mlijekom' is correct — instrumental case. 📚 See: Instrumental Case (Lesson 4)",
      },
      {
        speaker: 'Konobar',
        line: 'Izvolite. Trebate li još nešto?',
        en: 'Here you go. Do you need anything else?',
        opts: [
          'Molim vas, možete li donijeti i čašu vode?',
          'Ja trebam voda.',
          'Daj vodu.',
          'Ne, bog.',
        ],
        answer: 0,
        tip: "Polite request with 'možete li donijeti' — could you bring. Always use 'molim vas' in formal settings.",
      },
      {
        speaker: 'Konobar',
        line: 'Naravno! Još nešto?',
        en: 'Of course! Anything else?',
        opts: ['Ne, hvala, to je sve.', 'Ništa ne.', 'Nema.', 'Ne hvala.'],
        answer: 0,
        tip: "'To je sve' (that's all) is the natural way to close an order.",
      },
      {
        speaker: 'Konobar',
        line: 'Mogu li vam donijeti račun?',
        en: 'May I bring you the bill?',
        opts: ['Da, molim. Koliko je to?', 'Koliko košta?', 'Daj račun.', 'Da, hvala.'],
        answer: 0,
        tip: "'Koliko je to?' (How much is that?) is more natural than just accepting.",
      },
    ],
  },
  {
    id: 'directions',
    title: '🗺️ Asking for Directions',
    subtitle: 'Find your way around a Croatian city',
    difficulty: 'A1',
    turns: [
      {
        speaker: 'You approach someone',
        line: '[You need to ask where the post office is]',
        en: 'Ask politely for directions',
        opts: ['Oprostite, gdje je pošta?', 'Gdje je pošta?', 'Pošta gdje?', 'Tražim poštu.'],
        answer: 0,
        tip: "'Oprostite' (excuse me) is essential before asking a stranger.",
      },
      {
        speaker: 'Prolaznik',
        line: 'Pošta? Idite ravno, pa skrenite lijevo.',
        en: 'The post office? Go straight, then turn left.',
        opts: ['Hvala lijepa, koliko je daleko?', 'Što?', 'Hvala.', 'Ne razumijem.'],
        answer: 0,
        tip: "Asking 'koliko je daleko?' (how far is it?) shows you're engaged.",
      },
      {
        speaker: 'Prolaznik',
        line: 'Otprilike deset minuta pješice.',
        en: 'About ten minutes on foot.',
        opts: ['Odlično, hvala puno!', 'Dobro.', 'Ok.', 'Hvala.'],
        answer: 0,
        tip: "'Odlično' (excellent) + 'hvala puno' (thank you very much) is warm and natural.",
      },
      {
        speaker: 'Prolaznik',
        line: 'Nema na čemu! Sretno!',
        en: "Don't mention it! Good luck!",
        opts: ['Hvala, i vama!', 'Ok.', 'Bog.', 'Hvala.'],
        answer: 0,
        tip: "'I vama' (to you too) is the standard response to a kind wish.",
      },
    ],
  },
  {
    id: 'doctor',
    title: '🏥 At the Doctor',
    subtitle: 'Describe symptoms and understand advice',
    difficulty: 'A2',
    turns: [
      {
        speaker: 'Doktor',
        line: 'Dobar dan. Što vas muči?',
        en: "Good day. What's bothering you?",
        opts: [
          'Boli me grlo i imam temperaturu.',
          'Ja imam bolestan.',
          'Moj grlo boli.',
          'Temperatura.',
        ],
        answer: 0,
        tip: "'Boli me grlo' (my throat hurts) is the correct Croatian structure. 📚 See: Cases — Accusative (Lesson 4)",
      },
      {
        speaker: 'Doktor',
        line: 'Koliko dugo imate te tegobe?',
        en: 'How long have you had these symptoms?',
        opts: ['Od jučer, oko dva dana.', 'Dva dana.', 'Ja imam ovo dva dana.', 'Jučer.'],
        answer: 0,
        tip: "'Od jučer' (since yesterday) + specific timeframe is natural.",
      },
      {
        speaker: 'Doktor',
        line: 'Imate li kakve alergije na lijekove?',
        en: 'Do you have any allergies to medications?',
        opts: ['Ne, koliko znam, nemam alergija.', 'Ne.', 'Nemam.', 'Ja nemam alergija.'],
        answer: 0,
        tip: "'Koliko znam' (as far as I know) is a natural hedge.",
      },
      {
        speaker: 'Doktor',
        line: 'Prepisat ću vam antibiotike. Uzimajte tri puta dnevno.',
        en: "I'll prescribe antibiotics. Take them three times daily.",
        opts: ['Razumijem. Koliko dana ih trebam uzimati?', 'Ok.', 'Hvala.', 'Razumijem.'],
        answer: 0,
        tip: "Always ask clarifying questions! 'Koliko dana' (how many days) shows you're engaged.",
      },
      {
        speaker: 'Doktor',
        line: 'Sedam dana. I odmarajte se više.',
        en: 'Seven days. And rest more.',
        opts: ['Hoću, hvala doktore. Vidimo se!', 'Ok doktor.', 'Hvala.', 'Vidimo se.'],
        answer: 0,
        tip: "'Vidimo se!' (See you!) is a warm farewell.",
      },
    ],
  },
  {
    id: 'shopping',
    title: '🛍️ Shopping',
    subtitle: 'Buy clothes at a Croatian shop',
    difficulty: 'A2',
    turns: [
      {
        speaker: 'Prodavačica',
        line: 'Mogu li vam pomoći?',
        en: 'Can I help you?',
        opts: ['Samo gledam, hvala.', 'Ne.', 'Da.', 'Tražim majicu.'],
        answer: 0,
        tip: "'Samo gledam' (just browsing) is the universal polite answer.",
      },
      {
        speaker: 'Prodavačica',
        line: '[You found a shirt you like] Imate li ovo u većoj veličini?',
        en: 'Do you have this in a larger size?',
        opts: ['Imate li ovo u većoj veličini?', 'Ja hoću veće.', 'Veće, molim.', 'Ovo je malo.'],
        answer: 0,
        tip: "'Imate li' (do you have) + 'u većoj veličini' (in a larger size) is the full natural question.",
      },
      {
        speaker: 'Prodavačica',
        line: 'Naravno, imate medium i large.',
        en: 'Of course, we have medium and large.',
        opts: ['Mogu li probati medium?', 'Daj mi medium.', 'Medium.', 'Probati?'],
        answer: 0,
        tip: "'Mogu li probati' (may I try on) is polite and natural.",
      },
      {
        speaker: 'Prodavačica',
        line: 'Svlačionica je tamo lijevo.',
        en: 'The fitting room is over there on the left.',
        opts: ['Hvala!', 'Ok.', 'Dobro.', 'Da.'],
        answer: 0,
        tip: "A simple warm 'Hvala!' is perfect here.",
      },
      {
        speaker: 'Prodavačica',
        line: 'Kako vam stoji?',
        en: 'How does it fit you?',
        opts: ['Savršeno! Uzet ću ovo. Gdje se plaća?', 'Dobro.', 'Ok.', 'Stoji mi.'],
        answer: 0,
        tip: "'Savršeno!' (perfectly) + 'uzet ću' (I'll take it) + asking where to pay.",
      },
    ],
  },
  {
    id: 'meeting',
    title: '👋 Meeting Someone New',
    subtitle: 'Introduce yourself at a social event',
    difficulty: 'A1',
    turns: [
      {
        speaker: 'Stranger',
        line: 'Bog! Jesi li ti novi u gradu?',
        en: 'Hi! Are you new to the city?',
        opts: [
          'Da, tek sam se doselio/doselila. Ja sam [ime].',
          'Da, ja sam novi.',
          'Da.',
          'Novi sam.',
        ],
        answer: 0,
        tip: "'Tek sam se doselio' (I just moved here) + introducing yourself is the natural full response.",
      },
      {
        speaker: 'Stranger',
        line: 'Drago mi je! Ja sam Marko. Otkud si?',
        en: "Nice to meet you! I'm Marko. Where are you from?",
        opts: [
          'Drago mi je, Marko! Ja sam iz Engleske, ali učim hrvatski.',
          'Engleska.',
          'Iz Engleske.',
          'Ja sam Englez.',
        ],
        answer: 0,
        tip: "Full response with their name + your origin + showing you're learning Croatian.",
      },
      {
        speaker: 'Marko',
        line: 'Super! Kako ti ide s hrvatskim?',
        en: "Great! How's your Croatian going?",
        opts: [
          'Polako, ali napredujem. Jezik mi je teži nego što sam mislio.',
          'Dobro.',
          'Teško.',
          'Ok, teško.',
        ],
        answer: 0,
        tip: "'Polako, ali napredujem' (slowly but I'm progressing) is honest and shows effort.",
      },
      {
        speaker: 'Marko',
        line: 'Ha! Svima nam je bio težak. Hoćeš još piće?',
        en: 'Ha! It was hard for all of us. Do you want another drink?',
        opts: ['Rado! Hvala puno, Marko.', 'Da.', 'Hoću.', 'Ok.'],
        answer: 0,
        tip: "'Rado!' (gladly/with pleasure) is a warm enthusiastic yes.",
      },
    ],
  },
  {
    id: 'transport',
    title: '🚌 Public Transport',
    subtitle: 'Buy a ticket and find your platform',
    difficulty: 'A2',
    turns: [
      {
        speaker: 'Blagajnica',
        line: 'Izvolite, slušam vas.',
        en: "Yes, I'm listening.",
        opts: [
          'Molim vas jednu kartu za Split, molim.',
          'Jedan karta za Split.',
          'Split karta.',
          'Karta Split.',
        ],
        answer: 0,
        tip: "'Jednu kartu za Split' — accusative 'kartu' (ticket-ACC).",
      },
      {
        speaker: 'Blagajnica',
        line: 'Povratnu ili u jednom smjeru?',
        en: 'Return or one-way?',
        opts: ['U jednom smjeru, molim.', 'Jedan smjer.', 'One way.', 'Samo tamo.'],
        answer: 0,
        tip: "'U jednom smjeru' (one-way) is the Croatian term.",
      },
      {
        speaker: 'Blagajnica',
        line: 'To je sto dvadeset kuna... pardon, eura.',
        en: "That's 120 euros.",
        opts: ['Izvolite. S kojeg perona polazi vlak?', 'Hvala.', 'Ok.', 'Peron?'],
        answer: 0,
        tip: "'S kojeg perona' (from which platform) — genitive after 's'.",
      },
      {
        speaker: 'Blagajnica',
        line: 'S petog perona, polazi u 14:30.',
        en: 'From platform 5, it departs at 14:30.',
        opts: ['Hvala lijepa! Imate li neku kavu dok čekam?', 'Hvala.', 'Ok.', 'Razumijem.'],
        answer: 0,
        tip: 'All options are grammatically acceptable here.',
      },
    ],
  },
  {
    id: 'emergency',
    title: '🚨 Emergency',
    subtitle: 'Handle an urgent situation in Croatian',
    difficulty: 'A2',
    turns: [
      {
        speaker: '(You need to call for help)',
        line: '[You see someone fall and need help]',
        en: 'Call for help urgently',
        opts: ['Pomoć! Zovite hitnu pomoć, molim!', 'Pomoć!', 'Hitna pomoć!', 'Help!'],
        answer: 0,
        tip: 'Full clear sentence gives bystanders all the information.',
      },
      {
        speaker: 'Prolaznik',
        line: 'Što se dogodilo?',
        en: 'What happened?',
        opts: ['Čovjek je pao i ne reagira. Zovite 112!', 'Pao je.', 'Hitna pomoć.', 'Ne znam.'],
        answer: 0,
        tip: "Clear description + '112' (Croatian emergency number). Be specific in emergencies!",
      },
      {
        speaker: 'Dispečer (112)',
        line: 'Koji je vaš položaj?',
        en: 'What is your location?',
        opts: ['Nalazimo se na Trgu bana Jelačića, ispred fontane.', 'Trg.', 'Centar.', 'Ovdje.'],
        answer: 0,
        tip: 'Specific landmark + position is critical.',
      },
      {
        speaker: 'Dispečer',
        line: 'Hitna pomoć dolazi. Je li osoba svjesna?',
        en: 'Ambulance is coming. Is the person conscious?',
        opts: ['Čini se da nije. Disanje je nepravilno.', 'Ne.', 'Nesvjestan.', 'Ne znam.'],
        answer: 0,
        tip: 'Providing breathing information is crucial medical data.',
      },
    ],
  },
  {
    id: 'pharmacy',
    title: '💊 At the Pharmacy',
    subtitle: 'Get medication for a headache in Split',
    difficulty: 'A2',
    turns: [
      {
        speaker: 'Ljekarnica Ana',
        line: 'Dobar dan! Mogu li vam pomoći?',
        en: 'Good day! Can I help you?',
        opts: [
          'Dobar dan! Imate li nešto za glavobolju?',
          'Ja imam glavobolja.',
          'Hoću lijek za glava.',
          'Glavobolja.',
        ],
        answer: 0,
        tip: "'Imate li nešto za glavobolju?' — correct accusative 'glavobolju' after 'za'.",
      },
      {
        speaker: 'Ljekarnica Ana',
        line: 'Imate li recept, ili vam treba nešto bez recepta?',
        en: 'Do you have a prescription, or do you need something over the counter?',
        opts: [
          'Nemam recept. Trebam nešto bez recepta, molim.',
          'Ja nemam recept.',
          'Ne imam recept.',
          'Bez recept.',
        ],
        answer: 0,
        tip: "'Nemam recept' + 'trebam nešto bez recepta' is a complete natural response.",
      },
      {
        speaker: 'Ljekarnica Ana',
        line: 'U redu. Preporučujem ibuprofen ili aspirin. Koji preferirate?',
        en: 'Alright. I recommend ibuprofen or aspirin. Which do you prefer?',
        opts: [
          'Ibuprofen, molim. Koliko tableta trebam uzimati i kako često?',
          'Ibuprofen.',
          'Dajte mi ibuprofen.',
          'Hoću ibuprofen.',
        ],
        answer: 0,
        tip: "Asking 'koliko tableta... i kako često?' shows competence and gets dosage info.",
      },
      {
        speaker: 'Ljekarnica Ana',
        line: 'Jednu do dvije tablete, svaka četiri do šest sati. Ne više od šest tableta dnevno.',
        en: 'One to two tablets every four to six hours. No more than six tablets per day.',
        opts: [
          'Razumijem, hvala. Smiju li se uzimati na prazan želudac?',
          'Ok.',
          'Razumijem.',
          'Hvala, gotovo.',
        ],
        answer: 0,
        tip: "'Smiju li se uzimati na prazan želudac?' is a practical follow-up question.",
      },
      {
        speaker: 'Ljekarnica Ana',
        line: 'Bolje s hranom ili mlijekom. Ima li još nešto?',
        en: 'Better with food or milk. Is there anything else?',
        opts: ['Hvala lijepa. Koliko to košta?', 'Koliko košta?', 'Što košta?', 'Cijena?'],
        answer: 0,
        tip: "'Hvala lijepa' before asking the price is polite.",
      },
      {
        speaker: 'Ljekarnica Ana',
        line: 'Deset eura, molim. Evo vam račun.',
        en: 'Ten euros, please. Here is your receipt.',
        opts: ['Izvolite, hvala lijepa! Ugodan dan!', 'Hvala.', 'Ok, bog.', 'Bog.'],
        answer: 0,
        tip: "'Izvolite' + 'hvala lijepa' + 'Ugodan dan!' is the complete warm leave-taking.",
      },
    ],
  },
  {
    id: 'restaurant',
    title: '🍽️ Restaurant Reservation',
    subtitle: 'Make a reservation and order a meal',
    difficulty: 'B1',
    turns: [
      {
        speaker: 'Recepcionista',
        line: "Dobra večer, restoran 'Dubrovnik', izvolite.",
        en: "Good evening, restaurant 'Dubrovnik', how can I help?",
        opts: [
          'Dobra večer. Htjela bih rezervirati stol za dvoje za petak navečer.',
          'Rezervacija.',
          'Htjeti stol.',
          'Stol za dvoje.',
        ],
        answer: 0,
        tip: "'Htjela bih' (I would like — conditional, feminine) is perfectly polite.",
      },
      {
        speaker: 'Recepcionista',
        line: 'Za koliko sati?',
        en: 'For what time?',
        opts: ['Za osam sati navečer, ako je moguće.', 'Osam sati.', '20:00.', 'Osam.'],
        answer: 0,
        tip: "'Ako je moguće' (if possible) is a polite hedge.",
      },
      {
        speaker: 'Recepcionista',
        line: 'Savršeno. Ime i prezime?',
        en: 'Perfect. Name and surname?',
        opts: ['[Vaše ime i prezime], molim.', 'Moje ime je...', 'Ja sam...', '[Ime].'],
        answer: 0,
        tip: "In Croatian, you'd state your full name naturally.",
      },
      {
        speaker: 'Konobar (at restaurant)',
        line: 'Što preporučujete?',
        en: 'What do you recommend?',
        opts: [
          'Što biste Vi preporučili — riba ili meso?',
          'Riba.',
          'Što je dobro?',
          'Preporučite nešto.',
        ],
        answer: 0,
        tip: "Turning the question back — 'što BISTE Vi preporučili' — is elegant and social. 📚 See: Conditional Mood (Lesson 7)",
      },
      {
        speaker: 'Konobar',
        line: 'Naša riba je danas posebno svježa. Dorade imate od lokalne flote.',
        en: 'Our fish is especially fresh today. The sea bream is from the local fleet.',
        opts: ['Zvuči odlično! Uzet ću dorade s povrćem.', 'Ok.', 'Da.', 'Dorade.'],
        answer: 0,
        tip: "'Zvuči odlično' (sounds excellent) + complete order = perfect response.",
      },
    ],
  },
  {
    id: 'family_gathering',
    title: '🏠 Obiteljski susret',
    subtitle: "Meet your Croatian partner's family for the first time",
    difficulty: 'B1',
    turns: [
      {
        speaker: 'Gospođa Horvat',
        line: 'Dobro došli! Drago mi je što ste konačno došli k nama.',
        en: "Welcome! I'm so glad you've finally come to us.",
        opts: [
          'Hvala lijepa! I meni je drago. Lijepo ste uredili.',
          'Hvala. Tvoja kuća je lijepa.',
          'Ja sam sretan što sam ovdje.',
          'Hvala, bog.',
        ],
        answer: 0,
        tip: 'Use "Vi" (formal you) with elders and on first meetings. "Lijepo ste uredili" is the perfect house compliment.',
      },
      {
        speaker: 'Gospođa Horvat',
        line: 'Hoćete li rakiju? Domaća je, od šljiva.',
        en: "Would you like some rakija? It's homemade, from plums.",
        opts: [
          'Hvala lijepa, malo, molim. Čuo sam da je vaša domaća rakija posebna.',
          'Ne, ne volim rakiju.',
          'Da, ja pijem rakiju svaki dan.',
          'Što je rakija?',
        ],
        answer: 0,
        tip: 'Never flatly refuse — "malo, molim" (just a little) is the graceful acceptance.',
      },
      {
        speaker: 'Baka',
        line: 'Probajte ovo! Ja sam to cijeli dan kuhala za vas.',
        en: 'Try this! I cooked it all day for you.',
        opts: [
          'Hvala, izvrsno je! Nikad nisam jeo/jela ovako ukusno.',
          'Hvala, ali nisam gladan/gladna.',
          'Što je ovo?',
          'Ok, probat ću.',
        ],
        answer: 0,
        tip: '"Izvrsno je" (it\'s excellent) said immediately upon tasting is mandatory Croatian table etiquette.',
      },
      {
        speaker: 'Gospodin Horvat',
        line: 'Kako učite naš jezik? Teško je, zar ne?',
        en: "How are you learning our language? It's hard, isn't it?",
        opts: [
          'Polako napredujem. Jezik mi je teži nego što sam mislio, ali vrijedi svaki trud.',
          'Da, jako je težak. Možda odustanem.',
          'Nije teško, brzo učim.',
          'Učim malo svaki dan na telefonu.',
        ],
        answer: 0,
        tip: '"Vrijedi svaki trud" (it\'s worth every effort) shows respect for the language and the family.',
      },
      {
        speaker: 'Tomislav (Anin bratić)',
        line: 'Hej, možemo li prijeći na ti? Vi mi zvuči čudno od nekoga Anine dobi.',
        en: 'Hey, can we switch to "ti"? "Vi" sounds strange from someone Ana\'s age.',
        opts: [
          'Naravno, s veseljem! Hvala što si predložio.',
          'Ne, preferiram Vi.',
          'Nisam razumio/razumjela — možeš li ponoviti?',
          'Sve mi je isto.',
        ],
        answer: 0,
        tip: 'When a Croatian peer explicitly offers to switch to "ti", always accept warmly.',
      },
      {
        speaker: 'Gospodin Horvat',
        line: 'Za zdravlje naših obitelji! Živjeli!',
        en: 'To the health of our families! Cheers!',
        opts: ['Živjeli! Za zdravlje i sreću!', 'Cheers!', 'Hvala, živjeli.', 'Ok.'],
        answer: 0,
        tip: 'Always respond to "Živjeli!" with "Živjeli!" — it\'s the universal Croatian toast.',
      },
      {
        speaker: 'Gospođa Horvat',
        line: 'Ostanite na večeru! Imam još toliko hrane.',
        en: 'Stay for dinner! I have so much more food.',
        opts: [
          'Hvala puno na pozivu! Jako smo se lijepo proveli. Vidimo se uskoro!',
          'Ne možemo, idemo kući.',
          'Možda drugi put.',
          'Ok, doviđenja.',
        ],
        answer: 0,
        tip: '"Hvala puno na pozivu" (thank you so much for the invitation) is the essential parting phrase.',
      },
    ],
  },
  // ── 2026-07 expansion: 12 new scenarios (4×A1, 3×A2, 3×B1, 2×B2) ──────────
  {
    id: 'bakery',
    title: '🥐 At the Bakery',
    subtitle: 'Buy bread and burek for breakfast',
    difficulty: 'A1',
    turns: [
      {
        speaker: 'Prodavačica',
        line: 'Dobro jutro! Izvolite?',
        en: 'Good morning! What can I get you?',
        opts: [
          'Dobro jutro! Jedan burek sa sirom, molim vas.',
          'Daj mi burek.',
          'Hoću burek sa sir.',
          'Burek!',
        ],
        answer: 0,
        tip: "'Sa sirom' — instrumental case after 'sa'. Greet back before ordering; it's expected in small shops.",
      },
      {
        speaker: 'Prodavačica',
        line: 'Sa sirom ili s mesom?',
        en: 'With cheese or with meat?',
        opts: ['Sa sirom, molim.', 'S sirom, molim.', 'Sir.', 'Meso ne.'],
        answer: 0,
        tip: "'Sa' (not 's') is used before words starting with s, š, z, ž — 'sa sirom', never 's sirom'.",
      },
      {
        speaker: 'Prodavačica',
        line: 'Želite li još nešto?',
        en: 'Would you like anything else?',
        opts: ['Da, i jedan kruh, molim.', 'Daj kruh.', 'Još kruh.', 'Ne, kruh.'],
        answer: 0,
        tip: "'Jedan kruh' (one bread) is how Croatians say 'a loaf of bread' — no extra word needed.",
      },
      {
        speaker: 'Prodavačica',
        line: 'Izvolite. To je četiri eura i pedeset centi.',
        en: "Here you go. That's four euros and fifty cents.",
        opts: ['Izvolite, hvala lijepa!', 'Evo.', 'Skupo!', 'Ok.'],
        answer: 0,
        tip: "'Izvolite' works both directions — 'here you go' when handing money AND when receiving goods.",
      },
      {
        speaker: 'Prodavačica',
        line: 'Hvala vama! Ugodan dan!',
        en: 'Thank YOU! Have a pleasant day!',
        opts: ['Hvala, također!', 'Bog.', 'Da.', 'Isto.'],
        answer: 0,
        tip: "'Također' (likewise) is the natural response to 'ugodan dan' — short, warm, correct.",
      },
    ],
  },
  {
    id: 'market',
    title: '🍅 At the Market',
    subtitle: 'Buy fruit and vegetables at the open-air tržnica',
    difficulty: 'A1',
    turns: [
      {
        speaker: 'Prodavač',
        line: 'Dobar dan! Što trebate?',
        en: 'Good day! What do you need?',
        opts: [
          'Dobar dan! Koliko koštaju rajčice?',
          'Rajčice cijena?',
          'Koliko rajčica?',
          'Daj rajčice.',
        ],
        answer: 0,
        tip: "'Koliko košta?' for one thing, 'koliko koštaju?' for plural — tomatoes are plural here.",
      },
      {
        speaker: 'Prodavač',
        line: 'Tri eura za kilogram. Svježe su, jutros ubrane!',
        en: 'Three euros per kilogram. They are fresh, picked this morning!',
        opts: [
          'Odlično, dajte mi kilogram, molim vas.',
          'Daj kilogram.',
          'Jedan kilogram rajčica hoću.',
          'Kupujem.',
        ],
        answer: 0,
        tip: "'Dajte mi... molim vas' — the polite imperative. Note genitive plural 'rajčica' after a quantity.",
      },
      {
        speaker: 'Prodavač',
        line: 'Izvolite. Trebate li još voća ili povrća?',
        en: 'Here you go. Do you need more fruit or vegetables?',
        opts: [
          'Da, pola kile krumpira, molim.',
          'Krumpir pola.',
          'Pola kilogram krumpir.',
          'Da, krumpire.',
        ],
        answer: 0,
        tip: "Quantities take the genitive: 'pola kile krumpira' (half a kilo OF potatoes). 📚 See: Genitive Case",
      },
      {
        speaker: 'Prodavač',
        line: 'Evo, izvolite. Još nešto?',
        en: 'There you are. Anything else?',
        opts: ['Ne, hvala, to je sve. Koliko je ukupno?', 'Gotovo.', 'Ne.', 'Plaćam.'],
        answer: 0,
        tip: "'Koliko je ukupno?' (how much in total?) — the phrase that closes every market purchase.",
      },
      {
        speaker: 'Prodavač',
        line: 'Pet eura ukupno. Hvala vam i dođite opet!',
        en: 'Five euros total. Thank you and come again!',
        opts: ['Hvala vama! Doviđenja!', 'Evo pet.', 'Bog!', 'Ok, idem.'],
        answer: 0,
        tip: "'Hvala vama' (thank YOU) returns the thanks with emphasis — market sellers love a warm goodbye.",
      },
    ],
  },
  {
    id: 'hotel',
    title: '🏨 Hotel Check-in',
    subtitle: 'Check into your hotel on the coast',
    difficulty: 'A1',
    turns: [
      {
        speaker: 'Recepcionar',
        line: 'Dobra večer! Kako vam mogu pomoći?',
        en: 'Good evening! How can I help you?',
        opts: [
          'Dobra večer! Imam rezervaciju na ime Marić.',
          'Ja sam rezervacija.',
          'Rezervacija Marić!',
          'Trebam sobu.',
        ],
        answer: 0,
        tip: "'Na ime...' (under the name...) is the standard check-in phrase.",
      },
      {
        speaker: 'Recepcionar',
        line: 'Samo trenutak... Da, soba s pogledom na more, tri noći?',
        en: 'One moment... Yes, a room with a sea view, three nights?',
        opts: ['Tako je, s pogledom na more.', 'Da, more soba.', 'Tri noć, da.', 'Aha.'],
        answer: 0,
        tip: "'Tako je' — that's right. 'S pogledom na more' uses the instrumental: with a view of the sea.",
      },
      {
        speaker: 'Recepcionar',
        line: 'Mogu li dobiti vašu putovnicu, molim?',
        en: 'May I have your passport, please?',
        opts: ['Naravno, izvolite.', 'Zašto?', 'Evo ti.', 'Putovnica je u torbi.'],
        answer: 0,
        tip: "'Izvolite' when handing something over. 'Evo ti' is too informal for a hotel desk.",
      },
      {
        speaker: 'Recepcionar',
        line: 'Doručak je od sedam do deset. Evo vašeg ključa — soba 204.',
        en: 'Breakfast is from seven to ten. Here is your key — room 204.',
        opts: ['Hvala! Ima li hotel Wi-Fi?', 'Wi-Fi?', 'Gdje je 204?', 'Dobro.'],
        answer: 0,
        tip: "'Ima li...?' (is there...?) — the universal availability question.",
      },
      {
        speaker: 'Recepcionar',
        line: 'Naravno, besplatan je. Lozinka je u sobi. Ugodan boravak!',
        en: 'Of course, it is free. The password is in the room. Pleasant stay!',
        opts: ['Hvala lijepa, laku noć!', 'Bog.', 'Ok.', 'Noć.'],
        answer: 0,
        tip: "'Laku noć' fits the evening arrival; answer a kind wish with warmth, not just 'ok'.",
      },
    ],
  },
  {
    id: 'taxi',
    title: '🚕 In the Taxi',
    subtitle: 'Take a taxi and chat with the driver',
    difficulty: 'A1',
    turns: [
      {
        speaker: 'Taksist',
        line: 'Dobar dan! Kamo idemo?',
        en: 'Good day! Where are we going?',
        opts: [
          'Dobar dan! Na glavni kolodvor, molim.',
          'Kolodvor.',
          'Idem kolodvor.',
          'Vozite brzo!',
        ],
        answer: 0,
        tip: "'Kamo' asks about direction. Destination takes 'na' + accusative: 'na glavni kolodvor'.",
      },
      {
        speaker: 'Taksist',
        line: 'U redu. Jeste li prvi put u Zagrebu?',
        en: 'All right. Is this your first time in Zagreb?',
        opts: ['Da, prvi put. Grad je prekrasan!', 'Da.', 'Ne znam.', 'Prvi put, da, Zagreb.'],
        answer: 0,
        tip: "'U Zagrebu' — locative for location. Taxi small talk is a free speaking lesson; engage!",
      },
      {
        speaker: 'Taksist',
        line: 'Odakle ste?',
        en: 'Where are you from?',
        opts: [
          'Iz Amerike, ali moja obitelj je iz Hrvatske.',
          'Amerika.',
          'Od Amerike.',
          'Ja Amerika.',
        ],
        answer: 0,
        tip: "Origin uses 'iz' + genitive: 'iz Amerike', 'iz Hrvatske'. 📚 See: Genitive Case",
      },
      {
        speaker: 'Taksist',
        line: 'Ah, povratnik! Evo nas — glavni kolodvor. Sedam eura.',
        en: 'Ah, a returnee! Here we are — the main station. Seven euros.',
        opts: ['Izvolite deset — zadržite ostatak.', 'Evo.', 'Skupo je!', 'Deset, vrati tri.'],
        answer: 0,
        tip: "'Zadržite ostatak' (keep the change) — the polite imperative 'zadržite' for strangers.",
      },
      {
        speaker: 'Taksist',
        line: 'Hvala lijepa! Sretan put!',
        en: 'Thank you kindly! Safe travels!',
        opts: ['Hvala, doviđenja!', 'Bog!', 'Da.', 'Idem.'],
        answer: 0,
        tip: "'Sretan put' — safe travels. A simple 'hvala, doviđenja' closes it perfectly.",
      },
    ],
  },
  {
    id: 'post_office',
    title: '📮 At the Post Office',
    subtitle: 'Send a package to relatives abroad',
    difficulty: 'A2',
    turns: [
      {
        speaker: 'Službenica',
        line: 'Izvolite?',
        en: 'Yes, please?',
        opts: [
          'Dobar dan! Htio bih poslati paket u Njemačku.',
          'Paket. Njemačka.',
          'Šaljem ovo.',
          'Trebam marke za paket u Njemačku poslati.',
        ],
        answer: 0,
        tip: "'Htio bih' (m.) / 'htjela bih' (f.) — the conditional makes requests polite. Destination: 'u' + accusative.",
      },
      {
        speaker: 'Službenica',
        line: 'Stavite ga na vagu, molim... Dva kilograma. Obično ili preporučeno?',
        en: 'Put it on the scale, please... Two kilograms. Regular or registered?',
        opts: [
          'Preporučeno, molim vas. Kada će stići?',
          'Obično jer jeftino.',
          'Šta je razlika?',
          'Brzo neka bude.',
        ],
        answer: 0,
        tip: "'Preporučeno' — registered mail. 'Kada će stići?' uses the future of 'stići' (to arrive).",
      },
      {
        speaker: 'Službenica',
        line: 'Za tri do pet radnih dana. Ispunite ovaj obrazac, molim.',
        en: 'In three to five working days. Fill out this form, please.',
        opts: [
          'Može. Trebam li ovdje napisati adresu primatelja?',
          'Ne volim obrasce.',
          'Vi napišite.',
          'Što je obrazac?',
        ],
        answer: 0,
        tip: "'Primatelj' — recipient; genitive 'primatelja' after 'adresu'. Forms are a fact of Croatian life.",
      },
      {
        speaker: 'Službenica',
        line: 'Da, tu. I vašu adresu dolje. To je dvanaest eura.',
        en: "Yes, there. And your address below. That's twelve euros.",
        opts: ['Izvolite. Mogu li dobiti račun?', 'Evo novca.', 'Skupo!', 'Račun.'],
        answer: 0,
        tip: "'Mogu li dobiti račun?' — always ask for the receipt when shipping; you may need the tracking number.",
      },
      {
        speaker: 'Službenica',
        line: 'Naravno. Paket će stići do petka. Doviđenja!',
        en: 'Of course. The package will arrive by Friday. Goodbye!',
        opts: ['Hvala na pomoći! Doviđenja!', 'Bog.', 'Ok.', 'Nadam se.'],
        answer: 0,
        tip: "'Hvala na' takes the locative: 'hvala na pomoći' (thanks for the help).",
      },
    ],
  },
  {
    id: 'hairdresser',
    title: '💇 At the Hairdresser',
    subtitle: 'Get a haircut and describe what you want',
    difficulty: 'A2',
    turns: [
      {
        speaker: 'Frizerka',
        line: 'Dobar dan! Imate li termin?',
        en: 'Good day! Do you have an appointment?',
        opts: [
          'Dobar dan! Nemam, ali možete li me primiti danas?',
          'Ne. Šišajte me.',
          'Termin ne treba.',
          'Imam kosu.',
        ],
        answer: 0,
        tip: "'Termin' — appointment. 'Možete li me primiti?' (can you fit me in?) is the polite walk-in ask.",
      },
      {
        speaker: 'Frizerka',
        line: 'Imamo slobodno za pola sata. Što želite?',
        en: 'We have an opening in half an hour. What would you like?',
        opts: [
          'Samo šišanje, molim — kraće sa strane, malo dulje gore.',
          'Kratko sve.',
          'Ne znam, vi odlučite sve.',
          'Šišaj.',
        ],
        answer: 0,
        tip: "Comparatives do the work: 'kraće' (shorter), 'dulje' (longer). Precision prevents surprises.",
      },
      {
        speaker: 'Frizerka',
        line: 'U redu. Želite li i pranje kose?',
        en: 'All right. Would you like a wash as well?',
        opts: [
          'Da, može pranje, hvala.',
          'Kosa je čista.',
          'Ne treba, oprao sam se.',
          'Pranje da.',
        ],
        answer: 0,
        tip: "'Može' — the wonderfully Croatian casual 'sure, OK'. You'll hear it everywhere.",
      },
      {
        speaker: 'Frizerka',
        line: 'Gotovi smo! Kako vam se čini?',
        en: "We're done! How does it look to you?",
        opts: [
          'Odlično izgleda, baš kako sam htio. Hvala!',
          'Može.',
          'Vidjet ću doma.',
          'Kratko je.',
        ],
        answer: 0,
        tip: "'Kako vam se čini?' — how does it seem to you? 'Baš kako sam htio/htjela' — exactly how I wanted.",
      },
      {
        speaker: 'Frizerka',
        line: 'Drago mi je! To je petnaest eura.',
        en: "I'm glad! That's fifteen euros.",
        opts: ['Izvolite. Hvala vam puno, vidimo se opet!', 'Evo.', 'Skupo za kosu.', 'Bog.'],
        answer: 0,
        tip: "'Vidimo se opet' (see you again) — the phrase that makes you a regular.",
      },
    ],
  },
  {
    id: 'apartment',
    title: '🏖️ Renting an Apartment',
    subtitle: 'Book a summer apartman on the coast by phone',
    difficulty: 'A2',
    turns: [
      {
        speaker: 'Vlasnica',
        line: 'Halo, izvolite?',
        en: 'Hello, yes?',
        opts: [
          'Dobar dan! Zovem zbog apartmana. Je li slobodan u kolovozu?',
          'Apartman?',
          'Trebam apartman odmah.',
          'Koliko košta apartman vaš?',
        ],
        answer: 0,
        tip: "'Zovem zbog' + genitive — I'm calling about. Months take the locative: 'u kolovozu' (in August).",
      },
      {
        speaker: 'Vlasnica',
        line: 'Slobodan je od prvog do petnaestog kolovoza. Koliko vas dolazi?',
        en: 'It is free from the 1st to the 15th of August. How many of you are coming?',
        opts: [
          'Nas četvero — dvoje odraslih i dvoje djece.',
          'Četiri ljudi.',
          'Mi smo četiri.',
          'Puno nas.',
        ],
        answer: 0,
        tip: "Mixed groups use collective numerals: 'nas četvero', 'dvoje djece'. 📚 See: Numbers & Counting",
      },
      {
        speaker: 'Vlasnica',
        line: 'Imamo dvije spavaće sobe i pogled na more. Osamdeset eura po noći.',
        en: 'We have two bedrooms and a sea view. Eighty euros per night.',
        opts: [
          'Zvuči dobro. Je li parking uključen u cijenu?',
          'Skupo.',
          'Osamdeset? Hm.',
          'Gdje parkiram auto ja?',
        ],
        answer: 0,
        tip: "'Uključen u cijenu' — included in the price. Ask before you book, not after you arrive.",
      },
      {
        speaker: 'Vlasnica',
        line: 'Da, parking je besplatan. Želite li rezervirati?',
        en: 'Yes, parking is free. Would you like to book?',
        opts: [
          'Da, rezervirao bih od prvog do osmog kolovoza.',
          'Da, dolazimo kad stignemo.',
          'Rezerviram možda.',
          'Da. Osam dana. Dolazim.',
        ],
        answer: 0,
        tip: "'Rezervirao/rezervirala bih' — conditional again for politeness. Dates take the genitive.",
      },
      {
        speaker: 'Vlasnica',
        line: 'Odlično! Pošaljite mi ime i broj telefona porukom.',
        en: 'Excellent! Send me your name and phone number by message.',
        opts: [
          'Može, odmah šaljem. Hvala vam i vidimo se u kolovozu!',
          'Ok.',
          'Poslat ću nekad.',
          'Vidimo se.',
        ],
        answer: 0,
        tip: "'Porukom' — instrumental for the means: by message. Confirm details in writing, always.",
      },
    ],
  },
  {
    id: 'phone_appointment',
    title: '📞 Calling the Dentist',
    subtitle: 'Schedule an appointment over the phone',
    difficulty: 'B1',
    turns: [
      {
        speaker: 'Sestra',
        line: 'Ordinacija doktora Kovača, izvolite.',
        en: "Doctor Kovač's office, how can I help?",
        opts: [
          'Dobar dan! Htio bih se naručiti na pregled — boli me zub već tri dana.',
          'Trebam doktora odmah.',
          'Htio bih naručiti se na pregled.',
          'Zub boli, dajte termin.',
        ],
        answer: 0,
        tip: "Clitic order! 'Htio bih se naručiti' — 'bih se' clusters in second position, never 'naručiti se' at the end.",
      },
      {
        speaker: 'Sestra',
        line: 'Naravno. Kada vam odgovara?',
        en: 'Of course. When suits you?',
        opts: [
          'Što prije, ako je moguće. Imate li što sutra ujutro?',
          'Odmah!',
          'Kad god.',
          'Sutra dođem u osam.',
        ],
        answer: 0,
        tip: "'Što prije' — as soon as possible. 'Kada vam odgovara?' is the standard scheduling question; learn both sides.",
      },
      {
        speaker: 'Sestra',
        line: 'Sutra u devet i trideset kod doktorice Marić. Odgovara li vam?',
        en: 'Tomorrow at nine thirty with Doctor Marić. Does that work for you?',
        opts: [
          'Odgovara mi savršeno. Trebam li ponijeti zdravstvenu iskaznicu?',
          'Da.',
          'Devet i trideset, dolazim.',
          'Doktorica? Htio sam doktora.',
        ],
        answer: 0,
        tip: "'Ponijeti' — to bring along. 'Zdravstvena iskaznica' — the health card you'll need at every Croatian clinic.",
      },
      {
        speaker: 'Sestra',
        line: 'Da, iskaznicu i osobnu. Na koje ime?',
        en: 'Yes, the health card and your ID. Under what name?',
        opts: ['Na ime Ivan Marić. M-A-R-I-Ć.', 'Ivan.', 'Marić, znate već.', 'Moje ime.'],
        answer: 0,
        tip: 'Spell your surname on the phone — Croatian bureaucracy runs on exact names, diacritics included.',
      },
      {
        speaker: 'Sestra',
        line: 'Zapisano. Vidimo se sutra u devet i trideset. Doviđenja!',
        en: 'Noted. See you tomorrow at nine thirty. Goodbye!',
        opts: ['Puno vam hvala na brzom terminu. Doviđenja!', 'Bog.', 'Ok, doviđenja.', 'Hvala.'],
        answer: 0,
        tip: "'Hvala na brzom terminu' — 'hvala na' + locative. Thanking for the quick slot is good phone manners.",
      },
    ],
  },
  {
    id: 'complaint',
    title: '📦 Returning a Purchase',
    subtitle: 'Return a faulty item — politely but firmly',
    difficulty: 'B1',
    turns: [
      {
        speaker: 'Prodavač',
        line: 'Dobar dan, kako vam mogu pomoći?',
        en: 'Good day, how can I help you?',
        opts: [
          'Dobar dan. Jučer sam kupio ovaj aparat, ali nažalost ne radi.',
          'Ovo ne radi, vratite novac!',
          'Aparat pokvaren.',
          'Imate loše proizvode.',
        ],
        answer: 0,
        tip: "'Nažalost' (unfortunately) softens a complaint. State the facts calmly — it gets better results.",
      },
      {
        speaker: 'Prodavač',
        line: 'Žao mi je. Imate li račun?',
        en: "I'm sorry. Do you have the receipt?",
        opts: [
          'Imam, izvolite. Htio bih zamjenu ili povrat novca.',
          'Račun? Zašto?',
          'Negdje je.',
          'Novac natrag odmah.',
        ],
        answer: 0,
        tip: "Know both remedies: 'zamjena' (exchange) and 'povrat novca' (refund). Name what you want.",
      },
      {
        speaker: 'Prodavač',
        line: 'Moramo prvo provjeriti uređaj. Možete li doći sutra?',
        en: 'We have to check the device first. Can you come tomorrow?',
        opts: [
          'Razumijem, ali sutra radim. Postoji li brže rješenje?',
          'Ne! Danas!',
          'Sutra ne mogu pa vi vidite.',
          'Uvijek komplikacije.',
        ],
        answer: 0,
        tip: "'Postoji li brže rješenje?' — polite pushback. Acknowledge, then ask for the alternative.",
      },
      {
        speaker: 'Prodavač',
        line: 'Mogu vam odmah dati zamjenski uređaj, ako želite.',
        en: 'I can give you a replacement device right away, if you like.',
        opts: ['To bi bilo odlično — hvala vam na susretljivosti.', 'Napokon.', 'Može.', 'Dajte.'],
        answer: 0,
        tip: "'Susretljivost' — helpfulness. 'To bi bilo odlično' uses the conditional to accept graciously.",
      },
      {
        speaker: 'Prodavač',
        line: 'Izvolite novi uređaj i ispriku kuće.',
        en: 'Here is a new device, with the house’s apologies.',
        opts: [
          'Hvala vam! Cijenim brzu uslugu unatoč problemu.',
          'Nadam se da ovaj radi.',
          'Doviđenja.',
          'Konačno gotovo.',
        ],
        answer: 0,
        tip: "'Unatoč' takes the dative: 'unatoč problemu' (despite the problem). 📚 See: Dative Case",
      },
    ],
  },
  {
    id: 'job_interview',
    title: '💼 Job Interview',
    subtitle: 'Interview for a seasonal café job',
    difficulty: 'B1',
    turns: [
      {
        speaker: 'Voditeljica',
        line: 'Dobar dan, sjednite. Recite mi nešto o sebi.',
        en: 'Good day, have a seat. Tell me something about yourself.',
        opts: [
          'Dobar dan, hvala. Zovem se Ana, studiram turizam i tečno govorim engleski i njemački.',
          'Ja sam Ana. Trebam posao.',
          'Što vas zanima?',
          'Sve piše u životopisu.',
        ],
        answer: 0,
        tip: "'O sebi' — about oneself (reflexive). Lead with name, study/work, languages: the Croatian interview trio.",
      },
      {
        speaker: 'Voditeljica',
        line: 'Zašto želite raditi baš u našem kafiću?',
        en: 'Why do you want to work in OUR café specifically?',
        opts: [
          'Volim rad s ljudima, a vaš kafić ima izvrsnu reputaciju u gradu.',
          'Trebam novac.',
          'Blizu mi je.',
          'Svejedno gdje radim.',
        ],
        answer: 0,
        tip: "'Rad s ljudima' — instrumental after 's'. 'Baš' adds emphasis: why THIS café.",
      },
      {
        speaker: 'Voditeljica',
        line: 'Imate li iskustva u ugostiteljstvu?',
        en: 'Do you have experience in hospitality?',
        opts: [
          'Imam — radila sam dvije sezone kao konobarica u Splitu.',
          'Nemam, ali brzo učim valjda.',
          'Malo.',
          'Radila sam nešto slično nekad negdje.',
        ],
        answer: 0,
        tip: "'Iskustva' — partitive genitive after 'imati'. 'Ugostiteljstvo' — the hospitality industry; a must-know word on the coast.",
      },
      {
        speaker: 'Voditeljica',
        line: 'Možete li raditi vikendom i navečer?',
        en: 'Can you work weekends and evenings?',
        opts: [
          'Mogu, fleksibilna sam — vikendi mi ne predstavljaju problem.',
          'Vikendom baš i ne.',
          'Navečer izlazim.',
          'Moram pitati mamu.',
        ],
        answer: 0,
        tip: "'Vikendom', 'navečer' — instrumental/adverb forms for recurring time. Flexibility wins seasonal jobs.",
      },
      {
        speaker: 'Voditeljica',
        line: 'Odlično. Javit ćemo vam se do petka.',
        en: "Excellent. We'll get back to you by Friday.",
        opts: [
          'Hvala vam na razgovoru. Radujem se vašem pozivu!',
          'Znači, dobila sam?',
          'Ok.',
          'Nadam se da ćete zvati.',
        ],
        answer: 0,
        tip: "'Radovati se' takes the dative: 'radujem se vašem pozivu' (I look forward to your call). 📚 See: Dative Case",
      },
    ],
  },
  {
    id: 'bank',
    title: '🏦 Opening a Bank Account',
    subtitle: 'Navigate Croatian bureaucracy in formal register',
    difficulty: 'B2',
    turns: [
      {
        speaker: 'Službenik',
        line: 'Dobar dan. Izvolite?',
        en: 'Good day. How can I help?',
        opts: [
          'Dobar dan. Preselio sam se iz Kanade i htio bih otvoriti tekući račun.',
          'Račun otvorite mi.',
          'Trebam banku.',
          'Dajte mi papire za račun.',
        ],
        answer: 0,
        tip: "'Tekući račun' — checking account. 'Preseliti se iz' + genitive: to move from.",
      },
      {
        speaker: 'Službenik',
        line: 'Dobro došli! Imate li OIB i važeću osobnu iskaznicu ili putovnicu?',
        en: 'Welcome! Do you have an OIB and a valid ID card or passport?',
        opts: [
          'OIB sam već dobio u poreznoj upravi, a evo i putovnice.',
          'Što je OIB?',
          'Imam nešto od toga.',
          'Zar treba toliko papira?',
        ],
        answer: 0,
        tip: 'OIB — osobni identifikacijski broj, issued by the porezna uprava (tax office). The key that unlocks all Croatian bureaucracy.',
      },
      {
        speaker: 'Službenik',
        line: 'Odlično. Želite li i internetsko bankarstvo uz račun?',
        en: 'Excellent. Would you also like internet banking with the account?',
        opts: [
          'Svakako — većinu plaćanja ionako obavljam preko mobitela.',
          'Ne vjerujem internetu.',
          'Može, valjda.',
          'Što god vi kažete.',
        ],
        answer: 0,
        tip: "'Ionako' (anyway/in any case) and 'obavljati plaćanja' (to carry out payments) — natural B2 collocations.",
      },
      {
        speaker: 'Službenik',
        line: 'Naknada za vođenje računa iznosi tri eura mjesečno. Slažete li se s uvjetima?',
        en: 'The account maintenance fee amounts to three euros monthly. Do you agree to the terms?',
        opts: [
          'Slažem se, ali molim vas da mi uvjete pošaljete i na e-mail.',
          'Naknada? Nitko nije spomenuo naknadu!',
          'Potpisujem bilo što.',
          'Tri eura je previše, spustite.',
        ],
        answer: 0,
        tip: "'Naknada' (fee), 'iznositi' (to amount to) — formal register. Always ask for terms in writing.",
      },
      {
        speaker: 'Službenik',
        line: 'Naravno. Potpišite ovdje i ovdje. Kartica stiže poštom za sedam dana.',
        en: 'Of course. Sign here and here. The card arrives by mail in seven days.',
        opts: [
          'Hvala vam na strpljenju i detaljnom objašnjenju. Ugodan dan!',
          'Napokon smo gotovi.',
          'Sedam dana?! Zašto tako dugo?',
          'Ok, bog.',
        ],
        answer: 0,
        tip: "'Hvala na' + locative: 'na strpljenju', 'na detaljnom objašnjenju'. Grace closes bureaucracy best.",
      },
    ],
  },
  {
    id: 'dinner_debate',
    title: '🍷 Dinner Table Debate',
    subtitle: 'Hold your own when the family debates life in Croatia',
    difficulty: 'B2',
    turns: [
      {
        speaker: 'Stric Ante',
        line: 'I, kako ti se čini život ovdje? Bi li se mogao zauvijek vratiti u Hrvatsku?',
        en: 'So, how does life here seem to you? Could you move back to Croatia for good?',
        opts: [
          'Iskreno, razmišljam o tome. Kvaliteta života ovdje me svaki put iznenadi.',
          'Nikad! Plaće su male.',
          'Ne znam.',
          'Možda, vidjet ću, svašta.',
        ],
        answer: 0,
        tip: "'Razmišljati o' + locative — to think about. Engage honestly; the dinner table is Croatia's real debate club.",
      },
      {
        speaker: 'Stric Ante',
        line: 'Ma kakva kvaliteta! Mladi odlaze jer nema posla. Nije li tako i kod vas?',
        en: "What quality! Young people leave because there are no jobs. Isn't it the same where you live?",
        opts: [
          'Ima istine u tome, ali čini mi se da se stvari polako mijenjaju na bolje.',
          'Nemaš pojma, striče.',
          'Da, sve je propalo.',
          'Ne pričajmo o tome.',
        ],
        answer: 0,
        tip: "'Ima istine u tome' — there's truth in that. Concede a point before countering; that's how you win Croatian debates.",
      },
      {
        speaker: 'Stric Ante',
        line: 'A što tvoja generacija uopće zna o teškim vremenima?',
        en: 'And what does your generation even know about hard times?',
        opts: [
          'Slažem se da smo imali sreće, no svaka generacija nosi svoje izazove.',
          'Opet ta priča o teškim vremenima...',
          'Ništa, u pravu si.',
          'Dosta politike za stolom!',
        ],
        answer: 0,
        tip: "'No' — the formal 'but'. 'Nositi svoje izazove' — to carry one's own challenges: idiom-level fluency.",
      },
      {
        speaker: 'Stric Ante',
        line: 'Hm. Pametno zboriš. A jezik? Djeca ti neće znati hrvatski!',
        en: "Hm. You speak wisely. And the language? Your children won't know Croatian!",
        opts: [
          'Zato i učim — želim da moja djeca jednog dana razgovaraju s vama bez prevoditelja.',
          'Znat će engleski, to je važnije.',
          'Vidjet ćemo.',
          'Zato postoje aplikacije.',
        ],
        answer: 0,
        tip: "'Želim da' + present tense — the volitive clause. This answer wins every Croatian grandparent's heart.",
      },
      {
        speaker: 'Stric Ante',
        line: 'E, na to ćemo nazdraviti! Živjeli!',
        en: "Now THAT we'll toast to! Cheers!",
        opts: [
          'Živjeli! I hvala vam što me uvijek natjerate na razmišljanje.',
          'Živjeli, valjda.',
          'Konačno kraj rasprave.',
          'Ok, živjeli.',
        ],
        answer: 0,
        tip: "'Natjerati na' + accusative — to push someone to (something). Thank the sparring partner; it's family.",
      },
    ],
  },
];
