// Exercise catalog for PracticeTab — every practice/exercise tile with its
// CEFR/category metadata and launch action. Extracted from PracticeTab as part
// of the 1d decomposition. Actions are heterogeneous (go(id) nav, named handlers,
// inline setScr/sCurEx), so the list is built by a factory that takes those
// handlers as deps rather than being pure data.

type ExerciseDeps = {
  go: (screen: string, id?: string) => () => void;
  setScr: (id: string) => void;
  sCurEx: (id: string) => void;
  startPitchAccent: () => void;
  startShadowing: () => void;
  startReview: () => void;
  startAspectDrill: () => void;
};

export function buildExercises({
  go,
  setScr,
  sCurEx,
  startPitchAccent,
  startShadowing,
  startReview,
  startAspectDrill,
}: ExerciseDeps) {
  return [
    // Grammar
    {
      id: 'grammarmap',
      label: 'Case Constellation',
      icon: '⭐',
      desc: 'Explore all 7 cases visually',
      category: 'grammar',
      cefr: 'B1',
      duration: '~10 min',
      action: go('grammarmap'),
    },
    {
      id: 'cloze',
      label: 'Sentence Cloze',
      icon: '🧩',
      desc: 'Fill the blank — cases in context',
      category: 'grammar',
      cefr: 'A2',
      duration: '~8 min',
      action: go('cloze'),
    },
    {
      id: 'unjumble',
      label: 'Word Order',
      icon: '🧩',
      desc: 'Put words in the right order',
      category: 'grammar',
      cefr: 'A2',
      duration: '~8 min',
      action: go('unjumble'),
    },
    {
      id: 'prepdrill',
      label: 'Prepositions',
      icon: '📍',
      desc: 'u, na, od, do — which one?',
      category: 'grammar',
      cefr: 'A2',
      duration: '~8 min',
      action: go('prepdrill'),
    },
    {
      id: 'qwords',
      label: 'Questions',
      icon: '❓',
      desc: 'Tko, Što, Gdje, Zašto...',
      category: 'grammar',
      cefr: 'A1+',
      duration: '~5 min',
      action: go('qwords'),
    },
    {
      id: 'negation',
      label: 'Negation',
      icon: '❌',
      desc: 'Ne, nije, nisam...',
      category: 'grammar',
      cefr: 'A2',
      duration: '~8 min',
      action: go('negation'),
    },
    {
      id: 'genderdrill',
      label: 'Gender',
      icon: '♂️♀️',
      desc: 'Masculine, feminine, neuter',
      category: 'grammar',
      cefr: 'A1+',
      duration: '~5 min',
      action: go('genderdrill'),
    },
    {
      id: 'profgender',
      label: 'M/F Jobs',
      icon: '👨‍⚖️',
      desc: 'Učitelj vs učiteljica',
      category: 'grammar',
      cefr: 'A2',
      duration: '~5 min',
      action: go('profgender'),
    },
    {
      id: 'comparatives',
      label: 'Compare',
      icon: '📈',
      desc: 'Bigger, faster, better',
      category: 'grammar',
      cefr: 'B1',
      duration: '~10 min',
      action: go('comparatives'),
    },
    {
      id: 'future',
      label: 'Future Tense',
      icon: '🚀',
      desc: 'ću, ćeš, će...',
      category: 'grammar',
      cefr: 'B1',
      duration: '~10 min',
      action: go('future'),
    },
    {
      id: 'sibil',
      label: 'Sibilization',
      icon: '🔄',
      desc: 'k→c, g→z sound changes',
      category: 'grammar',
      cefr: 'B1',
      duration: '~8 min',
      action: go('sibil'),
    },
    {
      id: 'coloragree',
      label: 'Color Agreement',
      icon: '🎨',
      desc: 'Colors match noun gender',
      category: 'grammar',
      cefr: 'A2',
      duration: '~5 min',
      action: go('coloragree'),
    },
    {
      id: 'accusativedrill',
      label: 'Accusative',
      icon: '🍽️',
      desc: 'Direct objects change form',
      category: 'grammar',
      cefr: 'B1',
      duration: '~10 min',
      action: go('accusativedrill'),
    },
    {
      id: 'relpron',
      label: 'Koji/Koja',
      icon: '🔗',
      desc: 'Relative pronouns',
      category: 'grammar',
      cefr: 'B1',
      duration: '~8 min',
      action: go('relpron'),
    },
    {
      id: 'reflexive',
      label: 'SE Verbs',
      icon: '🧲',
      desc: 'Reflexive verbs with se/si',
      category: 'grammar',
      cefr: 'B1',
      duration: '~10 min',
      action: go('reflexive'),
    },
    {
      id: 'sentbuild',
      label: 'Build Sentences',
      icon: '🏗️',
      desc: 'Arrange the building blocks',
      category: 'grammar',
      cefr: 'A2',
      duration: '~8 min',
      action: go('sentbuild'),
    },
    {
      id: 'sentencetiles',
      label: 'Tile Assembly',
      icon: '🧱',
      desc: 'Tap tiles to assemble Croatian sentences',
      category: 'grammar',
      cefr: 'A2',
      duration: '~8 min',
      action: go('sentencetiles'),
    },
    {
      id: 'clitic',
      label: 'Clitic Drill',
      icon: '🔗',
      desc: 'The #1 hardest rule in Croatian',
      category: 'grammar',
      cefr: 'B1+',
      duration: '~10 min',
      action: go('clitic'),
    },
    {
      id: 'numcases',
      label: 'Numbers+Cases',
      icon: '🔢',
      desc: '1/2-4/5+ — never wrong again',
      category: 'grammar',
      cefr: 'B1',
      duration: '~10 min',
      action: go('numcases'),
    },
    {
      id: 'imperative',
      label: 'Imperative',
      icon: '⚡',
      desc: 'Commands — essential production',
      category: 'grammar',
      cefr: 'B1',
      duration: '~8 min',
      action: go('imperative'),
    },
    {
      id: 'neggen',
      label: 'Negation+Genitive',
      icon: '❌',
      desc: 'Negate correctly — case shifts!',
      category: 'grammar',
      cefr: 'B1',
      duration: '~10 min',
      action: go('neggen'),
    },
    {
      id: 'animateacc',
      label: 'Animate Accusative',
      icon: '🎯',
      desc: 'Animate vs inanimate — accusative rule',
      category: 'grammar',
      cefr: 'A2',
      duration: '~8 min',
      action: go('animateacc'),
    },
    {
      id: 'instrumental',
      label: 'Instrumental Case',
      icon: '🔧',
      desc: 'With s/sa, means, baviti se, postati',
      category: 'grammar',
      cefr: 'A2',
      duration: '~8 min',
      action: go('instrumental'),
    },
    {
      id: 'dative',
      label: 'Dative Case',
      icon: '🤝',
      desc: 'Indirect objects, giving, liking',
      category: 'grammar',
      cefr: 'A2',
      duration: '~8 min',
      action: go('dative'),
    },
    {
      id: 'passive',
      label: 'Passive Voice',
      icon: '🔄',
      desc: 'Se-passive and biti+participle',
      category: 'grammar',
      cefr: 'B2',
      duration: '~8 min',
      action: go('passive'),
    },
    {
      id: 'fleetinga',
      label: 'Fleeting-A & L→O',
      icon: '✨',
      desc: 'Mobile vowels and past tense forms',
      category: 'grammar',
      cefr: 'C1',
      duration: '~8 min',
      action: go('fleetinga'),
    },
    // Vocab
    {
      id: 'znam',
      label: 'Translate',
      icon: '🇭🇷',
      desc: 'English ↔ Croatian',
      category: 'vocab',
      cefr: 'A1+',
      duration: '~5 min',
      action: go('znam'),
    },
    {
      id: 'possess',
      label: 'My/Your',
      icon: '👤',
      desc: 'Moj, tvoj, njegov, njezin',
      category: 'vocab',
      cefr: 'A1+',
      duration: '~5 min',
      action: go('possess'),
    },
    {
      id: 'opposites',
      label: 'Opposites',
      icon: '↔️',
      desc: 'Hot/cold, big/small...',
      category: 'vocab',
      cefr: 'A1+',
      duration: '~5 min',
      action: go('opposites'),
    },
    {
      id: 'ordinals',
      label: 'Ordinals',
      icon: '🏢',
      desc: 'First, second, third...',
      category: 'vocab',
      cefr: 'A2',
      duration: '~5 min',
      action: go('ordinals'),
    },
    {
      id: 'emogender',
      label: 'Emotions',
      icon: '😀',
      desc: 'Sretan, sretna — feel it',
      category: 'vocab',
      cefr: 'A2',
      duration: '~5 min',
      action: go('emogender'),
    },
    {
      id: 'verbdrill',
      label: '20 Core Verbs',
      icon: '💪',
      desc: 'The most-used Croatian verbs',
      category: 'vocab',
      cefr: 'A2',
      duration: '~8 min',
      action: go('verbdrill'),
    },
    {
      id: 'pronouns',
      label: 'Pronouns',
      icon: '🎯',
      desc: 'Ja, ti, on, ona, mi...',
      category: 'vocab',
      cefr: 'A1+',
      duration: '~5 min',
      action: go('pronouns'),
    },
    {
      id: 'cityloc',
      label: 'City Locations',
      icon: '🏙️',
      desc: 'Where is it in Croatia?',
      category: 'vocab',
      cefr: 'A2+',
      duration: '~5 min',
      action: go('cityloc'),
    },
    {
      id: 'collocations',
      label: 'Collocations',
      icon: '🔀',
      desc: 'Which words belong together',
      category: 'vocab',
      cefr: 'B1',
      duration: '~8 min',
      action: go('collocations'),
    },
    {
      id: 'wordfamilies',
      label: 'Word Families',
      icon: '🌱',
      desc: 'One root, a hundred words',
      category: 'vocab',
      cefr: 'B1',
      duration: '~8 min',
      action: go('wordfamilies'),
    },
    // Practical
    {
      id: 'restaurant',
      label: 'Restaurant',
      icon: '🍽️',
      desc: 'Order food like a local',
      category: 'practical',
      cefr: 'A2',
      duration: '~8 min',
      action: go('restaurant'),
    },
    {
      id: 'numtime',
      label: 'Numbers & Time',
      icon: '🔢',
      desc: 'Tell time, count anything',
      category: 'practical',
      cefr: 'A2',
      duration: '~5 min',
      action: go('numtime'),
    },
    {
      id: 'convmatch',
      label: 'Conversations',
      icon: '💬',
      desc: 'Match real-world dialogues',
      category: 'practical',
      cefr: 'A2+',
      duration: '~8 min',
      action: go('convmatch'),
    },
    {
      id: 'scenes',
      label: 'Describe',
      icon: '🖼️',
      desc: 'Describe what you see',
      category: 'practical',
      cefr: 'B1',
      duration: '~8 min',
      action: go('scenes'),
    },
    {
      id: 'tenseflip',
      label: 'Tense Flip',
      icon: '⏳',
      desc: 'Switch tense on the fly',
      category: 'practical',
      cefr: 'B1',
      duration: '~8 min',
      action: go('tenseflip'),
    },
    {
      id: 'fillstory',
      label: 'Story Fill',
      icon: '📝',
      desc: 'Fill in the blanks',
      category: 'practical',
      cefr: 'B1',
      duration: '~15 min',
      action: go('fillstory'),
    },
    {
      id: 'storyselect',
      label: 'Stories',
      icon: '📖',
      desc: 'Read short Croatian tales',
      category: 'practical',
      cefr: 'B1',
      duration: '~15 min',
      action: go('storyselect'),
    },
    {
      id: 'riddles',
      label: 'Riddles',
      icon: '🧩',
      desc: 'Can you guess the answer?',
      category: 'practical',
      cefr: 'A2+',
      duration: '~5 min',
      action: go('riddles'),
    },
    {
      id: 'logicquiz',
      label: 'Think Croatian',
      icon: '🧠',
      desc: 'Logic puzzles in Croatian',
      category: 'practical',
      cefr: 'B1',
      duration: '~10 min',
      action: go('logicquiz'),
    },
    {
      id: 'brzalice',
      label: 'Tongue Twisters',
      icon: '😝',
      desc: 'Brzalice — dare yourself',
      category: 'practical',
      cefr: 'A2+',
      duration: '~5 min',
      action: go('brzalice'),
    },
    // Advanced
    {
      id: 'pitchaccent',
      label: 'Pitch Accent',
      icon: '🎵',
      desc: 'Master Croatian tonal stress',
      category: 'advanced',
      cefr: 'B1+',
      duration: '~10 min',
      action: startPitchAccent,
    },
    {
      id: 'shadowing',
      label: 'Shadowing',
      icon: '🗣️',
      desc: 'Native-speed listen & repeat',
      category: 'advanced',
      cefr: 'B1+',
      duration: '~10 min',
      action: startShadowing,
    },
    {
      id: 'srsreview',
      label: 'SRS Review',
      icon: '🔁',
      desc: 'Smart spaced repetition',
      category: 'advanced',
      cefr: 'A1+',
      duration: 'self-paced',
      action: startReview,
    },
    {
      id: 'aspectdrill',
      label: 'Aspect Drill',
      icon: '🔄',
      desc: 'Imperfective vs perfective',
      category: 'advanced',
      cefr: 'B1+',
      duration: '~10 min',
      action: startAspectDrill,
    },
    {
      id: 'dialogue',
      label: 'Dialogue Sim',
      icon: '💬',
      desc: 'Real turn-based conversations',
      category: 'practical',
      cefr: 'A1+',
      duration: '~10 min',
      action: () => {
        setScr('dialogue');
        sCurEx('dialogue');
      },
    },
    {
      id: 'dictation',
      label: 'Dictation',
      icon: '🎧',
      desc: 'Listen and type Croatian',
      category: 'advanced',
      cefr: 'B1',
      duration: '~10 min',
      action: () => {
        setScr('dictation');
        sCurEx('dictation');
      },
    },
    {
      id: 'proncontrast',
      label: 'Sound Contrast',
      icon: '🔤',
      desc: 'č/ć, š/ž, đ/dž mastery',
      category: 'advanced',
      cefr: 'A2+',
      duration: '~8 min',
      action: () => {
        setScr('proncontrast');
        sCurEx('proncontrast');
      },
    },
    {
      id: 'pronunciation_assess',
      label: 'Pronunciation Test',
      icon: '🎙️',
      desc: 'CEFR-graded pronunciation assessment & grade',
      category: 'advanced',
      cefr: 'A1+',
      duration: '~5 min',
      action: () => {
        setScr('pronunciation_assess');
        sCurEx('pronunciation_assess');
      },
    },
    {
      id: 'production_drill',
      label: 'Production Drill ✨',
      icon: '✍️',
      desc: 'Transform, translate, build sentences — active output practice',
      category: 'advanced',
      cefr: 'A2+',
      duration: '~12 min',
      action: () => {
        setScr('production_drill');
        sCurEx('production_drill');
      },
    },
    {
      id: 'adaptive_review',
      label: 'Smart Review ✨',
      icon: '🧠',
      desc: 'Personalized session built from your weak spots',
      category: 'advanced',
      cefr: 'A1+',
      duration: '~10 min',
      action: () => {
        setScr('adaptive_review');
        sCurEx('adaptive_review');
      },
    },
    {
      id: 'translate_drills',
      label: 'Translate Production',
      icon: '✍️',
      desc: 'English → Croatian — produce full sentences',
      category: 'grammar',
      cefr: 'A2',
      duration: '~10 min',
      action: () => {
        setScr('translate_drills');
        sCurEx('translate_drills');
      },
    },
    {
      id: 'cefrtest',
      label: 'CEFR Test',
      icon: '🎓',
      desc: 'A1→B2 proficiency check',
      category: 'advanced',
      cefr: 'A1+',
      duration: '~15 min',
      action: () => {
        setScr('cefrtest');
        sCurEx('cefrtest');
      },
    },
    // Slang (advanced)
    {
      id: 'slang_classics',
      label: 'The Classics',
      icon: '🔥',
      desc: 'Foundation expletives — built on one root verb',
      category: 'advanced',
      cefr: 'B1+',
      duration: '~10 min',
      action: go('slang:classics'),
    },
    {
      id: 'slang_everyday',
      label: 'Svaki Dan',
      icon: '😤',
      desc: 'Mild-to-medium — usable around most adults',
      category: 'advanced',
      cefr: 'A2+',
      duration: '~8 min',
      action: go('slang:everyday'),
    },
    {
      id: 'slang_slang',
      label: 'Ulični Sleng',
      icon: '😎',
      desc: 'General everyday slang — sound like a local',
      category: 'advanced',
      cefr: 'A2+',
      duration: '~8 min',
      action: go('slang:slang'),
    },
    {
      id: 'slang_people',
      label: 'Ljudi i Adrese',
      icon: '👥',
      desc: 'How Croatians address each other',
      category: 'advanced',
      cefr: 'A2',
      duration: '~5 min',
      action: go('slang:people'),
    },
    {
      id: 'slang_dalmatian',
      label: 'Dalmatinski',
      icon: '☀️',
      desc: 'Split, Dalmatia & coast dialect',
      category: 'advanced',
      cefr: 'B1',
      duration: '~10 min',
      action: go('slang:dalmatian'),
    },
    {
      id: 'slang_zagreb',
      label: 'Zagrebački',
      icon: '🏙️',
      desc: 'Capital city slang — German meets Slavic',
      category: 'advanced',
      cefr: 'B1',
      duration: '~10 min',
      action: go('slang:zagreb'),
    },
    {
      id: 'slang_satrovski',
      label: 'Šatrovački',
      icon: '🔄',
      desc: 'Croatian pig latin — reverse syllable slang',
      category: 'advanced',
      cefr: 'B1+',
      duration: '~10 min',
      action: go('slang:satrovski'),
    },
    {
      id: 'slang_genz',
      label: 'Gen Z & Internet',
      icon: '📱',
      desc: 'Digital generation slang & memes',
      category: 'advanced',
      cefr: 'A2+',
      duration: '~8 min',
      action: go('slang:genz'),
    },
    {
      id: 'slang_pijani',
      label: 'Pijani & Mamurani',
      icon: '🍺',
      desc: 'Drinking culture & hangover vocabulary',
      category: 'advanced',
      cefr: 'B1',
      duration: '~8 min',
      action: go('slang:pijani'),
    },
    {
      id: 'slang_football',
      label: 'Nogomet',
      icon: '⚽',
      desc: 'Football supporter slang',
      category: 'advanced',
      cefr: 'A2+',
      duration: '~8 min',
      action: go('slang:football'),
    },
    {
      id: 'slang_regional',
      label: 'Zagreb vs Split',
      icon: '🗺️',
      desc: 'Regional rivalries & dialect wars',
      category: 'advanced',
      cefr: 'B1',
      duration: '~10 min',
      action: go('slang:regional'),
    },
    {
      id: 'slang_art',
      label: 'Psovanje kao Kunst',
      icon: '🎨',
      desc: 'Swearing elevated to an art form',
      category: 'advanced',
      cefr: 'B2',
      duration: '~10 min',
      action: go('slang:art'),
    },
  ];
}
