// ─── SlangScreen data ─────────────────────────────────────────────────────────
// All SECTIONS data extracted from SlangScreen.jsx for co-location.

export const SECTIONS = [

  // ─── 1. THE CLASSICS ────────────────────────────────────────────────────────
  {
    id: 'classics', icon: '🔥', title: 'The Classics',
    subtitle: 'The essential Croatian expletives — an artform built on one root verb',
    color: '#dc2626', light: '#fff1f2', border: '#fca5a5',
    entries: [
      { hr: 'Jebem ti mater', en: 'I f*** your mother', ph: 'YEH-bem tee MAH-tehr', level: '🌶🌶🌶',
        note: 'The foundational Croatian curse. Everything builds from this. "Jebem" = I f***, "ti" = your, "mater" = mother (archaic accusative). Versatile — expresses rage, awe, or deep affection depending on tone.',
        variants: [
          { hr: 'Jebem ti mater po rebru', en: '...your mother by the rib — adding body parts for emphasis' },
          { hr: 'Jebem mu mater', en: 'Third person — used when raging at a situation, not a person' },
          { hr: 'Mamicu im jebem', en: 'Slavonian intensifier — "mamicu" is a diminutive of mama, paradoxically making it more informal and cutting' },
          { hr: 'Jebemo si mater', en: 'Reciprocal form using "si" (dative of sebe) — "we f*** each other\'s mothers" — uniquely South Slavic grammatical construction' },
          { hr: 'Tri pizde materine', en: 'Triple maternal intensification — Slavonian/Bosnian escalation for when once isn\'t nearly enough' },
          { hr: 'Jebo te Bog', en: 'May God f*** you — invoking the divine for maximum impact' },
          { hr: 'Jebo ti pas mater', en: 'May a dog f*** your mother — multi-species escalation' },
          { hr: 'Jebo ti konj mater', en: 'May a horse f*** your mother — equine variant' },
          { hr: 'Jebem ti sve po spisku', en: 'F***ing everything on your list — when listing family feels like too much effort' },
          { hr: 'Jebem ti krv mlade rode', en: 'F***ing your blood of a young stork — peak Croatian poetic creativity' },
          { hr: 'Jebem ti juhu od Isusovih kostiju', en: 'F***ing your soup made of Jesus\' bones — considered a masterpiece of the form' },
        ]},
      { hr: 'Jebote', en: 'Holy sh** / F*** me / Wow', ph: 'YEH-boh-teh', level: '🌶🌶',
        note: 'Short for "jebo te." Functionally equivalent to "Jesus Christ!" — used for surprise, frustration, amazement. Very high frequency. Almost neutral in casual Zagreb speech.',
        variants: [
          { hr: 'Ma jebote...', en: 'Oh for f***\'s sake...' },
          { hr: 'Jebote pa to je nevjerojatno', en: 'Holy sh**, that\'s unbelievable' },
        ]},
      { hr: 'Jebi ga', en: 'F*** it / Whatever / Oh well', ph: 'YEH-bee gah', level: '🌶🌶',
        note: '"Jebi ga" is used like a verbal comma among Croatians. Almost neutral in context — expressing resignation, acceptance, or mild frustration. You\'ll hear it multiple times in any casual conversation.',
        variants: [
          { hr: 'A jebi ga', en: 'Ah, forget it / What can you do — the Croatian shrug' },
          { hr: 'Jebi ga, bit će bolje', en: 'F*** it, it\'ll get better' },
        ]},
      { hr: 'Boli me kurac', en: 'I couldn\'t care less', ph: 'BOH-lee meh KOO-rahts', level: '🌶🌶🌶',
        note: 'Literally "my d*** hurts." Grammatically pristine — boli (hurts) + me (me) + kurac. Means complete indifference. The full "I don\'t care" ladder: "Nije me briga" → "Boli me briga" → "Boli me kurac."',
        variants: [
          { hr: 'Pun mi je kurac svega', en: 'I\'m fed up with everything — "my d*** is full"' },
          { hr: 'Koji kurac radiš?!', en: 'What the f*** are you doing?!' },
          { hr: 'U kurac!', en: 'F*** that! / No f***ing way!' },
          { hr: 'Kurac od ovce', en: 'A sheep\'s d*** = completely useless / worthless' },
          { hr: 'Ni kurac', en: 'Absolutely nothing / Not a damn thing' },
          { hr: 'Pičkin dim', en: 'P*ssy smoke = nothing / don\'t believe the hype' },
        ]},
      { hr: 'Idi u pizdu materinu', en: 'The Croatian nuclear option', ph: 'EE-dee oo PEEZ-doo mah-TEH-ree-noo', level: '🌶🌶🌶',
        note: 'The maximum escalation. "Idi" = go, "u pizdu" = into the c***, "materinu" = of your mother. Reserve for absolute final breaks.',
        variants: [
          { hr: 'Idi u tri pičke materine', en: 'The triple version — for when once isn\'t enough' },
          { hr: 'Idi u pičku strininu', en: 'Aunt variant — the unexpected family member escalation' },
        ]},
      { hr: 'Odjebi', en: 'F*** off', ph: 'OD-yeh-bee', level: '🌶🌶',
        note: 'Clean, direct dismissal. "Odjebi odmah" = F*** off right now.',
        variants: [
          { hr: 'Jebi se', en: 'Go f*** yourself — direct' },
          { hr: 'Nabijem te na kurac', en: 'I\'ll stick you on a d*** — threat-level insult' },
          { hr: 'Jebeš tebe i tvog oca', en: 'F*** you and your father — rare father variant' },
        ]},
      { hr: 'Jebačina', en: 'An almighty f***-up / absolute chaos', ph: 'yeh-BAH-chee-nah', level: '🌶🌶🌶',
        note: 'The suffix -čina added to "jebanje" creates an augmentative noun. "Polarna jebačina" is the Krankšvester classic.',
        variants: [
          { hr: 'Polarna jebačina', en: 'Polar f***-fest — the Krankšvester construction' },
          { hr: 'Moj kurac je odavno prekinuo s tobom', en: 'My dick broke up with you long ago — anthropomorphizing the penis with relationship agency' },
          { hr: 'Pucaj si u kurac', en: 'Shoot yourself in the dick — reflexive "si" makes it self-directed' },
        ]},
      { hr: 'Šupak', en: 'A**hole', ph: 'SHOO-pahk', level: '🌶🌶',
        note: 'From "šupljina" (hole). The Croatian all-purpose "a**hole." Widely used, cross-generational.',
        variants: [
          { hr: 'Kurvin sine', en: 'Son of a b**** — literally "son of a wh***"' },
          { hr: 'Đubre', en: 'Garbage / Piece of trash' },
          { hr: 'Glupi majmune', en: 'You stupid monkey' },
        ]},
    ],
  },

  // ─── 2. EVERYDAY EXPRESSIONS ────────────────────────────────────────────────
  {
    id: 'everyday', icon: '😤', title: 'Svaki Dan',
    subtitle: 'Mild-to-medium — usable around most adults',
    color: '#d97706', light: '#fffbeb', border: '#fde68a',
    entries: [
      { hr: 'Sranje', en: 'Sh** / Crap', ph: 'SRAH-nyeh', level: '🌶',
        note: 'All-purpose "sh**." Minor disasters, frustrations, surprises.',
        variants: [
          { hr: 'Kakvo sranje', en: 'What a mess / What a load of crap' },
          { hr: 'Ne seri / Nemoj srat\'', en: 'Don\'t bullsh** me' },
          { hr: 'Napravio si sranje', en: 'You made a mess / You screwed up' },
        ]},
      { hr: 'Sjebano', en: 'F***ed up', ph: 'SYEH-bah-noh', level: '🌶🌶',
        note: 'Past participle of "sjebati." For situations, things, people, or yourself.',
        variants: [
          { hr: 'Totalno sam sjebo', en: 'I totally screwed up' },
          { hr: 'Zajebao sam', en: 'I messed it up / I f***ed that up' },
          { hr: 'Zajebavaš me', en: 'You\'re messing with me / You\'re kidding me' },
        ]},
      { hr: 'Govno', en: 'Sh** (literal)', ph: 'GOV-noh', level: '🌶',
        note: 'The literal word for sh**. "Govnar" = a sh***y person.',
        variants: [
          { hr: 'Govno jedno', en: 'Piece of sh** — direct insult' },
          { hr: 'Jedi govna', en: 'Eat sh** — extreme dismissal' },
          { hr: 'Govnar', en: 'A sh***y/worthless person' },
        ]},
      { hr: 'Majku mu / Majku ti', en: 'Damn it / F*** (mild)', ph: 'MY-koo moo / MY-koo tee', level: '🌶',
        note: 'Shortened mater curse — widely used as a mild expletive.',
        variants: [
          { hr: 'Majko moja', en: 'Oh my God / Oh my mother — surprise/disbelief' },
          { hr: 'Jao', en: 'Oh no / Ouch — very mild exclamation' },
          { hr: 'Ajme', en: 'Oh my / Oh dear — surprise or pain' },
        ]},
      { hr: 'Popizdio je', en: 'He lost his mind / He flipped out', ph: 'poh-peez-DEE-oh', level: '🌶🌶🌶',
        note: '"Popizditi" = to go insane with rage or excitement.',
        variants: [
          { hr: 'Popizdio od sreće', en: 'Went crazy with happiness' },
          { hr: 'Pizdjen sam danas', en: 'I\'m in a sh** mood today' },
          { hr: 'Pizdarija', en: 'A total f***-up / complete mess' },
        ]},
      { hr: 'Jebu me živci', en: 'My nerves are screwing me / I\'m losing it', ph: 'YEH-boo meh ZHEEV-tsee', level: '🌶🌶',
        note: 'Abstract nouns as the agent doing the "jebanje" — a uniquely native construction.',
        variants: [
          { hr: 'Jebu me emocije', en: 'My emotions are killing me' },
          { hr: 'Jebu me ove situacije', en: 'These situations are doing me in' },
          { hr: 'Jebe mi mozak', en: 'It\'s screwing with my brain' },
        ]},
      { hr: 'Crkni', en: 'Drop dead', ph: 'TSRK-nee', level: '🌶🌶',
        note: 'From "crknuti" (to die like an animal). Between friends it\'s often affectionate teasing.',
        variants: [
          { hr: 'Crknuo sam od smijeha', en: 'I died laughing — common positive use' },
          { hr: 'Dabog da ti se noge osušile', en: 'May your legs dry out — old-school hex curse' },
          { hr: 'Vrag ti kosti glodao', en: 'May the Devil gnaw your bones — classical hex' },
        ]},
      { hr: 'Frka', en: 'Panic / Stress / Chaos', ph: 'FER-kah', level: '✅',
        note: 'Zagreb-heavy. "Totalna frka" = total panic. "Nema frke" = no stress, relax.',
        variants: [
          { hr: 'Nema frke', en: 'No stress / It\'s fine / Relax' },
          { hr: 'Totalna frka', en: 'Complete chaos / Total panic' },
        ]},
      { hr: 'Katastrofa', en: 'Disaster / Total mess', ph: 'kah-tah-STROH-fah', level: '✅',
        note: 'Used as hyperbolic exclamation. "Kakva katastrofa!" = What a disaster!',
        variants: [
          { hr: 'Kakva katastrofa', en: 'What a disaster! (mild or major)' },
          { hr: 'Bruka', en: 'Embarrassment / Shame' },
        ]},
    ],
  },

  // ─── 3. STREET SLANG ────────────────────────────────────────────────────────
  {
    id: 'slang', icon: '😎', title: 'Ulični Sleng',
    subtitle: 'Sound like a local — general everyday slang',
    color: '#7c3aed', light: '#faf5ff', border: '#ddd6fe',
    entries: [
      { hr: 'Zakon!', en: 'Awesome! / Brilliant! / The law', ph: 'ZAH-kon', level: '✅',
        note: 'Literally "the law." The most universally positive Croatian exclamation.',
        variants: [
          { hr: 'Brutala!', en: 'Brutal (positive!) / Amazing' },
          { hr: 'Top!', en: 'Top notch / Excellent' },
          { hr: 'Oriđiđi', en: 'Original / The real deal' },
        ]},
      { hr: 'Kužiš?', en: 'You get it? / You know what I mean?', ph: 'KOO-zhish', level: '✅',
        note: 'From "kužiti" (to understand/sniff out). Mandatory at the end of sentences.',
        variants: [
          { hr: 'Kontam', en: 'I get it / I understand' },
          { hr: 'Skontaj', en: 'Figure it out / Get it through your head' },
          { hr: 'Skužio sam', en: 'I figured it out / I got it' },
        ]},
      { hr: 'Fora', en: 'Joke / Cool / The point', ph: 'FOH-rah', level: '✅',
        note: 'Borrowed from Italian "fuori." "Koja fora" = What a cool/funny thing.',
        variants: [
          { hr: 'Koja fora!', en: 'That\'s hilarious! / What a trick!' },
          { hr: 'Nema fore', en: 'No joke / Seriously / That\'s not cool' },
          { hr: 'Fora lik', en: 'Cool guy' },
        ]},
      { hr: 'Brate / Buraz', en: 'Bro / Dude / Man', ph: 'BRAH-teh / BOO-rahz', level: '✅',
        note: '"Brat" = brother, "brate" = vocative. "Buraz" = more Zagreb slang.',
        variants: [
          { hr: 'Brate moj, ne mogu', en: 'Bro, I just can\'t even' },
          { hr: 'Ma buraz, jesi normalan?', en: 'Dude, are you normal?' },
          { hr: 'Buraz moj', en: 'My bro (reversed word order) — possessive after noun = maximum street register' },
          { hr: 'Stari / Stara', en: 'Old man / Old lady — also means Dad/Mum in slang' },
        ]},
      { hr: 'Faca', en: 'A big deal / Someone important', ph: 'FAH-tsah', level: '✅',
        note: 'From Italian "faccia" (face). "On je faca" = He\'s a big deal.',
        variants: [
          { hr: 'Jebote, faca si!', en: 'Holy sh**, you\'re a legend!' },
          { hr: 'Šmeker', en: 'Smooth operator / Charmer' },
          { hr: 'Frajer', en: 'Cool confident guy' },
        ]},
      { hr: 'Ful / Baš', en: 'Super / Really / Very', ph: 'FOOL / BAHSH', level: '✅',
        note: '"Ful" from English "full." "Baš" is the milder universal intensifier.',
        variants: [
          { hr: 'Ful dobro', en: 'Really good / Super good' },
          { hr: 'Fakat', en: 'For real / Seriously — from Turkish' },
          { hr: 'Ziher', en: 'For sure / Definitely — from German "sicher"' },
        ]},
      { hr: 'Ma daj!', en: 'Come on! / No way! / Are you serious?', ph: 'mah DIE', level: '✅',
        note: '"Ma" (filler) + "daj" (give/come on). Tone determines meaning completely.',
        variants: [
          { hr: 'Ma daj, nije moguće', en: 'No way, that\'s impossible' },
          { hr: 'Daj već jednom', en: 'Come on already / Just do it' },
          { hr: 'Kako da ne', en: 'Of course... NOT — sarcastic' },
        ]},
      { hr: 'Bezveze / Bez veze', en: 'Pointless / Lame / For nothing', ph: 'bez-VEH-zeh', level: '✅',
        note: '"Bez veze" = without connection/reason. One of the most used words in Croatian casual speech.',
        variants: [
          { hr: 'Nema veze', en: 'No worries / Doesn\'t matter / It\'s fine' },
          { hr: 'Dosadnjak', en: 'Boring person' },
          { hr: 'Lapim', en: 'I\'m bored to death' },
        ]},
      { hr: 'Brijati', en: 'To think / to be into / to date', ph: 'BREE-yah-tee', level: '✅',
        note: 'One of the most multi-functional Croatian verbs.',
        variants: [
          { hr: 'Furati', en: 'To wear / to drive / to date / to rock' },
          { hr: 'Bariti', en: 'To flirt / hit on someone' },
          { hr: 'Skompati se', en: 'To click with someone / become friends instantly' },
        ]},
      { hr: 'Pomalo', en: 'Easy / Take it slow / Gradually', ph: 'poh-MAH-loh', level: '✅',
        note: 'The coastal philosophy of life in one word.',
        variants: [
          { hr: 'Sve pet', en: 'Everything\'s great — literally "all five"' },
          { hr: 'To je to!', en: 'That\'s it! / That\'s the one!' },
          { hr: 'Ajde / Ajmo', en: 'Come on / Let\'s go' },
        ]},
      { hr: 'Muljati', en: 'To lie / to deceive / to hustle', ph: 'MOO-lyah-tee', level: '✅',
        note: '"Ne muljaj" = Don\'t lie to me / stop hustling me.',
        variants: [
          { hr: 'Ne muljaj', en: 'Don\'t lie to me / Stop bullsh***ing' },
          { hr: 'Fejkati', en: 'To fake — direct from English' },
          { hr: 'Nacrtan se', en: 'He just showed up out of nowhere' },
        ]},
      { hr: '\'Oće kurac', en: 'Yeah right / Fat chance / As if', ph: 'OH-cheh KOO-rahts', level: '🌶🌶',
        note: 'Sarcastic complete denial. Non-native speakers cannot guess the meaning from the words.',
        variants: [
          { hr: '\'Oće kurac da plaća!', en: 'Yeah right he\'s paying!' },
          { hr: 'Kurac \'oće', en: 'Reversed word order for even more emphasis' },
          { hr: 'Isp\'o pička', en: 'He turned out to be a coward' },
        ]},
      { hr: 'Kontrakcije — o\'šo, pos\'o, rek\'o', en: 'Contracted past tense — how Croatians actually speak', ph: '—', level: '📚',
        note: 'In fast colloquial speech, masculine past participles drop "-ao" to "-o".',
        variants: [
          { hr: 'O\'šo je', en: 'He went / He left' },
          { hr: 'Pos\'o mi je sranje', en: 'My job is sh**' },
          { hr: 'Rek\'o sam ti', en: 'I told you' },
          { hr: 'Dos\'o sam', en: 'I arrived / I came' },
        ]},
      { hr: 'Biti u banani', en: 'To be in trouble / to have a problem', ph: 'BOO-tee oo bah-NAH-nee', level: '✅',
        note: 'Literally "to be in a banana." "U banani smo" = We\'re in trouble.',
        variants: [
          { hr: 'U banani smo', en: 'We\'re in trouble / We\'re in a jam' },
          { hr: 'Pošorati se', en: 'To get into a fight (Zagreb)' },
          { hr: 'Brukati se', en: 'To embarrass yourself' },
        ]},
    ],
  },

  // ─── 4. PEOPLE & ADDRESSES ──────────────────────────────────────────────────
  {
    id: 'people', icon: '👥', title: 'Ljudi i Adrese',
    subtitle: 'How Croatians address and describe each other',
    color: '#0e7490', light: '#f0f9ff', border: '#7dd3fc',
    entries: [
      { hr: 'Lik / Tip', en: 'Guy / Dude', ph: 'LEEK / TEEP', level: '✅',
        note: '"Lik" for any male person. "Likuša" for female.',
        variants: [
          { hr: 'Klinac / Klinka', en: 'Kid / Young person' },
          { hr: 'Cura', en: 'Girl / Girlfriend — standard informal' },
          { hr: 'Dečko', en: 'Boy / Boyfriend — standard informal' },
        ]},
      { hr: 'Ekipa', en: 'Squad / Crew / Friend group', ph: 'EH-kee-pah', level: '✅',
        note: '"Idemo s ekipom" = We\'re going with the crew.',
        variants: [
          { hr: 'Banda', en: 'Gang / Crew' },
          { hr: 'Mala / Mali', en: 'Little one — affectionate for someone younger' },
          { hr: 'Šef', en: 'Boss — also used to address strangers respectfully' },
          { hr: 'Dušmani', en: 'Enemies — from Turkish "düşman"' },
        ]},
      { hr: 'Šupak / Debil', en: 'A**hole / Moron (insults)', ph: 'SHOO-pahk / DEH-beel', level: '🌶🌶',
        note: 'The Croatian standard insult pair.',
        variants: [
          { hr: 'Mamlaz', en: 'Idiot / Knucklehead' },
          { hr: 'Levat', en: 'Idiot (Zagreb-specific)' },
          { hr: 'Kreten', en: 'Cretin / Moron — cross-regional' },
          { hr: 'Tukac', en: 'Idiot (Dalmatian)' },
          { hr: 'Jazavac', en: 'Social outcast — literally "badger"' },
        ]},
      { hr: 'Mačka / Riba', en: 'Hot woman (cat / fish)', ph: 'MACH-kah / REE-bah', level: '🌶',
        note: 'Both used for attractive women.',
        variants: [
          { hr: 'Čista 10', en: 'A perfect ten' },
          { hr: 'Snack', en: 'Attractive person — English loanword used natively by Gen Z' },
          { hr: 'Sladak / Slatka', en: 'Sweet / Cute' },
        ]},
      { hr: 'Cinkaroš', en: 'Snitch / Whistleblower', ph: 'tseen-kah-ROSH', level: '🌶',
        note: '"Ne budi cinkaroš" = Don\'t be a snitch.',
        variants: [
          { hr: 'Ne budi cinkaroš', en: 'Don\'t be a snitch' },
          { hr: 'Džaba-džabist', en: 'Freeloader' },
          { hr: 'Palamudit', en: 'Show-off / Acting smart — Dalmatian' },
        ]},
      { hr: 'Pizdjen/a', en: 'In a foul mood', ph: 'PEEZ-dyen', level: '🌶🌶',
        note: '"Pizdjena sam danas" = I\'m in a sh** mood today.',
        variants: [
          { hr: 'Ljut ko pas', en: 'Angry as a dog — furious' },
          { hr: 'Idan/Idna', en: 'Angry / Furious — Dalmatian' },
          { hr: 'Grinta', en: 'Nagging / Complaining' },
        ]},
    ],
  },

  // ─── 5. DALMATIAN ───────────────────────────────────────────────────────────
  {
    id: 'dalmatian', icon: '☀️', title: 'Dalmatinski',
    subtitle: 'Split, Dalmatia & coast — a world of its own',
    color: '#0369a1', light: '#f0f9ff', border: '#93c5fd',
    entries: [
      { hr: 'Fjaka', en: 'The art of doing nothing', ph: 'FYAH-kah', level: '⚓',
        note: 'The defining Dalmatian concept — a meditative, philosophical state of not doing anything.',
        variants: [
          { hr: 'Tramak', en: 'Reluctance to do tasks — related to fjaka' },
          { hr: 'Pomalo', en: 'Easy / Take it slow — the coastal philosophy' },
          { hr: 'Guštati', en: 'To enjoy / savor' },
        ]},
      { hr: 'Ćakula', en: 'Chat / Gossip / Small talk', ph: 'CHAH-koo-lah', level: '⚓',
        note: '"Idemo na ćakulu" = Let\'s have a chat.',
        variants: [
          { hr: 'Bufun / Bufunat', en: 'Jokester / To clown around' },
          { hr: 'Burdil', en: 'Madness / Total chaos' },
          { hr: 'Brontulat', en: 'Complaining / talking nonsense constantly' },
        ]},
      { hr: 'Šoldi', en: 'Money (Dalmatian)', ph: 'SHOL-dee', level: '⚓',
        note: 'From Italian "soldi." Zagreb says "lova" or "kinta" — Dalmatia says "šoldi."',
        variants: [
          { hr: 'Mukte', en: 'Free / For nothing' },
          { hr: 'Spiza', en: 'Groceries / Food shopping' },
          { hr: 'Piaca / Pijaca', en: 'Market — from Italian "piazza"' },
        ]},
      { hr: 'Pegulan', en: 'Unlucky person', ph: 'peh-GOO-lahn', level: '⚓',
        note: '"Ima pegulu" = He\'s got bad luck.',
        variants: [
          { hr: 'Dišpeta / Iz dišpeta', en: 'Spite / Out of spite' },
          { hr: 'Priša', en: 'Pressure / Rushing' },
          { hr: 'A nec!', en: 'No way! / No chance! — strong Dalmatian refusal' },
        ]},
      { hr: 'Makina', en: 'Car (Dalmatian)', ph: 'MAH-kee-nah', level: '⚓',
        note: 'From Italian "macchina." Zagreb says "kola" or "auto."',
        variants: [
          { hr: 'Šjor', en: 'Mister / Gentleman — from Italian "signore"' },
          { hr: 'Barba', en: 'Uncle / Old man — respectful informal address' },
          { hr: 'Cukarin', en: 'Sweetie / Sugar — term of endearment' },
          { hr: 'Ojro', en: 'Euro (money) — phonological adaptation' },
        ]},
      { hr: 'Uvik / Nisan / Sisa\' sa planine', en: 'Ikavian dialect markers — instant coast identification', ph: 'OO-veek / NEE-sahn', level: '⚓',
        note: 'Three words that instantly mark a Dalmatian speaker.',
        variants: [
          { hr: 'Uvik', en: 'Always (Dalmatian) — standard Croatian: uvijek' },
          { hr: 'Nisan', en: 'I\'m not (Dalmatian) — standard: nisam' },
          { hr: 'Sisa\' sa planine', en: 'Sucked from the mountain — dismissing someone as a naive provincial' },
        ]},
      { hr: 'Retaj / Redikul', en: 'Fool / Laughingstock (Dalmatian insults)', ph: 'REH-tai / REH-dee-kool', level: '🌶',
        note: '"Redikul" from Italian "ridicolo." Distinctly Dalmatian insults.',
        variants: [
          { hr: 'Tukac', en: 'Idiot — the standard Dalmatian go-to insult' },
          { hr: 'Greza / Grezulja', en: 'Ugly / rough' },
          { hr: 'Štraca', en: 'Rag / promiscuous woman — Dalmatian derogatory' },
        ]},
      { hr: 'Picigin', en: 'The sport of Split', ph: 'PEE-tsee-geen', level: '⚓',
        note: 'Traditional Split ball game played in very shallow sea water.',
        variants: [
          { hr: 'Mol / Mul', en: 'Pier / Marina' },
          { hr: 'Badić', en: 'Swimsuit — the essential summer vocabulary' },
          { hr: 'Šugaman', en: 'Towel — cannot go to the beach without your šugaman' },
        ]},
    ],
  },

  // ─── 6. ZAGREB / KAJKAVIAN ──────────────────────────────────────────────────
  {
    id: 'zagreb', icon: '🏙️', title: 'Zagrebački',
    subtitle: 'Capital city slang — where German meets Slavic',
    color: '#16a34a', light: '#f0fdf4', border: '#86efac',
    entries: [
      { hr: 'Kaj', en: 'What (Kajkavian)', ph: 'KAI', level: '🏙️',
        note: 'The defining Zagreb word. "Kaj" replaces "što/šta" (standard Croatian).',
        variants: [
          { hr: 'Kaj ima?', en: 'What\'s up? — the Zagreb greeting' },
          { hr: 'Doma', en: 'At home — used in both Zagreb and Dalmatia' },
          { hr: 'Tekma', en: 'Match / Game' },
        ]},
      { hr: 'Cugati / Cuga', en: 'To drink (booze) / A drinking session', ph: 'TSOO-gah-tee / TSOO-gah', level: '🍺',
        note: 'Zagreb-heavy. "Idemo cugati" = Let\'s go drinking.',
        variants: [
          { hr: 'Birc', en: 'Bar / Pub — from German "Wirtshaus"' },
          { hr: 'Viksa', en: 'Holiday home / weekend house' },
          { hr: 'Špica', en: 'The main scene — being seen on Tkalčićeva' },
        ]},
      { hr: 'Murja', en: 'The Police', ph: 'MOOR-yah', level: '🏙️',
        note: '"Dolazi murja!" = The cops are coming!',
        variants: [
          { hr: 'Šora', en: 'A fight (Zagreb)' },
          { hr: 'Nogoš', en: 'Football — short for "nogomet"' },
          { hr: 'Trac', en: 'Tram — short for "tramvaj"' },
        ]},
      { hr: 'Frajla', en: 'Miss / Young lady', ph: 'FRAY-lah', level: '🏙️',
        note: 'From German "Fräulein." The Zagreb German influence.',
        variants: [
          { hr: 'Ziher', en: 'For sure / Definitely — from German "sicher"' },
          { hr: 'Šljiva mi je', en: 'I\'m cold — literally "my plum is cold"; uniquely Zagreb' },
          { hr: 'Šora', en: 'Fight — from German "Schar"' },
        ]},
      { hr: 'Pazi kaj se dela', en: 'Watch what\'s happening', ph: 'PAH-zee kai seh DEH-lah', level: '🏙️',
        note: 'Two Kajkavian markers stacked: "kaj" and "dela." This broadcasts Zagreb street origin immediately.',
        variants: [
          { hr: 'Kaj ima?', en: 'What\'s up? — the Kajkavian greeting' },
          { hr: 'Kvart', en: 'Neighborhood / Block — from German "Quartier"' },
          { hr: 'Kruzamo / Tegamo', en: 'Cruising / Hanging around' },
          { hr: 'Kesu riješit\'', en: 'Sort out the money — "kesa" (bag) = cash in Zagreb slang' },
        ]},
    ],
  },

  // ─── 7. ŠATROVAČKI ──────────────────────────────────────────────────────────
  {
    id: 'satrovski', icon: '🔄', title: 'Šatrovački',
    subtitle: 'Syllable-reversal street language — the Croatian secret code',
    color: '#9333ea', light: '#faf5ff', border: '#d8b4fe',
    entries: [
      { hr: 'What is Šatrovački?', en: 'Croatia\'s street code — syllables swapped', ph: '—', level: '📚',
        note: 'Šatrovački is a form of slang where words are split and syllables reversed.',
        variants: [
          { hr: 'Vopi', en: '"Pivo" (beer) reversed — the most famous example' },
          { hr: 'Ćešho', en: '"Hoćeš" (do you want) reversed' },
        ]},
      { hr: 'Vopi', en: 'Beer (pivo reversed)', ph: 'VOH-pee', level: '🔄',
        note: 'The most famous šatrovački word.',
        variants: [
          { hr: 'Zika', en: '"Muzika" (music) — reversed and shortened' },
          { hr: 'Mado', en: '"Doma" (home) reversed' },
          { hr: 'Trasu', en: '"Sutra" (tomorrow) reversed' },
        ]},
      { hr: 'Vutra', en: 'Weed / Grass (trava reversed)', ph: 'VOO-trah', level: '🔄',
        note: '"Trava" (grass/weed) → reversed → "vutra."',
        variants: [
          { hr: 'Voplo', en: '"Lopov" (thief) reversed' },
          { hr: 'Garaci', en: '"Cigara" (cigarette) reversed' },
          { hr: 'Brodo', en: '"Dobro" (good) reversed' },
        ]},
      { hr: 'Žišku', en: 'You get it? (kužiš reversed)', ph: 'ZHISH-koo', level: '🔄',
        note: '"Kužiš" reversed = "žišku."',
        variants: [
          { hr: 'Zipa', en: '"Pazi" (watch out / careful) reversed' },
          { hr: 'Đido', en: '"Dođi" (come here) reversed' },
          { hr: 'Lahva', en: '"Hvala" (thank you) reversed' },
        ]},
    ],
  },

  // ─── 8. GEN Z / INTERNET ────────────────────────────────────────────────────
  {
    id: 'genz', icon: '📱', title: 'Gen Z & Internet',
    subtitle: 'How Croatian youth actually talk online and IRL in 2025',
    color: '#db2777', light: '#fdf2f8', border: '#f9a8d4',
    entries: [
      { hr: 'Mid', en: 'Mediocre / Nothing special', ph: 'MID', level: '📱',
        note: 'English Gen Z loanword fully adopted. "To je mid" = That\'s mid.',
        variants: [
          { hr: 'Bussin', en: 'Excellent / Hits different' },
          { hr: 'No cap', en: 'No lie / For real' },
          { hr: 'Bet', en: 'Bet / For sure' },
        ]},
      { hr: 'Rizz', en: 'Game / Charisma / Charm', ph: 'REEZ', level: '📱',
        note: '"Ima rizz" = He has game/charisma.',
        variants: [
          { hr: 'Aura', en: '"Ima auru" = He has aura / presence' },
          { hr: 'Drip', en: '"Kakav drip" = What style/drip' },
          { hr: 'Slay', en: '"Slayala si" = You slayed / nailed it' },
        ]},
      { hr: 'Delulu', en: 'Delusional', ph: 'deh-LOO-loo', level: '📱',
        note: '"Ona je totalno delulu" = She\'s completely delusional.',
        variants: [
          { hr: 'Cringe', en: '"To je cringe" = That\'s cringe' },
          { hr: 'Sus', en: '"Malo je sus" = A bit suspicious' },
          { hr: 'Red flag', en: '"Totalni red flag"' },
        ]},
      { hr: 'Ghostati', en: 'To ghost someone', ph: 'GHOST-ah-tee', level: '📱',
        note: '"Ghostao me" = He ghosted me. Croatian Gen Z adapted English "ghost" with Croatian verb endings.',
        variants: [
          { hr: 'Hypeati', en: 'To hype up' },
          { hr: 'Cancelati', en: 'To cancel someone' },
          { hr: 'Shipati', en: 'To ship (as a couple)' },
        ]},
      { hr: 'Hejtat', en: 'To hate on / low-key hate', ph: 'HEY-taht', level: '📱',
        note: 'From English "hate." Complete Croatian conjugation fully established.',
        variants: [
          { hr: 'Fomo', en: 'Fear of missing out' },
          { hr: 'Simp', en: '"Ne budi simp"' },
          { hr: 'Bestie', en: '"Ti si moj bestie"' },
        ]},
      { hr: 'Vibes', en: 'Vibes / The feel / Energy', ph: 'VYBS', level: '📱',
        note: '"Kakvi vibes" = What vibes.',
        variants: [
          { hr: 'Lit', en: '"Večeras je bilo lit" = Tonight was lit' },
          { hr: 'GOAT', en: '"On je goat" = He\'s the greatest of all time' },
          { hr: 'Skibidi', en: 'Nonsense / chaotic' },
        ]},
    ],
  },

  // ─── 9. DRUNK & HUNGOVER ────────────────────────────────────────────────────
  {
    id: 'pijani', icon: '🍺', title: 'Pijani & Mamurani',
    subtitle: 'Drunk, hungover, broke — the essential survival vocabulary',
    color: '#b45309', light: '#fffbeb', border: '#fcd34d',
    entries: [
      { hr: 'Nakresan / Srušen', en: 'Drunk / Wrecked', ph: 'nah-KREH-sahn / SROO-shen', level: '🍺',
        note: '"Nakresan" = drunk (like tiles knocked crooked). "Srušen" = demolished/wrecked.',
        variants: [
          { hr: 'U zuju', en: 'Tipsy — the pleasant early stage' },
          { hr: 'Nacugan', en: 'Wasted' },
          { hr: 'Naroljan', en: 'Completely wasted' },
        ]},
      { hr: 'Pijan ko smuk', en: 'Drunk as a snake', ph: 'PEE-yahn koh SMOOK', level: '🍺',
        note: 'Classic Croatian drunk simile.',
        variants: [
          { hr: 'Pijan ko majka', en: 'Drunk as a mother — colorful hyperbole' },
          { hr: 'Pijan ko pička', en: 'Completely hammered — explicit intensifier' },
          { hr: 'Idemo se nacugati', en: 'Let\'s go get wasted' },
        ]},
      { hr: 'Mamuran', en: 'Hungover', ph: 'mah-MOO-rahn', level: '🍺',
        note: 'The inevitable morning after.',
        variants: [
          { hr: 'Mamurluk', en: 'A hangover (noun)' },
          { hr: 'Krepavam od mamurluka', en: 'I\'m dying of a hangover' },
          { hr: 'Mrtav od mamurluka', en: 'Dead from a hangover — the nuclear version' },
        ]},
      { hr: 'Švorc', en: 'Broke / No money', ph: 'SHVORTS', level: '💸',
        note: 'The standard "I\'m broke."',
        variants: [
          { hr: 'Na nuli', en: 'At zero / flat broke' },
          { hr: 'Nema kinte', en: 'No money' },
          { hr: 'Lova / Pare / Šoldi', en: 'Money — Zagreb: lova/kinta; Dalmatia: šoldi; standard: pare' },
        ]},
      { hr: 'Čaga / Žurka', en: 'Dance party / Party', ph: 'CHAH-gah / ZHOOR-kah', level: '🎉',
        note: '"Žurka" = party (pan-Croatian). "Čaga" = more specifically a dance party.',
        variants: [
          { hr: 'Festin', en: 'Feast / Party (Dalmatian) — from Italian' },
          { hr: 'Noćni izlazak', en: 'Night out' },
          { hr: 'Đuskati / Čagati', en: 'To dance' },
        ]},
    ],
  },

  // ─── 10. FOOTBALL ───────────────────────────────────────────────────────────
  {
    id: 'football', icon: '⚽', title: 'Nogomet',
    subtitle: 'Football culture — where half the country\'s passion lives',
    color: '#dc2626', light: '#fff1f2', border: '#fecaca',
    entries: [
      { hr: 'Vatreni', en: 'The Fiery Ones — Croatia national team', ph: 'vah-TREH-nee', level: '⚽',
        note: 'The nickname for the Croatian national football team.',
        variants: [
          { hr: 'Idemo Hrvatska!', en: 'Let\'s go Croatia! — the national chant' },
          { hr: 'Šahovnica', en: 'Checkerboard — the Croatian coat of arms' },
          { hr: 'Lijepa naša', en: 'Our beautiful (one) — Croatian anthem, chanted at matches' },
        ]},
      { hr: 'Vječni derbi', en: 'The Eternal Derby', ph: 'VYE-chnee DEHR-bee', level: '⚽',
        note: 'Dinamo Zagreb vs Hajduk Split — the most intense domestic rivalry.',
        variants: [
          { hr: 'Hajduk do neba!', en: 'Hajduk to the heavens!' },
          { hr: 'Bili smo, jesmo i bit ćemo!', en: 'We were, we are, and we will be!' },
          { hr: 'Plavi', en: 'The Blues — Dinamo Zagreb nickname' },
          { hr: 'Bijeli', en: 'The Whites — Hajduk Split nickname' },
        ]},
      { hr: 'Torcida', en: 'Hajduk Split\'s ultras — Europe\'s oldest', ph: 'tor-TSEE-dah', level: '⚽',
        note: 'Founded 28 October 1950 in Split — the oldest organized supporter group in Europe.',
        variants: [
          { hr: 'Torcido, volim te!', en: 'Torcida, I love you!' },
          { hr: 'Hajduk je naš!', en: 'Hajduk is ours!' },
          { hr: 'Ubij Dinamovca!', en: 'Kill the Dynamo fan! — terrace hyperbole' },
          { hr: 'Dinamo je sranje', en: 'Dinamo is sh** — the minimum acceptable position for any Hajduk supporter' },
          { hr: 'Cigani', en: 'Gypsies — Torcida\'s insult for BBB / Dinamo fans' },
          { hr: 'Tovari', en: 'Donkeys — BBB\'s insult for Torcida' },
        ]},
      { hr: 'Poljud', en: 'Hajduk\'s cathedral', ph: 'POH-lyood', level: '⚽',
        note: 'Stadion Poljud in Split — opened 1979. To Hajduk fans it is sacred ground.',
        variants: [
          { hr: 'Na Poljudu', en: 'At Poljud — "idemo na Poljud" = we\'re going to the match' },
          { hr: 'Sjever', en: 'The North Stand — where Torcida stands' },
          { hr: 'Ajmo Bili!', en: 'Come on Whites!' },
          { hr: 'Kad mi idemo na derbi, cijeli Split zna', en: 'When we go to the derby, all of Split knows' },
        ]},
      { hr: 'Ajmo! / Idemo! / Naprijed!', en: 'Come on! / Let\'s go! / Forward!', ph: 'AY-mo / EE-demo / NAH-pryehd', level: '⚽',
        note: 'The three essential football encouragement chants.',
        variants: [
          { hr: 'Gol!', en: 'Goal!' },
          { hr: 'Pobjeda!', en: 'Victory!' },
          { hr: 'Tekma', en: 'Match / Game' },
        ]},
    ],
  },

  // ─── 11. REGIONAL COMPARISON ────────────────────────────────────────────────
  {
    id: 'regional', icon: '🗺️', title: 'Zagreb vs Split',
    subtitle: 'The same thing — completely different word. A field guide.',
    color: '#065f46', light: '#ecfdf5', border: '#6ee7b7',
    entries: [
      { hr: 'Kaj / Ča / Što', en: '"What" — three dialects, one Croatia', ph: 'KAI / CHAH / SHTOH', level: '🗺️',
        note: 'Croatia has three dialects: Kajkavian (Zagreb/north), Čakavian (coast), Štokavian (standard).',
        variants: [
          { hr: 'Kaj ima? (Zagreb)', en: 'What\'s up? — Zagreb' },
          { hr: 'Ča ima? (Dalmatia)', en: 'What\'s up? — coastal/island' },
          { hr: 'Šta ima? (standard)', en: 'What\'s up? — everywhere else' },
        ]},
      { hr: 'Lova vs Šoldi', en: 'Money — Zagreb vs Dalmatia', ph: 'LOH-vah vs SHOL-dee', level: '🗺️',
        note: '"Lova" or "kinta" in Zagreb. "Šoldi" (from Italian "soldi") in Dalmatia.',
        variants: [
          { hr: 'Kola (Zagreb) vs Makina (Split)', en: 'Car — German vs Italian loanword' },
          { hr: 'Birc (Zagreb) vs Konoba (Dalmatia)', en: 'Bar' },
          { hr: 'Baka (Zagreb) vs Nona (Dalmatia)', en: 'Grandma — the most emotional regional difference' },
        ]},
      { hr: 'Baka / Dida vs Nona / Nono', en: 'Grandparents — Zagreb vs Coast', ph: 'BAH-kah / DEE-dah vs NOH-nah / NOH-noh', level: '🗺️',
        note: 'Possibly the single most emotionally charged regional difference.',
        variants: [
          { hr: 'Nona / Nonić', en: 'Grandma / Grandpa — coastal/Dalmatian' },
          { hr: 'Baka / Dida', en: 'Grandma / Grandpa — Zagreb and inland' },
          { hr: 'Naša kuhinja vs naša kužina', en: 'Our kitchen — Zagreb standard vs Dalmatian Italian loanword' },
        ]},
      { hr: 'Generacijski jaz', en: 'The generation gap in words', ph: '—', level: '📚',
        note: 'Grandparents use German/Italian/Austro-Hungarian loanwords. Grandkids use English/Internet loanwords.',
        variants: [
          { hr: 'Šuster (grandpa)', en: 'Cobbler / Shoemaker — from German "Schuster"' },
          { hr: 'Ghostati (grandkid)', en: 'To ghost' },
          { hr: 'Frajla (grandpa) vs Snack (grandkid)', en: 'How each generation describes an attractive woman' },
        ]},
    ],
  },

  // ─── 12. THE ART OF THE CURSE ───────────────────────────────────────────────
  {
    id: 'art', icon: '🎨', title: 'Psovanje kao Umjetnost',
    subtitle: 'The grammar, culture, and mastery of Croatian swearing',
    color: '#1a1a2e', light: '#f1f5f9', border: '#94a3b8',
    entries: [
      { hr: 'The Jeb- Construction', en: 'How Croatian builds infinite curses from one root', ph: '—', level: '📚',
        note: 'The root "jeb-" (from "jebati") is uniquely productive.',
        variants: [
          { hr: 'Zajebao si', en: 'You screwed up (za- = imperfective)' },
          { hr: 'Pojebali su ga', en: 'They completely did him over (po- = completed action)' },
          { hr: 'Nadjebao sam ga', en: 'I dominated/outdid him (nad- = over/above)' },
          { hr: 'Ujebali su me', en: 'They conned/tricked me (u- = into)' },
          { hr: 'Jebu me živci', en: 'Abstract noun as agent — "my nerves are screwing me"' },
          { hr: 'Jebeno', en: 'F***ing (adverb) — "jebeno dobro" = f***ing good' },
          { hr: 'Jebačina', en: '-čina augmentative suffix — elevates jebanje to an epic scale' },
        ]},
      { hr: 'The Mater Elaboration Scale', en: 'From mild to nuclear — know your level', ph: '—', level: '📚',
        note: 'Croatian mater curses have levels. Each addition escalates intensity.',
        variants: [
          { hr: 'Između prijatelja', en: 'Among close friends — almost everything is acceptable, tone = love' },
          { hr: 'S neznancima', en: 'With strangers — maximum "jebote" or "jebi ga"' },
          { hr: 'Na poslu', en: 'At work — "sranje" and "govno" only' },
        ]},
      { hr: 'Affectionate Swearing', en: 'When curses mean the exact opposite', ph: '—', level: '📚',
        note: 'The most important concept: Croatian swearing is deeply social and tone-dependent.',
        variants: [
          { hr: 'Jebote, faca si!', en: 'Holy sh**, you\'re a legend! — said with genuine admiration' },
          { hr: 'Picka mu materina, uspio si!', en: 'Holy sh**, he/you did it! — overwhelming pride' },
          { hr: 'Jebo te, pa to je nevjerojatno', en: 'F*** you (= you amazing person), that\'s incredible' },
        ]},
      { hr: 'The I Don\'t Care Ladder', en: 'Five levels of not caring — exactly calibrated', ph: '—', level: '📚',
        note: 'Croatian has a beautifully precise indifference vocabulary.',
        variants: [
          { hr: 'Nije me briga', en: '1. Polite — I don\'t care (neutral, professional context fine)' },
          { hr: 'Baš me briga', en: '2. Mild — I really don\'t care' },
          { hr: 'Boli me briga', en: '3. Medium — I genuinely couldn\'t care less' },
          { hr: 'Boli me kurac', en: '4. Strong — I absolutely do not give a damn (explicit)' },
          { hr: 'Pun mi je kurac svega', en: '5. Nuclear — I\'m completely fed up with everything' },
        ]},
    ],
  },

];
